/* Generated by tools/build.py — do not edit.
   Content lives in tools/chapters/ch05_housing.py; rebuild after changing it. */

KIIP.chapter({
 "number": 5,
 "unit": "사회",
 "title": "주거",
 "titleEnglish": "Housing",
 "chapterGlossary": [],
 "blocks": [
  {
   "type": "section",
   "kind": "warmup",
   "text": "생각해 봅시다"
  },
  {
   "type": "paragraph",
   "spans": [
    "다음은 한국에서 볼 수 있는 집의 모습입니다."
   ]
  },
  {
   "type": "labels",
   "groups": [
    {
     "name": [
      {
       "word": "단독 주택",
       "annotation": "단독 주택"
      }
     ],
     "items": [
      [
       {
        "word": "양옥",
        "annotation": "양옥"
       }
      ],
      [
       {
        "word": "한옥",
        "annotation": "한옥"
       }
      ]
     ]
    },
    {
     "name": [
      {
       "word": "공동 주택",
       "annotation": "공동 주택"
      }
     ],
     "items": [
      [
       {
        "word": "빌라",
        "annotation": "빌라"
       }
      ],
      [
       {
        "word": "아파트",
        "annotation": "아파트"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "01 한국에서 많이 본 집의 모습은 어떤 것 입니까?"
  },
  {
   "type": "heading",
   "level": 4,
   "text": "02 지금 본인이 살고 있는 집은 어떤 형태입니까? 어떤 점이 편리하고 어떤 점이 불편합니까?"
  },
  {
   "type": "section",
   "kind": "goals",
   "text": "학습목표"
  },
  {
   "type": "bullet",
   "spans": [
    "한국에서 많이 볼 수 있는 집의 ",
    {
     "word": "형태",
     "annotation": "형태"
    },
    "와 주거 문화의 특징을 설명할 수 있다."
   ],
   "ordered": true
  },
  {
   "type": "bullet",
   "spans": [
    "한국인의 거주 형태와 집 구하는 방법을 설명할 수 있다."
   ],
   "ordered": true
  },
  {
   "type": "section",
   "kind": "related",
   "text": "관련 단원 확인하기"
  },
  {
   "type": "table",
   "header": [
    {
     "text": "영역",
     "span": 2
    },
    "제목",
    "관련 내용"
   ],
   "rows": [
    [
     "기본",
     "법",
     "34. 재산과 법",
     "부동산과 등기부 등본, 부동산 거래 과정"
    ]
   ]
  },
  {
   "type": "section",
   "kind": "part",
   "text": "01 한국인이 많이 살고 있는 집의 형태는 무엇일까?"
  },
  {
   "type": "heading",
   "level": 2,
   "text": "집의 형태",
   "titleTranslation": "Types of Homes"
  },
  {
   "type": "glossary",
   "entries": [
    {
     "term": "세",
     "definition": [
      "다른 사람의 건물 등을 빌려 쓰는 대가로 내는 돈"
     ],
     "annotation": "세"
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "한국인이 거주하는 집의 형태는 크게 ",
    {
     "word": "단독",
     "annotation": "단독"
    },
    " 주택(일반 주택, ",
    {
     "word": "다가구 주택",
     "annotation": "다가구 주택"
    },
    " 등)과 ",
    {
     "word": "공동",
     "annotation": "공동"
    },
    " 주택(",
    {
     "word": "다세대 주택",
     "annotation": "다세대 주택"
    },
    ", ",
    {
     "word": "연립",
     "annotation": "연립"
    },
    " 주택, ",
    {
     "word": "아파트",
     "annotation": "아파트"
    },
    " 등)으로 나눌 수 있다. ",
    {
     "word": "단독 주택",
     "annotation": "단독 주택"
    },
    "은 보통 한 가구가 독립적으로 생활할 수 있도록 집을 한 채씩 각각 ",
    {
     "word": "지은",
     "annotation": "지은"
    },
    " 형태를 말한다. 단독 주택에는 여러 가구가 각각의 독립적인 공간을 ",
    {
     "word": "차지하며",
     "annotation": "차지하며"
    },
    " 살 수 있도록 지은 다가구 주택도 포함된다. ",
    {
     "word": "다가구",
     "annotation": "다가구"
    },
    " 주택은 3층 이하의 건물이며 전체에 대한 ",
    {
     "word": "소유권",
     "annotation": "소유권"
    },
    "은 집주인이 가지고 있고 나머지 가구는 거기에 ",
    {
     "word": "세",
     "annotation": "세"
    },
    "를 들어 산다."
   ],
   "translation": "The types of homes Koreans live in can broadly be divided into single-family homes (단독 주택 — including general houses, multi-household houses, etc.) and multi-unit housing (공동 주택 — including multi-family houses, row houses, apartments, etc.). 단독 주택 (single-family housing) generally refers to a house built individually so that one household can live independently. This category also includes 다가구 주택 (multi-household houses), built so that several households can each occupy their own independent space. A 다가구 주택 is a building of 3 stories or fewer, where ownership of the entire building belongs to one landlord, and the other households rent their units from that owner.",
   "sentences": [
    {
     "spans": [
      "한국인이 거주하는 집의 형태는 크게 ",
      {
       "word": "단독",
       "annotation": "단독"
      },
      " 주택(일반 주택, ",
      {
       "word": "다가구 주택",
       "annotation": "다가구 주택"
      },
      " 등)과 ",
      {
       "word": "공동",
       "annotation": "공동"
      },
      " 주택(",
      {
       "word": "다세대 주택",
       "annotation": "다세대 주택"
      },
      ", ",
      {
       "word": "연립",
       "annotation": "연립"
      },
      " 주택, ",
      {
       "word": "아파트",
       "annotation": "아파트"
      },
      " 등)으로 나눌 수 있다. "
     ],
     "translation": "The types of homes Koreans live in can broadly be divided into single-family homes (단독 주택 — including general houses, multi-household houses, etc.) and multi-unit housing (공동 주택 — including multi-family houses, row houses, apartments, etc.)."
    },
    {
     "spans": [
      {
       "word": "단독 주택",
       "annotation": "단독 주택"
      },
      "은 보통 한 가구가 독립적으로 생활할 수 있도록 집을 한 채씩 각각 ",
      {
       "word": "지은",
       "annotation": "지은"
      },
      " 형태를 말한다. "
     ],
     "translation": "단독 주택 (single-family housing) generally refers to a house built individually so that one household can live independently."
    },
    {
     "spans": [
      "단독 주택에는 여러 가구가 각각의 독립적인 공간을 ",
      {
       "word": "차지하며",
       "annotation": "차지하며"
      },
      " 살 수 있도록 지은 다가구 주택도 포함된다. "
     ],
     "translation": "This category also includes 다가구 주택 (multi-household houses), built so that several households can each occupy their own independent space."
    },
    {
     "spans": [
      {
       "word": "다가구",
       "annotation": "다가구"
      },
      " 주택은 3층 이하의 건물이며 전체에 대한 ",
      {
       "word": "소유권",
       "annotation": "소유권"
      },
      "은 집주인이 가지고 있고 나머지 가구는 거기에 ",
      {
       "word": "세",
       "annotation": "세"
      },
      "를 들어 산다."
     ],
     "translation": "A 다가구 주택 is a building of 3 stories or fewer, where ownership of the entire building belongs to one landlord, and the other households rent their units from that owner."
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    {
     "word": "공동 주택",
     "annotation": "공동 주택"
    },
    "은 한 건물에 여러 가구가 각각 독립된 생활을 할 수 있게 만든 집의 형태를 말한다. 다세대 주택, ",
    {
     "word": "연립 주택",
     "annotation": "연립 주택"
    },
    ", 아파트 등이 있다. 다세대 주택은 다가구 주택과 달리 건물의 부분별로 주인이 다르다. 연립 주택은 4층 이하의 주택으로, 종종 지하 1층에도 주",
    {
     "word": "거공간",
     "annotation": "거공간"
    },
    "이 있는 경우가 있다. 연립 주택은 다세대 주택보다 건물의 총 ",
    {
     "word": "면적",
     "annotation": "면적"
    },
    "이 더 넓다. 아파트는 5층 이상의 공동 주택이며, ",
    {
     "word": "수백",
     "annotation": "수백"
    },
    " 가구에서 ",
    {
     "word": "수 천",
     "annotation": "수 천"
    },
    " 가구까지 ",
    {
     "word": "대규모",
     "annotation": "대규모"
    },
    "로 지어지는 경우가 많다."
   ],
   "translation": "공동 주택 (multi-unit housing) refers to a housing form built within one building so that several households can each live independently. This includes 다세대 주택 (multi-family housing), 연립 주택 (row/townhouse), and 아파트 (apartments). Unlike 다가구 주택, a 다세대 주택 has different owners for different parts/units of the building. A 연립 주택 is housing of 4 stories or fewer, and sometimes even has living space on basement level 1. A 연립 주택 has a larger total building area than a 다세대 주택. An apartment (아파트) is multi-unit housing of 5 stories or more, and is often built on a large scale, ranging from hundreds to thousands of households.",
   "sentences": [
    {
     "spans": [
      {
       "word": "공동 주택",
       "annotation": "공동 주택"
      },
      "은 한 건물에 여러 가구가 각각 독립된 생활을 할 수 있게 만든 집의 형태를 말한다. "
     ],
     "translation": "공동 주택 (multi-unit housing) refers to a housing form built within one building so that several households can each live independently."
    },
    {
     "spans": [
      "다세대 주택, ",
      {
       "word": "연립 주택",
       "annotation": "연립 주택"
      },
      ", 아파트 등이 있다. "
     ],
     "translation": "This includes 다세대 주택 (multi-family housing), 연립 주택 (row/townhouse), and 아파트 (apartments)."
    },
    {
     "spans": [
      "다세대 주택은 다가구 주택과 달리 건물의 부분별로 주인이 다르다. "
     ],
     "translation": "Unlike 다가구 주택, a 다세대 주택 has different owners for different parts/units of the building."
    },
    {
     "spans": [
      "연립 주택은 4층 이하의 주택으로, 종종 지하 1층에도 주",
      {
       "word": "거공간",
       "annotation": "거공간"
      },
      "이 있는 경우가 있다. "
     ],
     "translation": "A 연립 주택 is housing of 4 stories or fewer, and sometimes even has living space on basement level 1."
    },
    {
     "spans": [
      "연립 주택은 다세대 주택보다 건물의 총 ",
      {
       "word": "면적",
       "annotation": "면적"
      },
      "이 더 넓다. "
     ],
     "translation": "A 연립 주택 has a larger total building area than a 다세대 주택."
    },
    {
     "spans": [
      "아파트는 5층 이상의 공동 주택이며, ",
      {
       "word": "수백",
       "annotation": "수백"
      },
      " 가구에서 ",
      {
       "word": "수 천",
       "annotation": "수 천"
      },
      " 가구까지 ",
      {
       "word": "대규모",
       "annotation": "대규모"
      },
      "로 지어지는 경우가 많다."
     ],
     "translation": "An apartment (아파트) is multi-unit housing of 5 stories or more, and is often built on a large scale, ranging from hundreds to thousands of households."
    }
   ]
  },
  {
   "type": "labels",
   "items": [
    [
     "단독 주택(일반 주택)"
    ],
    [
     "단독 주택(다가구 주택)"
    ],
    [
     "공동 주택(다세대 주택)"
    ]
   ]
  },
  {
   "type": "heading",
   "level": 2,
   "text": "주거 문화의 변화",
   "titleTranslation": "Changes in Housing Culture"
  },
  {
   "type": "glossary",
   "entries": [
    {
     "term": "층간 소음",
     "definition": [
      "건물의 한 층에서 발생한 소리가 다른 층에 전달되어 피해를 주는 것"
     ],
     "annotation": "층간 소음"
    },
    {
     "term": "쾌적",
     "definition": [
      "기분이 상쾌하고 즐거움"
     ],
     "annotation": "쾌적"
    },
    {
     "term": "한적",
     "definition": [
      "한가하고 고요함"
     ],
     "annotation": "한적"
    },
    {
     "term": "전원 주택",
     "definition": [
      "도시에서 조금 떨어져 있어서 자연의 분위기를 느낄 수 있도록 지은 집"
     ],
     "annotation": "전원 주택"
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "한국의 주거 형태는 빠르게 변화하고 있다. 과거에는 단독 주택이 대부분이었으나 도시에 ",
    {
     "word": "인구",
     "annotation": "인구"
    },
    "가 집중되면서 단독 주택보다 공동 주택에 살고 있는 가구 수가 많아졌다. 특히 아파트는 ",
    {
     "word": "대체로",
     "annotation": "대체로"
    },
    " 교통이 편리한 곳에 지어지고 놀이터, ",
    {
     "word": "체력 단련실",
     "annotation": "체력 단련실"
    },
    " 등 여러 가지 편의 ",
    {
     "word": "시설",
     "annotation": "시설"
    },
    "이 ",
    {
     "word": "갖추어져",
     "annotation": "갖추어져"
    },
    " 있어서 많은 사람들이 아파트에서 사는 것을 선호한다. 그러나 ",
    {
     "word": "층간 소음",
     "annotation": "층간 소음"
    },
    "으로 인해 이웃 간의 ",
    {
     "word": "갈등",
     "annotation": "갈등"
    },
    "이 심해지는 경우도 있다. 최근에는 1인 가구, 2인 가구가 늘어나면서 ",
    {
     "word": "원룸",
     "annotation": "원룸"
    },
    "이나 소형 주택에 대한 ",
    {
     "word": "수요",
     "annotation": "수요"
    },
    "가 늘고 있다. 은퇴를 맞아 ",
    {
     "word": "노년",
     "annotation": "노년"
    },
    "을 준비하는 사람들이나 ",
    {
     "word": "쾌적한",
     "annotation": "쾌적하다"
    },
    " 자연환경에 살기 원하는 사람들은 대도시 주변의 ",
    {
     "word": "한적한",
     "annotation": "한적하다"
    },
    " 지역에 ",
    {
     "word": "전원 주택",
     "annotation": "전원 주택"
    },
    "을 짓고 사는 경우도 있다."
   ],
   "translation": "Korea's housing forms are changing rapidly. In the past, single-family houses (단독 주택) made up the majority, but as population concentrated in cities, the number of households living in multi-unit housing (공동 주택) has grown larger than those in single-family homes. Apartments (아파트) in particular tend to be built in locations with convenient transportation, and are equipped with various amenities like playgrounds and fitness rooms, so many people prefer living in apartments. However, conflicts between neighbors sometimes worsen due to noise between floors (층간 소음). Recently, as one-person and two-person households increase, demand for studio apartments (원룸) or small housing has been rising. Some people preparing for old age around retirement, or those who want to live in a pleasant natural environment, build and live in country houses (전원 주택) in quiet areas on the outskirts of large cities.",
   "sentences": [
    {
     "spans": [
      "한국의 주거 형태는 빠르게 변화하고 있다. "
     ],
     "translation": "Korea's housing forms are changing rapidly."
    },
    {
     "spans": [
      "과거에는 단독 주택이 대부분이었으나 도시에 ",
      {
       "word": "인구",
       "annotation": "인구"
      },
      "가 집중되면서 단독 주택보다 공동 주택에 살고 있는 가구 수가 많아졌다. "
     ],
     "translation": "In the past, single-family houses (단독 주택) made up the majority, but as population concentrated in cities, the number of households living in multi-unit housing (공동 주택) has grown larger than those in single-family homes."
    },
    {
     "spans": [
      "특히 아파트는 ",
      {
       "word": "대체로",
       "annotation": "대체로"
      },
      " 교통이 편리한 곳에 지어지고 놀이터, ",
      {
       "word": "체력 단련실",
       "annotation": "체력 단련실"
      },
      " 등 여러 가지 편의 ",
      {
       "word": "시설",
       "annotation": "시설"
      },
      "이 ",
      {
       "word": "갖추어져",
       "annotation": "갖추어져"
      },
      " 있어서 많은 사람들이 아파트에서 사는 것을 선호한다. "
     ],
     "translation": "Apartments (아파트) in particular tend to be built in locations with convenient transportation, and are equipped with various amenities like playgrounds and fitness rooms, so many people prefer living in apartments."
    },
    {
     "spans": [
      "그러나 ",
      {
       "word": "층간 소음",
       "annotation": "층간 소음"
      },
      "으로 인해 이웃 간의 ",
      {
       "word": "갈등",
       "annotation": "갈등"
      },
      "이 심해지는 경우도 있다. "
     ],
     "translation": "However, conflicts between neighbors sometimes worsen due to noise between floors (층간 소음)."
    },
    {
     "spans": [
      "최근에는 1인 가구, 2인 가구가 늘어나면서 ",
      {
       "word": "원룸",
       "annotation": "원룸"
      },
      "이나 소형 주택에 대한 ",
      {
       "word": "수요",
       "annotation": "수요"
      },
      "가 늘고 있다. "
     ],
     "translation": "Recently, as one-person and two-person households increase, demand for studio apartments (원룸) or small housing has been rising."
    },
    {
     "spans": [
      "은퇴를 맞아 ",
      {
       "word": "노년",
       "annotation": "노년"
      },
      "을 준비하는 사람들이나 ",
      {
       "word": "쾌적한",
       "annotation": "쾌적하다"
      },
      " 자연환경에 살기 원하는 사람들은 대도시 주변의 ",
      {
       "word": "한적한",
       "annotation": "한적하다"
      },
      " 지역에 ",
      {
       "word": "전원 주택",
       "annotation": "전원 주택"
      },
      "을 짓고 사는 경우도 있다."
     ],
     "translation": "Some people preparing for old age around retirement, or those who want to live in a pleasant natural environment, build and live in country houses (전원 주택) in quiet areas on the outskirts of large cities."
    }
   ]
  },
  {
   "type": "section",
   "kind": "aside",
   "text": "알아두면 좋아요",
   "topic": "공공 임대 주택이란?"
  },
  {
   "type": "paragraph",
   "spans": [
    "대도시는 집값이 비싸기 때문에 서민들이 집을 구하기 어렵다. 그래서 정부에서는 아파트와 같은 공동 주택을 지어 경제적으로 어려운 사람들이 싼 값에 집을 사거나 빌릴 수 있도록 하고 있다. ",
    {
     "word": "기초생활수급자",
     "annotation": "기초생활수급자"
    },
    " 등 사회의 보호가 필요한 계층을 위한 공공 임대 주택뿐만 아니라 대학생, 신혼부부, ",
    {
     "word": "사회초년생",
     "annotation": "사회초년생"
    },
    "(일을 시작한 지 얼마 되지 않은 사람) 등 젊은 층을 위한 임대 주택(행복 주택), 소득이 낮은 독거노인(혼자 사는 노인)을 위한 임대 주택(공공 실버 주택), 다문화 가족, 한부모 가족을 위한 임대 주택 등 다양한 사람들의 주거 안정을 지원하고 있다."
   ]
  },
  {
   "type": "section",
   "kind": "part",
   "text": "02 한국에서는 집을 어떻게 구할까?"
  },
  {
   "type": "heading",
   "level": 2,
   "text": "거주 형태와 집 구하는 방법",
   "titleTranslation": "Housing forms and methods of finding a house"
  },
  {
   "type": "glossary",
   "entries": [
    {
     "term": "세입자",
     "definition": [
      "세를 내고 남의 집이나 방 따위를 빌려 쓰는 사람"
     ],
     "annotation": "세입자"
    },
    {
     "term": "파기",
     "definition": [
      "계약이나 약속 등을 깨뜨려 무효로 하는 것"
     ],
     "annotation": "파기"
    },
    {
     "term": "확정 일자",
     "definition": [
      "집을 계약한 날짜에 대해 법원이나 행정복지센터(주민센터) 등이 사실임을 증명해 준 날짜"
     ],
     "annotation": "확정 일자"
    },
    {
     "term": "중개",
     "definition": [
      "두 사람 사이에서 일을 맡아 잘 진행되도록 함"
     ],
     "annotation": "중개"
    },
    {
     "term": "부동산 중개 업소",
     "definition": [
      "다른 사람을 위하여 부동산 거래를 대리하거나 중개하고 수수료를 받는 영업소"
     ],
     "annotation": "부동산/중개 업소"
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "한국에서 집에 거주하는 형태는 ",
    {
     "word": "자가",
     "annotation": "자가"
    },
    ", ",
    {
     "word": "전세",
     "annotation": "전세"
    },
    ", ",
    {
     "word": "월세",
     "annotation": "월세"
    },
    "로 나눌 수 있다. 자가는 자기가 소유한 집에 살고 있는 것을 말한다. 전세는 집주인에게 ",
    {
     "word": "일정한",
     "annotation": "일정한"
    },
    " 돈을 ",
    {
     "word": "보증금",
     "annotation": "보증금"
    },
    "으로 ",
    {
     "word": "맡기",
     "annotation": "맡기"
    },
    "고 계약 기간 동안 집이나 방을 빌려 쓰는 방식으로 한국에서만 널리 활용된다. 전세 계약은 보통 2년 단위로 하며, 집주인은 ",
    {
     "word": "세입자",
     "annotation": "세입자"
    },
    "가 원하지 않는 한 2년 이내에는 계약을 ",
    {
     "word": "파기",
     "annotation": "파기"
    },
    "할 수 없도록 법률로 규정되어 있다. 계약 기간이 끝나고 보증금을 안전하게 돌려받기 위해서는 이사 전후에 행정복지센터에 가서 ",
    {
     "word": "확정 일자",
     "annotation": "확정 일자"
    },
    "를 받아 두는 것이 좋다. 월세는 집주인에게 매달 일정한 돈을 내고 집이나 방을 빌려 쓰는 방식이다. 월세의 경우도 어느 정도의 보증금을 내야 하는 경우가 많은데 그 금액은 전세에 비해 적다. 최근에는 전세와 월세를 ",
    {
     "word": "혼합한",
     "annotation": "혼합한"
    },
    " ",
    {
     "word": "반전세",
     "annotation": "반전세"
    },
    "라는 방식도 많아지고 있는데 반전세의 보증금은 전세보다는 적고 월세보다는 많은 편이다."
   ],
   "translation": "The ways of living in a house in Korea divide into owning it, 전세 and 월세. Owning means living in a house one owns oneself. 전세 is an arrangement in which a fixed sum is left with the owner as a deposit and the house or room is borrowed for the term of the contract; it is used widely only in Korea. A 전세 contract usually runs in two-year terms, and the law provides that the owner cannot break it within those two years unless the tenant wishes it. To get the deposit back safely once the term is over, it is as well to go to the administrative welfare centre around the time of moving and have the date of the contract certified. 월세 is an arrangement in which a fixed sum is paid to the owner each month for the use of the house or room. With 월세 too a deposit of some size is often required, but the amount is small next to 전세. Lately 반전세, which mixes the two, has become more common; its deposit is smaller than a 전세 deposit and larger than a 월세 one.",
   "sentences": [
    {
     "spans": [
      "한국에서 집에 거주하는 형태는 ",
      {
       "word": "자가",
       "annotation": "자가"
      },
      ", ",
      {
       "word": "전세",
       "annotation": "전세"
      },
      ", ",
      {
       "word": "월세",
       "annotation": "월세"
      },
      "로 나눌 수 있다. "
     ],
     "translation": "The ways of living in a house in Korea divide into owning it, 전세 and 월세."
    },
    {
     "spans": [
      "자가는 자기가 소유한 집에 살고 있는 것을 말한다. "
     ],
     "translation": "Owning means living in a house one owns oneself."
    },
    {
     "spans": [
      "전세는 집주인에게 ",
      {
       "word": "일정한",
       "annotation": "일정한"
      },
      " 돈을 ",
      {
       "word": "보증금",
       "annotation": "보증금"
      },
      "으로 ",
      {
       "word": "맡기",
       "annotation": "맡기"
      },
      "고 계약 기간 동안 집이나 방을 빌려 쓰는 방식으로 한국에서만 널리 활용된다. "
     ],
     "translation": "전세 is an arrangement in which a fixed sum is left with the owner as a deposit and the house or room is borrowed for the term of the contract; it is used widely only in Korea."
    },
    {
     "spans": [
      "전세 계약은 보통 2년 단위로 하며, 집주인은 ",
      {
       "word": "세입자",
       "annotation": "세입자"
      },
      "가 원하지 않는 한 2년 이내에는 계약을 ",
      {
       "word": "파기",
       "annotation": "파기"
      },
      "할 수 없도록 법률로 규정되어 있다. "
     ],
     "translation": "A 전세 contract usually runs in two-year terms, and the law provides that the owner cannot break it within those two years unless the tenant wishes it."
    },
    {
     "spans": [
      "계약 기간이 끝나고 보증금을 안전하게 돌려받기 위해서는 이사 전후에 행정복지센터에 가서 ",
      {
       "word": "확정 일자",
       "annotation": "확정 일자"
      },
      "를 받아 두는 것이 좋다. "
     ],
     "translation": "To get the deposit back safely once the term is over, it is as well to go to the administrative welfare centre around the time of moving and have the date of the contract certified."
    },
    {
     "spans": [
      "월세는 집주인에게 매달 일정한 돈을 내고 집이나 방을 빌려 쓰는 방식이다. "
     ],
     "translation": "월세 is an arrangement in which a fixed sum is paid to the owner each month for the use of the house or room."
    },
    {
     "spans": [
      "월세의 경우도 어느 정도의 보증금을 내야 하는 경우가 많은데 그 금액은 전세에 비해 적다. "
     ],
     "translation": "With 월세 too a deposit of some size is often required, but the amount is small next to 전세."
    },
    {
     "spans": [
      "최근에는 전세와 월세를 ",
      {
       "word": "혼합한",
       "annotation": "혼합한"
      },
      " ",
      {
       "word": "반전세",
       "annotation": "반전세"
      },
      "라는 방식도 많아지고 있는데 반전세의 보증금은 전세보다는 적고 월세보다는 많은 편이다."
     ],
     "translation": "Lately 반전세, which mixes the two, has become more common; its deposit is smaller than a 전세 deposit and larger than a 월세 one."
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "집을 사거나 전세 또는 월세를 구할 때는 ",
    {
     "word": "부동산",
     "annotation": "부동산"
    },
    " ",
    {
     "word": "중개",
     "annotation": "중개"
    },
    "업소(공인 중개사)를 통해 알아보는 것이 안전하다. 공인 중개사는 집 계약을 할 때 계약자가 반드시 확인해야 할 사항들을 대신 확인해 주고 계약에 필요한 서류 준비에 도움을 주기 때문에 안전하고 편리하게 부동산을 거래할 수 있다."
   ],
   "translation": "When buying a house or looking for a 전세 or 월세, it is safer to go through an estate agency — a licensed agent. A licensed agent checks, on the client's behalf, the things a party to a housing contract must be sure of, and helps prepare the documents the contract needs, so the transaction can be made safely and conveniently.",
   "sentences": [
    {
     "spans": [
      "집을 사거나 전세 또는 월세를 구할 때는 ",
      {
       "word": "부동산",
       "annotation": "부동산"
      },
      " ",
      {
       "word": "중개",
       "annotation": "중개"
      },
      "업소(공인 중개사)를 통해 알아보는 것이 안전하다. "
     ],
     "translation": "When buying a house or looking for a 전세 or 월세, it is safer to go through an estate agency — a licensed agent."
    },
    {
     "spans": [
      "공인 중개사는 집 계약을 할 때 계약자가 반드시 확인해야 할 사항들을 대신 확인해 주고 계약에 필요한 서류 준비에 도움을 주기 때문에 안전하고 편리하게 부동산을 거래할 수 있다."
     ],
     "translation": "A licensed agent checks, on the client's behalf, the things a party to a housing contract must be sure of, and helps prepare the documents the contract needs, so the transaction can be made safely and conveniently."
    }
   ]
  },
  {
   "type": "heading",
   "level": 2,
   "text": "주거 선택 기준",
   "titleTranslation": "Criteria for Choosing Housing"
  },
  {
   "type": "glossary",
   "entries": [
    {
     "term": "포장 이사",
     "definition": [
      "이삿짐 업체에서 이삿짐을 포장한 뒤 목적지까지 날라 주는 서비스"
     ],
     "annotation": "포장 이사"
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "요즘은 이사를 할 때 대부분 ",
    {
     "word": "포장 이사",
     "annotation": "포장 이사"
    },
    "를 이용한다. 어디에서 거주할 것인가와 관련하여 중요하게 여기는 것으로는 교통, 교육 ",
    {
     "word": "여건",
     "annotation": "여건"
    },
    ", ",
    {
     "word": "주거",
     "annotation": "주거"
    },
    " 환경, ",
    {
     "word": "편의 시설",
     "annotation": "편의 시설"
    },
    " 등이 있다. 출퇴근하기 편한지, 다른 지역으로 이동하기 편한지를 고려하는 사람들은 지하철역 주변이나 교통이 편리한 곳을 선호한다. 자녀 교육을 위한 주변의 여건을 ",
    {
     "word": "중시하",
     "annotation": "중시하"
    },
    "는 사람들은 교육 시설이 ",
    {
     "word": "발달해",
     "annotation": "발달하다"
    },
    " 있는 곳에 집을 구한다. 현재의 ",
    {
     "word": "경제적",
     "annotation": "경제적"
    },
    " 상황이나 미래의 계획 등을 고려하여 집을 살 것인지, 전세나 월세 등으로 빌려 쓸 것인지 등을 살펴보고 자신에게 적합한 방식을 선택하는 것이 좋다."
   ],
   "translation": "These days, when people move, most use a full-service packing move (포장 이사, a Korean moving service where movers pack, transport, and unpack everything). Regarding where to live, things people consider important include transportation, educational conditions, residential environment, and convenience facilities. People who consider whether it's convenient to commute to work or travel to other areas prefer areas near subway stations or places with convenient transportation. People who prioritize the surrounding conditions for their children's education look for homes in areas where educational facilities are well-developed. It's good to consider your current financial situation and future plans, examine whether to buy a house or rent it via jeonse or monthly rent, and choose the method that suits you best.",
   "sentences": [
    {
     "spans": [
      "요즘은 이사를 할 때 대부분 ",
      {
       "word": "포장 이사",
       "annotation": "포장 이사"
      },
      "를 이용한다. "
     ],
     "translation": "These days, when people move, most use a full-service packing move (포장 이사, a Korean moving service where movers pack, transport, and unpack everything)."
    },
    {
     "spans": [
      "어디에서 거주할 것인가와 관련하여 중요하게 여기는 것으로는 교통, 교육 ",
      {
       "word": "여건",
       "annotation": "여건"
      },
      ", ",
      {
       "word": "주거",
       "annotation": "주거"
      },
      " 환경, ",
      {
       "word": "편의 시설",
       "annotation": "편의 시설"
      },
      " 등이 있다. "
     ],
     "translation": "Regarding where to live, things people consider important include transportation, educational conditions, residential environment, and convenience facilities."
    },
    {
     "spans": [
      "출퇴근하기 편한지, 다른 지역으로 이동하기 편한지를 고려하는 사람들은 지하철역 주변이나 교통이 편리한 곳을 선호한다. "
     ],
     "translation": "People who consider whether it's convenient to commute to work or travel to other areas prefer areas near subway stations or places with convenient transportation."
    },
    {
     "spans": [
      "자녀 교육을 위한 주변의 여건을 ",
      {
       "word": "중시하",
       "annotation": "중시하"
      },
      "는 사람들은 교육 시설이 ",
      {
       "word": "발달해",
       "annotation": "발달하다"
      },
      " 있는 곳에 집을 구한다. "
     ],
     "translation": "People who prioritize the surrounding conditions for their children's education look for homes in areas where educational facilities are well-developed."
    },
    {
     "spans": [
      "현재의 ",
      {
       "word": "경제적",
       "annotation": "경제적"
      },
      " 상황이나 미래의 계획 등을 고려하여 집을 살 것인지, 전세나 월세 등으로 빌려 쓸 것인지 등을 살펴보고 자신에게 적합한 방식을 선택하는 것이 좋다."
     ],
     "translation": "It's good to consider your current financial situation and future plans, examine whether to buy a house or rent it via jeonse or monthly rent, and choose the method that suits you best."
    }
   ]
  },
  {
   "type": "figure",
   "text": "포장 이사 모습"
  },
  {
   "type": "section",
   "kind": "aside",
   "text": "알아두면 좋아요",
   "topic": "부동산에 갈 시간이 없다면? 온라인으로 알아보세요"
  },
  {
   "type": "paragraph",
   "spans": [
    "거주하거나 구매할 집을 찾고자 할 때 부동산을 직접 방문하지 않고도 온라인으로도 알아볼 수 있다. 부동산 사이트에서 원하는 지역을 선택한 후, 집의 형태(아파트, ",
    {
     "word": "빌라",
     "annotation": "빌라"
    },
    ", 주택, 오피스텔, 상가 등), 거래 방식(매매, 전세, 월세, 단기 임대), 가격대 등에 따라 검색해 볼 수 있다. 다만, 온라인 사이트에서 ",
    {
     "word": "매물",
     "annotation": "매물"
    },
    "(팔려고 내놓은 물건)을 보고 부동산을 방문했는데 방문 직전에 거래가 완료됐다고 하면서 다른 매물을 권유하는 경우도 많으므로 주의해야 한다. 또한 계약하기 전에 주택에 문제가 있는지, 계약을 하러 나온 사람이 진짜 집주인인지 꼭 확인해야 한다. 경우도 있다."
   ]
  },
  {
   "type": "section",
   "kind": "review",
   "text": "주요 내용정리"
  },
  {
   "type": "heading",
   "level": 3,
   "text": "한국인이 많이 살고 있는 집의 형태는 무엇일까?"
  },
  {
   "type": "bullet",
   "spans": [
    "한국인들이 살고 있는 주택은 크게 ",
    {
     "blank": "단독 주택"
    },
    "과 ",
    {
     "blank": "공동 주택"
    },
    "으로 나뉜다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "단독 주택에는 일반 주택, ",
    {
     "blank": "다가구 주택"
    },
    " 등이 있고 공동 주택에는 다세대 주택, 연립 주택, ",
    {
     "blank": "아파트"
    },
    " 등이 포함된다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "공동 주택에 살고 있는 가구 수가 많아지면서 ",
    {
     "blank": "층간 소음"
    },
    "으로 인해 이웃 간의 갈등이 심해지는"
   ]
  },
  {
   "type": "heading",
   "level": 3,
   "text": "한국에서는 집을 어떻게 구할까?"
  },
  {
   "type": "bullet",
   "spans": [
    "한국에서 집에 거주하는 형태는 자가, ",
    {
     "blank": "전세"
    },
    ", 월세가 있는데 이중 ",
    {
     "blank": "전세"
    },
    "는 한국에서만 널리 활용되는 방식이다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "집을 사거나 전세 또는 월세를 구할 때는 ",
    {
     "blank": "부동산 중개업소"
    },
    "를 통해 알아보고 계약서를 작성하는 것이 안전하다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "한국인들이 주거 선택에서 중요하게 여기는 것으로는 편리한 ",
    {
     "blank": "교통"
    },
    ", 교육 여건, 주변 환경의 ",
    {
     "word": "쾌적",
     "annotation": "쾌적"
    },
    "함, 편의 시설 등이 있다."
   ]
  },
  {
   "type": "margin",
   "items": [
    [
     {
      "word": "스세권",
      "annotation": "스세권"
     }
    ],
    [
     {
      "word": "학세권",
      "annotation": "학세권"
     }
    ],
    [
     {
      "word": "역세권",
      "annotation": "역세권"
     }
    ]
   ]
  },
  {
   "type": "section",
   "kind": "discuss",
   "text": "이야기 나누기",
   "topic": "여러 나라의 다양한 이사 문화",
   "titleTranslation": "Moving-house customs in various countries"
  },
  {
   "type": "paragraph",
   "spans": [
    "한국에서는 이사를 하고 나면 ",
    {
     "word": "친척",
     "annotation": "친척"
    },
    "이나 ",
    {
     "word": "친지",
     "annotation": "친지"
    },
    "들을 초대해 ‘",
    {
     "word": "집들이",
     "annotation": "집들이"
    },
    "’라는 간단한 잔치를 베풀기도 하고 예전에는 ‘",
    {
     "word": "이사떡",
     "annotation": "이사떡"
    },
    "’이라 하여 붉은 팥고물을 묻힌 시루떡을 이웃과 나누어 먹기도 하였다. 집들이에 초대 받은 사람들은 보통 ",
    {
     "word": "세제",
     "annotation": "세제"
    },
    "나 화장지를 선물로 사 들고 간다."
   ],
   "translation": "In Korea, after moving house people sometimes invite relatives and friends round for a small party called a 집들이, and in the past they would share 시루떡, a steamed rice cake coated in red bean, with the neighbours as ‘moving-house cake’. Those invited to a 집들이 usually bring detergent or toilet paper as a gift.",
   "sentences": [
    {
     "spans": [
      "한국에서는 이사를 하고 나면 ",
      {
       "word": "친척",
       "annotation": "친척"
      },
      "이나 ",
      {
       "word": "친지",
       "annotation": "친지"
      },
      "들을 초대해 ‘",
      {
       "word": "집들이",
       "annotation": "집들이"
      },
      "’라는 간단한 잔치를 베풀기도 하고 예전에는 ‘",
      {
       "word": "이사떡",
       "annotation": "이사떡"
      },
      "’이라 하여 붉은 팥고물을 묻힌 시루떡을 이웃과 나누어 먹기도 하였다. "
     ],
     "translation": "In Korea, after moving house people sometimes invite relatives and friends round for a small party called a 집들이, and in the past they would share 시루떡, a steamed rice cake coated in red bean, with the neighbours as ‘moving-house cake’."
    },
    {
     "spans": [
      "집들이에 초대 받은 사람들은 보통 ",
      {
       "word": "세제",
       "annotation": "세제"
      },
      "나 화장지를 선물로 사 들고 간다."
     ],
     "translation": "Those invited to a 집들이 usually bring detergent or toilet paper as a gift."
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "미국에서는 House warming이라고 하여 이사를 하거나 집을 새로 지었을 경우 친구나 가족들을 초청하여 파티를 연다."
   ],
   "translation": "In the United States it is called a house warming: when people move or have built a new house they invite friends and family and hold a party.",
   "sentences": [
    {
     "spans": [
      "미국에서는 House warming이라고 하여 이사를 하거나 집을 새로 지었을 경우 친구나 가족들을 초청하여 파티를 연다."
     ],
     "translation": "In the United States it is called a house warming: when people move or have built a new house they invite friends and family and hold a party."
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "중국에서는 이사를 간 후에 폭죽을 터트리는 ",
    {
     "word": "풍습",
     "annotation": "풍습"
    },
    "이 있다. 짧게는 몇 초에서 길게는 몇 분까지 요란한 소리의 폭죽을 터트리는데 이는 이웃에게 우리 가족이 이사를 왔다고 알리는 의미이다. 또한 나쁜 것들이 요란한 소리를 듣고서 다가오지 못하게 하기 위한 목적도 있다. 중국에도 친구나 다른 가족을 초대하여 집들이 하는 문화가 있다."
   ],
   "translation": "In China there is a custom of setting off firecrackers after moving in. They let off loud firecrackers for anything from a few seconds to a few minutes, which is a way of telling the neighbours that the family has moved in. It also serves to keep bad things from coming near, since they hear the din. China too has a custom of inviting friends and other families round to warm the house.",
   "sentences": [
    {
     "spans": [
      "중국에서는 이사를 간 후에 폭죽을 터트리는 ",
      {
       "word": "풍습",
       "annotation": "풍습"
      },
      "이 있다. "
     ],
     "translation": "In China there is a custom of setting off firecrackers after moving in."
    },
    {
     "spans": [
      "짧게는 몇 초에서 길게는 몇 분까지 요란한 소리의 폭죽을 터트리는데 이는 이웃에게 우리 가족이 이사를 왔다고 알리는 의미이다. "
     ],
     "translation": "They let off loud firecrackers for anything from a few seconds to a few minutes, which is a way of telling the neighbours that the family has moved in."
    },
    {
     "spans": [
      "또한 나쁜 것들이 요란한 소리를 듣고서 다가오지 못하게 하기 위한 목적도 있다. "
     ],
     "translation": "It also serves to keep bad things from coming near, since they hear the din."
    },
    {
     "spans": [
      "중국에도 친구나 다른 가족을 초대하여 집들이 하는 문화가 있다."
     ],
     "translation": "China too has a custom of inviting friends and other families round to warm the house."
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "러시아에서는 고양이가 행운을 가져다주는 존재라고 생각한다. 그래서 이사를 하게 되면 고양이를 데리고 들어가거나 고양이를 집안에 먼저 들여보내 그 집안의 기운을 살펴보기도 한다."
   ],
   "translation": "In Russia the cat is thought of as something that brings good fortune. So when people move they take the cat in with them, or send the cat into the house first to see what the spirit of the place is like.",
   "sentences": [
    {
     "spans": [
      "러시아에서는 고양이가 행운을 가져다주는 존재라고 생각한다. "
     ],
     "translation": "In Russia the cat is thought of as something that brings good fortune."
    },
    {
     "spans": [
      "그래서 이사를 하게 되면 고양이를 데리고 들어가거나 고양이를 집안에 먼저 들여보내 그 집안의 기운을 살펴보기도 한다."
     ],
     "translation": "So when people move they take the cat in with them, or send the cat into the house first to see what the spirit of the place is like."
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "★ 자신의 고향 나라의 이사 문화를 한국의 이사 문화와 비교하여 이야기 해 봅시다."
   ],
   "translation": "Compare the moving-house customs of your home country with Korea’s and talk about them.",
   "role": "prompt",
   "sentences": [
    {
     "spans": [
      "★ 자신의 고향 나라의 이사 문화를 한국의 이사 문화와 비교하여 이야기 해 봅시다."
     ],
     "translation": "Compare the moving-house customs of your home country with Korea’s and talk about them."
    }
   ]
  }
 ],
 "annotations": {
  "형태": {
   "headword": "형태",
   "hanja": null,
   "meaning": "shape",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "세": {
   "headword": "세",
   "hanja": "貰",
   "meaning": "rent, the money paid for use",
   "characters": [
    {
     "char": "貰",
     "reading": "세",
     "gloss": "to hire, rent — as in 전세, 월세, 세입자"
    }
   ],
   "notes": [
    "세를 들다 is to take a tenancy, 세를 내다 to pay the rent. Not the 세 of 세금 “tax”, which is 稅, nor the 세 of 세제 “detergent”, 洗."
   ],
   "surfaces": []
  },
  "단독": {
   "headword": "단독",
   "hanja": null,
   "meaning": "single/alone/independent",
   "characters": [],
   "notes": [
    "단독 주택 = a standalone single-family house."
   ],
   "surfaces": []
  },
  "공동": {
   "headword": "공동",
   "hanja": null,
   "meaning": "joint/shared/communal",
   "characters": [],
   "notes": [
    "공동 주택 = jointly-occupied multi-unit housing."
   ],
   "surfaces": []
  },
  "연립": {
   "headword": "연립",
   "hanja": null,
   "meaning": "row/joined together",
   "characters": [],
   "notes": [
    "연립 주택 = row houses/townhouses, units standing side by side."
   ],
   "surfaces": []
  },
  "지은": {
   "headword": "지은",
   "hanja": null,
   "meaning": "짓다 — to build",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "차지하며": {
   "headword": "차지하다",
   "hanja": null,
   "meaning": "to occupy/take up [space/position]",
   "characters": [],
   "notes": [
    "각각의 독립적인 공간을 차지하며 살다 = \"living while each occupying their own independent space\""
   ],
   "surfaces": []
  },
  "다가구": {
   "headword": "다가구",
   "hanja": null,
   "meaning": "multi-household",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "소유권": {
   "headword": "소유권",
   "hanja": "所有權",
   "meaning": "title, right of ownership",
   "characters": [
    {
     "char": "所",
     "reading": "소",
     "gloss": "place, that which — as in 주소 “address”"
    },
    {
     "char": "有",
     "reading": "유",
     "gloss": "to have — as in 유용하다 “useful”, 고유 “inherent”"
    },
    {
     "char": "權",
     "reading": "권",
     "gloss": "right, authority — the same 權 as in 권위"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "거공간": {
   "headword": "거공간",
   "hanja": null,
   "meaning": "주거공간 — living space/residential space",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "면적": {
   "headword": "면적",
   "hanja": null,
   "meaning": "area (surface measurement",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "수백": {
   "headword": "수백",
   "hanja": null,
   "meaning": "several hundred",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "수 천": {
   "headword": "수천",
   "hanja": null,
   "meaning": "several thousand",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "대규모": {
   "headword": "대규모",
   "hanja": "大規模",
   "meaning": "on a large scale",
   "characters": [
    {
     "char": "規",
     "reading": "규",
     "gloss": "rule, standard — as in 규칙 “rule”, 규정"
    },
    {
     "char": "模",
     "reading": "모",
     "gloss": "pattern, model — as in 모양 “shape”, 모방하다"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "층간 소음": {
   "headword": "층간 소음",
   "hanja": "層間騷音",
   "meaning": "noise between floors",
   "characters": [
    {
     "char": "層",
     "reading": "층",
     "gloss": "storey, layer — as in 1층, 계층 “stratum”"
    },
    {
     "char": "間",
     "reading": "간",
     "gloss": "between — the same 間 as in 가족 간, 시간"
    },
    {
     "char": "騷",
     "reading": "소",
     "gloss": "clamour, disturbance"
    },
    {
     "char": "音",
     "reading": "음",
     "gloss": "sound — the same 音 as in 훈민정음, 발음"
    }
   ],
   "notes": [
    "A standing subject of dispute in Korean flats, and the reason the passage gives for friction between neighbours."
   ],
   "surfaces": []
  },
  "쾌적": {
   "headword": "쾌적",
   "hanja": null,
   "meaning": "pleasant/comfortable",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "한적": {
   "headword": "한적",
   "hanja": null,
   "meaning": "quiet/secluded",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "전원 주택": {
   "headword": "전원 주택",
   "hanja": "田園住宅",
   "meaning": "a country house",
   "characters": [
    {
     "char": "田",
     "reading": "전",
     "gloss": "field, paddy — as in 전답"
    },
    {
     "char": "園",
     "reading": "원",
     "gloss": "garden — as in 공원 “park”, 유치원"
    }
   ],
   "notes": [
    "Built a little away from the city so the feel of nature can be had, which is how the page glosses it."
   ],
   "surfaces": []
  },
  "인구": {
   "headword": "인구",
   "hanja": null,
   "meaning": "population",
   "characters": [],
   "notes": [
    "인구가 집중되다 = \"population becomes concentrated\""
   ],
   "surfaces": []
  },
  "대체로": {
   "headword": "대체로",
   "hanja": null,
   "meaning": "generally/on the whole",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "체력 단련실": {
   "headword": "체력 단련실",
   "hanja": null,
   "meaning": "fitness/exercise room",
   "characters": [],
   "notes": [
    "體力 (physical strength) + 단련 (training/tempering) + 실 (room)"
   ],
   "surfaces": []
  },
  "시설": {
   "headword": "시설",
   "hanja": null,
   "meaning": "facility",
   "characters": [],
   "notes": [
    "편의 시설 = \"convenience facilities/amenities\""
   ],
   "surfaces": []
  },
  "갖추어져": {
   "headword": "갖추다",
   "hanja": null,
   "meaning": "to equip/have prepared",
   "characters": [],
   "notes": [
    "편의 시설이 갖추어져 있다 = \"amenities are equipped/in place\""
   ],
   "surfaces": []
  },
  "갈등": {
   "headword": "갈등",
   "hanja": null,
   "meaning": "conflict",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "수요": {
   "headword": "수요",
   "hanja": null,
   "meaning": "demand (economic term)",
   "characters": [],
   "notes": [
    "공급 — \"supply"
   ],
   "surfaces": []
  },
  "노년": {
   "headword": "노년",
   "hanja": "老年",
   "meaning": "old age, one's later years",
   "characters": [
    {
     "char": "老",
     "reading": "노",
     "gloss": "old — as in 노인 “an old person”, 독거노인"
    },
    {
     "char": "年",
     "reading": "년",
     "gloss": "year — the same 年 as in 연령 “age”, 작년"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "사회초년생": {
   "headword": "사회초년생",
   "hanja": null,
   "meaning": "someone new to working life",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "세입자": {
   "headword": "세입자",
   "hanja": "貰入者",
   "meaning": "a tenant",
   "characters": [
    {
     "char": "貰",
     "reading": "세",
     "gloss": "rent"
    },
    {
     "char": "入",
     "reading": "입",
     "gloss": "to enter — as in 입구 “entrance”, 수입"
    },
    {
     "char": "者",
     "reading": "자",
     "gloss": "person"
    }
   ],
   "notes": [
    "Literally the person who has entered on a tenancy — 세를 들어 사는 사람, as the passage puts it of the 다가구 주택."
   ],
   "surfaces": []
  },
  "파기": {
   "headword": "파기",
   "hanja": "破棄",
   "meaning": "to break off, annul",
   "characters": [
    {
     "char": "破",
     "reading": "파",
     "gloss": "to break — as in 파괴 “destruction”"
    },
    {
     "char": "棄",
     "reading": "기",
     "gloss": "to discard, abandon — as in 포기 “giving up”"
    }
   ],
   "notes": [
    "Used of contracts and promises: 계약을 파기하다."
   ],
   "surfaces": []
  },
  "확정 일자": {
   "headword": "확정 일자",
   "hanja": "確定日字",
   "meaning": "a certified date",
   "characters": [
    {
     "char": "確",
     "reading": "확",
     "gloss": "certain — the same 確 as in 명확하다, 확인"
    },
    {
     "char": "定",
     "reading": "정",
     "gloss": "to fix, settle — as in 결정 “decision”, 정하다"
    },
    {
     "char": "日",
     "reading": "일",
     "gloss": "day"
    },
    {
     "char": "字",
     "reading": "자",
     "gloss": "character, letter — the 字 of 문자, 한자"
    }
   ],
   "notes": [
    "A date stamped on a lease by a court or the 행정복지센터 to prove when it was made. It is what protects the deposit's priority if the property is later sold or seized, which is why the page says to get one around the time of moving."
   ],
   "surfaces": []
  },
  "중개": {
   "headword": "중개",
   "hanja": "仲介",
   "meaning": "brokerage, acting between two parties",
   "characters": [
    {
     "char": "仲",
     "reading": "중",
     "gloss": "middle, to mediate"
    },
    {
     "char": "介",
     "reading": "개",
     "gloss": "to introduce, come between — as in 소개"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "부동산/중개 업소": {
   "headword": "부동산 중개 업소",
   "hanja": null,
   "meaning": "real estate/brokerage office",
   "characters": [],
   "notes": [
    "an office that represents or mediates real estate transactions on someone's behalf in exchange for a commission (수수료)"
   ],
   "surfaces": []
  },
  "자가": {
   "headword": "자가",
   "hanja": "自家",
   "meaning": "owning the home one lives in",
   "characters": [
    {
     "char": "自",
     "reading": "자",
     "gloss": "self — the same 自 as in 자가용 “private car”"
    },
    {
     "char": "家",
     "reading": "가",
     "gloss": "house, household"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "일정한": {
   "headword": "일정한",
   "hanja": null,
   "meaning": "fixed/set/certain (amount)",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "보증금": {
   "headword": "보증금",
   "hanja": "保證金",
   "meaning": "a deposit",
   "characters": [
    {
     "char": "保",
     "reading": "보",
     "gloss": "to protect, guarantee — as in 보호, 보험"
    },
    {
     "char": "證",
     "reading": "증",
     "gloss": "proof — as in 증명 “proof”, 신분증"
    },
    {
     "char": "金",
     "reading": "금",
     "gloss": "money, gold — the same 金 as in 임금 “wages”"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "맡기": {
   "headword": "맡기다",
   "hanja": null,
   "meaning": "to entrust/deposit [something with someone]",
   "characters": [],
   "notes": [
    "돈을 맡기다 = \"to entrust/deposit money [with the landlord].\""
   ],
   "surfaces": []
  },
  "혼합한": {
   "headword": "혼합하다",
   "hanja": null,
   "meaning": "to mix/combine",
   "characters": [],
   "notes": [
    "전세와 월세를 혼합한 방식 = \"a method that combines jeonse and monthly rent.\""
   ],
   "surfaces": []
  },
  "포장 이사": {
   "headword": "포장 이사",
   "hanja": "包裝이사",
   "meaning": "a packing removal service",
   "characters": [
    {
     "char": "包",
     "reading": "포",
     "gloss": "to wrap — as in 포함 “inclusion”, 소포 “parcel”"
    },
    {
     "char": "裝",
     "reading": "장",
     "gloss": "to fit out, equip — as in 장비 “equipment”"
    }
   ],
   "notes": [
    "The firm packs everything as well as carrying it, which the page says is now what most people use."
   ],
   "surfaces": []
  },
  "여건": {
   "headword": "여건",
   "hanja": "與件",
   "meaning": "conditions, the given circumstances",
   "characters": [
    {
     "char": "與",
     "reading": "여",
     "gloss": "to give, grant"
    },
    {
     "char": "件",
     "reading": "건",
     "gloss": "matter, item — as in 사건 “incident”, 조건"
    }
   ],
   "notes": [
    "교육 여건 is the conditions for education in an area — the schools and what surrounds them, not the schooling itself."
   ],
   "surfaces": []
  },
  "주거": {
   "headword": "주거",
   "hanja": null,
   "meaning": "residence/dwelling",
   "characters": [],
   "notes": [
    "a general term for \"housing/residence\" as a concept",
    "주거 환경 = \"residential environment\"",
    "주거 형태 = \"housing form/type\""
   ],
   "surfaces": []
  },
  "편의 시설": {
   "headword": "편의 시설",
   "hanja": null,
   "meaning": "convenience facilities/amenities",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "중시하": {
   "headword": "중시하다",
   "hanja": null,
   "meaning": "to place importance on/value highly",
   "characters": [],
   "notes": [
    "교육 여건을 중시하다 = \"to place importance on educational conditions.\""
   ],
   "surfaces": []
  },
  "발달하다": {
   "headword": "발달하다",
   "hanja": null,
   "meaning": "to develop",
   "characters": [],
   "notes": [
    "교육 시설이 발달해 있는 곳 = \"a place where educational facilities are well-developed.\""
   ],
   "surfaces": [
    "발달해"
   ]
  },
  "경제적": {
   "headword": "경제적",
   "hanja": null,
   "meaning": "economic",
   "characters": [],
   "notes": [
    "경제적 상황 = \"economic/financial situation.\""
   ],
   "surfaces": []
  },
  "단독 주택": {
   "headword": "단독 주택",
   "hanja": "單獨住宅",
   "meaning": "a detached house",
   "characters": [
    {
     "char": "單",
     "reading": "단",
     "gloss": "single — as in 단순 “simple”, 단어 “word”"
    },
    {
     "char": "獨",
     "reading": "독",
     "gloss": "alone — as in 독립 “independence”, 독거 “living alone”"
    },
    {
     "char": "住",
     "reading": "주",
     "gloss": "to dwell — as in 주거, 주소 “address”"
    },
    {
     "char": "宅",
     "reading": "택",
     "gloss": "house — the same 宅 as in 택배 “home delivery”"
    }
   ],
   "notes": [
    "One building for one household, as against 공동 주택. The page counts the 다가구 주택 as a kind of it, which is the part worth remembering: 단독 does not always mean one family."
   ],
   "surfaces": []
  },
  "공동 주택": {
   "headword": "공동 주택",
   "hanja": "共同住宅",
   "meaning": "shared housing",
   "characters": [
    {
     "char": "共",
     "reading": "공",
     "gloss": "together — as in 공공 “public”, 공유 “sharing”"
    },
    {
     "char": "同",
     "reading": "동",
     "gloss": "same — as in 동시 “simultaneous”, 동료 “colleague”"
    }
   ],
   "notes": [
    "Several households living independently inside one building: 다세대 주택, 연립 주택 and 아파트."
   ],
   "surfaces": []
  },
  "다가구 주택": {
   "headword": "다가구 주택",
   "hanja": "多家口住宅",
   "meaning": "a multi-household house",
   "characters": [
    {
     "char": "多",
     "reading": "다",
     "gloss": "many — as in 다양 “various”, 다문화"
    },
    {
     "char": "家",
     "reading": "가",
     "gloss": "household"
    },
    {
     "char": "口",
     "reading": "구",
     "gloss": "mouth, a person counted — the 口 of 가구, 인구"
    }
   ],
   "notes": [
    "Three storeys or fewer, one owner for the whole building and the other households renting. Told apart from 다세대 주택 by exactly that: who owns what."
   ],
   "surfaces": []
  },
  "다세대 주택": {
   "headword": "다세대 주택",
   "hanja": "多世帶住宅",
   "meaning": "a multi-family house",
   "characters": [
    {
     "char": "世",
     "reading": "세",
     "gloss": "generation, world — as in 세대, 세계"
    },
    {
     "char": "帶",
     "reading": "대",
     "gloss": "band, belt — 세대 together meaning a household"
    }
   ],
   "notes": [
    "Each part of the building is separately owned, which is what distinguishes it from 다가구 주택."
   ],
   "surfaces": []
  },
  "연립 주택": {
   "headword": "연립 주택",
   "hanja": "聯立住宅",
   "meaning": "a row house, a low-rise block",
   "characters": [
    {
     "char": "聯",
     "reading": "연",
     "gloss": "to join, link — as in 연결 “connection”, 연합"
    },
    {
     "char": "立",
     "reading": "립",
     "gloss": "to stand — the same 立 as in 설립 “to establish”"
    }
   ],
   "notes": [
    "Four storeys or fewer, with a greater total floor area than a 다세대 주택, and often living space in the basement."
   ],
   "surfaces": []
  },
  "쾌적하다": {
   "headword": "쾌적하다",
   "hanja": "快適",
   "meaning": "to be pleasant, agreeable",
   "characters": [
    {
     "char": "快",
     "reading": "쾌",
     "gloss": "pleasant, quick — as in 쾌속 “high speed”"
    },
    {
     "char": "適",
     "reading": "적",
     "gloss": "to suit — as in 적합하다 “suitable”, 적당하다"
    }
   ],
   "notes": [
    "Used of surroundings rather than of people: 쾌적한 자연환경, 쾌적한 실내."
   ],
   "surfaces": []
  },
  "한적하다": {
   "headword": "한적하다",
   "hanja": "閑寂",
   "meaning": "to be quiet and secluded",
   "characters": [
    {
     "char": "閑",
     "reading": "한",
     "gloss": "leisure, idle — as in 한가하다 “to be free”"
    },
    {
     "char": "寂",
     "reading": "적",
     "gloss": "still, lonely — as in 적막 “silence”"
    }
   ],
   "notes": [
    "Glossed on the page as 한가하고 고요함. A different 한 from the one in 한국 or 한글."
   ],
   "surfaces": []
  },
  "원룸": {
   "headword": "원룸",
   "hanja": null,
   "meaning": "a studio flat",
   "characters": [],
   "notes": [
    "From English “one room”, but Korean-made: a single room holding the living space, kitchen and bathroom together. Demand for them rises with one- and two-person households."
   ],
   "surfaces": []
  },
  "기초생활수급자": {
   "headword": "기초생활수급자",
   "hanja": "基礎生活受給者",
   "meaning": "a recipient of basic living support",
   "characters": [
    {
     "char": "基",
     "reading": "기",
     "gloss": "foundation — as in 기본 “basic”, 기초"
    },
    {
     "char": "礎",
     "reading": "초",
     "gloss": "cornerstone"
    },
    {
     "char": "受",
     "reading": "수",
     "gloss": "to receive — as in 수입 “income”"
    },
    {
     "char": "給",
     "reading": "급",
     "gloss": "to give, supply — as in 보급 “distribution”, 공급"
    },
    {
     "char": "者",
     "reading": "자",
     "gloss": "person — as in 근로자 “worker”, 세입자"
    }
   ],
   "notes": [
    "The legal term for a household receiving the state's basic livelihood benefit, and the group the page names first among those public rental housing is for."
   ],
   "surfaces": []
  },
  "전세": {
   "headword": "전세",
   "hanja": "傳貰",
   "meaning": "a lump-sum deposit lease",
   "characters": [
    {
     "char": "傳",
     "reading": "전",
     "gloss": "to hand over, pass on — as in 전달, 전통"
    },
    {
     "char": "貰",
     "reading": "세",
     "gloss": "to hire, rent — the 貰 of 월세, 세입자"
    }
   ],
   "notes": [
    "A large deposit is left with the owner instead of monthly rent and returned at the end of the term. The page says it is used widely only in Korea, which is why it has no English name.",
    "Usually two-year terms, and the owner cannot break the contract inside them unless the tenant wants it."
   ],
   "surfaces": []
  },
  "월세": {
   "headword": "월세",
   "hanja": "月貰",
   "meaning": "monthly rent",
   "characters": [
    {
     "char": "月",
     "reading": "월",
     "gloss": "month — as in 월요일, 매월"
    },
    {
     "char": "貰",
     "reading": "세",
     "gloss": "to hire, rent — the 貰 of 전세"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "반전세": {
   "headword": "반전세",
   "hanja": "半傳貰",
   "meaning": "a half-전세, part deposit and part monthly rent",
   "characters": [
    {
     "char": "半",
     "reading": "반",
     "gloss": "half — as in 반년 “half a year”, 후반"
    }
   ],
   "notes": [
    "Its deposit sits between the two: smaller than a 전세 deposit, larger than a 월세 one."
   ],
   "surfaces": []
  },
  "부동산": {
   "headword": "부동산",
   "hanja": "不動産",
   "meaning": "real estate",
   "characters": [
    {
     "char": "不",
     "reading": "부",
     "gloss": "not — as in 불편 “inconvenient”"
    },
    {
     "char": "動",
     "reading": "동",
     "gloss": "to move — as in 운동 “exercise”, 활동"
    },
    {
     "char": "産",
     "reading": "산",
     "gloss": "property, to produce — the same 産 as in 산업"
    }
   ],
   "notes": [
    "Literally “immovable property”, against 동산 for movables. In speech 부동산 also means the agency itself: 부동산에 가다 is to go to the estate agent."
   ],
   "surfaces": []
  },
  "매물": {
   "headword": "매물",
   "hanja": "賣物",
   "meaning": "a property on the market",
   "characters": [
    {
     "char": "賣",
     "reading": "매",
     "gloss": "to sell — as in 판매 “sales”, 매매"
    },
    {
     "char": "物",
     "reading": "물",
     "gloss": "thing — as in 물건 “article”, 소화물"
    }
   ],
   "notes": [
    "Glossed in line on the page as 팔려고 내놓은 물건."
   ],
   "surfaces": []
  },
  "양옥": {
   "headword": "양옥",
   "hanja": "洋屋",
   "meaning": "a Western-style house",
   "characters": [
    {
     "char": "洋",
     "reading": "양",
     "gloss": "ocean, Western — as in 서양 “the West”, 양식"
    },
    {
     "char": "屋",
     "reading": "옥",
     "gloss": "house — the same 屋 as in 한옥"
    }
   ],
   "notes": [
    "The counterpart of the 한옥: built to a Western plan, of brick or concrete, with rooms off a hallway rather than around a courtyard. Both are 단독 주택 — one household to a building."
   ],
   "surfaces": []
  },
  "한옥": {
   "headword": "한옥",
   "hanja": "韓屋",
   "meaning": "a Korean traditional house",
   "characters": [
    {
     "char": "韓",
     "reading": "한",
     "gloss": "Korea — the same 韓 as in 한국, 대한민국"
    },
    {
     "char": "屋",
     "reading": "옥",
     "gloss": "house"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "빌라": {
   "headword": "빌라",
   "hanja": null,
   "meaning": "a low-rise block of flats",
   "characters": [],
   "notes": [
    "From “villa”, but in Korean it means a small block of a few storeys — roughly the 다세대 주택 or 연립 주택 of this chapter, not a grand house."
   ],
   "surfaces": []
  },
  "아파트": {
   "headword": "아파트",
   "hanja": null,
   "meaning": "a flat, an apartment block",
   "characters": [],
   "notes": [
    "From “apartment”. Five storeys or more, per the page, and usually a whole estate rather than a single building."
   ],
   "surfaces": []
  },
  "스세권": {
   "headword": "스세권",
   "hanja": null,
   "meaning": "within walking distance of a Starbucks",
   "characters": [],
   "notes": [
    "A joke on 역세권, swapping 역 for the 스 of 스타벅스, and formed the same way as 학세권. Your own note in the margin of p. 35."
   ],
   "surfaces": []
  },
  "학세권": {
   "headword": "학세권",
   "hanja": "學勢圈",
   "meaning": "within easy reach of schools",
   "characters": [
    {
     "char": "學",
     "reading": "학",
     "gloss": "to learn — the same 學 as in 학교, 학습"
    }
   ],
   "notes": [
    "Built on 역세권 by swapping the first character."
   ],
   "surfaces": []
  },
  "역세권": {
   "headword": "역세권",
   "hanja": "驛勢圈",
   "meaning": "the catchment of a station",
   "characters": [
    {
     "char": "驛",
     "reading": "역",
     "gloss": "station — as in 지하철역, 역장"
    },
    {
     "char": "勢",
     "reading": "세",
     "gloss": "force, influence — as in 형세, 기세"
    },
    {
     "char": "圈",
     "reading": "권",
     "gloss": "sphere, zone — the same 圈 as in 생활권"
    }
   ],
   "notes": [
    "The area close enough to a station to be worth paying for, and the original of which 학세권 and 스세권 are jokes."
   ],
   "surfaces": []
  },
  "친척": {
   "headword": "친척",
   "hanja": "親戚",
   "meaning": "relatives",
   "characters": [
    {
     "char": "親",
     "reading": "친",
     "gloss": "close, kin — the same 親 as in 친사촌, 친밀하다"
    },
    {
     "char": "戚",
     "reading": "척",
     "gloss": "kin by marriage"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "친지": {
   "headword": "친지",
   "hanja": "親知",
   "meaning": "close acquaintances",
   "characters": [
    {
     "char": "親",
     "reading": "친",
     "gloss": "close"
    },
    {
     "char": "知",
     "reading": "지",
     "gloss": "to know — as in 지식 “knowledge”, 지인"
    }
   ],
   "notes": [
    "Not relatives but people one knows well — paired with 친척 in the passage to mean everyone one would invite."
   ],
   "surfaces": []
  },
  "집들이": {
   "headword": "집들이",
   "hanja": null,
   "meaning": "a housewarming",
   "characters": [],
   "notes": [
    "Native Korean: 집 “house” plus 들이 from 들이다 “to bring in”. Guests usually bring detergent or toilet paper, per the page."
   ],
   "surfaces": []
  },
  "이사떡": {
   "headword": "이사떡",
   "hanja": null,
   "meaning": "moving-day rice cake",
   "characters": [],
   "notes": [
    "시루떡 coated in red bean, shared with the neighbours on moving in. The red was thought to keep bad things off — the same reason the page gives for the Chinese firecrackers."
   ],
   "surfaces": []
  },
  "세제": {
   "headword": "세제",
   "hanja": "洗劑",
   "meaning": "detergent",
   "characters": [
    {
     "char": "洗",
     "reading": "세",
     "gloss": "to wash — as in 세수, 세탁 “laundry”"
    },
    {
     "char": "劑",
     "reading": "제",
     "gloss": "preparation, agent — as in 약제"
    }
   ],
   "notes": [
    "A different 세 from the 貰 of 전세 and 월세 in this same chapter."
   ],
   "surfaces": []
  },
  "풍습": {
   "headword": "풍습",
   "hanja": "風習",
   "meaning": "a custom",
   "characters": [
    {
     "char": "風",
     "reading": "풍",
     "gloss": "wind, manner — as in 풍경 “scenery”, 태풍"
    },
    {
     "char": "習",
     "reading": "습",
     "gloss": "to practise — the same 習 as in 학습, 습관"
    }
   ],
   "notes": [],
   "surfaces": []
  }
 },
 "notes": [
  {
   "why": "The four photos on p. 32 are two 단독 주택 (양옥, 한옥) over two 공동 주택 (빌라, 아파트), which is the division the first article then explains. The handwriting on the page names the two kinds beside the rows; here the labels are grouped under them."
  }
 ],
 "slug": "05-housing"
});
