/* Generated by tools/build.py — do not edit.
   Content lives in tools/chapters/ch07_welfare.py; rebuild after changing it. */

KIIP.chapter({
 "number": 7,
 "unit": "사회",
 "title": "복지",
 "titleEnglish": "Welfare",
 "chapterGlossary": [],
 "blocks": [
  {
   "type": "section",
   "kind": "warmup",
   "text": "생각해 봅시다"
  },
  {
   "type": "paragraph",
   "spans": [
    "다음은 한국에서 생활하면서 겪을 수 있는 상황을 나타낸 것입니다"
   ]
  },
  {
   "type": "figure",
   "text": "일하다가 다친 모습 · 회사에서 해고된 모습 · 장애가 있는 사람의 모습 · 나이가 들어 걷기 어려운 모습"
  },
  {
   "type": "heading",
   "level": 4,
   "text": "01 자신의 고향 나라에서는 이런 경우 어떻게 대응합니까?"
  },
  {
   "type": "heading",
   "level": 4,
   "text": "02 본인은 한국에서 이와 같은 상황에 대비하여 무엇을 준비하고 있습니까?"
  },
  {
   "type": "section",
   "kind": "goals",
   "text": "학습목표"
  },
  {
   "type": "bullet",
   "spans": [
    "최소한의 인간다운 삶을 보장하는 한국의 사회 복지 제도를 설명할 수 있다."
   ],
   "ordered": true
  },
  {
   "type": "bullet",
   "spans": [
    "외국인 대상 복지 서비스를 이해하고 이용할 수 있다."
   ],
   "ordered": true
  },
  {
   "type": "section",
   "kind": "related",
   "text": "관련 단원 확인하기"
  },
  {
   "type": "table",
   "header": [
    {
     "text": "영역",
     "span": 2
    },
    "제목",
    "관련 내용"
   ],
   "rows": [
    [
     "심화",
     "국민",
     "4. 대한민국 국민을 위한 복지",
     "사회보험, 공공부조"
    ]
   ]
  },
  {
   "type": "section",
   "kind": "part",
   "text": "01 한국의 사회 복지 제도에는 어떤 것들이 있을까?"
  },
  {
   "type": "margin",
   "items": [
    [
     {
      "word": "4대 보험",
      "annotation": "4대 보험"
     }
    ]
   ]
  },
  {
   "type": "heading",
   "level": 2,
   "text": "사회보험",
   "titleTranslation": "Social Insurance"
  },
  {
   "type": "paragraph",
   "spans": [
    "한국에서는 국민이 ",
    {
     "word": "최소한",
     "annotation": "최소한"
    },
    "의 ",
    {
     "word": "인간다운",
     "annotation": "인간다운"
    },
    " 삶을 ",
    {
     "word": "누릴",
     "annotation": "누릴"
    },
    " 수 있도록 다양한 사회 복지 제도를 ",
    {
     "word": "마련해",
     "annotation": "마련해"
    },
    " 두고 있다. 한국의 사회 복지 제도는 크게 ",
    {
     "word": "사회보험",
     "annotation": "사회보험"
    },
    "과 ",
    {
     "word": "공공부조",
     "annotation": "공공부조"
    },
    "로 나눌 수 있다."
   ],
   "translation": "Korea has put in place a range of social welfare arrangements so that its people may enjoy at least a life fit for a human being. They divide broadly into social insurance and public assistance.",
   "sentences": [
    {
     "spans": [
      "한국에서는 국민이 ",
      {
       "word": "최소한",
       "annotation": "최소한"
      },
      "의 ",
      {
       "word": "인간다운",
       "annotation": "인간다운"
      },
      " 삶을 ",
      {
       "word": "누릴",
       "annotation": "누릴"
      },
      " 수 있도록 다양한 사회 복지 제도를 ",
      {
       "word": "마련해",
       "annotation": "마련해"
      },
      " 두고 있다. "
     ],
     "translation": "Korea has put in place a range of social welfare arrangements so that its people may enjoy at least a life fit for a human being."
    },
    {
     "spans": [
      "한국의 사회 복지 제도는 크게 ",
      {
       "word": "사회보험",
       "annotation": "사회보험"
      },
      "과 ",
      {
       "word": "공공부조",
       "annotation": "공공부조"
      },
      "로 나눌 수 있다."
     ],
     "translation": "They divide broadly into social insurance and public assistance."
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "사회보험은 미래의 위험에 ",
    {
     "word": "대비하여",
     "annotation": "대비하여"
    },
    " 법에 따라 국민들이 ",
    {
     "word": "가입",
     "annotation": "가입"
    },
    "하도록 하고 있는 제도이다. 여기에는 ",
    {
     "word": "건강보험",
     "annotation": "건강보험"
    },
    ", ",
    {
     "word": "고용보험",
     "annotation": "고용보험"
    },
    ", ",
    {
     "word": "국민연금",
     "annotation": "국민연금"
    },
    ", ",
    {
     "word": "산업재해보상보험",
     "annotation": "산업재해보상보험"
    },
    "이 있다."
   ],
   "translation": "Social insurance is a system the people are required by law to join, against the risks of the future. It comprises health insurance, employment insurance, the national pension and industrial accident compensation insurance.",
   "sentences": [
    {
     "spans": [
      "사회보험은 미래의 위험에 ",
      {
       "word": "대비하여",
       "annotation": "대비하여"
      },
      " 법에 따라 국민들이 ",
      {
       "word": "가입",
       "annotation": "가입"
      },
      "하도록 하고 있는 제도이다. "
     ],
     "translation": "Social insurance is a system the people are required by law to join, against the risks of the future."
    },
    {
     "spans": [
      "여기에는 ",
      {
       "word": "건강보험",
       "annotation": "건강보험"
      },
      ", ",
      {
       "word": "고용보험",
       "annotation": "고용보험"
      },
      ", ",
      {
       "word": "국민연금",
       "annotation": "국민연금"
      },
      ", ",
      {
       "word": "산업재해보상보험",
       "annotation": "산업재해보상보험"
      },
      "이 있다."
     ],
     "translation": "It comprises health insurance, employment insurance, the national pension and industrial accident compensation insurance."
    }
   ]
  },
  {
   "type": "table",
   "header": [
    "건강보험",
    {
     "spans": [
      "아파서 병원에 갈 때 의료비의 ",
      {
       "word": "일부",
       "annotation": "일부"
      },
      "를 지원 받을 수 있다."
     ]
    }
   ],
   "rows": [
    [
     "고용보험",
     {
      "spans": [
       "회사에서 ",
       {
        "word": "해고되었을",
        "annotation": "해고"
       },
       " 때 일정 기간 ",
       {
        "word": "금전적",
        "annotation": "금전적"
       },
       " 지원을 받을 수 있다"
      ]
     }
    ],
    [
     "국민연금",
     {
      "spans": [
       "나이가 들어 더 이상 돈을 벌기 어려울 때 매달 일정 금액을 생활비로 ",
       {
        "word": "지급",
        "annotation": "지급"
       },
       " 받을 수 있다."
      ]
     }
    ],
    [
     "산업재해보상보험",
     {
      "spans": [
       "회사에서 일하다가 사고로 다쳤을 때 병원비 등 피해에 대해 ",
       {
        "word": "보상",
        "annotation": "보상"
       },
       "을 받을 수 있다."
      ]
     }
    ]
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "개인보험"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "생명보험"
   ],
   "level": 2
  },
  {
   "type": "bullet",
   "spans": [
    "손해보험"
   ],
   "level": 2
  },
  {
   "type": "bullet",
   "spans": [
    "교육보험"
   ],
   "level": 2
  },
  {
   "type": "bullet",
   "spans": [
    "사회보험"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "연금보험"
   ],
   "level": 2
  },
  {
   "type": "bullet",
   "spans": [
    "국민건강보험"
   ],
   "level": 2
  },
  {
   "type": "bullet",
   "spans": [
    "고용보험"
   ],
   "level": 2
  },
  {
   "type": "bullet",
   "spans": [
    "산재"
   ],
   "level": 2
  },
  {
   "type": "margin",
   "items": [
    [
     {
      "word": "국민연금공단",
      "annotation": "국민연금공단"
     }
    ],
    [
     "국민연금 업무를 담당하는 기관"
    ],
    [
     "문의:1355, www.nps.or.kr"
    ]
   ]
  },
  {
   "type": "heading",
   "level": 2,
   "text": "공공부조",
   "titleTranslation": "Public assistance"
  },
  {
   "type": "glossary",
   "entries": [
    {
     "term": "최저 생계비",
     "definition": [
      "생활에 필요한 최소한의 비용"
     ],
     "annotation": "최저 생계비"
    },
    {
     "term": "저소득층",
     "definition": [
      "소득이 낮아 경제적 지원이 필요한 사람들"
     ],
     "annotation": "저소득층"
    },
    {
     "term": "생계",
     "definition": [
      "살아 나가는 형편"
     ],
     "annotation": "생계"
    },
    {
     "term": "긴급",
     "definition": [
      "중요하고 급함"
     ],
     "annotation": "긴급"
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "공공부조는 생활이 어려운 사람들의 기본적인 생활 ",
    {
     "word": "수준",
     "annotation": "수준"
    },
    "을 ",
    {
     "word": "보장",
     "annotation": "보장"
    },
    "해주기 위해 국가나 지방자치단체에서 생활비, 교육비, 의료비 등을 지원해 주는 제도이다. ",
    {
     "word": "소득",
     "annotation": "소득"
    },
    "이 ",
    {
     "word": "최저 생계비",
     "annotation": "최저 생계비"
    },
    "보다 적은 ",
    {
     "word": "저소득층",
     "annotation": "저소득층"
    },
    "은 국민 ",
    {
     "word": "기초생활보장",
     "annotation": "기초생활보장"
    },
    " 제도를 통해 생활비를 지원 받을 수 있다."
   ],
   "translation": "Public assistance is a system under which the state or a local authority supports living costs, education costs and medical costs, so as to guarantee a basic standard of living to people whose circumstances are hard. Those on low incomes, whose income is below the minimum cost of living, can have their living costs supported through the National Basic Livelihood Security scheme.",
   "sentences": [
    {
     "spans": [
      "공공부조는 생활이 어려운 사람들의 기본적인 생활 ",
      {
       "word": "수준",
       "annotation": "수준"
      },
      "을 ",
      {
       "word": "보장",
       "annotation": "보장"
      },
      "해주기 위해 국가나 지방자치단체에서 생활비, 교육비, 의료비 등을 지원해 주는 제도이다. "
     ],
     "translation": "Public assistance is a system under which the state or a local authority supports living costs, education costs and medical costs, so as to guarantee a basic standard of living to people whose circumstances are hard."
    },
    {
     "spans": [
      {
       "word": "소득",
       "annotation": "소득"
      },
      "이 ",
      {
       "word": "최저 생계비",
       "annotation": "최저 생계비"
      },
      "보다 적은 ",
      {
       "word": "저소득층",
       "annotation": "저소득층"
      },
      "은 국민 ",
      {
       "word": "기초생활보장",
       "annotation": "기초생활보장"
      },
      " 제도를 통해 생활비를 지원 받을 수 있다."
     ],
     "translation": "Those on low incomes, whose income is below the minimum cost of living, can have their living costs supported through the National Basic Livelihood Security scheme."
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "갑작스럽게 어려운 일을 당해 ",
    {
     "word": "생계",
     "annotation": "생계"
    },
    " 유지가 곤란한 저소득층 가구를 지원하는 ",
    {
     "word": "긴급",
     "annotation": "긴급"
    },
    " 복지 지원 제도도 있다. 예를 들어 돈을 주로 벌어오는 사람이 크게 다치거나 큰 병을 앓게 되어 일을 할 수 없게 된 경우, ",
    {
     "word": "화재",
     "annotation": "화재"
    },
    " 등으로 인해 살고 있던 집이나 건물에서 생활하기 어려운 경우 등이 발생하면 지방자치단체의 ",
    {
     "word": "담당",
     "annotation": "담당"
    },
    " 부서나 ",
    {
     "word": "보건복지부",
     "annotation": "보건복지부"
    },
    " 콜센터로 전화하여 도움을 받을 수 있다."
   ],
   "translation": "There is also emergency welfare support, for low-income households that have suddenly met with hardship and cannot keep themselves. If, for instance, the main earner is badly injured or falls seriously ill and can no longer work, or a fire makes the house or building they were living in unfit to live in, one can telephone the responsible department of the local authority, or the Ministry of Health and Welfare call centre, and get help.",
   "sentences": [
    {
     "spans": [
      "갑작스럽게 어려운 일을 당해 ",
      {
       "word": "생계",
       "annotation": "생계"
      },
      " 유지가 곤란한 저소득층 가구를 지원하는 ",
      {
       "word": "긴급",
       "annotation": "긴급"
      },
      " 복지 지원 제도도 있다. "
     ],
     "translation": "There is also emergency welfare support, for low-income households that have suddenly met with hardship and cannot keep themselves."
    },
    {
     "spans": [
      "예를 들어 돈을 주로 벌어오는 사람이 크게 다치거나 큰 병을 앓게 되어 일을 할 수 없게 된 경우, ",
      {
       "word": "화재",
       "annotation": "화재"
      },
      " 등으로 인해 살고 있던 집이나 건물에서 생활하기 어려운 경우 등이 발생하면 지방자치단체의 ",
      {
       "word": "담당",
       "annotation": "담당"
      },
      " 부서나 ",
      {
       "word": "보건복지부",
       "annotation": "보건복지부"
      },
      " 콜센터로 전화하여 도움을 받을 수 있다."
     ],
     "translation": "If, for instance, the main earner is badly injured or falls seriously ill and can no longer work, or a fire makes the house or building they were living in unfit to live in, one can telephone the responsible department of the local authority, or the Ministry of Health and Welfare call centre, and get help."
    }
   ]
  },
  {
   "type": "margin",
   "items": [
    [
     "보건복지부"
    ],
    [
     "상담센터(☎ 129)"
    ],
    [
     "본인과 가족에게 필요한 복지 정보와 상담을 원할 때는 129로 전화하면 된다."
    ],
    [
     "특히 보건복지부에서는 각종 의료보장제도에 의해 의료혜택을 받을 수 없는 국내에 거주하는 외국인에게도 심의를 통해 의료비를 지원하고 있다."
    ]
   ]
  },
  {
   "type": "figure",
   "text": "복지로 누리집에서 복지 관련 정보를 얻을 수 있다. (http://www.bokjiro.go.kr/)"
  },
  {
   "type": "section",
   "kind": "aside",
   "text": "알아두면 좋아요",
   "topic": "태풍, 지진, 전염병 등의 재난상황에서도 도움을 받을 수 있는 방법이 있을까?"
  },
  {
   "type": "paragraph",
   "spans": [
    "태풍, 지진, 전염병 확산 등 ",
    {
     "word": "재난",
     "annotation": "재난"
    },
    "상황에서 정부나 지방자치단체 등이 ",
    {
     "word": "한시적",
     "annotation": "한시적"
    },
    "으로 지급하는 재난관련 지원금이 있다. 대표적으로 한국에서는 2020년 코로나바이러스 감염증-19가 확산됨에 따라 재난 피해자의 지원과 경기활성화를 위한 방법으로 재난관련 지원금이 지급되었다. 정부의 긴급재난지원금은 기초생활수급자 등 ",
    {
     "word": "취약가정",
     "annotation": "취약가정"
    },
    "에는 별도 신청과정 없이 현금으로 지급되었으며, 나머지 가구는 신청을 받아 카드 포인트, 소비쿠폰, 지역사랑 상품권 등으로 지급되었다."
   ]
  },
  {
   "type": "section",
   "kind": "part",
   "text": "02 다문화 가족 및 외국인을 위한 기관과 지원 서비스에는 어떤 것들이 있을까?"
  },
  {
   "type": "table",
   "header": [
    {
     "text": "생계급여 대상자선정 기준(월 소득액)",
     "span": 2
    }
   ],
   "rows": [
    [
     "1인가구",
     "527,158"
    ],
    [
     "2인가구",
     "897,594"
    ],
    [
     "3인가구",
     "1,161,173"
    ],
    [
     "4인가구",
     "1,424,752"
    ]
   ]
  },
  {
   "type": "source",
   "text": "(보건복지부, 2020)"
  },
  {
   "type": "heading",
   "level": 2,
   "text": "외국인 대상 지원 서비스",
   "titleTranslation": "Support Services for Foreigners"
  },
  {
   "type": "glossary",
   "entries": [
    {
     "term": "신생아",
     "definition": [
      "갓 태어난 아기"
     ],
     "annotation": "신생아"
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "사회 복지 제도 중 공공부조는 ",
    {
     "word": "원칙적",
     "annotation": "원칙적"
    },
    "으로 한국 국민에게만 적용된다. 그러나 한국에 살고 있는 외국인 중 대한민국 국민과 ",
    {
     "word": "혼인",
     "annotation": "혼인"
    },
    "한 사람, 대한민국 ",
    {
     "word": "국적",
     "annotation": "국적"
    },
    "을 가진 부모나 자녀를 돌보고 있는 사람, 법에 따라 ",
    {
     "word": "난민",
     "annotation": "난민"
    },
    "으로 인정된 사람 등은 소득이 최저 생계비보다 적은 경우 최저 생계비, 의료비, 긴급 복지 등을 지원받을 수 있다. 이외에도 한국 생활에 잘 적응하고 한국에서 ",
    {
     "word": "주체적",
     "annotation": "주체적"
    },
    "으로 살아갈 수 있도록 무료로 한국어와 한국 문화를 배울 수 있는 프로그램도 운영되고 있다. 또한 ",
    {
     "word": "임신",
     "annotation": "임신"
    },
    "을 한 상태이거나 출산을 앞둔 여성 결혼 이민자는 자신과 ",
    {
     "word": "신생아",
     "annotation": "신생아"
    },
    "의 건강 관리 서비스를 받을 수 있다."
   ],
   "translation": "Among Korea's social welfare systems, public assistance (공공부조) in principle applies only to Korean citizens. However, among foreigners living in Korea, those who are married to a Korean citizen, those caring for a parent or child holding Korean nationality, and those legally recognized as refugees can, if their income is below the minimum cost of living (최저 생계비), receive support such as minimum living expenses, medical costs, and emergency welfare. Beyond this, programs are also being run offering free Korean language and Korean culture classes to help people adapt well to life in Korea and live independently/on their own terms. In addition, female marriage immigrants who are pregnant or about to give birth can receive health management services for themselves and their newborn baby.",
   "sentences": [
    {
     "spans": [
      "사회 복지 제도 중 공공부조는 ",
      {
       "word": "원칙적",
       "annotation": "원칙적"
      },
      "으로 한국 국민에게만 적용된다. "
     ],
     "translation": "Among Korea's social welfare systems, public assistance (공공부조) in principle applies only to Korean citizens."
    },
    {
     "spans": [
      "그러나 한국에 살고 있는 외국인 중 대한민국 국민과 ",
      {
       "word": "혼인",
       "annotation": "혼인"
      },
      "한 사람, 대한민국 ",
      {
       "word": "국적",
       "annotation": "국적"
      },
      "을 가진 부모나 자녀를 돌보고 있는 사람, 법에 따라 ",
      {
       "word": "난민",
       "annotation": "난민"
      },
      "으로 인정된 사람 등은 소득이 최저 생계비보다 적은 경우 최저 생계비, 의료비, 긴급 복지 등을 지원받을 수 있다. "
     ],
     "translation": "However, among foreigners living in Korea, those who are married to a Korean citizen, those caring for a parent or child holding Korean nationality, and those legally recognized as refugees can, if their income is below the minimum cost of living (최저 생계비), receive support such as minimum living expenses, medical costs, and emergency welfare."
    },
    {
     "spans": [
      "이외에도 한국 생활에 잘 적응하고 한국에서 ",
      {
       "word": "주체적",
       "annotation": "주체적"
      },
      "으로 살아갈 수 있도록 무료로 한국어와 한국 문화를 배울 수 있는 프로그램도 운영되고 있다. "
     ],
     "translation": "Beyond this, programs are also being run offering free Korean language and Korean culture classes to help people adapt well to life in Korea and live independently/on their own terms."
    },
    {
     "spans": [
      "또한 ",
      {
       "word": "임신",
       "annotation": "임신"
      },
      "을 한 상태이거나 출산을 앞둔 여성 결혼 이민자는 자신과 ",
      {
       "word": "신생아",
       "annotation": "신생아"
      },
      "의 건강 관리 서비스를 받을 수 있다."
     ],
     "translation": "In addition, female marriage immigrants who are pregnant or about to give birth can receive health management services for themselves and their newborn baby."
    }
   ]
  },
  {
   "type": "heading",
   "level": 2,
   "text": "다문화 가족·외국인 지원 기관",
   "titleTranslation": "Multicultural Family and Foreigner Support Agencies"
  },
  {
   "type": "glossary",
   "entries": [
    {
     "term": "다국어",
     "definition": [
      "여러 나라의 언어"
     ],
     "annotation": "다국어"
    },
    {
     "term": "이주",
     "definition": [
      "다른 나라나 지역으로 옮겨 가서 사는 것"
     ],
     "annotation": "이주"
    },
    {
     "term": "권익",
     "definition": [
      "권리와 이익"
     ],
     "annotation": "권익"
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "다문화 가족과 외국인을 지원하는 기관으로는 ",
    {
     "word": "법무부",
     "annotation": "법무부"
    },
    "의 외국인 종합 안내 센터, ",
    {
     "word": "여성가족부",
     "annotation": "여성가족부"
    },
    "의 ",
    {
     "word": "다누리",
     "annotation": "다누리"
    },
    "콜센터, 다문화 가족 지원 센터, ",
    {
     "word": "고용노동부",
     "annotation": "고용노동부"
    },
    "의 외국인 근로자 지원센터 등이 있다."
   ],
   "translation": "Agencies that support multicultural families and foreigners include: the Ministry of Justice's Foreigner Comprehensive Information Center, the Ministry of Gender Equality and Family's Danuri Call Center, Multicultural Family Support Centers, and the Ministry of Employment and Labor's Foreign Worker Support Centers.",
   "sentences": [
    {
     "spans": [
      "다문화 가족과 외국인을 지원하는 기관으로는 ",
      {
       "word": "법무부",
       "annotation": "법무부"
      },
      "의 외국인 종합 안내 센터, ",
      {
       "word": "여성가족부",
       "annotation": "여성가족부"
      },
      "의 ",
      {
       "word": "다누리",
       "annotation": "다누리"
      },
      "콜센터, 다문화 가족 지원 센터, ",
      {
       "word": "고용노동부",
       "annotation": "고용노동부"
      },
      "의 외국인 근로자 지원센터 등이 있다."
     ],
     "translation": "Agencies that support multicultural families and foreigners include: the Ministry of Justice's Foreigner Comprehensive Information Center, the Ministry of Gender Equality and Family's Danuri Call Center, Multicultural Family Support Centers, and the Ministry of Employment and Labor's Foreign Worker Support Centers."
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "외국인 종합 안내센터(1345)는 ",
    {
     "word": "신분증",
     "annotation": "신분증"
    },
    " 관련 업무, ",
    {
     "word": "체류",
     "annotation": "체류"
    },
    {
     "word": "허가",
     "annotation": "허가"
    },
    " 관련 업무, 국적 관련 업무 등 한국에 거주하는 외국인의 ",
    {
     "word": "출입국",
     "annotation": "출입국"
    },
    " ",
    {
     "word": "행정",
     "annotation": "행정"
    },
    {
     "word": "민원",
     "annotation": "민원"
    },
    " 상담과 정보를 ",
    {
     "word": "다국어",
     "annotation": "다국어"
    },
    "로 지원한다. 다누리콜센터(1577-1366)는 국내에 거주하는 다문화 가족·",
    {
     "word": "이주",
     "annotation": "이주"
    },
    " 여성에게 필요한 한국 생활 정보를 제공하고, 위기 상담 및 긴급 지원 등 전문 상담원과 자국 언어로 통화할 수 있도록 지원한다. 다문화 가족 지원센터는 다문화 가족의 한국 사회 적응을 돕는 교육, 자녀 언어발달 지원 서비스 등을 제공한다. 외국인 근로자 지원센터는 외국인 근로자들을 대상으로 한국어 교육을 실시하고, 외국인 근로자의 ",
    {
     "word": "권익",
     "annotation": "권익"
    },
    " 보호를 지원한다."
   ],
   "translation": "The Foreigner Comprehensive Information Center (1345) provides multilingual support and consultation for immigration-related civil affairs matters for foreigners living in Korea — including ID-related matters, stay permit matters, and nationality matters. The Danuri Call Center (1577-1366) provides multicultural families and migrant women living in Korea with the information they need for life in Korea, and supports crisis counseling and emergency assistance, allowing people to speak with professional counselors in their native language. Multicultural Family Support Centers provide education to help multicultural families adapt to Korean society, and services supporting children's language development. Foreign Worker Support Centers provide Korean language education for foreign workers and support the protection of foreign workers' rights and interests (권익).",
   "sentences": [
    {
     "spans": [
      "외국인 종합 안내센터(1345)는 ",
      {
       "word": "신분증",
       "annotation": "신분증"
      },
      " 관련 업무, ",
      {
       "word": "체류",
       "annotation": "체류"
      },
      {
       "word": "허가",
       "annotation": "허가"
      },
      " 관련 업무, 국적 관련 업무 등 한국에 거주하는 외국인의 ",
      {
       "word": "출입국",
       "annotation": "출입국"
      },
      " ",
      {
       "word": "행정",
       "annotation": "행정"
      },
      {
       "word": "민원",
       "annotation": "민원"
      },
      " 상담과 정보를 ",
      {
       "word": "다국어",
       "annotation": "다국어"
      },
      "로 지원한다. "
     ],
     "translation": "The Foreigner Comprehensive Information Center (1345) provides multilingual support and consultation for immigration-related civil affairs matters for foreigners living in Korea — including ID-related matters, stay permit matters, and nationality matters."
    },
    {
     "spans": [
      "다누리콜센터(1577-1366)는 국내에 거주하는 다문화 가족·",
      {
       "word": "이주",
       "annotation": "이주"
      },
      " 여성에게 필요한 한국 생활 정보를 제공하고, 위기 상담 및 긴급 지원 등 전문 상담원과 자국 언어로 통화할 수 있도록 지원한다. "
     ],
     "translation": "The Danuri Call Center (1577-1366) provides multicultural families and migrant women living in Korea with the information they need for life in Korea, and supports crisis counseling and emergency assistance, allowing people to speak with professional counselors in their native language."
    },
    {
     "spans": [
      "다문화 가족 지원센터는 다문화 가족의 한국 사회 적응을 돕는 교육, 자녀 언어발달 지원 서비스 등을 제공한다. "
     ],
     "translation": "Multicultural Family Support Centers provide education to help multicultural families adapt to Korean society, and services supporting children's language development."
    },
    {
     "spans": [
      "외국인 근로자 지원센터는 외국인 근로자들을 대상으로 한국어 교육을 실시하고, 외국인 근로자의 ",
      {
       "word": "권익",
       "annotation": "권익"
      },
      " 보호를 지원한다."
     ],
     "translation": "Foreign Worker Support Centers provide Korean language education for foreign workers and support the protection of foreign workers' rights and interests (권익)."
    }
   ]
  },
  {
   "type": "figure",
   "text": "외국인 종합 안내센터(법무부, 1345) — 1345 + 국가번호 + * 로 20개 언어 상담이 가능하다."
  },
  {
   "type": "section",
   "kind": "aside",
   "text": "알아두면 좋아요",
   "topic": "자신의 고향 나라 언어로 법률 상담을 받을 수 있는 방법은?"
  },
  {
   "type": "paragraph",
   "spans": [
    {
     "word": "재외 동포",
     "annotation": "재외 동포"
    },
    " A씨는 회사에 다니며 나이가 많은 홀어머니를 모시고 있었다. 수개월 간 약 500만원의 임금이 밀렸지만 사장으로부터 돈을 받지 못해 A씨는 생활에 어려움을 겪던 중 외국인 종합 안내센터(1345 콜센터)가 제공하는 ‘마을변호사-외국인’ 간 무료 통역 서비스를 통해 법률 ",
    {
     "word": "자문",
     "annotation": "자문"
    },
    "을 받았다. 그 결과 그동안 밀린 임금을 모두 받을 수 있었다."
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "외국인 종합 안내센터(1345)에서는 법무부가 지정한 변호사가 1345센터 상담사의 통역 지원을 받아 언어 장벽과 정보 부족으로 법률 서비스를 이용하기 어려운 외국인에게 법률 상담을 제공하고 있다."
   ]
  },
  {
   "type": "margin",
   "items": [
    [
     "상담시간: 평일 09:00 ~ 22:00 (1345-④마을변호사 법률 상담)"
    ]
   ]
  },
  {
   "type": "section",
   "kind": "review",
   "text": "주요 내용정리"
  },
  {
   "type": "heading",
   "level": 2,
   "text": "01 한국의 사회 복지 제도에는 어떤 것들이 있을까?"
  },
  {
   "type": "bullet",
   "spans": [
    "미래의 위험에 대비하여 법에 따라 국민들이 가입하도록 하고 있는 사회보험에는 ",
    {
     "blank": "건강 보험"
    },
    ", ",
    {
     "blank": "고용 보험"
    },
    ", ",
    {
     "blank": ""
    },
    ", ",
    {
     "blank": ""
    },
    "이 있다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    {
     "blank": ""
    },
    "는 소득이 최저 생계비보다 적은 저소득층의 기본적인 생활 수준을 보장해주기 위해 국가나 지방자치단체에서 생활비와 교육비, 의료비 등을 지원해주는 제도이다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    {
     "blank": ""
    },
    " 지원 제도는 갑작스럽게 어려운 일을 당해 생계 유지가 곤란한 저소득층 가구를 지원하는 제도이다."
   ]
  },
  {
   "type": "heading",
   "level": 2,
   "text": "02 다문화 가족·외국인 지원 서비스와 기관에는 어떤 것들이 있을까?"
  },
  {
   "type": "bullet",
   "spans": [
    "한국에 체류하고 있는 외국인 중 대한민국 국민과 ",
    {
     "blank": ""
    },
    "한 사람, 대한민국 ",
    {
     "blank": ""
    },
    "을 가진 부모나 자녀를 돌보고 있는 사람, 법에 따라 ",
    {
     "blank": ""
    },
    "으로 인정된 사람 등은 최저 ",
    {
     "blank": ""
    },
    " 지원, 의료비 지원, 긴급 복지 지원을 받을 수 있다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "외국인이 한국에 잘 적응하고 주체적으로 살아갈 수 있도록 무료로 ",
    {
     "blank": ""
    },
    "와 한국 ",
    {
     "blank": "언어"
    },
    " 교육, 임신 및 출산 지원 서비스, 상담 서비스 등을 제공하고 있다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "다문화 가족과 외국인을 지원하는 기관으로는 ",
    {
     "blank": ""
    },
    " 종합 안내센터, 다누리 콜센터, 다문화 가족 지원센터, 외국인 근로자 지원센터 등이 있다."
   ]
  },
  {
   "type": "section",
   "kind": "discuss",
   "text": "이야기 나누기",
   "topic": "네팔 출신 1호 의사의 꿈"
  },
  {
   "type": "paragraph",
   "spans": [
    "네팔 출신 한국인 1호 의사인 정제한씨는 가족 외에도 챙겨야 할 수많은 ",
    {
     "word": "형제",
     "annotation": "형제"
    },
    "가 있다. 바로 국내에 체류 중인 이주노동자들이다. 정제한씨는 한국말이 ",
    {
     "word": "서툴러",
     "annotation": "서툴러"
    },
    " 자신의 의견을 제대로 표현하지 못하는 이주 노동자들을 돕기 위해 여러 노력을 기울이고 있다."
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "정제한씨는 대구 지역 법사랑 위원회의 외국인 위원이 되어 이주민의 목소리를 대신 전해 주기도 한다. 또한, 동료 의사들과 함께 모바일 커뮤니티를 열어 한국에서 어려움을 겪는 네팔인들과 이주 노동자들을 돕고 있다."
   ]
  },
  {
   "type": "source",
   "text": "[출처] 다문화 가족과 함께 만드는 정보 매거진 레인보우 웹진, 2016 가을 호, 여성가족부"
  },
  {
   "type": "paragraph",
   "spans": [
    "★ 본인이 한국에서 지원받은 복지 제도나 서비스, 본인에게 도움을 주었던 사람이나 기관에 대해 이야기해 봅시다."
   ]
  }
 ],
 "annotations": {
  "최소한": {
   "headword": "최소한",
   "hanja": null,
   "meaning": "at least/minimum",
   "characters": [],
   "notes": [
    "最 (most, same 最 as in 최근 \"recently\")",
    "小 (small)",
    "限 (limit, same 限 as in 제한 \"restriction\")",
    "literally \"smallest limit\"",
    "최소한의 삶 = \"a minimal standard of living\"."
   ],
   "surfaces": []
  },
  "인간다운": {
   "headword": "인간답다",
   "hanja": null,
   "meaning": "to be human-like/befitting a human",
   "characters": [],
   "notes": [
    "인간 (human)",
    "답다 (a suffix meaning \"to be worthy of/befitting\")",
    "인간다운 삶 = \"a life befitting a human/humane life\""
   ],
   "surfaces": []
  },
  "누릴": {
   "headword": "누리다",
   "hanja": null,
   "meaning": "to enjoy/partake of",
   "characters": [],
   "notes": [
    "a slightly more formal word than 즐기다",
    "삶을 누리다 = \"to enjoy life\""
   ],
   "surfaces": []
  },
  "마련해": {
   "headword": "마련하다",
   "hanja": null,
   "meaning": "to prepare/set up/arrange",
   "characters": [],
   "notes": [
    "제도를 마련하다 = \"to establish/set up a system\""
   ],
   "surfaces": []
  },
  "공공부조": {
   "headword": "공공부조",
   "hanja": "公共扶助",
   "meaning": "public assistance",
   "characters": [
    {
     "char": "公",
     "reading": "공",
     "gloss": "public — the same 公 as in 공기업, 공공"
    },
    {
     "char": "共",
     "reading": "공",
     "gloss": "together — the same 共 as in 공동 주택"
    },
    {
     "char": "扶",
     "reading": "부",
     "gloss": "to help, support"
    },
    {
     "char": "助",
     "reading": "조",
     "gloss": "to assist — as in 도움, 원조, 보조"
    }
   ],
   "notes": [
    "Paid for out of tax and given according to need, with nothing contributed by the recipient — the other half of the pair with 사회보험. In principle for nationals only, which is what part 02 of the chapter qualifies."
   ],
   "surfaces": []
  },
  "대비하여": {
   "headword": "대비하다",
   "hanja": null,
   "meaning": "to prepare for/provide against",
   "characters": [],
   "notes": [
    "對 (facing/against, same 對 as in 반대 \"opposition\")",
    "備 (to prepare, same 備 as in 준비 \"preparation\")",
    "미래의 위험에 대비하다 = \"to prepare against future risks\""
   ],
   "surfaces": []
  },
  "일부": {
   "headword": "일부",
   "hanja": null,
   "meaning": "a part/portion",
   "characters": [],
   "notes": [
    "一 (one)",
    "部 (part, same 部 as in 법무부's ministry suffix)",
    "의료비의 일부 = \"a portion of medical costs\""
   ],
   "surfaces": []
  },
  "해고": {
   "headword": "해고",
   "hanja": null,
   "meaning": "dismissal/layoff",
   "characters": [],
   "notes": [
    "解 (to release/undo, same 解 as in 해례본, 이해)",
    "雇 (to hire, same 雇 as in 고용)",
    "literally \"release-hiring\"",
    "to be fired/laid off from a job"
   ],
   "surfaces": []
  },
  "금전적": {
   "headword": "금전적",
   "hanja": null,
   "meaning": "financial/monetary",
   "characters": [],
   "notes": [
    "金錢 (money, 金 = gold/money + 錢 = coin/money)",
    "적 (adjective suffix)",
    "금전적 지원 = \"financial support\""
   ],
   "surfaces": []
  },
  "지급": {
   "headword": "지급",
   "hanja": null,
   "meaning": "payment/disbursement",
   "characters": [],
   "notes": [
    "支 (to pay/support, same 支 as in 지불하다 \"to pay\")",
    "給 (to give, same 給 as in 공급 \"supply\")",
    "생활비로 지급받다 = \"to be paid/disbursed as living expenses\""
   ],
   "surfaces": []
  },
  "보상": {
   "headword": "보상",
   "hanja": null,
   "meaning": "compensation",
   "characters": [],
   "notes": [
    "補 (to supplement/repair, same 補 as in 보완 \"supplementation\")",
    "償 (to compensate/repay)",
    "피해에 대해 보상을 받다 = \"to receive compensation for damages\""
   ],
   "surfaces": []
  },
  "신생아": {
   "headword": "신생아",
   "hanja": "新生兒",
   "meaning": "a newborn",
   "characters": [
    {
     "char": "新",
     "reading": "신",
     "gloss": "new — as in 신도시, 신설"
    },
    {
     "char": "生",
     "reading": "생",
     "gloss": "to be born"
    },
    {
     "char": "兒",
     "reading": "아",
     "gloss": "child — the same 兒 as in 육아 “childcare”"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "다국어": {
   "headword": "다국어",
   "hanja": "多國語",
   "meaning": "multiple languages",
   "characters": [
    {
     "char": "多",
     "reading": "다",
     "gloss": "many — the same 多 as in 다문화, 다세대"
    },
    {
     "char": "國",
     "reading": "국",
     "gloss": "country"
    },
    {
     "char": "語",
     "reading": "어",
     "gloss": "language — as in 한국어, 언어"
    }
   ],
   "notes": [
    "The 1345 centre works in twenty of them, per the figure on p. 42."
   ],
   "surfaces": []
  },
  "이주": {
   "headword": "이주",
   "hanja": "移住",
   "meaning": "migration, moving to live elsewhere",
   "characters": [
    {
     "char": "移",
     "reading": "이",
     "gloss": "to move — the same 移 as in 이직, 이사"
    },
    {
     "char": "住",
     "reading": "주",
     "gloss": "to dwell — the same 住 as in 주거, 주택"
    }
   ],
   "notes": [
    "이주 여성 and 이주 노동자 are the terms the chapter and the discussion use, and are preferred to older words for the same people."
   ],
   "surfaces": []
  },
  "권익": {
   "headword": "권익",
   "hanja": "權益",
   "meaning": "rights and interests",
   "characters": [
    {
     "char": "權",
     "reading": "권",
     "gloss": "right — the same 權 as in 권위, 소유권"
    },
    {
     "char": "益",
     "reading": "익",
     "gloss": "benefit, profit — as in 이익 “profit”, 유익하다"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "법무부": {
   "headword": "법무부",
   "hanja": "法務部",
   "meaning": "the Ministry of Justice",
   "characters": [
    {
     "char": "法",
     "reading": "법",
     "gloss": "law — as in 법률, 법원"
    },
    {
     "char": "務",
     "reading": "무",
     "gloss": "duty — the same 務 as in 업무협약, 공무원"
    },
    {
     "char": "部",
     "reading": "부",
     "gloss": "ministry, part — as in 보건복지부, 부서"
    }
   ],
   "notes": [
    "Runs the 외국인 종합 안내센터 on 1345, and immigration generally."
   ],
   "surfaces": []
  },
  "여성가족부": {
   "headword": "여성가족부",
   "hanja": "女性家族部",
   "meaning": "the Ministry of Gender Equality and Family",
   "characters": [
    {
     "char": "女",
     "reading": "여",
     "gloss": "woman — as in 여성, 자녀"
    },
    {
     "char": "性",
     "reading": "성",
     "gloss": "sex, nature — the same 性 as in 양성평등"
    }
   ],
   "notes": [
    "Runs the 다누리 콜센터 and the 다문화 가족 지원센터."
   ],
   "surfaces": []
  },
  "다누리": {
   "headword": "다누리",
   "hanja": null,
   "meaning": "다 (\"all/every\") + 누리 (an old/poetic native word for \"world\"), meaning roughly \"everyone's world\"",
   "characters": [],
   "notes": [
    "used as a branded name for the call center, not a regular vocabulary word you'd use elsewhere"
   ],
   "surfaces": []
  },
  "고용노동부": {
   "headword": "고용노동부",
   "hanja": "雇用勞動部",
   "meaning": "the Ministry of Employment and Labor",
   "characters": [
    {
     "char": "雇",
     "reading": "고",
     "gloss": "to hire — the same 雇 as in 고용보험"
    },
    {
     "char": "勞",
     "reading": "로",
     "gloss": "to labour — the same 勞 as in 근로자"
    },
    {
     "char": "動",
     "reading": "동",
     "gloss": "to move — the same 動 as in 활동, 부동산"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "신분증": {
   "headword": "신분증",
   "hanja": "身分證",
   "meaning": "an identity document",
   "characters": [
    {
     "char": "身",
     "reading": "신",
     "gloss": "body, self — as in 신체, 자신"
    },
    {
     "char": "分",
     "reading": "분",
     "gloss": "to divide, status — the same 分 as in 분산, 분리수거"
    },
    {
     "char": "證",
     "reading": "증",
     "gloss": "proof — the same 證 as in 보증금, 증명"
    }
   ],
   "notes": [
    "For a foreign resident this means the 외국인등록증."
   ],
   "surfaces": []
  },
  "체류": {
   "headword": "체류",
   "hanja": "滯留",
   "meaning": "staying, residing in a country",
   "characters": [
    {
     "char": "滯",
     "reading": "체",
     "gloss": "to be held up, stagnate"
    },
    {
     "char": "留",
     "reading": "류",
     "gloss": "to remain"
    }
   ],
   "notes": [
    "Also in chapter 6, of the seasonal worker's period of stay. 체류 허가 is the residence permit this centre advises on."
   ],
   "surfaces": []
  },
  "허가": {
   "headword": "허가",
   "hanja": null,
   "meaning": "permission/permit",
   "characters": [],
   "notes": [
    "許 (to allow/permit)",
    "可 (permissible/possible, same 可 as in 불가능 \"impossible\")",
    "체류 허가 = \"residence/stay permit\""
   ],
   "surfaces": []
  },
  "행정": {
   "headword": "행정",
   "hanja": null,
   "meaning": "administration",
   "characters": [],
   "notes": [
    "行 (to act/go, same 行 as in 여행 \"travel\", 통행)",
    "政 (governance/politics, same 政 as in 정책 \"policy\")",
    "출입국 행정 = \"immigration administration\""
   ],
   "surfaces": []
  },
  "민원": {
   "headword": "민원",
   "hanja": "民願",
   "meaning": "a citizen's request to an office",
   "characters": [
    {
     "char": "民",
     "reading": "민",
     "gloss": "people"
    },
    {
     "char": "願",
     "reading": "원",
     "gloss": "to wish, request — as in 지원, 소원"
    }
   ],
   "notes": [
    "Anything a member of the public asks an administrative office to do — a certificate, a registration, a complaint. 민원을 넣다 is to file one."
   ],
   "surfaces": []
  },
  "4대 보험": {
   "headword": "4대 보험",
   "hanja": "四大保險",
   "meaning": "the four major insurances",
   "characters": [
    {
     "char": "四",
     "reading": "사",
     "gloss": "four"
    },
    {
     "char": "大",
     "reading": "대",
     "gloss": "great, major"
    }
   ],
   "notes": [
    "The four the law requires: 국민연금, 건강보험, 고용보험 and 산재보험. Your note at the top of p. 41 names them, and every Korean employment contract turns on them.",
    "Set against 개인 보험, the private policies one takes out by choice — 생명 보험, 손해 보험, 교육 보험."
   ],
   "surfaces": []
  },
  "사회보험": {
   "headword": "사회보험",
   "hanja": "社會保險",
   "meaning": "social insurance",
   "characters": [
    {
     "char": "社",
     "reading": "사",
     "gloss": "society, company — the same 社 as in 회사, 퇴사"
    },
    {
     "char": "會",
     "reading": "회",
     "gloss": "to gather — the same 會 as in 회식, 회사"
    },
    {
     "char": "保",
     "reading": "보",
     "gloss": "to protect — the same 保 as in 보증금, 보호"
    },
    {
     "char": "險",
     "reading": "험",
     "gloss": "risk — as in 위험 “danger”, 산재보험"
    }
   ],
   "notes": [
    "Compulsory and contributory: one pays in against a future risk. That is what separates it from 공공부조, which is paid out of tax to those who need it."
   ],
   "surfaces": []
  },
  "가입": {
   "headword": "가입",
   "hanja": "加入",
   "meaning": "joining, enrolling",
   "characters": [
    {
     "char": "加",
     "reading": "가",
     "gloss": "to add — as in 추가 “addition”, 참가"
    },
    {
     "char": "入",
     "reading": "입",
     "gloss": "to enter — the same 入 as in 세입자, 수입"
    }
   ],
   "notes": [
    "The word for signing up to anything with membership: insurance, a union, a website. 산재보험에 가입하다."
   ],
   "surfaces": []
  },
  "건강보험": {
   "headword": "건강보험",
   "hanja": "健康保險",
   "meaning": "health insurance",
   "characters": [
    {
     "char": "健",
     "reading": "건",
     "gloss": "healthy — as in 건강, 건전"
    },
    {
     "char": "康",
     "reading": "강",
     "gloss": "at ease, healthy"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "고용보험": {
   "headword": "고용보험",
   "hanja": "雇用保險",
   "meaning": "employment insurance",
   "characters": [
    {
     "char": "雇",
     "reading": "고",
     "gloss": "to hire — as in 고용 “employment”, 해고"
    },
    {
     "char": "用",
     "reading": "용",
     "gloss": "to use — the same 用 as in 전용, 이용"
    }
   ],
   "notes": [
    "What pays out on being dismissed. Its counterpart 해고 “dismissal” uses the same 雇."
   ],
   "surfaces": []
  },
  "국민연금": {
   "headword": "국민연금",
   "hanja": "國民年金",
   "meaning": "the national pension",
   "characters": [
    {
     "char": "國",
     "reading": "국",
     "gloss": "country"
    },
    {
     "char": "民",
     "reading": "민",
     "gloss": "people — the same 民 as in 훈민정음, 결혼이민자"
    },
    {
     "char": "年",
     "reading": "년",
     "gloss": "year — the same 年 as in 연령, 노년"
    },
    {
     "char": "金",
     "reading": "금",
     "gloss": "money — the same 金 as in 보증금, 임금"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "산업재해보상보험": {
   "headword": "산업재해보상보험",
   "hanja": "産業災害補償保險",
   "meaning": "industrial accident compensation insurance",
   "characters": [
    {
     "char": "災",
     "reading": "재",
     "gloss": "disaster — the same 災 as in 재난"
    },
    {
     "char": "害",
     "reading": "해",
     "gloss": "harm — as in 피해 “damage”, 해로운"
    },
    {
     "char": "補",
     "reading": "보",
     "gloss": "to supplement, make up — as in 보충, 보완"
    },
    {
     "char": "償",
     "reading": "상",
     "gloss": "to compensate — as in 보상, 배상"
    }
   ],
   "notes": [
    "Shortened to 산재보험, and to 산재 in speech — which is how your note on p. 41 writes it. Chapter 6's article on seasonal workers turns on who may join it."
   ],
   "surfaces": []
  },
  "국민연금공단": {
   "headword": "국민연금공단",
   "hanja": "國民年金公團",
   "meaning": "the National Pension Service",
   "characters": [
    {
     "char": "公",
     "reading": "공",
     "gloss": "public"
    },
    {
     "char": "團",
     "reading": "단",
     "gloss": "group, body — as in 단체 “organisation”, 집단"
    }
   ],
   "notes": [
    "공단 is the word for a public corporation run at arm's length from a ministry. Enquiries on 1355."
   ],
   "surfaces": []
  },
  "보건복지부": {
   "headword": "보건복지부",
   "hanja": "保健福祉部",
   "meaning": "the Ministry of Health and Welfare",
   "characters": [
    {
     "char": "保",
     "reading": "보",
     "gloss": "to protect — the same 保 as in 보험, 보장"
    },
    {
     "char": "健",
     "reading": "건",
     "gloss": "healthy — the same 健 as in 건강보험"
    },
    {
     "char": "福",
     "reading": "복",
     "gloss": "blessing, welfare — the 福 of 복지"
    },
    {
     "char": "祉",
     "reading": "지",
     "gloss": "welfare, blessing"
    },
    {
     "char": "部",
     "reading": "부",
     "gloss": "ministry — the same 部 as in 법무부, 여성가족부"
    }
   ],
   "notes": [
    "보건 is public health and 복지 is welfare; the ministry covers both. Its counselling line is 129, and the box on p. 41 notes that it supports medical costs even for foreign residents who fall outside the medical insurance schemes."
   ],
   "surfaces": []
  },
  "최저 생계비": {
   "headword": "최저 생계비",
   "hanja": "最低生計費",
   "meaning": "the minimum cost of living",
   "characters": [
    {
     "char": "最",
     "reading": "최",
     "gloss": "most — as in 최고 “highest”, 최근 “recently”"
    },
    {
     "char": "低",
     "reading": "저",
     "gloss": "low — the same 低 as in 저소득층"
    },
    {
     "char": "生",
     "reading": "생",
     "gloss": "life"
    },
    {
     "char": "計",
     "reading": "계",
     "gloss": "to reckon, plan — as in 계획 “plan”, 통계"
    },
    {
     "char": "費",
     "reading": "비",
     "gloss": "expense — as in 의료비, 생활비, 교통비"
    }
   ],
   "notes": [
    "The threshold the whole of 공공부조 is measured against: fall below it and the support applies."
   ],
   "surfaces": []
  },
  "저소득층": {
   "headword": "저소득층",
   "hanja": "低所得層",
   "meaning": "the low-income bracket",
   "characters": [
    {
     "char": "低",
     "reading": "저",
     "gloss": "low"
    },
    {
     "char": "所",
     "reading": "소",
     "gloss": "that which — the same 所 as in 소유권, 주소"
    },
    {
     "char": "得",
     "reading": "득",
     "gloss": "to obtain — as in 획득, 소득"
    },
    {
     "char": "層",
     "reading": "층",
     "gloss": "layer, stratum — the same 層 as in 층간 소음, 계층"
    }
   ],
   "notes": [
    "층 is the same character as a storey of a building, used here of a stratum of society. 소득 is income."
   ],
   "surfaces": []
  },
  "생계": {
   "headword": "생계",
   "hanja": "生計",
   "meaning": "livelihood, making a living",
   "characters": [
    {
     "char": "生",
     "reading": "생",
     "gloss": "life"
    },
    {
     "char": "計",
     "reading": "계",
     "gloss": "to reckon, plan"
    }
   ],
   "notes": [
    "생계 유지 is keeping oneself; 생계급여 is the livelihood benefit whose thresholds are tabled on p. 42."
   ],
   "surfaces": []
  },
  "긴급": {
   "headword": "긴급",
   "hanja": "緊急",
   "meaning": "urgent, emergency",
   "characters": [
    {
     "char": "緊",
     "reading": "긴",
     "gloss": "tight, tense — as in 긴장 “tension”"
    },
    {
     "char": "急",
     "reading": "급",
     "gloss": "urgent, hurried — as in 급하다, 응급"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "수준": {
   "headword": "수준",
   "hanja": "水準",
   "meaning": "level, standard",
   "characters": [
    {
     "char": "水",
     "reading": "수",
     "gloss": "water — the same 水 as in 수로, 수질"
    },
    {
     "char": "準",
     "reading": "준",
     "gloss": "standard, to prepare — as in 준비, 기준"
    }
   ],
   "notes": [
    "From the water level of a builder's level: the line something is measured against. 세계 최고 수준 in chapter 4, 생활 수준 here."
   ],
   "surfaces": []
  },
  "보장": {
   "headword": "보장",
   "hanja": "保障",
   "meaning": "to guarantee, secure",
   "characters": [
    {
     "char": "保",
     "reading": "보",
     "gloss": "to protect"
    },
    {
     "char": "障",
     "reading": "장",
     "gloss": "to obstruct, shield — as in 장애 “disability”, 고장"
    }
   ],
   "notes": [
    "Of a right or a standard the state undertakes to hold up: 기초생활보장, 사회보장. The 학습목표 uses it of 인간다운 삶."
   ],
   "surfaces": []
  },
  "소득": {
   "headword": "소득",
   "hanja": "所得",
   "meaning": "income",
   "characters": [
    {
     "char": "所",
     "reading": "소",
     "gloss": "that which"
    },
    {
     "char": "得",
     "reading": "득",
     "gloss": "to obtain, gain"
    }
   ],
   "notes": [
    "Literally what one gets. Distinct from 수입, which is also income but can mean imports too."
   ],
   "surfaces": []
  },
  "기초생활보장": {
   "headword": "기초생활보장",
   "hanja": "基礎生活保障",
   "meaning": "basic livelihood security",
   "characters": [
    {
     "char": "基",
     "reading": "기",
     "gloss": "foundation — the same 基 as in 기초생활수급자"
    },
    {
     "char": "礎",
     "reading": "초",
     "gloss": "cornerstone"
    }
   ],
   "notes": [
    "The scheme; 기초생활수급자, met in chapter 5, is the person on it."
   ],
   "surfaces": []
  },
  "화재": {
   "headword": "화재",
   "hanja": "火災",
   "meaning": "a fire",
   "characters": [
    {
     "char": "火",
     "reading": "화",
     "gloss": "fire — as in 화요일, 소화기"
    },
    {
     "char": "災",
     "reading": "재",
     "gloss": "disaster — the same 災 as in 재난, 산재"
    }
   ],
   "notes": [
    "A different 화 from the 化 of 도시화 or the 和 of 화합."
   ],
   "surfaces": []
  },
  "담당": {
   "headword": "담당",
   "hanja": "擔當",
   "meaning": "being in charge of",
   "characters": [
    {
     "char": "擔",
     "reading": "담",
     "gloss": "to bear, shoulder — as in 부담 “burden”, 분담"
    },
    {
     "char": "當",
     "reading": "당",
     "gloss": "to correspond to — as in 당시, 상당하다"
    }
   ],
   "notes": [
    "담당 부서 is the department responsible; 담당자 the person handling your case — the word you want at any Korean counter."
   ],
   "surfaces": []
  },
  "재난": {
   "headword": "재난",
   "hanja": "災難",
   "meaning": "a disaster",
   "characters": [
    {
     "char": "災",
     "reading": "재",
     "gloss": "disaster"
    },
    {
     "char": "難",
     "reading": "난",
     "gloss": "difficulty — the same 難 as in 취업난"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "한시적": {
   "headword": "한시적",
   "hanja": "限時的",
   "meaning": "for a limited time",
   "characters": [
    {
     "char": "限",
     "reading": "한",
     "gloss": "limit — as in 제한 “restriction”, 한계"
    },
    {
     "char": "時",
     "reading": "시",
     "gloss": "time — as in 시간, 당시"
    },
    {
     "char": "的",
     "reading": "적",
     "gloss": "-ic, -al"
    }
   ],
   "notes": [
    "Of a measure with an end date built in, which is how the pandemic payments were framed."
   ],
   "surfaces": []
  },
  "취약가정": {
   "headword": "취약가정",
   "hanja": "脆弱家庭",
   "meaning": "a vulnerable household",
   "characters": [
    {
     "char": "脆",
     "reading": "취",
     "gloss": "brittle, fragile"
    },
    {
     "char": "弱",
     "reading": "약",
     "gloss": "weak — as in 약하다, 강약"
    }
   ],
   "notes": [
    "취약계층 is the wider term for vulnerable groups. These households were paid in cash without having to apply."
   ],
   "surfaces": []
  },
  "원칙적": {
   "headword": "원칙적",
   "hanja": "原則的",
   "meaning": "in principle, as a general rule",
   "characters": [
    {
     "char": "原",
     "reading": "원",
     "gloss": "origin — the same 原 as in 원리, 원인"
    },
    {
     "char": "則",
     "reading": "칙",
     "gloss": "rule — as in 규칙 “rule”, 법칙"
    },
    {
     "char": "的",
     "reading": "적",
     "gloss": "-ic, -al"
    }
   ],
   "notes": [
    "Carries the same implication as the English: what follows is the rule, and exceptions are about to be named. Here they are — the sentence after it lists who does qualify."
   ],
   "surfaces": []
  },
  "혼인": {
   "headword": "혼인",
   "hanja": "婚姻",
   "meaning": "marriage",
   "characters": [
    {
     "char": "婚",
     "reading": "혼",
     "gloss": "marriage — the same 婚 as in 결혼, 미혼, 기혼"
    },
    {
     "char": "姻",
     "reading": "인",
     "gloss": "marriage tie, affinity"
    }
   ],
   "notes": [
    "The legal word where 결혼 is the everyday one: 혼인신고 is registering a marriage."
   ],
   "surfaces": []
  },
  "국적": {
   "headword": "국적",
   "hanja": "國籍",
   "meaning": "nationality",
   "characters": [
    {
     "char": "國",
     "reading": "국",
     "gloss": "country"
    },
    {
     "char": "籍",
     "reading": "적",
     "gloss": "register, record — as in 호적, 학적"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "난민": {
   "headword": "난민",
   "hanja": "難民",
   "meaning": "a refugee",
   "characters": [
    {
     "char": "難",
     "reading": "난",
     "gloss": "difficulty — the same 難 as in 재난, 취업난"
    },
    {
     "char": "民",
     "reading": "민",
     "gloss": "people"
    }
   ],
   "notes": [
    "Literally people in hardship. 난민 인정 is recognition of refugee status, which is what the passage means by 법에 따라 난민으로 인정된."
   ],
   "surfaces": []
  },
  "주체적": {
   "headword": "주체적",
   "hanja": "主體的",
   "meaning": "on one's own terms, as an agent",
   "characters": [
    {
     "char": "主",
     "reading": "주",
     "gloss": "master, main — as in 주인 “owner”, 주로"
    },
    {
     "char": "體",
     "reading": "체",
     "gloss": "body — as in 신체, 업체"
    },
    {
     "char": "的",
     "reading": "적",
     "gloss": "-ic, -al"
    }
   ],
   "notes": [
    "주체 is the subject that acts, against 대상, the object acted on — and 대상 is the very word in this chapter's other heading, 외국인 대상 지원 서비스. The two sit oddly close together."
   ],
   "surfaces": []
  },
  "임신": {
   "headword": "임신",
   "hanja": "妊娠",
   "meaning": "pregnancy",
   "characters": [
    {
     "char": "妊",
     "reading": "임",
     "gloss": "to conceive"
    },
    {
     "char": "娠",
     "reading": "신",
     "gloss": "to be with child"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "출입국": {
   "headword": "출입국",
   "hanja": "出入國",
   "meaning": "immigration and emigration",
   "characters": [
    {
     "char": "出",
     "reading": "출",
     "gloss": "to go out — the same 出 as in 진출, 출산"
    },
    {
     "char": "入",
     "reading": "입",
     "gloss": "to enter"
    },
    {
     "char": "國",
     "reading": "국",
     "gloss": "country"
    }
   ],
   "notes": [
    "Going out and coming in, taken together — the Korean name for what English calls immigration: 출입국·외국인청."
   ],
   "surfaces": []
  },
  "재외 동포": {
   "headword": "재외 동포",
   "hanja": "在外同胞",
   "meaning": "an overseas Korean",
   "characters": [
    {
     "char": "在",
     "reading": "재",
     "gloss": "to exist, be at — as in 현재 “the present”, 재학"
    },
    {
     "char": "外",
     "reading": "외",
     "gloss": "outside — the same 外 as in 시외버스, 외국"
    },
    {
     "char": "同",
     "reading": "동",
     "gloss": "same — the same 同 as in 공동, 동료"
    },
    {
     "char": "胞",
     "reading": "포",
     "gloss": "womb, kin"
    }
   ],
   "notes": [
    "동포 is literally from the same womb — a person of Korean descent living abroad, or returned. A different legal footing again from 결혼이민자 or 난민."
   ],
   "surfaces": []
  },
  "자문": {
   "headword": "자문",
   "hanja": "諮問",
   "meaning": "professional advice",
   "characters": [
    {
     "char": "諮",
     "reading": "자",
     "gloss": "to consult"
    },
    {
     "char": "問",
     "reading": "문",
     "gloss": "to ask — as in 질문 “question”, 문의"
    }
   ],
   "notes": [
    "Of expert counsel sought from outside: 법률 자문, 자문위원. Not the 자 of 자기 or 자신."
   ],
   "surfaces": []
  },
  "형제": {
   "headword": "형제",
   "hanja": "兄弟",
   "meaning": "brothers, siblings",
   "characters": [
    {
     "char": "兄",
     "reading": "형",
     "gloss": "elder brother — as in 형, 형님"
    },
    {
     "char": "弟",
     "reading": "제",
     "gloss": "younger brother — as in 제자, 사제"
    }
   ],
   "notes": [
    "Used figuratively in the article: the migrant workers the doctor counts as family besides his own."
   ],
   "surfaces": []
  },
  "서툴러": {
   "headword": "서투르다",
   "hanja": null,
   "meaning": "to be clumsy, unpractised",
   "characters": [],
   "notes": [
    "Native Korean, of a skill not yet mastered — here of Korean not well enough to say what one means. 서툴다 is the shortened form."
   ],
   "surfaces": []
  }
 },
 "notes": [
  {
   "why": "The 사회보험 table on p. 41 and the 생계급여 thresholds on p. 42 are set as tables. The four photographs in 생각해 봅시다 are described in one caption rather than four, since the page gives them no labels."
  },
  {
   "why": "Your bracketed taxonomy at the top of p. 41 — 개인 보험 over 사회 보험, with three and four under them — is set as a two-level list. 4대 보험 names the four under 사회 보험."
  }
 ],
 "slug": "07-welfare"
});
