/* Generated by tools/build.py — do not edit.
   Content lives in tools/chapters/ch19_leisure.py; rebuild after changing it. */

KIIP.chapter({
 "number": 19,
 "unit": "문화",
 "title": "여가문화",
 "titleEnglish": "Leisure",
 "chapterGlossary": [],
 "blocks": [
  {
   "type": "section",
   "kind": "warmup",
   "text": "생각해 봅시다"
  },
  {
   "type": "paragraph",
   "spans": [
    "다음은 한국인이 ",
    {
     "word": "여가",
     "annotation": "여가"
    },
    " 시간에 즐기는 ",
    {
     "word": "주요",
     "annotation": "주요"
    },
    " 활동입니다."
   ]
  },
  {
   "type": "labels",
   "items": [
    [
     {
      "word": "텔레비전 시청",
      "annotation": "텔레비전 시청"
     }
    ],
    [
     {
      "word": "영화 관람",
      "annotation": "영화 관람"
     }
    ],
    [
     {
      "word": "등산",
      "annotation": "등산"
     }
    ],
    [
     {
      "word": "배드민턴",
      "annotation": "배드민턴"
     }
    ]
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "01 한국에서 직장 일이나 가정 일, 공부 등에서 벗어난 자유로운 시간에 무엇을 합니까?",
   "spans": [
    "01 한국에서 직장 일이나 ",
    {
     "word": "가정",
     "annotation": "가정"
    },
    " 일, 공부 등에서 ",
    {
     "word": "벗어난",
     "annotation": "벗어나다"
    },
    " 자유로운 시간에 무엇을 합니까?"
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "02 자신의 고향 나라에서는 여가 활동으로 주로 무엇을 합니까?"
  },
  {
   "type": "section",
   "kind": "goals",
   "text": "학습목표"
  },
  {
   "type": "bullet",
   "spans": [
    "한국의 여가문화 종류와 특징을 설명할 수 있다."
   ],
   "ordered": true
  },
  {
   "type": "bullet",
   "spans": [
    "여가활동에 능동적으로 참여할 수 있다."
   ],
   "ordered": true
  },
  {
   "type": "section",
   "kind": "related",
   "text": "관련 단원 확인하기"
  },
  {
   "type": "table",
   "header": [
    {
     "text": "영역",
     "span": 2
    },
    "제목",
    "관련 내용"
   ],
   "rows": [
    [
     {
      "text": "기본",
      "spanDown": 2
     },
     "사회",
     "12. 평생 교육",
     "평생 교육기관과 지원제도"
    ],
    [
     "문화",
     "18. 대중문화",
     "한국의 대중문화"
    ]
   ]
  },
  {
   "type": "section",
   "kind": "part",
   "text": "01 한국에는 어떤 여가문화가 있을까?"
  },
  {
   "type": "heading",
   "level": 2,
   "text": "여가가 있는 삶",
   "titleTranslation": "A life with leisure in it"
  },
  {
   "type": "glossary",
   "entries": [
    {
     "term": "1인당 국민소득",
     "definition": [
      "평균적으로 국민 한 사람이 일정 기간(1년)에 벌어들이는 소득"
     ],
     "annotation": "1인당 국민소득"
    },
    {
     "term": "국민여가활성화기본법",
     "definition": [
      "자유로운 여가활동을 할 수 있는 기반을 만들고 여가활동을 통하여 삶의 질을 향상시킬 수 있도록 지원하는 법"
     ],
     "annotation": "국민여가활성화기본법"
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "일과 생활이 ",
    {
     "word": "균형",
     "annotation": "균형"
    },
    "을 ",
    {
     "word": "갖춘",
     "annotation": "갖추다"
    },
    " 삶을 살아가기 위해서는 자신이 좋아하고 흥미를 느낄 수 있는 활동에 참여하는 시간이 필요하다. 이를 ‘",
    {
     "word": "여가",
     "annotation": "여가"
    },
    "’라고 하며, 이와 관련하여 ",
    {
     "word": "형성",
     "annotation": "형성"
    },
    "된 문화를 ‘",
    {
     "word": "여가문화",
     "annotation": "여가문화"
    },
    "’라고 한다. 한국은 2000년대 초·중반 무렵 ",
    {
     "word": "주 5일 근무제",
     "annotation": "주 5일 근무제"
    },
    " ",
    {
     "word": "시행",
     "annotation": "시행"
    },
    "을 시작으로 현재 ",
    {
     "word": "1인당 국민소득",
     "annotation": "1인당 국민소득"
    },
    " 3만 달러 시대, ",
    {
     "word": "주 52시간 근무제",
     "annotation": "주 52시간 근무제"
    },
    " ",
    {
     "word": "도입",
     "annotation": "도입"
    },
    ", 평균 ",
    {
     "word": "기대 수명",
     "annotation": "기대 수명"
    },
    " 증가와 같은 변화를 맞이하면서 여가의 ",
    {
     "word": "중요성",
     "annotation": "중요성"
    },
    "이 더욱 높아지고 있다. 한국 정부에서도 여가가 있는 삶을 ",
    {
     "word": "보장",
     "annotation": "보장"
    },
    " 받을 수 있도록 ‘",
    {
     "word": "국민여가활성화기본법",
     "annotation": "국민여가활성화기본법"
    },
    "’을 ",
    {
     "word": "제정",
     "annotation": "제정"
    },
    "하기도 하였다."
   ],
   "translation": "Living a life in which work and living are in balance takes time spent on the activities one likes and can take an interest in. That is what is meant by 여가, and the culture formed around it is 여가문화. Korea began the five-day working week around the early to middle 2000s, and as it has met further changes since — an era of thirty thousand dollars of national income a head, the introduction of the 52-hour week, a rising average life expectancy — the importance of leisure has risen further still. The government has gone so far as to enact a Framework Act on the Promotion of National Leisure, so that a life with leisure in it may be guaranteed.",
   "sentences": [
    {
     "spans": [
      "일과 생활이 ",
      {
       "word": "균형",
       "annotation": "균형"
      },
      "을 ",
      {
       "word": "갖춘",
       "annotation": "갖추다"
      },
      " 삶을 살아가기 위해서는 자신이 좋아하고 흥미를 느낄 수 있는 활동에 참여하는 시간이 필요하다. "
     ],
     "translation": "Living a life in which work and living are in balance takes time spent on the activities one likes and can take an interest in."
    },
    {
     "spans": [
      "이를 ‘",
      {
       "word": "여가",
       "annotation": "여가"
      },
      "’라고 하며, 이와 관련하여 ",
      {
       "word": "형성",
       "annotation": "형성"
      },
      "된 문화를 ‘",
      {
       "word": "여가문화",
       "annotation": "여가문화"
      },
      "’라고 한다. "
     ],
     "translation": "That is what is meant by 여가, and the culture formed around it is 여가문화."
    },
    {
     "spans": [
      "한국은 2000년대 초·중반 무렵 ",
      {
       "word": "주 5일 근무제",
       "annotation": "주 5일 근무제"
      },
      " ",
      {
       "word": "시행",
       "annotation": "시행"
      },
      "을 시작으로 현재 ",
      {
       "word": "1인당 국민소득",
       "annotation": "1인당 국민소득"
      },
      " 3만 달러 시대, ",
      {
       "word": "주 52시간 근무제",
       "annotation": "주 52시간 근무제"
      },
      " ",
      {
       "word": "도입",
       "annotation": "도입"
      },
      ", 평균 ",
      {
       "word": "기대 수명",
       "annotation": "기대 수명"
      },
      " 증가와 같은 변화를 맞이하면서 여가의 ",
      {
       "word": "중요성",
       "annotation": "중요성"
      },
      "이 더욱 높아지고 있다. "
     ],
     "translation": "Korea began the five-day working week around the early to middle 2000s, and as it has met further changes since — an era of thirty thousand dollars of national income a head, the introduction of the 52-hour week, a rising average life expectancy — the importance of leisure has risen further still."
    },
    {
     "spans": [
      "한국 정부에서도 여가가 있는 삶을 ",
      {
       "word": "보장",
       "annotation": "보장"
      },
      " 받을 수 있도록 ‘",
      {
       "word": "국민여가활성화기본법",
       "annotation": "국민여가활성화기본법"
      },
      "’을 ",
      {
       "word": "제정",
       "annotation": "제정"
      },
      "하기도 하였다."
     ],
     "translation": "The government has gone so far as to enact a Framework Act on the Promotion of National Leisure, so that a life with leisure in it may be guaranteed."
    }
   ]
  },
  {
   "type": "heading",
   "level": 2,
   "text": "한국의 여가",
   "titleTranslation": "Leisure in Korea"
  },
  {
   "type": "glossary",
   "entries": [
    {
     "term": "동호회",
     "definition": [
      "취미나 공통의 관심사, 목표를 가지고 정보를 나누면서 함께 즐기는 사람들의 모임"
     ],
     "annotation": "동호회"
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    {
     "word": "문화체육관광부",
     "annotation": "문화체육관광부"
    },
    "의 ‘2018 국민여가활동 조사’에 따르면 한국인의 ",
    {
     "word": "평일",
     "annotation": "평일"
    },
    "과 ",
    {
     "word": "휴일",
     "annotation": "휴일"
    },
    " 여가 시간이 예전에 비해 증가하였고, ",
    {
     "word": "월평균",
     "annotation": "월평균"
    },
    " 여가 ",
    {
     "word": "비용",
     "annotation": "비용"
    },
    " 역시 ",
    {
     "word": "상승",
     "annotation": "상승"
    },
    "한 것으로 나타났다. 이는 과거보다 여가를 더 중요하게 여기고 있음을 보여준다."
   ],
   "translation": "By the Ministry of Culture, Sports and Tourism's 2018 survey of national leisure activity, Koreans' leisure time on both working days and holidays has increased against what it was, and monthly spending on leisure has risen as well. That shows leisure being held more important than it was.",
   "sentences": [
    {
     "spans": [
      {
       "word": "문화체육관광부",
       "annotation": "문화체육관광부"
      },
      "의 ‘2018 국민여가활동 조사’에 따르면 한국인의 ",
      {
       "word": "평일",
       "annotation": "평일"
      },
      "과 ",
      {
       "word": "휴일",
       "annotation": "휴일"
      },
      " 여가 시간이 예전에 비해 증가하였고, ",
      {
       "word": "월평균",
       "annotation": "월평균"
      },
      " 여가 ",
      {
       "word": "비용",
       "annotation": "비용"
      },
      " 역시 ",
      {
       "word": "상승",
       "annotation": "상승"
      },
      "한 것으로 나타났다. "
     ],
     "translation": "By the Ministry of Culture, Sports and Tourism's 2018 survey of national leisure activity, Koreans' leisure time on both working days and holidays has increased against what it was, and monthly spending on leisure has risen as well."
    },
    {
     "spans": [
      "이는 과거보다 여가를 더 중요하게 여기고 있음을 보여준다."
     ],
     "translation": "That shows leisure being held more important than it was."
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "한국인이 가장 많이 참여한 여가활동은 ",
    {
     "word": "휴식",
     "annotation": "휴식"
    },
    "활동으로 TV 시청, ",
    {
     "word": "낮잠",
     "annotation": "낮잠"
    },
    ", ",
    {
     "word": "산책",
     "annotation": "산책"
    },
    ", 찜질방 등이 여기에 해당한다. 또한, 쇼핑, ",
    {
     "word": "외식",
     "annotation": "외식"
    },
    ", 인터넷 ",
    {
     "word": "검색",
     "annotation": "검색"
    },
    ", ",
    {
     "word": "1인 미디어",
     "annotation": "1인 미디어"
    },
    ", SNS 등과 같은 ",
    {
     "word": "취미",
     "annotation": "취미"
    },
    "·",
    {
     "word": "오락",
     "annotation": "오락"
    },
    "활동 ",
    {
     "word": "비중",
     "annotation": "비중"
    },
    "도 높다. 한편, 친구를 만나 이야기를 나누기도 하고, ",
    {
     "word": "친지",
     "annotation": "친지"
    },
    " 및 친척을 방문하여 ",
    {
     "word": "오붓한",
     "annotation": "오붓하다"
    },
    " 시간을 보내기도 한다. 또한, 운동이나 ",
    {
     "word": "악기",
     "annotation": "악기"
    },
    ", ",
    {
     "word": "독서",
     "annotation": "독서"
    },
    ", 외국어 등 여러 분야에서 자신이 좋아하거나 배우고 싶은 것을 다른 사람들과 함께 공유할 수 있는 ",
    {
     "word": "동호회",
     "annotation": "동호회"
    },
    "가 ",
    {
     "word": "활성화",
     "annotation": "활성화"
    },
    " 되어 있다. 스포츠·",
    {
     "word": "문화예술",
     "annotation": "문화예술"
    },
    " ",
    {
     "word": "관람",
     "annotation": "관람"
    },
    "도 한국에서 인기 있는 여가활동이다. 스포츠 ",
    {
     "word": "경기장",
     "annotation": "경기장"
    },
    "을 직접 방문하여 응원하기도 하며, ",
    {
     "word": "박물관",
     "annotation": "박물관"
    },
    "·",
    {
     "word": "미술관",
     "annotation": "미술관"
    },
    "에서 ",
    {
     "word": "전시회",
     "annotation": "전시회"
    },
    " 관람, ",
    {
     "word": "공연장",
     "annotation": "공연장"
    },
    "에서 콘서트, ",
    {
     "word": "뮤지컬",
     "annotation": "뮤지컬"
    },
    ", ",
    {
     "word": "연극",
     "annotation": "연극"
    },
    "을 즐기기도 한다. ",
    {
     "word": "코로나19",
     "annotation": "코로나19"
    },
    " 이후에는 전시나 공연 온라인 서비스를 통해 관람하는 새로운 ",
    {
     "word": "형태",
     "annotation": "형태"
    },
    "의 여가문화도 나타났다."
   ],
   "translation": "The leisure activity Koreans took part in most was rest — watching television, napping, walking, the 찜질방 and the like. Hobbies and amusements weigh heavily too: shopping, eating out, searching the internet, one-person media, social networks. Some meet friends and talk; some visit relatives and kin and spend a snug hour with them. There are also flourishing clubs, in which what one likes or wants to learn — sport, an instrument, reading, a foreign language — can be shared with others. Going to sport and to the arts is popular here as well. People go to the ground itself to cheer, see exhibitions at museums and galleries, and enjoy concerts, musicals and plays at the theatre. Since Covid-19 a new form of leisure has appeared too, watching exhibitions and performances through online services.",
   "sentences": [
    {
     "spans": [
      "한국인이 가장 많이 참여한 여가활동은 ",
      {
       "word": "휴식",
       "annotation": "휴식"
      },
      "활동으로 TV 시청, ",
      {
       "word": "낮잠",
       "annotation": "낮잠"
      },
      ", ",
      {
       "word": "산책",
       "annotation": "산책"
      },
      ", 찜질방 등이 여기에 해당한다. "
     ],
     "translation": "The leisure activity Koreans took part in most was rest — watching television, napping, walking, the 찜질방 and the like."
    },
    {
     "spans": [
      "또한, 쇼핑, ",
      {
       "word": "외식",
       "annotation": "외식"
      },
      ", 인터넷 ",
      {
       "word": "검색",
       "annotation": "검색"
      },
      ", ",
      {
       "word": "1인 미디어",
       "annotation": "1인 미디어"
      },
      ", SNS 등과 같은 ",
      {
       "word": "취미",
       "annotation": "취미"
      },
      "·",
      {
       "word": "오락",
       "annotation": "오락"
      },
      "활동 ",
      {
       "word": "비중",
       "annotation": "비중"
      },
      "도 높다. "
     ],
     "translation": "Hobbies and amusements weigh heavily too: shopping, eating out, searching the internet, one-person media, social networks."
    },
    {
     "spans": [
      "한편, 친구를 만나 이야기를 나누기도 하고, ",
      {
       "word": "친지",
       "annotation": "친지"
      },
      " 및 친척을 방문하여 ",
      {
       "word": "오붓한",
       "annotation": "오붓하다"
      },
      " 시간을 보내기도 한다. "
     ],
     "translation": "Some meet friends and talk; some visit relatives and kin and spend a snug hour with them."
    },
    {
     "spans": [
      "또한, 운동이나 ",
      {
       "word": "악기",
       "annotation": "악기"
      },
      ", ",
      {
       "word": "독서",
       "annotation": "독서"
      },
      ", 외국어 등 여러 분야에서 자신이 좋아하거나 배우고 싶은 것을 다른 사람들과 함께 공유할 수 있는 ",
      {
       "word": "동호회",
       "annotation": "동호회"
      },
      "가 ",
      {
       "word": "활성화",
       "annotation": "활성화"
      },
      " 되어 있다. "
     ],
     "translation": "There are also flourishing clubs, in which what one likes or wants to learn — sport, an instrument, reading, a foreign language — can be shared with others."
    },
    {
     "spans": [
      "스포츠·",
      {
       "word": "문화예술",
       "annotation": "문화예술"
      },
      " ",
      {
       "word": "관람",
       "annotation": "관람"
      },
      "도 한국에서 인기 있는 여가활동이다. "
     ],
     "translation": "Going to sport and to the arts is popular here as well."
    },
    {
     "spans": [
      "스포츠 ",
      {
       "word": "경기장",
       "annotation": "경기장"
      },
      "을 직접 방문하여 응원하기도 하며, ",
      {
       "word": "박물관",
       "annotation": "박물관"
      },
      "·",
      {
       "word": "미술관",
       "annotation": "미술관"
      },
      "에서 ",
      {
       "word": "전시회",
       "annotation": "전시회"
      },
      " 관람, ",
      {
       "word": "공연장",
       "annotation": "공연장"
      },
      "에서 콘서트, ",
      {
       "word": "뮤지컬",
       "annotation": "뮤지컬"
      },
      ", ",
      {
       "word": "연극",
       "annotation": "연극"
      },
      "을 즐기기도 한다. "
     ],
     "translation": "People go to the ground itself to cheer, see exhibitions at museums and galleries, and enjoy concerts, musicals and plays at the theatre."
    },
    {
     "spans": [
      {
       "word": "코로나19",
       "annotation": "코로나19"
      },
      " 이후에는 전시나 공연 온라인 서비스를 통해 관람하는 새로운 ",
      {
       "word": "형태",
       "annotation": "형태"
      },
      "의 여가문화도 나타났다."
     ],
     "translation": "Since Covid-19 a new form of leisure has appeared too, watching exhibitions and performances through online services."
    }
   ]
  },
  {
   "type": "figure",
   "text": "여가시간 및 여가비용 추이(문화체육관광부, 국민여가활동조사 2018) — 평일과 휴일의 여가 시간, 그리고 월평균 여가 비용이 2006년부터 2018년까지 어떻게 움직였는지를 겹쳐 그린 그래프"
  },
  {
   "type": "figure",
   "text": "‘슈퍼주니어’의 온라인 콘서트 모습"
  },
  {
   "type": "section",
   "kind": "aside",
   "text": "알아두면 좋아요",
   "topic": "여행을 떠나요! 대한민국 구석구석에 대한 여행 정보",
   "titleTranslation": "Let’s travel! Information on every corner of Korea"
  },
  {
   "type": "paragraph",
   "spans": [
    {
     "word": "한국관광공사",
     "annotation": "한국관광공사"
    },
    "가 운영하는 ‘",
    {
     "word": "대한민국 구석구석",
     "annotation": "대한민국 구석구석"
    },
    "’ 누리집(korean.visitkorea.or.kr)에서는 각 ",
    {
     "word": "지역별",
     "annotation": "지역별"
    },
    " 여행 정보와 전국의 ",
    {
     "word": "축제",
     "annotation": "축제"
    },
    " 정보를 ",
    {
     "word": "월별",
     "annotation": "월별"
    },
    "로 확인할 수 있다. 이 누리집에서는 가족과 함께 가는 여행, 휴식과 ",
    {
     "word": "회복",
     "annotation": "회복"
    },
    "이 필요한 여행, 아이들이 좋아하는 여행 등 주제에 따른 ",
    {
     "word": "관광",
     "annotation": "관광"
    },
    " 코스도 자세히 안내하고 있다. ‘대한민국 구석구석’ 블로그, 페이스북, 트위터, 인스타그램 등에서도 다양한 정보와 여행 사진을 ",
    {
     "word": "참고",
     "annotation": "참고"
    },
    "할 수 있다."
   ],
   "translation": "On the ‘대한민국 구석구석’ website (korean.visitkorea.or.kr), run by the Korea Tourism Organization, travel information for each region and festivals across the country can be looked up month by month. The site also sets out tourist routes by theme in detail: travelling with the family, travelling when rest and recovery are needed, travelling that children enjoy. Plenty of information and travel photographs can be found on the ‘대한민국 구석구석’ blog, Facebook, Twitter and Instagram as well.",
   "sentences": [
    {
     "spans": [
      {
       "word": "한국관광공사",
       "annotation": "한국관광공사"
      },
      "가 운영하는 ‘",
      {
       "word": "대한민국 구석구석",
       "annotation": "대한민국 구석구석"
      },
      "’ 누리집(korean.visitkorea.or.kr)에서는 각 ",
      {
       "word": "지역별",
       "annotation": "지역별"
      },
      " 여행 정보와 전국의 ",
      {
       "word": "축제",
       "annotation": "축제"
      },
      " 정보를 ",
      {
       "word": "월별",
       "annotation": "월별"
      },
      "로 확인할 수 있다. "
     ],
     "translation": "On the ‘대한민국 구석구석’ website (korean.visitkorea.or.kr), run by the Korea Tourism Organization, travel information for each region and festivals across the country can be looked up month by month."
    },
    {
     "spans": [
      "이 누리집에서는 가족과 함께 가는 여행, 휴식과 ",
      {
       "word": "회복",
       "annotation": "회복"
      },
      "이 필요한 여행, 아이들이 좋아하는 여행 등 주제에 따른 ",
      {
       "word": "관광",
       "annotation": "관광"
      },
      " 코스도 자세히 안내하고 있다. "
     ],
     "translation": "The site also sets out tourist routes by theme in detail: travelling with the family, travelling when rest and recovery are needed, travelling that children enjoy."
    },
    {
     "spans": [
      "‘대한민국 구석구석’ 블로그, 페이스북, 트위터, 인스타그램 등에서도 다양한 정보와 여행 사진을 ",
      {
       "word": "참고",
       "annotation": "참고"
      },
      "할 수 있다."
     ],
     "translation": "Plenty of information and travel photographs can be found on the ‘대한민국 구석구석’ blog, Facebook, Twitter and Instagram as well."
    }
   ]
  },
  {
   "type": "section",
   "kind": "part",
   "text": "02 여가활동에는 어떻게 참여할 수 있을까?"
  },
  {
   "type": "heading",
   "level": 2,
   "text": "여가활동 참여하기",
   "titleTranslation": "Taking part in leisure"
  },
  {
   "type": "glossary",
   "entries": [
    {
     "term": "행정복지센터",
     "definition": [
      "지역 주민의 생활 업무를 처리하고, 문화 및 복지 서비스를 지원하는 행정기관"
     ],
     "annotation": "행정복지센터"
    },
    {
     "term": "평생학습관",
     "definition": [
      "지역주민을 대상으로 인문교양, 문화예술, 직업능력 향상, 시민참여 등의 평생학습 프로그램을 운영"
     ],
     "annotation": "평생학습관"
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "여가활동에 참여하는 방법은 점점 쉽고 다양해지고 있다. 영화, 스포츠, 공연과 같은 문화예술 관람을 원하면 직접 방문하여 ",
    {
     "word": "입장권",
     "annotation": "입장권"
    },
    "을 살 수도 있고 스마트폰 ",
    {
     "word": "어플",
     "annotation": "어플"
    },
    "(앱)이나 누리집을 통해 ",
    {
     "word": "예매",
     "annotation": "예매"
    },
    "할 수도 있다."
   ],
   "translation": "Ways of taking part in leisure are becoming easier and more various. Someone wanting to see a film, a sporting fixture or a performance can go and buy a ticket in person, or book through a smartphone app or a website.",
   "sentences": [
    {
     "spans": [
      "여가활동에 참여하는 방법은 점점 쉽고 다양해지고 있다. "
     ],
     "translation": "Ways of taking part in leisure are becoming easier and more various."
    },
    {
     "spans": [
      "영화, 스포츠, 공연과 같은 문화예술 관람을 원하면 직접 방문하여 ",
      {
       "word": "입장권",
       "annotation": "입장권"
      },
      "을 살 수도 있고 스마트폰 ",
      {
       "word": "어플",
       "annotation": "어플"
      },
      "(앱)이나 누리집을 통해 ",
      {
       "word": "예매",
       "annotation": "예매"
      },
      "할 수도 있다."
     ],
     "translation": "Someone wanting to see a film, a sporting fixture or a performance can go and buy a ticket in person, or book through a smartphone app or a website."
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "또한 각 지역의 ",
    {
     "word": "행정복지센터",
     "annotation": "행정복지센터"
    },
    "나 ",
    {
     "word": "평생학습관",
     "annotation": "평생학습관"
    },
    "의 여가 프로그램에도 적은 비용으로 참여할 수 있다. 각 ",
    {
     "word": "기관",
     "annotation": "기관"
    },
    "은 지역 주민이 무엇을 배우기를 원하는지 조사하여 음악/미술/외국어/건강/컴퓨터/요리 등 다양한 프로그램을 제공하고 있다. ",
    {
     "word": "백화점",
     "annotation": "백화점"
    },
    "이나 ",
    {
     "word": "대형 마트",
     "annotation": "대형 마트"
    },
    "의 ",
    {
     "word": "문화센터",
     "annotation": "문화센터"
    },
    "에서도 다양한 프로그램을 만들어 놓고 있는데 여기에 참여하는 사람도 많다."
   ],
   "translation": "The leisure programmes at a district's community service centre or lifelong learning centre can also be joined for little money. Each of them surveys what local residents want to learn and offers a range accordingly — music, art, languages, health, computing, cooking. The culture centres at department stores and the large supermarkets put on a range of programmes too, and a good many people go to those.",
   "sentences": [
    {
     "spans": [
      "또한 각 지역의 ",
      {
       "word": "행정복지센터",
       "annotation": "행정복지센터"
      },
      "나 ",
      {
       "word": "평생학습관",
       "annotation": "평생학습관"
      },
      "의 여가 프로그램에도 적은 비용으로 참여할 수 있다. "
     ],
     "translation": "The leisure programmes at a district's community service centre or lifelong learning centre can also be joined for little money."
    },
    {
     "spans": [
      "각 ",
      {
       "word": "기관",
       "annotation": "기관"
      },
      "은 지역 주민이 무엇을 배우기를 원하는지 조사하여 음악/미술/외국어/건강/컴퓨터/요리 등 다양한 프로그램을 제공하고 있다. "
     ],
     "translation": "Each of them surveys what local residents want to learn and offers a range accordingly — music, art, languages, health, computing, cooking."
    },
    {
     "spans": [
      {
       "word": "백화점",
       "annotation": "백화점"
      },
      "이나 ",
      {
       "word": "대형 마트",
       "annotation": "대형 마트"
      },
      "의 ",
      {
       "word": "문화센터",
       "annotation": "문화센터"
      },
      "에서도 다양한 프로그램을 만들어 놓고 있는데 여기에 참여하는 사람도 많다."
     ],
     "translation": "The culture centres at department stores and the large supermarkets put on a range of programmes too, and a good many people go to those."
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "학교, 지역, 회사, 인터넷 ",
    {
     "word": "커뮤니티",
     "annotation": "커뮤니티"
    },
    " 등에는 다양한 동호회가 있다. 사진, 축구, 미술, 독서 등 자신이 흥미를 가진 분야를 찾아 ",
    {
     "word": "가입",
     "annotation": "가입"
    },
    "하여 다른 사람들과 공통의 ",
    {
     "word": "관심사",
     "annotation": "관심사"
    },
    "나 정보를 나누면서 함께 즐길 수 있다."
   ],
   "translation": "Schools, districts, companies and internet communities all have clubs of various kinds. One can find a field one is interested in — photography, football, art, reading — join it, and enjoy it with others while sharing a common interest and what one knows.",
   "sentences": [
    {
     "spans": [
      "학교, 지역, 회사, 인터넷 ",
      {
       "word": "커뮤니티",
       "annotation": "커뮤니티"
      },
      " 등에는 다양한 동호회가 있다. "
     ],
     "translation": "Schools, districts, companies and internet communities all have clubs of various kinds."
    },
    {
     "spans": [
      "사진, 축구, 미술, 독서 등 자신이 흥미를 가진 분야를 찾아 ",
      {
       "word": "가입",
       "annotation": "가입"
      },
      "하여 다른 사람들과 공통의 ",
      {
       "word": "관심사",
       "annotation": "관심사"
      },
      "나 정보를 나누면서 함께 즐길 수 있다."
     ],
     "translation": "One can find a field one is interested in — photography, football, art, reading — join it, and enjoy it with others while sharing a common interest and what one knows."
    }
   ]
  },
  {
   "type": "figure",
   "text": "수원 평생학습관 누리집"
  },
  {
   "type": "heading",
   "level": 2,
   "text": "변화하는 여가문화",
   "titleTranslation": "How leisure is changing"
  },
  {
   "type": "glossary",
   "entries": [
    {
     "term": "웹툰(WEBTOON)",
     "definition": [
      "웹(WEB)과 카툰(CARTOON)의 합성어로서 인터넷 만화를 지칭함"
     ],
     "annotation": "웹툰"
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "일과 삶의 균형(",
    {
     "word": "워라벨",
     "annotation": "워라벨"
    },
    ": Work and Life Balance), 휴식이 있는 삶에 대한 ",
    {
     "word": "요구",
     "annotation": "요구"
    },
    "가 높아지면서 여가문화는 더욱 강조될 것으로 예상된다. 예를 들어, 건강에 대한 관심이 ",
    {
     "word": "지속적",
     "annotation": "지속적"
    },
    "으로 높아짐으로써 ",
    {
     "word": "헬스",
     "annotation": "헬스"
    },
    ", 수영, ",
    {
     "word": "요가",
     "annotation": "요가"
    },
    " 등에 대한 ",
    {
     "word": "수요",
     "annotation": "수요"
    },
    "가 계속 늘어날 것이다. 금요일 오후부터 주말을 이용한 국내외 여행이 ",
    {
     "word": "일상화",
     "annotation": "일상화"
    },
    "되고, ",
    {
     "word": "자연휴양림",
     "annotation": "자연휴양림"
    },
    " 등에서 ",
    {
     "word": "캠핑",
     "annotation": "캠핑"
    },
    "을 즐기는 사람도 증가할 것이다."
   ],
   "translation": "As the demand grows for a balance between work and life — 워라벨, Work and Life Balance — and for a life with rest in it, leisure culture is expected to be stressed further. Interest in health, for one thing, keeps rising, so demand for the gym, for swimming and for yoga will go on increasing. Travel at home and abroad from Friday afternoon through the weekend will become an ordinary thing, and more people will camp in the recreational forests and the like.",
   "sentences": [
    {
     "spans": [
      "일과 삶의 균형(",
      {
       "word": "워라벨",
       "annotation": "워라벨"
      },
      ": Work and Life Balance), 휴식이 있는 삶에 대한 ",
      {
       "word": "요구",
       "annotation": "요구"
      },
      "가 높아지면서 여가문화는 더욱 강조될 것으로 예상된다. "
     ],
     "translation": "As the demand grows for a balance between work and life — 워라벨, Work and Life Balance — and for a life with rest in it, leisure culture is expected to be stressed further."
    },
    {
     "spans": [
      "예를 들어, 건강에 대한 관심이 ",
      {
       "word": "지속적",
       "annotation": "지속적"
      },
      "으로 높아짐으로써 ",
      {
       "word": "헬스",
       "annotation": "헬스"
      },
      ", 수영, ",
      {
       "word": "요가",
       "annotation": "요가"
      },
      " 등에 대한 ",
      {
       "word": "수요",
       "annotation": "수요"
      },
      "가 계속 늘어날 것이다. "
     ],
     "translation": "Interest in health, for one thing, keeps rising, so demand for the gym, for swimming and for yoga will go on increasing."
    },
    {
     "spans": [
      "금요일 오후부터 주말을 이용한 국내외 여행이 ",
      {
       "word": "일상화",
       "annotation": "일상화"
      },
      "되고, ",
      {
       "word": "자연휴양림",
       "annotation": "자연휴양림"
      },
      " 등에서 ",
      {
       "word": "캠핑",
       "annotation": "캠핑"
      },
      "을 즐기는 사람도 증가할 것이다."
     ],
     "translation": "Travel at home and abroad from Friday afternoon through the weekend will become an ordinary thing, and more people will camp in the recreational forests and the like."
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "또한 ",
    {
     "word": "스마트기기",
     "annotation": "스마트기기"
    },
    "를 활용하여 ",
    {
     "word": "웹서핑",
     "annotation": "웹서핑"
    },
    ", ",
    {
     "word": "모바일메신저",
     "annotation": "모바일메신저"
    },
    ", SNS활동, 게임, 쇼핑, 음악 ",
    {
     "word": "감상",
     "annotation": "감상"
    },
    ", 인터넷 방송 시청, ",
    {
     "word": "웹툰",
     "annotation": "웹툰"
    },
    " 읽기 등은 물론 직접 온라인 ",
    {
     "word": "콘텐츠",
     "annotation": "콘텐츠"
    },
    "를 ",
    {
     "word": "만들어내는",
     "annotation": "만들어내다"
    },
    " 방식의 여가활동을 즐기는 사람도 더욱 늘어날 것이다."
   ],
   "translation": "More people, too, will take their leisure through smart devices — surfing the web, mobile messaging, social networks, games, shopping, listening to music, watching internet broadcasts, reading 웹툰 — and, beyond all that, in making online content themselves.",
   "sentences": [
    {
     "spans": [
      "또한 ",
      {
       "word": "스마트기기",
       "annotation": "스마트기기"
      },
      "를 활용하여 ",
      {
       "word": "웹서핑",
       "annotation": "웹서핑"
      },
      ", ",
      {
       "word": "모바일메신저",
       "annotation": "모바일메신저"
      },
      ", SNS활동, 게임, 쇼핑, 음악 ",
      {
       "word": "감상",
       "annotation": "감상"
      },
      ", 인터넷 방송 시청, ",
      {
       "word": "웹툰",
       "annotation": "웹툰"
      },
      " 읽기 등은 물론 직접 온라인 ",
      {
       "word": "콘텐츠",
       "annotation": "콘텐츠"
      },
      "를 ",
      {
       "word": "만들어내는",
       "annotation": "만들어내다"
      },
      " 방식의 여가활동을 즐기는 사람도 더욱 늘어날 것이다."
     ],
     "translation": "More people, too, will take their leisure through smart devices — surfing the web, mobile messaging, social networks, games, shopping, listening to music, watching internet broadcasts, reading 웹툰 — and, beyond all that, in making online content themselves."
    }
   ]
  },
  {
   "type": "chart",
   "caption": "스마트기기를 활용한 여가활동(문화체육관광부, 국민여가활동조사 2018)(단위: %) — 스마트 기기 활용자 기준, 복수 응답",
   "unit": "%",
   "rows": [
    [
     "웹서핑",
     31.3
    ],
    [
     "모바일 메신저",
     17.9
    ],
    [
     "SNS활동",
     14.6
    ],
    [
     "게임",
     14.1
    ],
    [
     "TV시청",
     4.4
    ],
    [
     "쇼핑",
     3.9
    ],
    [
     "음악감상",
     3.8
    ],
    [
     "인터넷방송 시청",
     2.7
    ],
    [
     "웹툰 읽기",
     2.7
    ],
    [
     "웹소설 읽기",
     2.0
    ]
   ]
  },
  {
   "type": "section",
   "kind": "aside",
   "text": "알아두면 좋아요",
   "topic": "문화가 있는 날을 아세요?",
   "titleTranslation": "Do you know about the Day of Culture?"
  },
  {
   "type": "paragraph",
   "spans": [
    "‘",
    {
     "word": "문화가 있는 날",
     "annotation": "문화가 있는 날"
    },
    "’은 2014년 1월 29일 처음 시작되었다. 매달 마지막 수요일에 일상에서 문화를 쉽게 접할 수 있도록 다양한 문화 혜택을 제공하고 있다. ‘문화가 있는 날’에는 영화관, 공연장, 박물관, 미술관, ",
    {
     "word": "문화재",
     "annotation": "문화재"
    },
    " 등 전국의 2천여 개 ",
    {
     "word": "문화시설",
     "annotation": "문화시설"
    },
    "을 ",
    {
     "word": "할인",
     "annotation": "할인"
    },
    " 또는 무료로 즐길 수 있다. ",
    {
     "word": "더불어",
     "annotation": "더불어"
    },
    " 직장인도 ",
    {
     "word": "퇴근",
     "annotation": "퇴근"
    },
    " 후 이용이 가능하도록 일부 문화시설은 ",
    {
     "word": "야간 개방",
     "annotation": "야간 개방"
    },
    "을 한다. 예를 들어 2020년 기준으로 영화관에서는 매달 마지막 수요일 저녁 5시~9시까지의 영화는 5,000원으로 관람할 수 있다. (누리집: www.culture.go.kr)"
   ],
   "translation": "‘문화가 있는 날’ began on 29 January 2014. On the last Wednesday of every month it offers a range of cultural benefits, so that culture is easy to come by in daily life. On the day, some two thousand cultural venues across the country — cinemas, concert halls, museums, galleries, heritage sites — can be enjoyed at a discount or free. Some venues also open in the evening so that people can visit after work. As of 2020, for instance, cinemas show films for 5,000 won between five and nine in the evening on the last Wednesday of the month. Website: www.culture.go.kr",
   "sentences": [
    {
     "spans": [
      "‘",
      {
       "word": "문화가 있는 날",
       "annotation": "문화가 있는 날"
      },
      "’은 2014년 1월 29일 처음 시작되었다. "
     ],
     "translation": "‘문화가 있는 날’ began on 29 January 2014."
    },
    {
     "spans": [
      "매달 마지막 수요일에 일상에서 문화를 쉽게 접할 수 있도록 다양한 문화 혜택을 제공하고 있다. "
     ],
     "translation": "On the last Wednesday of every month it offers a range of cultural benefits, so that culture is easy to come by in daily life."
    },
    {
     "spans": [
      "‘문화가 있는 날’에는 영화관, 공연장, 박물관, 미술관, ",
      {
       "word": "문화재",
       "annotation": "문화재"
      },
      " 등 전국의 2천여 개 ",
      {
       "word": "문화시설",
       "annotation": "문화시설"
      },
      "을 ",
      {
       "word": "할인",
       "annotation": "할인"
      },
      " 또는 무료로 즐길 수 있다. "
     ],
     "translation": "On the day, some two thousand cultural venues across the country — cinemas, concert halls, museums, galleries, heritage sites — can be enjoyed at a discount or free."
    },
    {
     "spans": [
      {
       "word": "더불어",
       "annotation": "더불어"
      },
      " 직장인도 ",
      {
       "word": "퇴근",
       "annotation": "퇴근"
      },
      " 후 이용이 가능하도록 일부 문화시설은 ",
      {
       "word": "야간 개방",
       "annotation": "야간 개방"
      },
      "을 한다. "
     ],
     "translation": "Some venues also open in the evening so that people can visit after work."
    },
    {
     "spans": [
      "예를 들어 2020년 기준으로 영화관에서는 매달 마지막 수요일 저녁 5시~9시까지의 영화는 5,000원으로 관람할 수 있다. "
     ],
     "translation": "As of 2020, for instance, cinemas show films for 5,000 won between five and nine in the evening on the last Wednesday of the month."
    },
    {
     "spans": [
      "(누리집: www.culture.go.kr)"
     ],
     "translation": "Website: www.culture.go.kr"
    }
   ]
  },
  {
   "type": "section",
   "kind": "review",
   "text": "주요 내용정리"
  },
  {
   "type": "heading",
   "level": 3,
   "text": "01 한국에는 어떤 여가문화가 있을까?"
  },
  {
   "type": "bullet",
   "spans": [
    "한국은 1인당 국민소득 3만 달러 시대, 주 ",
    {
     "blank": ""
    },
    " 근무제 도입 등과 같은 변화를 맞이하면서 여가의 중요성이 더욱 높아지고 있다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "운동이나 악기, 독서, 외국어 등 자신이 좋아하거나 배우고 싶은 것을 다른 사람들과 정보를 나누면서 함께 즐기는 ",
    {
     "blank": ""
    },
    "가 활성화되어 있다."
   ]
  },
  {
   "type": "heading",
   "level": 3,
   "text": "02 여가활동에는 어떻게 참여할 수 있을까?"
  },
  {
   "type": "bullet",
   "spans": [
    "지역 주민의 생활 업무를 처리하고, 문화 및 복지 서비스를 지원하는 행정기관인 ",
    {
     "blank": ""
    },
    "를 통해 여가 프로그램에 참여할 수 있다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    {
     "blank": ""
    },
    "과 ",
    {
     "blank": ""
    },
    "의 균형, 휴식이 있는 삶에 대한 기대가 높아지면서 여가문화는 더욱 중시될 것이다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    {
     "blank": ""
    },
    " 관리에 대한 관심이 지속적으로 늘어남으로써 헬스, 수영, 요가에 대한 수요도 증가할 것이다."
   ]
  },
  {
   "type": "section",
   "kind": "discuss",
   "text": "이야기 나누기",
   "topic": "한국인의 여가활동의 목적은?",
   "titleTranslation": "What do Koreans do leisure activities for?"
  },
  {
   "type": "paragraph",
   "spans": [
    "2018 국민여가활동조사 ",
    {
     "word": "보고서",
     "annotation": "보고서"
    },
    "에 따르면 한국 국민의 여가활동의 ",
    {
     "word": "주된",
     "annotation": "주되다"
    },
    " 목적은 ‘개인의 즐거움’으로 나타났다. 그리고 ‘마음의 ",
    {
     "word": "안정",
     "annotation": "안정"
    },
    "과 휴식’, ‘스트레스 ",
    {
     "word": "해소",
     "annotation": "해소"
    },
    "’, ‘",
    {
     "word": "자기만족",
     "annotation": "자기만족"
    },
    "’, ‘가족과 시간을 함께하기’ 등에 응답한 ",
    {
     "word": "비율",
     "annotation": "비율"
    },
    "도 ",
    {
     "word": "대체로",
     "annotation": "대체로"
    },
    " 높게 나타났다."
   ],
   "translation": "According to the 2018 National Leisure Activity Survey report, the main purpose of Koreans’ leisure activities turned out to be ‘personal enjoyment’. The proportions answering ‘peace of mind and rest’, ‘relieving stress’, ‘self-satisfaction’ and ‘spending time with the family’ were also generally high.",
   "sentences": [
    {
     "spans": [
      "2018 국민여가활동조사 ",
      {
       "word": "보고서",
       "annotation": "보고서"
      },
      "에 따르면 한국 국민의 여가활동의 ",
      {
       "word": "주된",
       "annotation": "주되다"
      },
      " 목적은 ‘개인의 즐거움’으로 나타났다. "
     ],
     "translation": "According to the 2018 National Leisure Activity Survey report, the main purpose of Koreans’ leisure activities turned out to be ‘personal enjoyment’."
    },
    {
     "spans": [
      "그리고 ‘마음의 ",
      {
       "word": "안정",
       "annotation": "안정"
      },
      "과 휴식’, ‘스트레스 ",
      {
       "word": "해소",
       "annotation": "해소"
      },
      "’, ‘",
      {
       "word": "자기만족",
       "annotation": "자기만족"
      },
      "’, ‘가족과 시간을 함께하기’ 등에 응답한 ",
      {
       "word": "비율",
       "annotation": "비율"
      },
      "도 ",
      {
       "word": "대체로",
       "annotation": "대체로"
      },
      " 높게 나타났다."
     ],
     "translation": "The proportions answering ‘peace of mind and rest’, ‘relieving stress’, ‘self-satisfaction’ and ‘spending time with the family’ were also generally high."
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "15–19세, 20대에서는 39% 이상이 ‘개인의 즐거움을 위해’ 여가활동을 하고 있으며, 50대 이상에서는 ‘건강을 위해’ 여가활동을 하는 경우가 다른 ",
    {
     "word": "연령대",
     "annotation": "연령대"
    },
    "보다 많은 것으로 나타났다."
   ],
   "translation": "Among those aged 15–19 and in their twenties, more than 39% do leisure activities ‘for personal enjoyment’, while among those in their fifties and above, doing leisure activities ‘for health’ was found to be more common than in other age groups.",
   "sentences": [
    {
     "spans": [
      "15–19세, 20대에서는 39% 이상이 ‘개인의 즐거움을 위해’ 여가활동을 하고 있으며, 50대 이상에서는 ‘건강을 위해’ 여가활동을 하는 경우가 다른 ",
      {
       "word": "연령대",
       "annotation": "연령대"
      },
      "보다 많은 것으로 나타났다."
     ],
     "translation": "Among those aged 15–19 and in their twenties, more than 39% do leisure activities ‘for personal enjoyment’, while among those in their fifties and above, doing leisure activities ‘for health’ was found to be more common than in other age groups."
    }
   ]
  },
  {
   "type": "table",
   "header": [
    "여가활동 목적",
    "2015",
    "2018"
   ],
   "rows": [
    [
     "개인의 즐거움",
     "37.1",
     "32.5"
    ],
    [
     "마음의 안정과 휴식",
     "16.9",
     "18.2"
    ],
    [
     "스트레스 해소",
     "14.0",
     "14.7"
    ],
    [
     "건강을 위해",
     "10.3",
     "10.1"
    ],
    [
     "자기만족",
     "8.0",
     "8.8"
    ],
    [
     "대인관계",
     "5.2",
     "5.1"
    ],
    [
     "가족과 시간을 함께하기",
     "3.2",
     "4.7"
    ],
    [
     "시간을 보내기",
     "3.0",
     "3.8"
    ],
    [
     "자기 개발",
     "2.3",
     "2.0"
    ]
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "★ 자신이 한국에서 즐겨하는 여가활동과 그 목적을 서로 이야기해 봅시다."
   ],
   "translation": "Talk with each other about the leisure activities you enjoy in Korea and what you do them for.",
   "role": "prompt",
   "sentences": [
    {
     "spans": [
      "★ 자신이 한국에서 즐겨하는 여가활동과 그 목적을 서로 이야기해 봅시다."
     ],
     "translation": "Talk with each other about the leisure activities you enjoy in Korea and what you do them for."
    }
   ]
  }
 ],
 "annotations": {
  "여가": {
   "headword": "여가",
   "hanja": "餘暇",
   "meaning": "leisure, free time",
   "characters": [
    {
     "char": "餘",
     "reading": "여",
     "gloss": "surplus, remaining — as in 여유 “leeway”"
    },
    {
     "char": "暇",
     "reading": "가",
     "gloss": "leisure, idle time"
    }
   ],
   "notes": [
    "Literally “time left over”. The chapter's subject, and the 여가 of 여가활동 and 여가문화."
   ],
   "surfaces": []
  },
  "여가문화": {
   "headword": "여가문화",
   "hanja": "餘暇文化",
   "meaning": "leisure culture",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "주요": {
   "headword": "주요",
   "hanja": "主要",
   "meaning": "main, principal",
   "characters": [
    {
     "char": "主",
     "reading": "주",
     "gloss": "main — as in 주식, 주연"
    },
    {
     "char": "要",
     "reading": "요",
     "gloss": "essential — as in 요인, 중요"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "텔레비전 시청": {
   "headword": "텔레비전 시청",
   "hanja": "텔레비전視聽",
   "meaning": "watching television",
   "characters": [
    {
     "char": "視",
     "reading": "시",
     "gloss": "to see — as in 시청자, 중시"
    },
    {
     "char": "聽",
     "reading": "청",
     "gloss": "to listen — as in 청취"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "영화 관람": {
   "headword": "영화 관람",
   "hanja": "映畫觀覽",
   "meaning": "going to the cinema",
   "characters": [
    {
     "char": "觀",
     "reading": "관",
     "gloss": "to watch — as in 관객, 관광"
    },
    {
     "char": "覽",
     "reading": "람",
     "gloss": "to look over — as in 열람"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "등산": {
   "headword": "등산",
   "hanja": "登山",
   "meaning": "hill walking, hiking",
   "characters": [
    {
     "char": "登",
     "reading": "등",
     "gloss": "to climb — as in 등교 “going to school”"
    },
    {
     "char": "山",
     "reading": "산",
     "gloss": "mountain — as in 산소, 배산임수"
    }
   ],
   "notes": [
    "The commonest outdoor pastime in Korea, which is a mountainous country: 등산 is walking up a hill, not technical climbing."
   ],
   "surfaces": []
  },
  "배드민턴": {
   "headword": "배드민턴",
   "hanja": null,
   "meaning": "badminton",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "가정": {
   "headword": "가정",
   "hanja": "家庭",
   "meaning": "the home, the household",
   "characters": [
    {
     "char": "家",
     "reading": "가",
     "gloss": "house, family — as in 가족, 국가"
    },
    {
     "char": "庭",
     "reading": "정",
     "gloss": "courtyard, garden"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "벗어나다": {
   "headword": "벗어나다",
   "hanja": null,
   "meaning": "to get out of, to break free from",
   "characters": [],
   "notes": [
    "Of escaping a place, a state or an obligation: 일에서 벗어나다, 가난에서 벗어나다."
   ],
   "surfaces": []
  },
  "균형": {
   "headword": "균형",
   "hanja": "均衡",
   "meaning": "balance, equilibrium",
   "characters": [
    {
     "char": "均",
     "reading": "균",
     "gloss": "even — as in 평균 “average”"
    },
    {
     "char": "衡",
     "reading": "형",
     "gloss": "a balance, a scale"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "갖추다": {
   "headword": "갖추다",
   "hanja": null,
   "meaning": "to be equipped with, to have in place",
   "characters": [],
   "notes": [
    "Of having what is needed: 조건을 갖추다, 예를 갖추다 — the last of these appeared in chapter 15's funeral."
   ],
   "surfaces": []
  },
  "형성": {
   "headword": "형성",
   "hanja": "形成",
   "meaning": "formation, to take shape",
   "characters": [
    {
     "char": "形",
     "reading": "형",
     "gloss": "form — as in 형태 “form”, 유형"
    },
    {
     "char": "成",
     "reading": "성",
     "gloss": "to accomplish — as in 구성, 완성"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "주 5일 근무제": {
   "headword": "주 5일 근무제",
   "hanja": "週五日勤務制",
   "meaning": "the five-day working week",
   "characters": [
    {
     "char": "週",
     "reading": "주",
     "gloss": "week — as in 주말 “weekend”, 매주"
    },
    {
     "char": "勤",
     "reading": "근",
     "gloss": "diligent, to serve — as in 근로자, 출근"
    },
    {
     "char": "務",
     "reading": "무",
     "gloss": "duty — as in 업무 “work”, 의무"
    },
    {
     "char": "制",
     "reading": "제",
     "gloss": "system — as in 제도, 학점 은행제"
    }
   ],
   "notes": [
    "Phased in from 2004. Before it, Saturday morning was a working half-day."
   ],
   "surfaces": []
  },
  "주 52시간 근무제": {
   "headword": "주 52시간 근무제",
   "hanja": "週五十二時間勤務制",
   "meaning": "the 52-hour week",
   "characters": [],
   "notes": [
    "A cap of forty regular hours plus twelve of overtime, phased in from 2018. Chapter 3 mentions it too."
   ],
   "surfaces": []
  },
  "시행": {
   "headword": "시행",
   "hanja": "施行",
   "meaning": "to put into effect, to enforce",
   "characters": [
    {
     "char": "施",
     "reading": "시",
     "gloss": "to bestow, to carry out — as in 시상식"
    },
    {
     "char": "行",
     "reading": "행",
     "gloss": "to go, to do — as in 행동, 유행"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "1인당 국민소득": {
   "headword": "1인당 국민소득",
   "hanja": "一人當國民所得",
   "meaning": "national income per head",
   "characters": [
    {
     "char": "當",
     "reading": "당",
     "gloss": "per, to correspond — as in 해당, 담당"
    },
    {
     "char": "所",
     "reading": "소",
     "gloss": "that which — as in 소망, 소감"
    },
    {
     "char": "得",
     "reading": "득",
     "gloss": "to obtain — as in 취득 “acquisition”"
    }
   ],
   "notes": [
    "Korea passed thirty thousand US dollars in 2018."
   ],
   "surfaces": []
  },
  "도입": {
   "headword": "도입",
   "hanja": "導入",
   "meaning": "introduction, bringing in",
   "characters": [
    {
     "char": "導",
     "reading": "도",
     "gloss": "to guide — as in 지도자, 유도"
    },
    {
     "char": "入",
     "reading": "입",
     "gloss": "to enter — as in 입구, 수입"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "기대 수명": {
   "headword": "기대 수명",
   "hanja": "期待壽命",
   "meaning": "life expectancy",
   "characters": [],
   "notes": [
    "Chapter 12's word: the span one is expected to have at birth."
   ],
   "surfaces": []
  },
  "중요성": {
   "headword": "중요성",
   "hanja": "重要性",
   "meaning": "importance",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "보장": {
   "headword": "보장",
   "hanja": "保障",
   "meaning": "to guarantee",
   "characters": [
    {
     "char": "保",
     "reading": "보",
     "gloss": "to protect — as in 보험, 보호"
    },
    {
     "char": "障",
     "reading": "장",
     "gloss": "a barrier — as in 장벽 “barrier”"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "국민여가활성화기본법": {
   "headword": "국민여가활성화기본법",
   "hanja": "國民餘暇活性化基本法",
   "meaning": "the Framework Act on the Promotion of National Leisure",
   "characters": [],
   "notes": [
    "Enacted in 2015. 기본법 is a framework act — one that sets the principles other statutes work within."
   ],
   "surfaces": []
  },
  "제정": {
   "headword": "제정",
   "hanja": "制定",
   "meaning": "to enact (a law)",
   "characters": [
    {
     "char": "制",
     "reading": "제",
     "gloss": "system, to regulate — as in 제도, 규제"
    },
    {
     "char": "定",
     "reading": "정",
     "gloss": "to fix — as in 지정, 정착"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "문화체육관광부": {
   "headword": "문화체육관광부",
   "hanja": "文化體育觀光部",
   "meaning": "the Ministry of Culture, Sports and Tourism",
   "characters": [
    {
     "char": "體",
     "reading": "체",
     "gloss": "body — as in 체육 “physical education”"
    },
    {
     "char": "育",
     "reading": "육",
     "gloss": "to raise — as in 교육, 보육"
    },
    {
     "char": "觀",
     "reading": "관",
     "gloss": "to watch — as in 관광, 관객"
    },
    {
     "char": "光",
     "reading": "광",
     "gloss": "light — as in 관광, 영광"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "평일": {
   "headword": "평일",
   "hanja": "平日",
   "meaning": "a weekday, a working day",
   "characters": [
    {
     "char": "平",
     "reading": "평",
     "gloss": "flat, ordinary — as in 평범하다, 평등"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "휴일": {
   "headword": "휴일",
   "hanja": "休日",
   "meaning": "a holiday, a day off",
   "characters": [
    {
     "char": "休",
     "reading": "휴",
     "gloss": "to rest — as in 휴식, 연휴"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "월평균": {
   "headword": "월평균",
   "hanja": "月平均",
   "meaning": "the monthly average",
   "characters": [
    {
     "char": "均",
     "reading": "균",
     "gloss": "even — the same 均 as in 균형"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "비용": {
   "headword": "비용",
   "hanja": "費用",
   "meaning": "cost, expense",
   "characters": [
    {
     "char": "費",
     "reading": "비",
     "gloss": "to spend — as in 학비, 생활비"
    },
    {
     "char": "用",
     "reading": "용",
     "gloss": "to use — as in 이용, 활용"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "상승": {
   "headword": "상승",
   "hanja": "上昇",
   "meaning": "a rise, to go up",
   "characters": [
    {
     "char": "上",
     "reading": "상",
     "gloss": "up — as in 향상, 상영"
    },
    {
     "char": "昇",
     "reading": "승",
     "gloss": "to ascend"
    }
   ],
   "notes": [
    "Its counterpart is 하락."
   ],
   "surfaces": []
  },
  "휴식": {
   "headword": "휴식",
   "hanja": "休息",
   "meaning": "rest",
   "characters": [
    {
     "char": "休",
     "reading": "휴",
     "gloss": "to rest — as in 휴일, 연휴"
    },
    {
     "char": "息",
     "reading": "식",
     "gloss": "breath, to rest — as in 자식 “one's child”"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "낮잠": {
   "headword": "낮잠",
   "hanja": null,
   "meaning": "a nap",
   "characters": [],
   "notes": [
    "낮 “daytime” + 잠 “sleep”. Its counterpart is 밤잠."
   ],
   "surfaces": []
  },
  "산책": {
   "headword": "산책",
   "hanja": "散策",
   "meaning": "a walk, a stroll",
   "characters": [
    {
     "char": "散",
     "reading": "산",
     "gloss": "to scatter, to disperse — as in 확산, 분산"
    },
    {
     "char": "策",
     "reading": "책",
     "gloss": "a plan, a staff — as in 정책 “policy”"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "외식": {
   "headword": "외식",
   "hanja": "外食",
   "meaning": "eating out",
   "characters": [
    {
     "char": "外",
     "reading": "외",
     "gloss": "outside — as in 외국, 국내외"
    },
    {
     "char": "食",
     "reading": "식",
     "gloss": "food, to eat — as in 식사, 한식"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "검색": {
   "headword": "검색",
   "hanja": "檢索",
   "meaning": "a search",
   "characters": [
    {
     "char": "檢",
     "reading": "검",
     "gloss": "to examine — as in 검사 “inspection”, 검진"
    },
    {
     "char": "索",
     "reading": "색",
     "gloss": "to search for"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "1인 미디어": {
   "headword": "1인 미디어",
   "hanja": null,
   "meaning": "one-person media",
   "characters": [],
   "notes": [
    "A channel made and run by one person — a streamer, a YouTuber. Chapter 4's 1인 방송 is the same idea."
   ],
   "surfaces": []
  },
  "취미": {
   "headword": "취미",
   "hanja": "趣味",
   "meaning": "a hobby",
   "characters": [
    {
     "char": "趣",
     "reading": "취",
     "gloss": "interest, taste"
    },
    {
     "char": "味",
     "reading": "미",
     "gloss": "taste — as in 흥미, 의미"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "오락": {
   "headword": "오락",
   "hanja": "娛樂",
   "meaning": "amusement, entertainment",
   "characters": [
    {
     "char": "娛",
     "reading": "오",
     "gloss": "to amuse"
    },
    {
     "char": "樂",
     "reading": "락",
     "gloss": "pleasure, music — as in 음악 “music”"
    }
   ],
   "notes": [
    "The 오락 of 예능 프로그램's 오락적인 내용 in chapter 18."
   ],
   "surfaces": []
  },
  "비중": {
   "headword": "비중",
   "hanja": "比重",
   "meaning": "weight, relative share",
   "characters": [
    {
     "char": "比",
     "reading": "비",
     "gloss": "to compare — as in 비율, 비교"
    },
    {
     "char": "重",
     "reading": "중",
     "gloss": "heavy — as in 중요, 존중"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "친지": {
   "headword": "친지",
   "hanja": "親知",
   "meaning": "close acquaintances",
   "characters": [
    {
     "char": "親",
     "reading": "친",
     "gloss": "close, kin — as in 친척, 친구"
    },
    {
     "char": "知",
     "reading": "지",
     "gloss": "to know — as in 지식 “knowledge”, 지혜"
    }
   ],
   "notes": [
    "Those one knows well, not necessarily blood relatives — the article pairs it with 친척."
   ],
   "surfaces": []
  },
  "오붓하다": {
   "headword": "오붓하다",
   "hanja": null,
   "meaning": "to be snug, cosy and companionable",
   "characters": [],
   "notes": [
    "Of a small gathering that feels close and unhurried. A pure-Korean word, and a hard one to render — “a snug hour” comes near."
   ],
   "surfaces": []
  },
  "악기": {
   "headword": "악기",
   "hanja": "樂器",
   "meaning": "a musical instrument",
   "characters": [
    {
     "char": "樂",
     "reading": "악",
     "gloss": "music — the same 樂 as in 오락, read 락 there"
    },
    {
     "char": "器",
     "reading": "기",
     "gloss": "vessel, implement — as in 그릇의 용기, 기구"
    }
   ],
   "notes": [
    "The same character 樂 reads 악 in 음악 and 악기, but 락 in 오락 and 낙원 — “music” against “pleasure”."
   ],
   "surfaces": []
  },
  "독서": {
   "headword": "독서",
   "hanja": "讀書",
   "meaning": "reading",
   "characters": [
    {
     "char": "讀",
     "reading": "독",
     "gloss": "to read — as in 독학 “self-study”"
    },
    {
     "char": "書",
     "reading": "서",
     "gloss": "book, writing — as in 도서관, 서류"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "동호회": {
   "headword": "동호회",
   "hanja": "同好會",
   "meaning": "a club, a society of enthusiasts",
   "characters": [
    {
     "char": "同",
     "reading": "동",
     "gloss": "same — as in 동일, 동문회"
    },
    {
     "char": "好",
     "reading": "호",
     "gloss": "to like — as in 호기심, 선호하다"
    },
    {
     "char": "會",
     "reading": "회",
     "gloss": "society — as in 향우회, 교회"
    }
   ],
   "notes": [
    "Literally “the society of those who like the same thing”."
   ],
   "surfaces": []
  },
  "활성화": {
   "headword": "활성화",
   "hanja": "活性化",
   "meaning": "to become active, to flourish",
   "characters": [
    {
     "char": "活",
     "reading": "활",
     "gloss": "living — as in 생활, 활동"
    },
    {
     "char": "性",
     "reading": "성",
     "gloss": "nature — as in 다양성, 중요성"
    },
    {
     "char": "化",
     "reading": "화",
     "gloss": "-isation — as in 도시화, 일상화"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "문화예술": {
   "headword": "문화예술",
   "hanja": "文化藝術",
   "meaning": "culture and the arts",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "관람": {
   "headword": "관람",
   "hanja": "觀覽",
   "meaning": "to view, to attend",
   "characters": [
    {
     "char": "觀",
     "reading": "관",
     "gloss": "to watch — as in 관객, 관광"
    },
    {
     "char": "覽",
     "reading": "람",
     "gloss": "to look over"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "경기장": {
   "headword": "경기장",
   "hanja": "競技場",
   "meaning": "a stadium, a ground",
   "characters": [
    {
     "char": "競",
     "reading": "경",
     "gloss": "to compete — as in 경쟁 “competition”"
    },
    {
     "char": "技",
     "reading": "기",
     "gloss": "skill — as in 기술 “technique”"
    },
    {
     "char": "場",
     "reading": "장",
     "gloss": "place — as in 장례식장, 예식장"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "박물관": {
   "headword": "박물관",
   "hanja": "博物館",
   "meaning": "a museum",
   "characters": [
    {
     "char": "博",
     "reading": "박",
     "gloss": "wide, broad — as in 박사 “doctorate”"
    },
    {
     "char": "物",
     "reading": "물",
     "gloss": "thing — as in 물건 “object”, 매물"
    },
    {
     "char": "館",
     "reading": "관",
     "gloss": "hall — as in 도서관, 영화관"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "미술관": {
   "headword": "미술관",
   "hanja": "美術館",
   "meaning": "an art gallery",
   "characters": [
    {
     "char": "美",
     "reading": "미",
     "gloss": "beautiful — as in 미국 “America”, 미용"
    },
    {
     "char": "術",
     "reading": "술",
     "gloss": "art, skill — as in 예술성, 기술"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "전시회": {
   "headword": "전시회",
   "hanja": "展示會",
   "meaning": "an exhibition",
   "characters": [
    {
     "char": "展",
     "reading": "전",
     "gloss": "to display — as in 발전 “development”"
    },
    {
     "char": "示",
     "reading": "시",
     "gloss": "to show — as in 제시, 지시"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "공연장": {
   "headword": "공연장",
   "hanja": "公演場",
   "meaning": "a performance venue, a theatre",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "뮤지컬": {
   "headword": "뮤지컬",
   "hanja": null,
   "meaning": "a musical",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "연극": {
   "headword": "연극",
   "hanja": "演劇",
   "meaning": "a play, theatre",
   "characters": [
    {
     "char": "演",
     "reading": "연",
     "gloss": "to perform — as in 공연, 주연"
    },
    {
     "char": "劇",
     "reading": "극",
     "gloss": "drama — as in 사극 “historical drama”"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "코로나19": {
   "headword": "코로나19",
   "hanja": null,
   "meaning": "Covid-19",
   "characters": [],
   "notes": [
    "Korean uses the number rather than the year: 코로나19, read 코로나 일구."
   ],
   "surfaces": []
  },
  "형태": {
   "headword": "형태",
   "hanja": "形態",
   "meaning": "a form, a shape",
   "characters": [
    {
     "char": "形",
     "reading": "형",
     "gloss": "form — as in 형성, 유형"
    },
    {
     "char": "態",
     "reading": "태",
     "gloss": "condition — as in 태도, 상태"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "한국관광공사": {
   "headword": "한국관광공사",
   "hanja": "韓國觀光公社",
   "meaning": "the Korea Tourism Organization",
   "characters": [
    {
     "char": "社",
     "reading": "사",
     "gloss": "company, society — as in 회사, 사회"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "대한민국 구석구석": {
   "headword": "대한민국 구석구석",
   "hanja": null,
   "meaning": "“Every Corner of Korea”, the state tourism site",
   "characters": [],
   "notes": [
    "구석 is a corner or nook; doubling it gives “every last corner”. The English name of the site is Visit Korea."
   ],
   "surfaces": []
  },
  "지역별": {
   "headword": "지역별",
   "hanja": "地域別",
   "meaning": "by region",
   "characters": [
    {
     "char": "別",
     "reading": "별",
     "gloss": "to separate, by — as in 성별, 유형별"
    }
   ],
   "notes": [
    "The suffix -별 “by, per” makes 월별 “by month”, 연령별 “by age”, 지역별 “by region”."
   ],
   "surfaces": []
  },
  "축제": {
   "headword": "축제",
   "hanja": "祝祭",
   "meaning": "a festival",
   "characters": [
    {
     "char": "祝",
     "reading": "축",
     "gloss": "to celebrate — as in 축하, 축의금"
    },
    {
     "char": "祭",
     "reading": "제",
     "gloss": "rite, festival — as in 제사, 영화제"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "월별": {
   "headword": "월별",
   "hanja": "月別",
   "meaning": "by month, monthly",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "회복": {
   "headword": "회복",
   "hanja": "回復",
   "meaning": "recovery",
   "characters": [
    {
     "char": "回",
     "reading": "회",
     "gloss": "to turn round — as in 횟수, 회갑"
    },
    {
     "char": "復",
     "reading": "복",
     "gloss": "to return, again — as in 복습 “revision”"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "관광": {
   "headword": "관광",
   "hanja": "觀光",
   "meaning": "tourism, sightseeing",
   "characters": [
    {
     "char": "觀",
     "reading": "관",
     "gloss": "to watch — as in 관람, 관객"
    },
    {
     "char": "光",
     "reading": "광",
     "gloss": "light — as in 영광 “glory”"
    }
   ],
   "notes": [
    "Literally “to look at the light” — an old phrase for seeing the sights of a place."
   ],
   "surfaces": []
  },
  "참고": {
   "headword": "참고",
   "hanja": "參考",
   "meaning": "reference; to consult",
   "characters": [
    {
     "char": "參",
     "reading": "참",
     "gloss": "to take part — as in 참여, 참가"
    },
    {
     "char": "考",
     "reading": "고",
     "gloss": "to think, to examine — as in 고려"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "입장권": {
   "headword": "입장권",
   "hanja": "入場券",
   "meaning": "an admission ticket",
   "characters": [
    {
     "char": "場",
     "reading": "장",
     "gloss": "place — as in 경기장, 공연장"
    },
    {
     "char": "券",
     "reading": "권",
     "gloss": "ticket, certificate — as in 상품권"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "어플": {
   "headword": "어플",
   "hanja": null,
   "meaning": "an app",
   "characters": [],
   "notes": [
    "Clipped from 애플리케이션. 앱 is the newer and now commoner form; the page gives both."
   ],
   "surfaces": []
  },
  "예매": {
   "headword": "예매",
   "hanja": "豫買",
   "meaning": "advance booking",
   "characters": [
    {
     "char": "豫",
     "reading": "예",
     "gloss": "beforehand — as in 예방, 예상"
    },
    {
     "char": "買",
     "reading": "매",
     "gloss": "to buy — as in 구매 “purchase”, 매매"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "행정복지센터": {
   "headword": "행정복지센터",
   "hanja": "行政福祉센터",
   "meaning": "a community service centre",
   "characters": [],
   "notes": [
    "The office once called 동사무소 and then 주민센터. It handles residence registration and runs local programmes."
   ],
   "surfaces": []
  },
  "평생학습관": {
   "headword": "평생학습관",
   "hanja": "平生學習館",
   "meaning": "a lifelong learning centre",
   "characters": [],
   "notes": [
    "Chapter 12's 평생 학습관 — the local centre where the courses are held."
   ],
   "surfaces": []
  },
  "기관": {
   "headword": "기관",
   "hanja": "機關",
   "meaning": "an institution, an organ",
   "characters": [
    {
     "char": "機",
     "reading": "기",
     "gloss": "machine, workings — as in 기능, 계기"
    },
    {
     "char": "關",
     "reading": "관",
     "gloss": "to relate, a barrier — as in 관계, 관련"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "백화점": {
   "headword": "백화점",
   "hanja": "百貨店",
   "meaning": "a department store",
   "characters": [
    {
     "char": "百",
     "reading": "백",
     "gloss": "hundred — as in 백일, 백지장"
    },
    {
     "char": "貨",
     "reading": "화",
     "gloss": "goods — as in 화물 “freight”"
    },
    {
     "char": "店",
     "reading": "점",
     "gloss": "shop — as in 상점 “shop”, 서점"
    }
   ],
   "notes": [
    "Literally “the hundred-goods shop”."
   ],
   "surfaces": []
  },
  "대형 마트": {
   "headword": "대형 마트",
   "hanja": "大型마트",
   "meaning": "a hypermarket",
   "characters": [
    {
     "char": "型",
     "reading": "형",
     "gloss": "form, size — as in 유형, 형태"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "문화센터": {
   "headword": "문화센터",
   "hanja": null,
   "meaning": "a culture centre",
   "characters": [],
   "notes": [
    "The classes a department store or supermarket runs for its customers — cookery, flower arranging, languages."
   ],
   "surfaces": []
  },
  "커뮤니티": {
   "headword": "커뮤니티",
   "hanja": null,
   "meaning": "a community, an online forum",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "가입": {
   "headword": "가입",
   "hanja": "加入",
   "meaning": "to join, to enrol",
   "characters": [
    {
     "char": "加",
     "reading": "가",
     "gloss": "to add — as in 추가 “addition”"
    },
    {
     "char": "入",
     "reading": "입",
     "gloss": "to enter — as in 도입, 입구"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "관심사": {
   "headword": "관심사",
   "hanja": "關心事",
   "meaning": "a matter of interest",
   "characters": [
    {
     "char": "事",
     "reading": "사",
     "gloss": "affair, matter — as in 사례, 무사하다"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "워라벨": {
   "headword": "워라벨",
   "hanja": null,
   "meaning": "work-life balance",
   "characters": [],
   "notes": [
    "From the initials of Work and Life Balance. The standard spelling is 워라밸; the page prints 워라벨."
   ],
   "surfaces": []
  },
  "요구": {
   "headword": "요구",
   "hanja": "要求",
   "meaning": "a demand, a requirement",
   "characters": [
    {
     "char": "要",
     "reading": "요",
     "gloss": "essential — as in 주요, 요인"
    },
    {
     "char": "求",
     "reading": "구",
     "gloss": "to seek — as in 요구, 구하다"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "지속적": {
   "headword": "지속적",
   "hanja": "持續的",
   "meaning": "continuous, sustained",
   "characters": [
    {
     "char": "持",
     "reading": "지",
     "gloss": "to hold — as in 유지 “to maintain”"
    },
    {
     "char": "續",
     "reading": "속",
     "gloss": "to continue — as in 계속 “continuation”"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "헬스": {
   "headword": "헬스",
   "hanja": null,
   "meaning": "the gym, working out",
   "characters": [],
   "notes": [
    "From “health”, but meaning weight training. A gym is a 헬스장 or 헬스클럽."
   ],
   "surfaces": []
  },
  "요가": {
   "headword": "요가",
   "hanja": null,
   "meaning": "yoga",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "수요": {
   "headword": "수요",
   "hanja": "需要",
   "meaning": "demand",
   "characters": [
    {
     "char": "需",
     "reading": "수",
     "gloss": "to need, to require"
    },
    {
     "char": "要",
     "reading": "요",
     "gloss": "essential — as in 요구, 주요"
    }
   ],
   "notes": [
    "Its counterpart is 공급, supply. Not the 수요 of 수요일, Wednesday."
   ],
   "surfaces": []
  },
  "일상화": {
   "headword": "일상화",
   "hanja": "日常化",
   "meaning": "to become an everyday thing",
   "characters": [
    {
     "char": "常",
     "reading": "상",
     "gloss": "usual, constant — as in 일상 “daily life”"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "자연휴양림": {
   "headword": "자연휴양림",
   "hanja": "自然休養林",
   "meaning": "a recreational forest",
   "characters": [
    {
     "char": "養",
     "reading": "양",
     "gloss": "to nurture — as in 양육, 함양"
    },
    {
     "char": "林",
     "reading": "림",
     "gloss": "forest — as in 산림 “forest”"
    }
   ],
   "notes": [
    "A state-run forest with cabins and camping, managed by the Korea Forest Service."
   ],
   "surfaces": []
  },
  "캠핑": {
   "headword": "캠핑",
   "hanja": null,
   "meaning": "camping",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "스마트기기": {
   "headword": "스마트기기",
   "hanja": "스마트機器",
   "meaning": "a smart device",
   "characters": [
    {
     "char": "機",
     "reading": "기",
     "gloss": "machine — as in 기관, 기능"
    },
    {
     "char": "器",
     "reading": "기",
     "gloss": "implement — as in 악기, 용기"
    }
   ],
   "notes": [
    "Two different 기 characters side by side: 機 the mechanism and 器 the implement."
   ],
   "surfaces": []
  },
  "웹서핑": {
   "headword": "웹서핑",
   "hanja": null,
   "meaning": "web surfing",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "모바일메신저": {
   "headword": "모바일메신저",
   "hanja": null,
   "meaning": "a mobile messenger",
   "characters": [],
   "notes": [
    "In Korea this means KakaoTalk, which nearly everyone uses."
   ],
   "surfaces": []
  },
  "감상": {
   "headword": "감상",
   "hanja": "鑑賞",
   "meaning": "appreciation, listening to or looking at",
   "characters": [
    {
     "char": "鑑",
     "reading": "감",
     "gloss": "to examine, a mirror"
    },
    {
     "char": "賞",
     "reading": "상",
     "gloss": "to appreciate; a prize — as in 수상, 작품상"
    }
   ],
   "notes": [
    "음악 감상 “listening to music”, 영화 감상 “watching films” — with attention, not idly. A different 감상(感想) means one's impressions."
   ],
   "surfaces": []
  },
  "웹툰": {
   "headword": "웹툰",
   "hanja": null,
   "meaning": "webtoon",
   "characters": [],
   "notes": [
    "WEB + CARTOON. Korean webtoons scroll vertically on a phone rather than paging, and the form has been exported along with the word."
   ],
   "surfaces": []
  },
  "콘텐츠": {
   "headword": "콘텐츠",
   "hanja": null,
   "meaning": "content",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "만들어내다": {
   "headword": "만들어내다",
   "hanja": null,
   "meaning": "to produce, to turn out",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "문화가 있는 날": {
   "headword": "문화가 있는 날",
   "hanja": null,
   "meaning": "Culture Day",
   "characters": [],
   "notes": [
    "The last Wednesday of every month, since January 2014. Discounted or free admission at some two thousand venues."
   ],
   "surfaces": []
  },
  "문화재": {
   "headword": "문화재",
   "hanja": "文化財",
   "meaning": "a cultural property, a heritage site",
   "characters": [
    {
     "char": "財",
     "reading": "재",
     "gloss": "wealth, property — as in 재산 “property”"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "문화시설": {
   "headword": "문화시설",
   "hanja": "文化施設",
   "meaning": "a cultural facility",
   "characters": [
    {
     "char": "施",
     "reading": "시",
     "gloss": "to institute — as in 시행, 시상식"
    },
    {
     "char": "設",
     "reading": "설",
     "gloss": "to establish — as in 설립, 시설"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "할인": {
   "headword": "할인",
   "hanja": "割引",
   "meaning": "a discount",
   "characters": [
    {
     "char": "割",
     "reading": "할",
     "gloss": "to cut, to divide"
    },
    {
     "char": "引",
     "reading": "인",
     "gloss": "to pull — as in 인상 “a rise (in price)”"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "더불어": {
   "headword": "더불어",
   "hanja": null,
   "meaning": "together with, along with",
   "characters": [],
   "notes": [
    "From 더불다. 더불어 살다 “to live alongside others” — chapter 13's 생활협동조합 uses it."
   ],
   "surfaces": []
  },
  "퇴근": {
   "headword": "퇴근",
   "hanja": "退勤",
   "meaning": "leaving work",
   "characters": [
    {
     "char": "退",
     "reading": "퇴",
     "gloss": "to withdraw — as in 은퇴 “retirement”, 퇴사"
    },
    {
     "char": "勤",
     "reading": "근",
     "gloss": "to serve — as in 근무제, 근로자"
    }
   ],
   "notes": [
    "Its counterpart is 출근, going in to work."
   ],
   "surfaces": []
  },
  "야간 개방": {
   "headword": "야간 개방",
   "hanja": "夜間開放",
   "meaning": "opening in the evening",
   "characters": [
    {
     "char": "夜",
     "reading": "야",
     "gloss": "night — as in 야간보육, 야근"
    },
    {
     "char": "開",
     "reading": "개",
     "gloss": "to open — as in 개봉, 개설"
    },
    {
     "char": "放",
     "reading": "방",
     "gloss": "to release — as in 방송 “broadcast”, 개방"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "보고서": {
   "headword": "보고서",
   "hanja": "報告書",
   "meaning": "a report",
   "characters": [
    {
     "char": "報",
     "reading": "보",
     "gloss": "to report — as in 정보 “information”"
    },
    {
     "char": "告",
     "reading": "고",
     "gloss": "to tell — as in 신고 “to report”, 광고"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "주되다": {
   "headword": "주되다",
   "hanja": "主되다",
   "meaning": "to be the main, principal",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "안정": {
   "headword": "안정",
   "hanja": "安定",
   "meaning": "stability, calm",
   "characters": [
    {
     "char": "安",
     "reading": "안",
     "gloss": "peace — as in 안전, 안부"
    },
    {
     "char": "定",
     "reading": "정",
     "gloss": "to settle — as in 정착, 지정"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "해소": {
   "headword": "해소",
   "hanja": "解消",
   "meaning": "to relieve, to clear away",
   "characters": [
    {
     "char": "解",
     "reading": "해",
     "gloss": "to loosen, to resolve — as in 이해, 해결"
    },
    {
     "char": "消",
     "reading": "소",
     "gloss": "to extinguish — as in 소화기 “extinguisher”"
    }
   ],
   "notes": [
    "스트레스 해소 “relieving stress” — the set phrase."
   ],
   "surfaces": []
  },
  "자기만족": {
   "headword": "자기만족",
   "hanja": "自己滿足",
   "meaning": "self-satisfaction, contentment",
   "characters": [
    {
     "char": "滿",
     "reading": "만",
     "gloss": "full — as in 만점 “full marks”"
    },
    {
     "char": "足",
     "reading": "족",
     "gloss": "foot; enough — as in 부족 “lack”, 만족"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "비율": {
   "headword": "비율",
   "hanja": "比率",
   "meaning": "a proportion, a rate",
   "characters": [
    {
     "char": "比",
     "reading": "비",
     "gloss": "to compare — as in 비중, 비교"
    },
    {
     "char": "率",
     "reading": "률",
     "gloss": "rate — as in 진학률, 출산율"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "대체로": {
   "headword": "대체로",
   "hanja": "大體로",
   "meaning": "on the whole, generally",
   "characters": [
    {
     "char": "體",
     "reading": "체",
     "gloss": "body, substance — as in 전반적, 단체"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "연령대": {
   "headword": "연령대",
   "hanja": "年齡帶",
   "meaning": "an age group",
   "characters": [
    {
     "char": "齡",
     "reading": "령",
     "gloss": "age — as in 고령화, 연령"
    },
    {
     "char": "帶",
     "reading": "대",
     "gloss": "a band, a belt — as in 지대 “zone”"
    }
   ],
   "notes": [],
   "surfaces": []
  }
 },
 "notes": [
  {
   "why": "The 여가시간 및 여가비용 추이 figure on p. 101 is not drawn. It layers three series over eight years — leisure hours on working days and on holidays, and monthly cost — and its numbers cannot be read reliably off the photograph, so it is described rather than reproduced with invented values."
  },
  {
   "why": "The 여가활동 목적 figure on p. 103 gives two years side by side, which one bar chart cannot show, so it is set as a table of 2015 against 2018."
  },
  {
   "why": "The page prints 워라벨 where the standard spelling is 워라밸. It is set as printed."
  }
 ],
 "slug": "19-leisure"
});
