/* Generated by tools/build.py — do not edit.
   Content lives in tools/chapters/ch28_banking.py; rebuild after changing it. */

KIIP.chapter({
 "number": 28,
 "unit": "경제",
 "title": "금융기관 이용하기",
 "titleEnglish": "Using a financial institution",
 "chapterGlossary": [],
 "blocks": [
  {
   "type": "section",
   "kind": "warmup",
   "text": "생각해 봅시다"
  },
  {
   "type": "paragraph",
   "spans": [
    "다음은 ",
    {
     "word": "은행",
     "annotation": "은행"
    },
    "에서 볼 수 있는 모습입니다."
   ]
  },
  {
   "type": "labels",
   "items": [
    [
     {
      "word": "예금",
      "annotation": "예금"
     }
    ],
    [
     {
      "word": "대출",
      "annotation": "대출"
     }
    ],
    [
     {
      "word": "송금",
      "annotation": "송금"
     }
    ],
    [
     {
      "word": "환전",
      "annotation": "환전"
     }
    ]
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "01 각각의 장면은 무엇을 하는 모습입니까? 이 중 자신이 한국에서 해 본 것은 무엇입니까?",
   "spans": [
    "01 각각의 ",
    {
     "word": "장면",
     "annotation": "장면"
    },
    "은 무엇을 하는 모습입니까? 이 중 자신이 한국에서 해 본 것은 무엇입니까?"
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "02 자신의 고향 나라와 한국에서 은행 관련 일을 할 때의 공통점과 차이점은 무엇입니까?",
   "spans": [
    "02 자신의 고향 나라와 한국에서 은행 관련 일을 할 때의 ",
    {
     "word": "공통점",
     "annotation": "공통점"
    },
    "과 ",
    {
     "word": "차이점",
     "annotation": "차이점"
    },
    "은 무엇입니까?"
   ]
  },
  {
   "type": "section",
   "kind": "goals",
   "text": "학습목표"
  },
  {
   "type": "bullet",
   "spans": [
    {
     "word": "금융기관",
     "annotation": "금융기관"
    },
    "의 종류와 특징을 설명할 수 있다."
   ],
   "ordered": true
  },
  {
   "type": "bullet",
   "spans": [
    {
     "word": "금융 거래",
     "annotation": "금융 거래"
    },
    " 하는 방법을 알고 이를 활용할 수 있다."
   ],
   "ordered": true
  },
  {
   "type": "section",
   "kind": "related",
   "text": "관련 단원 확인하기"
  },
  {
   "type": "table",
   "header": [
    {
     "text": "영역",
     "span": 2
    },
    "제목",
    "관련 내용"
   ],
   "rows": [
    [
     "심화",
     "경제",
     "14. 금융과 자산관리",
     "금융기관 활용, 자산관리"
    ]
   ]
  },
  {
   "type": "section",
   "kind": "part",
   "text": "01 금융기관에는 어떤 것이 있을까?"
  },
  {
   "type": "heading",
   "level": 2,
   "text": "은행에서 하는 일",
   "titleTranslation": "What a bank does"
  },
  {
   "type": "glossary",
   "entries": [
    {
     "term": "금융",
     "definition": [
      "돈이 돌고 도는 것"
     ],
     "annotation": "금융"
    },
    {
     "term": "공과금",
     "definition": [
      "국가나 지방자치단체가 국민에게 내도록 하는 것으로 각종 세금, 전기요금, 수도요금 등이 있음"
     ],
     "annotation": "공과금"
    },
    {
     "term": "납부",
     "definition": [
      "공과금 등을 내는 것"
     ],
     "annotation": "납부"
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "한국의 ",
    {
     "word": "은행",
     "annotation": "은행"
    },
    "에서는 사람들의 돈을 ",
    {
     "word": "맡아",
     "annotation": "맡다"
    },
    " 주거나 돈을 필요로 하는 사람 또는 기업에게 ",
    {
     "word": "빌려주기",
     "annotation": "빌려주다"
    },
    "도 한다. 또한 다른 사람에게 돈을 보내 주기도 하며, 한국 돈과 외국 돈을 서로 ",
    {
     "word": "바꿔",
     "annotation": "바꾸다"
    },
    " 주기도 한다. ",
    {
     "word": "공과금",
     "annotation": "공과금"
    },
    ", 아파트 ",
    {
     "word": "관리비",
     "annotation": "관리비"
    },
    ", 대학 ",
    {
     "word": "등록금",
     "annotation": "등록금"
    },
    " 등도 은행을 통해 ",
    {
     "word": "납부",
     "annotation": "납부"
    },
    "할 수 있고 신용카드, 체크카드 등을 만드는 것도 가능하다. 은행 ",
    {
     "word": "업무",
     "annotation": "업무"
    },
    " 시간은 일반적으로 ",
    {
     "word": "평일",
     "annotation": "평일"
    },
    " 오전 9시부터 오후 4시까지이다."
   ],
   "translation": "A Korean bank will hold people's money for them, and lend to a person or a company that needs it. It will also send money to someone else, and exchange Korean money for foreign. Utility charges, apartment maintenance fees and university fees can be paid through a bank as well, and credit and debit cards obtained there. Banking hours are ordinarily nine in the morning to four in the afternoon on weekdays.",
   "sentences": [
    {
     "spans": [
      "한국의 ",
      {
       "word": "은행",
       "annotation": "은행"
      },
      "에서는 사람들의 돈을 ",
      {
       "word": "맡아",
       "annotation": "맡다"
      },
      " 주거나 돈을 필요로 하는 사람 또는 기업에게 ",
      {
       "word": "빌려주기",
       "annotation": "빌려주다"
      },
      "도 한다. "
     ],
     "translation": "A Korean bank will hold people's money for them, and lend to a person or a company that needs it."
    },
    {
     "spans": [
      "또한 다른 사람에게 돈을 보내 주기도 하며, 한국 돈과 외국 돈을 서로 ",
      {
       "word": "바꿔",
       "annotation": "바꾸다"
      },
      " 주기도 한다. "
     ],
     "translation": "It will also send money to someone else, and exchange Korean money for foreign."
    },
    {
     "spans": [
      {
       "word": "공과금",
       "annotation": "공과금"
      },
      ", 아파트 ",
      {
       "word": "관리비",
       "annotation": "관리비"
      },
      ", 대학 ",
      {
       "word": "등록금",
       "annotation": "등록금"
      },
      " 등도 은행을 통해 ",
      {
       "word": "납부",
       "annotation": "납부"
      },
      "할 수 있고 신용카드, 체크카드 등을 만드는 것도 가능하다. "
     ],
     "translation": "Utility charges, apartment maintenance fees and university fees can be paid through a bank as well, and credit and debit cards obtained there."
    },
    {
     "spans": [
      "은행 ",
      {
       "word": "업무",
       "annotation": "업무"
      },
      " 시간은 일반적으로 ",
      {
       "word": "평일",
       "annotation": "평일"
      },
      " 오전 9시부터 오후 4시까지이다."
     ],
     "translation": "Banking hours are ordinarily nine in the morning to four in the afternoon on weekdays."
    }
   ]
  },
  {
   "type": "heading",
   "level": 2,
   "text": "은행의 종류",
   "titleTranslation": "Kinds of bank"
  },
  {
   "type": "glossary",
   "entries": [
    {
     "term": "금융기관",
     "definition": [
      "개인이나 기업의 돈을 맡아 주고 다른 개인이나 기업에게 빌려주는 일 등을 하는 기관"
     ],
     "annotation": "금융기관"
    },
    {
     "term": "금리",
     "definition": [
      "맡긴 돈이나 빌린 돈에 붙는 이자"
     ],
     "annotation": "금리"
    },
    {
     "term": "수수료",
     "definition": [
      "어떤 일을 맡아서 처리해 준 대가로 받는 요금"
     ],
     "annotation": "수수료"
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "한국에는 다양한 은행이 있다. 우선, 화폐를 발행하는 ",
    {
     "word": "한국은행",
     "annotation": "한국은행"
    },
    "이 있다. 그리고 사람들이 많이 이용하는 은행으로는 ",
    {
     "word": "시중은행",
     "annotation": "시중은행"
    },
    "과 ",
    {
     "word": "지방은행",
     "annotation": "지방은행"
    },
    "이 있다. 시중은행은 개인이 돈을 맡기거나 ",
    {
     "word": "빌리는",
     "annotation": "빌리다"
    },
    " 대표적인 ",
    {
     "word": "금융기관",
     "annotation": "금융기관"
    },
    "으로, 전국 곳곳에 ",
    {
     "word": "지점",
     "annotation": "지점"
    },
    "이 많이 설치되어 있어서 이용하기 편리하다. 신한은행, 국민은행, 하나은행, 우리은행, 기업은행, 농협은행 등이 여기에 해당한다."
   ],
   "translation": "Korea has banks of many kinds. First there is the Bank of Korea, which issues the currency. Then there are the commercial banks and the local banks, which people use most. A commercial bank is the typical institution for an individual to deposit with or borrow from, and convenient to use, with branches set up all over the country. Shinhan, KB Kookmin, Hana, Woori, IBK and NH Nonghyup are of this kind.",
   "sentences": [
    {
     "spans": [
      "한국에는 다양한 은행이 있다. "
     ],
     "translation": "Korea has banks of many kinds."
    },
    {
     "spans": [
      "우선, 화폐를 발행하는 ",
      {
       "word": "한국은행",
       "annotation": "한국은행"
      },
      "이 있다. "
     ],
     "translation": "First there is the Bank of Korea, which issues the currency."
    },
    {
     "spans": [
      "그리고 사람들이 많이 이용하는 은행으로는 ",
      {
       "word": "시중은행",
       "annotation": "시중은행"
      },
      "과 ",
      {
       "word": "지방은행",
       "annotation": "지방은행"
      },
      "이 있다. "
     ],
     "translation": "Then there are the commercial banks and the local banks, which people use most."
    },
    {
     "spans": [
      "시중은행은 개인이 돈을 맡기거나 ",
      {
       "word": "빌리는",
       "annotation": "빌리다"
      },
      " 대표적인 ",
      {
       "word": "금융기관",
       "annotation": "금융기관"
      },
      "으로, 전국 곳곳에 ",
      {
       "word": "지점",
       "annotation": "지점"
      },
      "이 많이 설치되어 있어서 이용하기 편리하다. "
     ],
     "translation": "A commercial bank is the typical institution for an individual to deposit with or borrow from, and convenient to use, with branches set up all over the country."
    },
    {
     "spans": [
      "신한은행, 국민은행, 하나은행, 우리은행, 기업은행, 농협은행 등이 여기에 해당한다."
     ],
     "translation": "Shinhan, KB Kookmin, Hana, Woori, IBK and NH Nonghyup are of this kind."
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "지방은행은 특히 지역 경제의 발전에 필요한 돈을 ",
    {
     "word": "공급",
     "annotation": "공급"
    },
    "하는 것을 ",
    {
     "word": "주된",
     "annotation": "주되다"
    },
    " 목적으로 광역시나 도에 ",
    {
     "word": "설립",
     "annotation": "설립"
    },
    "된 은행이다. 경남은행, 광주은행, 대구은행, 부산은행, 전북은행, 제주은행 등이 여기에 해당한다. 이 외에도 ",
    {
     "word": "단위농협",
     "annotation": "단위농협"
    },
    ", ",
    {
     "word": "우체국",
     "annotation": "우체국"
    },
    ", 새마을금고 등도 전국에 많은 지점이 있고 ",
    {
     "word": "안전성",
     "annotation": "안전성"
    },
    "이 높기 때문에 ",
    {
     "word": "안심",
     "annotation": "안심"
    },
    "하고 편리하게 이용할 수 있다. 지금까지 소개한 ",
    {
     "word": "금융",
     "annotation": "금융"
    },
    "기관은 모두 ",
    {
     "word": "대체로",
     "annotation": "대체로"
    },
    " 안전성이 높은 ",
    {
     "word": "반면",
     "annotation": "반면"
    },
    " ",
    {
     "word": "금리",
     "annotation": "금리"
    },
    "는 낮은 편이다."
   ],
   "translation": "A local bank is one established in a metropolitan city or a province with the chief purpose of supplying the money the local economy needs to develop. Kyongnam, Gwangju, Daegu, Busan, Jeonbuk and Jeju bank are of this kind. Besides these, the local Nonghyup branches, the post office and the Saemaul cooperatives have many branches nationwide and are very safe, so they can be used with confidence. All the institutions named so far are on the whole safe, but their interest rates are low.",
   "sentences": [
    {
     "spans": [
      "지방은행은 특히 지역 경제의 발전에 필요한 돈을 ",
      {
       "word": "공급",
       "annotation": "공급"
      },
      "하는 것을 ",
      {
       "word": "주된",
       "annotation": "주되다"
      },
      " 목적으로 광역시나 도에 ",
      {
       "word": "설립",
       "annotation": "설립"
      },
      "된 은행이다. "
     ],
     "translation": "A local bank is one established in a metropolitan city or a province with the chief purpose of supplying the money the local economy needs to develop."
    },
    {
     "spans": [
      "경남은행, 광주은행, 대구은행, 부산은행, 전북은행, 제주은행 등이 여기에 해당한다. "
     ],
     "translation": "Kyongnam, Gwangju, Daegu, Busan, Jeonbuk and Jeju bank are of this kind."
    },
    {
     "spans": [
      "이 외에도 ",
      {
       "word": "단위농협",
       "annotation": "단위농협"
      },
      ", ",
      {
       "word": "우체국",
       "annotation": "우체국"
      },
      ", 새마을금고 등도 전국에 많은 지점이 있고 ",
      {
       "word": "안전성",
       "annotation": "안전성"
      },
      "이 높기 때문에 ",
      {
       "word": "안심",
       "annotation": "안심"
      },
      "하고 편리하게 이용할 수 있다. "
     ],
     "translation": "Besides these, the local Nonghyup branches, the post office and the Saemaul cooperatives have many branches nationwide and are very safe, so they can be used with confidence."
    },
    {
     "spans": [
      "지금까지 소개한 ",
      {
       "word": "금융",
       "annotation": "금융"
      },
      "기관은 모두 ",
      {
       "word": "대체로",
       "annotation": "대체로"
      },
      " 안전성이 높은 ",
      {
       "word": "반면",
       "annotation": "반면"
      },
      " ",
      {
       "word": "금리",
       "annotation": "금리"
      },
      "는 낮은 편이다."
     ],
     "translation": "All the institutions named so far are on the whole safe, but their interest rates are low."
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "시중은행, 지방은행, 농협 등이 제공하는 낮은 금리에 만족하지 못한다면 ",
    {
     "word": "상호저축은행",
     "annotation": "상호저축은행"
    },
    "을 이용할 수 있다. 상호저축은행은 시중은행 등에 비해 금리가 높은 ",
    {
     "word": "장점",
     "annotation": "장점"
    },
    "이 있지만, 대체로 규모가 작고 지점 수가 많지 않다."
   ],
   "translation": "Anyone not satisfied with the low rates the commercial banks, the local banks and Nonghyup offer may use a mutual savings bank. Its rates are higher, but it is generally small and has few branches.",
   "sentences": [
    {
     "spans": [
      "시중은행, 지방은행, 농협 등이 제공하는 낮은 금리에 만족하지 못한다면 ",
      {
       "word": "상호저축은행",
       "annotation": "상호저축은행"
      },
      "을 이용할 수 있다. "
     ],
     "translation": "Anyone not satisfied with the low rates the commercial banks, the local banks and Nonghyup offer may use a mutual savings bank."
    },
    {
     "spans": [
      "상호저축은행은 시중은행 등에 비해 금리가 높은 ",
      {
       "word": "장점",
       "annotation": "장점"
      },
      "이 있지만, 대체로 규모가 작고 지점 수가 많지 않다."
     ],
     "translation": "Its rates are higher, but it is generally small and has few branches."
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "최근에는 지점을 따로 만들지 않고 온라인 네트워크를 통해 금융 서비스를 제공하는 ",
    {
     "word": "인터넷 전문 은행",
     "annotation": "인터넷 전문 은행"
    },
    "도 ",
    {
     "word": "등장",
     "annotation": "등장"
    },
    "하였다. ",
    {
     "word": "케이뱅크",
     "annotation": "케이뱅크"
    },
    ", ",
    {
     "word": "카카오뱅크",
     "annotation": "카카오뱅크"
    },
    " 등이 그 예이다. 인터넷 전문 은행은 기존의 은행에 비해 사용 ",
    {
     "word": "절차",
     "annotation": "절차"
    },
    "가 간단하고 ",
    {
     "word": "수수료",
     "annotation": "수수료"
    },
    "가 낮으며 언제 어느 때나 이용할 수 있다는 점에서 인기가 높다."
   ],
   "translation": "Lately internet-only banks have appeared, providing financial services over an online network rather than building branches of their own. K bank and KakaoBank are examples. They are popular because the process is simpler than at an established bank, the fees are lower, and they can be used at any hour.",
   "sentences": [
    {
     "spans": [
      "최근에는 지점을 따로 만들지 않고 온라인 네트워크를 통해 금융 서비스를 제공하는 ",
      {
       "word": "인터넷 전문 은행",
       "annotation": "인터넷 전문 은행"
      },
      "도 ",
      {
       "word": "등장",
       "annotation": "등장"
      },
      "하였다. "
     ],
     "translation": "Lately internet-only banks have appeared, providing financial services over an online network rather than building branches of their own."
    },
    {
     "spans": [
      {
       "word": "케이뱅크",
       "annotation": "케이뱅크"
      },
      ", ",
      {
       "word": "카카오뱅크",
       "annotation": "카카오뱅크"
      },
      " 등이 그 예이다. "
     ],
     "translation": "K bank and KakaoBank are examples."
    },
    {
     "spans": [
      "인터넷 전문 은행은 기존의 은행에 비해 사용 ",
      {
       "word": "절차",
       "annotation": "절차"
      },
      "가 간단하고 ",
      {
       "word": "수수료",
       "annotation": "수수료"
      },
      "가 낮으며 언제 어느 때나 이용할 수 있다는 점에서 인기가 높다."
     ],
     "translation": "They are popular because the process is simpler than at an established bank, the fees are lower, and they can be used at any hour."
    }
   ]
  },
  {
   "type": "figure",
   "text": "한국은행"
  },
  {
   "type": "figure",
   "text": "인터넷 전문 은행 — 카카오뱅크와 케이뱅크"
  },
  {
   "type": "section",
   "kind": "aside",
   "text": "알아두면 좋아요",
   "topic": "저축 상품에는 어떤 것이 있을까?"
  },
  {
   "type": "paragraph",
   "spans": [
    "돈을 모으기 위해서는 매달 ",
    {
     "word": "소득",
     "annotation": "소득"
    },
    " 중 일부를 저축하는 것이 중요하다. 저축 ",
    {
     "word": "상품",
     "annotation": "상품"
    },
    "에는 ",
    {
     "word": "입금",
     "annotation": "입금"
    },
    ", ",
    {
     "word": "출금",
     "annotation": "출금"
    },
    "이 자유로운 ",
    {
     "word": "보통 예금",
     "annotation": "보통 예금"
    },
    ", 일정 금액을 일정 기간 동안 맡겨 두는 ",
    {
     "word": "정기 예금",
     "annotation": "정기 예금"
    },
    ", 일정 기간 동안 저축할 금액을 정해 놓고 그만큼씩 내는 ",
    {
     "word": "정기 적금",
     "annotation": "정기 적금"
    },
    " 등이 있다. 보통 예금은 정기 적금이나 정기 예금에 비해 금리가 매우 낮다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "[정기 예금의 예] 100만원을 일정 기간 동안 은행에 맡겨두는 것"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "[정기 적금의 예] 10만원씩 매달 같은 날에 저축하는 것"
   ]
  },
  {
   "type": "figure",
   "text": "저금통에 돈을 모으는 두 사람 — ‘적금’과 ‘예금’의 깃발"
  },
  {
   "type": "section",
   "kind": "part",
   "text": "02 금융 거래는 어떻게 하면 될까?"
  },
  {
   "type": "heading",
   "level": 2,
   "text": "은행 계좌 만들기",
   "titleTranslation": "Opening a bank account"
  },
  {
   "type": "glossary",
   "entries": [
    {
     "term": "금융실명제",
     "definition": [
      "가짜 이름이나 다른 사람이 아닌, 오직 본인의 이름으로만 금융 거래를 할 수 있도록 한 제도"
     ],
     "annotation": "금융실명제"
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "은행 ",
    {
     "word": "계좌",
     "annotation": "계좌"
    },
    "를 만들기 위해서는 반드시 본인이 신분증을 가지고 직접 은행을 ",
    {
     "word": "방문",
     "annotation": "방문"
    },
    "해야 한다. 한국에서는 모든 금융 ",
    {
     "word": "거래",
     "annotation": "거래"
    },
    "를 본인 자신의 이름으로만 하도록 하는 ",
    {
     "word": "금융실명제",
     "annotation": "금융실명제"
    },
    "가 실시되고 있기 때문이다. 자신의 이름을 다른 사람에게 빌려주거나 다른 사람의 이름을 빌려서 계좌를 만들면 처벌을 받게 된다."
   ],
   "translation": "To open an account you must go to the bank in person with your identification. This is because Korea operates a real-name system, under which all financial dealing must be done in one's own name. Lending your name to someone else, or opening an account in another's name, is punishable.",
   "sentences": [
    {
     "spans": [
      "은행 ",
      {
       "word": "계좌",
       "annotation": "계좌"
      },
      "를 만들기 위해서는 반드시 본인이 신분증을 가지고 직접 은행을 ",
      {
       "word": "방문",
       "annotation": "방문"
      },
      "해야 한다. "
     ],
     "translation": "To open an account you must go to the bank in person with your identification."
    },
    {
     "spans": [
      "한국에서는 모든 금융 ",
      {
       "word": "거래",
       "annotation": "거래"
      },
      "를 본인 자신의 이름으로만 하도록 하는 ",
      {
       "word": "금융실명제",
       "annotation": "금융실명제"
      },
      "가 실시되고 있기 때문이다. "
     ],
     "translation": "This is because Korea operates a real-name system, under which all financial dealing must be done in one's own name."
    },
    {
     "spans": [
      "자신의 이름을 다른 사람에게 빌려주거나 다른 사람의 이름을 빌려서 계좌를 만들면 처벌을 받게 된다."
     ],
     "translation": "Lending your name to someone else, or opening an account in another's name, is punishable."
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "외국인이 은행에서 계좌를 만들 때도 신분증(여권, ",
    {
     "word": "외국인등록증",
     "annotation": "외국인등록증"
    },
    ", ",
    {
     "word": "외국국적동포",
     "annotation": "외국국적동포"
    },
    " ",
    {
     "word": "국내 거소 신고증",
     "annotation": "국내 거소 신고증"
    },
    " 등)이 필요하며, 경우에 따라 ",
    {
     "word": "재직증명서",
     "annotation": "재직증명서"
    },
    "나 ",
    {
     "word": "재학증명서",
     "annotation": "재학증명서"
    },
    " 등의 ",
    {
     "word": "서류",
     "annotation": "서류"
    },
    "를 요청하기도 한다. 이때 ",
    {
     "word": "인터넷 뱅킹",
     "annotation": "인터넷 뱅킹"
    },
    ", ",
    {
     "word": "현금 인출 카드",
     "annotation": "현금 인출 카드"
    },
    " 등도 함께 신청할 수 있다. 계좌 비밀번호와 현금 인출 카드 비밀번호는 본인만 알 수 있는 번호로 ",
    {
     "word": "신중",
     "annotation": "신중"
    },
    "하게 정해야 한다. 신용카드를 신청한 경우에는 며칠 후에 집이나 직장으로 ",
    {
     "word": "배송",
     "annotation": "배송"
    },
    "된다."
   ],
   "translation": "A foreigner opening an account also needs identification — a passport, an alien registration card, a domestic residence report for a foreign-national Korean — and may be asked for papers such as proof of employment or of enrolment at a school. Internet banking and a cash card may be applied for at the same time. The account password and the cash card's should be chosen carefully, so that only you can know them. A credit card applied for is delivered to your home or workplace a few days later.",
   "sentences": [
    {
     "spans": [
      "외국인이 은행에서 계좌를 만들 때도 신분증(여권, ",
      {
       "word": "외국인등록증",
       "annotation": "외국인등록증"
      },
      ", ",
      {
       "word": "외국국적동포",
       "annotation": "외국국적동포"
      },
      " ",
      {
       "word": "국내 거소 신고증",
       "annotation": "국내 거소 신고증"
      },
      " 등)이 필요하며, 경우에 따라 ",
      {
       "word": "재직증명서",
       "annotation": "재직증명서"
      },
      "나 ",
      {
       "word": "재학증명서",
       "annotation": "재학증명서"
      },
      " 등의 ",
      {
       "word": "서류",
       "annotation": "서류"
      },
      "를 요청하기도 한다. "
     ],
     "translation": "A foreigner opening an account also needs identification — a passport, an alien registration card, a domestic residence report for a foreign-national Korean — and may be asked for papers such as proof of employment or of enrolment at a school."
    },
    {
     "spans": [
      "이때 ",
      {
       "word": "인터넷 뱅킹",
       "annotation": "인터넷 뱅킹"
      },
      ", ",
      {
       "word": "현금 인출 카드",
       "annotation": "현금 인출 카드"
      },
      " 등도 함께 신청할 수 있다. "
     ],
     "translation": "Internet banking and a cash card may be applied for at the same time."
    },
    {
     "spans": [
      "계좌 비밀번호와 현금 인출 카드 비밀번호는 본인만 알 수 있는 번호로 ",
      {
       "word": "신중",
       "annotation": "신중"
      },
      "하게 정해야 한다. "
     ],
     "translation": "The account password and the cash card's should be chosen carefully, so that only you can know them."
    },
    {
     "spans": [
      "신용카드를 신청한 경우에는 며칠 후에 집이나 직장으로 ",
      {
       "word": "배송",
       "annotation": "배송"
      },
      "된다."
     ],
     "translation": "A credit card applied for is delivered to your home or workplace a few days later."
    }
   ]
  },
  {
   "type": "heading",
   "level": 2,
   "text": "금융 거래 하기",
   "titleTranslation": "Doing your banking"
  },
  {
   "type": "glossary",
   "entries": [
    {
     "term": "거래",
     "definition": [
      "돈이나 물건을 주고 받는 것"
     ],
     "annotation": "거래"
    },
    {
     "term": "ATM(현금자동입출금기)",
     "definition": [
      "현금을 넣고 뽑을 수 있는 기계"
     ],
     "annotation": "ATM"
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "은행에 계좌를 만든 후에는 ",
    {
     "word": "ATM",
     "annotation": "ATM"
    },
    "(현금자동입출금기), 인터넷 뱅킹, 스마트폰 뱅킹 등 자신이 편리한 방법을 자유롭게 선택하여 ",
    {
     "word": "금융 거래",
     "annotation": "금융 거래"
    },
    "를 할 수 있다."
   ],
   "translation": "Once the account is open, you may bank as you find convenient: at an ATM, by internet banking, by smartphone banking.",
   "sentences": [
    {
     "spans": [
      "은행에 계좌를 만든 후에는 ",
      {
       "word": "ATM",
       "annotation": "ATM"
      },
      "(현금자동입출금기), 인터넷 뱅킹, 스마트폰 뱅킹 등 자신이 편리한 방법을 자유롭게 선택하여 ",
      {
       "word": "금융 거래",
       "annotation": "금융 거래"
      },
      "를 할 수 있다."
     ],
     "translation": "Once the account is open, you may bank as you find convenient: at an ATM, by internet banking, by smartphone banking."
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "ATM에서는 출금, 입금, ",
    {
     "word": "이체",
     "annotation": "이체"
    },
    "(",
    {
     "word": "송금",
     "annotation": "송금"
    },
    "), ",
    {
     "word": "계좌조회",
     "annotation": "계좌조회"
    },
    " 등을 할 수 있다. 주의해야 할 점은 자신의 계좌가 있는 은행이 아닌 ATM ",
    {
     "word": "기기",
     "annotation": "기기"
    },
    "를 사용할 때나 은행업무시간 외에 출금을 하거나 이체를 할 때 수수료가 붙는다는 점이다."
   ],
   "translation": "An ATM will let you withdraw, deposit, transfer and check the account. Bear in mind that a fee applies when you use the machine of a bank other than your own, or withdraw or transfer outside banking hours.",
   "sentences": [
    {
     "spans": [
      "ATM에서는 출금, 입금, ",
      {
       "word": "이체",
       "annotation": "이체"
      },
      "(",
      {
       "word": "송금",
       "annotation": "송금"
      },
      "), ",
      {
       "word": "계좌조회",
       "annotation": "계좌조회"
      },
      " 등을 할 수 있다. "
     ],
     "translation": "An ATM will let you withdraw, deposit, transfer and check the account."
    },
    {
     "spans": [
      "주의해야 할 점은 자신의 계좌가 있는 은행이 아닌 ATM ",
      {
       "word": "기기",
       "annotation": "기기"
      },
      "를 사용할 때나 은행업무시간 외에 출금을 하거나 이체를 할 때 수수료가 붙는다는 점이다."
     ],
     "translation": "Bear in mind that a fee applies when you use the machine of a bank other than your own, or withdraw or transfer outside banking hours."
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "인터넷 뱅킹이나 스마트폰 뱅킹은 컴퓨터나 스마트폰을 통해 어디에서든 자유롭게 은행 관련 업무를 볼 수 있다. 이를 활용하려면 먼저 신분증을 가지고 은행에서 ",
    {
     "word": "신청서",
     "annotation": "신청서"
    },
    "를 ",
    {
     "word": "작성",
     "annotation": "작성"
    },
    "한 후 제출해야 한다. 그리고 안전한 이용을 위해 ",
    {
     "word": "공동인증서",
     "annotation": "공동인증서"
    },
    "를 발급받고, ",
    {
     "word": "OTP",
     "annotation": "OTP"
    },
    "를 통해 ",
    {
     "word": "1회용",
     "annotation": "1회용"
    },
    " 비밀번호를 입력한다."
   ],
   "translation": "Internet and smartphone banking let you do your banking freely from anywhere, by computer or telephone. To use them you must first fill in an application at the bank, with your identification, and submit it. For safety you are then issued a joint certificate, and enter a one-time password through an OTP device.",
   "sentences": [
    {
     "spans": [
      "인터넷 뱅킹이나 스마트폰 뱅킹은 컴퓨터나 스마트폰을 통해 어디에서든 자유롭게 은행 관련 업무를 볼 수 있다. "
     ],
     "translation": "Internet and smartphone banking let you do your banking freely from anywhere, by computer or telephone."
    },
    {
     "spans": [
      "이를 활용하려면 먼저 신분증을 가지고 은행에서 ",
      {
       "word": "신청서",
       "annotation": "신청서"
      },
      "를 ",
      {
       "word": "작성",
       "annotation": "작성"
      },
      "한 후 제출해야 한다. "
     ],
     "translation": "To use them you must first fill in an application at the bank, with your identification, and submit it."
    },
    {
     "spans": [
      "그리고 안전한 이용을 위해 ",
      {
       "word": "공동인증서",
       "annotation": "공동인증서"
      },
      "를 발급받고, ",
      {
       "word": "OTP",
       "annotation": "OTP"
      },
      "를 통해 ",
      {
       "word": "1회용",
       "annotation": "1회용"
      },
      " 비밀번호를 입력한다."
     ],
     "translation": "For safety you are then issued a joint certificate, and enter a one-time password through an OTP device."
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "한편, 입금과 출금을 알려주는 ",
    {
     "word": "문자",
     "annotation": "문자"
    },
    " 서비스를 신청하면 자신의 ",
    {
     "word": "통장",
     "annotation": "통장"
    },
    "에 돈이 들어오고 나가는 것을 스마트폰을 통해 ",
    {
     "word": "곧바로",
     "annotation": "곧바로"
    },
    " 확인할 수 있다. 만약 자신이 모르는 돈이 들어오거나 ",
    {
     "word": "빠져나갔을",
     "annotation": "빠져나가다"
    },
    " 경우에는 반드시 은행이나 경찰서에 신고해야 한다."
   ],
   "translation": "If you sign up for the text service that reports deposits and withdrawals, you can see money entering and leaving your account on your telephone at once. Should money you know nothing about come in or go out, report it to the bank or the police without fail.",
   "sentences": [
    {
     "spans": [
      "한편, 입금과 출금을 알려주는 ",
      {
       "word": "문자",
       "annotation": "문자"
      },
      " 서비스를 신청하면 자신의 ",
      {
       "word": "통장",
       "annotation": "통장"
      },
      "에 돈이 들어오고 나가는 것을 스마트폰을 통해 ",
      {
       "word": "곧바로",
       "annotation": "곧바로"
      },
      " 확인할 수 있다. "
     ],
     "translation": "If you sign up for the text service that reports deposits and withdrawals, you can see money entering and leaving your account on your telephone at once."
    },
    {
     "spans": [
      "만약 자신이 모르는 돈이 들어오거나 ",
      {
       "word": "빠져나갔을",
       "annotation": "빠져나가다"
      },
      " 경우에는 반드시 은행이나 경찰서에 신고해야 한다."
     ],
     "translation": "Should money you know nothing about come in or go out, report it to the bank or the police without fail."
    }
   ]
  },
  {
   "type": "figure",
   "text": "ATM(현금자동입출금기)을 이용하는 모습"
  },
  {
   "type": "figure",
   "text": "OTP (토큰형, 카드형)"
  },
  {
   "type": "section",
   "kind": "aside",
   "text": "알아두면 좋아요",
   "topic": "예금자 보호 제도란 무엇일까?"
  },
  {
   "type": "paragraph",
   "spans": [
    "한국에서는 사람들이 안심하고 ",
    {
     "word": "예금",
     "annotation": "예금"
    },
    "할 수 있도록 ‘",
    {
     "word": "예금자 보호 제도",
     "annotation": "예금자 보호 제도"
    },
    "’를 ",
    {
     "word": "시행",
     "annotation": "시행"
    },
    "하고 있다. 이 제도에 ",
    {
     "word": "의해",
     "annotation": "의해"
    },
    " ",
    {
     "word": "원금",
     "annotation": "원금"
    },
    "(원래 맡긴 돈)과 ",
    {
     "word": "이자",
     "annotation": "이자"
    },
    "(원금에 붙는 돈)를 합쳐 금융기관별로 1인당 최고 5천만 원까지 보호 받을 수 있다. 그러므로 ",
    {
     "word": "예금액",
     "annotation": "예금액"
    },
    "이 5천만 원을 넘을 경우에는 여러 금융기관에 나누어 맡기는 것이 더 안전하다."
   ]
  },
  {
   "type": "section",
   "kind": "review",
   "text": "주요 내용정리"
  },
  {
   "type": "heading",
   "level": 3,
   "text": "01 금융기관에는 어떤 것이 있을까?"
  },
  {
   "type": "bullet",
   "spans": [
    "한국의 은행 업무 시간은 일반적으로 평일 오전 ",
    {
     "blank": ""
    },
    "부터 오후 ",
    {
     "blank": ""
    },
    "까지이다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "시중은행이나 지방은행은 대체로 안정성은 높은 반면 ",
    {
     "blank": ""
    },
    "가 낮은 편이다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "최근에는 지점을 따로 만들지 않고 온라인 네트워크를 통해 금융서비스를 제공하는 ",
    {
     "blank": ""
    },
    "이 인기를 끌고 있다."
   ]
  },
  {
   "type": "heading",
   "level": 3,
   "text": "02 금융 거래는 어떻게 하면 될까?"
  },
  {
   "type": "bullet",
   "spans": [
    "은행 계좌를 만들기 위해서는 반드시 본인이 ",
    {
     "blank": ""
    },
    "을 가지고 직접 은행을 방문해야 한다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "한국에서는 모든 금융 거래를 본인 자신의 이름으로만 하도록 하는 ",
    {
     "blank": ""
    },
    "가 실시되고 있다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "인터넷 뱅킹이나 스마트폰 뱅킹은 ",
    {
     "blank": ""
    },
    "나 스마트폰을 통해 어디에서든 자유롭게 은행 관련 업무를 볼 수 있다."
   ]
  },
  {
   "type": "section",
   "kind": "discuss",
   "text": "이야기 나누기",
   "topic": "인터넷과 스마트폰을 이용한 금융 사기를 조심해요!"
  },
  {
   "type": "paragraph",
   "spans": [
    {
     "word": "메신저 피싱",
     "annotation": "메신저 피싱"
    },
    "이란 카카오톡, 페이스북 등과 같은 ",
    {
     "word": "소셜 미디어",
     "annotation": "소셜 미디어"
    },
    "의 ",
    {
     "word": "계정",
     "annotation": "계정"
    },
    "에 ",
    {
     "word": "몰래",
     "annotation": "몰래"
    },
    " 로그인한 뒤 거기에 등록된 친구나 가족에게 메시지를 보내 돈을 ",
    {
     "word": "빼가는",
     "annotation": "빼가다"
    },
    " 범죄이다. 누가 아프다거나 교통사고를 당해서 ",
    {
     "word": "급히",
     "annotation": "급히"
    },
    " 돈이 필요하니 돈을 보내 달라고 해서 다른 사람 계좌로 입금하도록 하는 ",
    {
     "word": "방식",
     "annotation": "방식"
    },
    "을 사용한다."
   ]
  },
  {
   "type": "verse",
   "lines": [
    [
     "[실제 사례] K씨는 스마트폰으로 메신저를 확인하던 중 친구로부터 “갑자기 아이가 많이 아파서 급하게 병원에 가야 하는 데 돈이 필요하니 100만 원을 빌려줘”라는 메시지를 받고 친구가 알려준 계좌번호로 100만 원을 송금했습니다."
    ],
    [
     "K씨는 나중에 친구에게 ",
     {
      "word": "안부",
      "annotation": "안부"
     },
     " 전화를 하는 과정에서 메신저 피싱(Phishing)을 당했다는 사실을 ",
     {
      "word": "뒤늦게",
      "annotation": "뒤늦게"
     },
     " 깨달았습니다."
    ]
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "메신저 피싱을 ",
    {
     "word": "예방",
     "annotation": "예방"
    },
    "하기 위해서는 다음을 반드시 지키도록 한다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "메신저로 돈을 ",
    {
     "word": "요구",
     "annotation": "요구"
    },
    "하는 경우 반드시 전화를 걸어 본인인지 아닌지 확인해야 합니다."
   ],
   "ordered": true
  },
  {
   "type": "bullet",
   "spans": [
    "메신저를 통해서는 절대 개인 정보를 주고받아서는 안 됩니다."
   ],
   "ordered": true
  },
  {
   "type": "bullet",
   "spans": [
    "메신저 비밀번호를 자주 바꿔 줍니다."
   ],
   "ordered": true
  },
  {
   "type": "bullet",
   "spans": [
    "메신저에 ",
    {
     "word": "출처",
     "annotation": "출처"
    },
    "가 ",
    {
     "word": "분명",
     "annotation": "분명"
    },
    "하지 않은 ",
    {
     "word": "첨부 파일",
     "annotation": "첨부 파일"
    },
    "이나 링크가 있을 때는 클릭하지 않습니다."
   ],
   "ordered": true
  },
  {
   "type": "bullet",
   "spans": [
    {
     "word": "공공장소",
     "annotation": "공공장소"
    },
    "에 설치되어 있는 컴퓨터로는 금융 거래를 하지 않습니다."
   ],
   "ordered": true
  },
  {
   "type": "paragraph",
   "spans": [
    "★ 안전한 금융 거래를 위해 주의해야 할 점에 대해 이야기를 나눠 봅시다."
   ],
   "role": "prompt"
  }
 ],
 "annotations": {
  "은행": {
   "headword": "은행",
   "hanja": "銀行",
   "meaning": "a bank",
   "characters": [
    {
     "char": "銀",
     "reading": "은",
     "gloss": "silver — as in 은메달"
    },
    {
     "char": "行",
     "reading": "행",
     "gloss": "to go, a business — as in 행정, 여행"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "예금": {
   "headword": "예금",
   "hanja": "預金",
   "meaning": "a deposit; savings",
   "characters": [
    {
     "char": "預",
     "reading": "예",
     "gloss": "to entrust, beforehand — as in 예산"
    },
    {
     "char": "金",
     "reading": "금",
     "gloss": "money — as in 현금, 세금"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "대출": {
   "headword": "대출",
   "hanja": "貸出",
   "meaning": "a loan",
   "characters": [
    {
     "char": "貸",
     "reading": "대",
     "gloss": "to lend — as in 임대 “letting”"
    },
    {
     "char": "出",
     "reading": "출",
     "gloss": "to go out — as in 출금, 수출"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "송금": {
   "headword": "송금",
   "hanja": "送金",
   "meaning": "a remittance, sending money",
   "characters": [
    {
     "char": "送",
     "reading": "송",
     "gloss": "to send — as in 방송, 배송"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "환전": {
   "headword": "환전",
   "hanja": "換錢",
   "meaning": "changing money",
   "characters": [
    {
     "char": "換",
     "reading": "환",
     "gloss": "to exchange — as in 교환, 외환"
    },
    {
     "char": "錢",
     "reading": "전",
     "gloss": "coin, money — as in 동전"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "장면": {
   "headword": "장면",
   "hanja": "場面",
   "meaning": "a scene",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "공통점": {
   "headword": "공통점",
   "hanja": "共通點",
   "meaning": "a point in common",
   "characters": [
    {
     "char": "共",
     "reading": "공",
     "gloss": "together — as in 공유, 공동"
    },
    {
     "char": "通",
     "reading": "통",
     "gloss": "to pass — as in 통과, 소통"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "차이점": {
   "headword": "차이점",
   "hanja": "差異點",
   "meaning": "a point of difference",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "금융": {
   "headword": "금융",
   "hanja": "金融",
   "meaning": "finance, banking",
   "characters": [
    {
     "char": "融",
     "reading": "융",
     "gloss": "to melt, to circulate"
    }
   ],
   "notes": [
    "Literally money melting and flowing — hence the margin's 돈이 돌고 도는 것."
   ],
   "surfaces": []
  },
  "금융기관": {
   "headword": "금융기관",
   "hanja": "金融機關",
   "meaning": "a financial institution",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "금융 거래": {
   "headword": "금융 거래",
   "hanja": "金融去來",
   "meaning": "a financial transaction",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "맡다": {
   "headword": "맡다",
   "hanja": null,
   "meaning": "to take charge of, to hold for someone",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "빌려주다": {
   "headword": "빌려주다",
   "hanja": null,
   "meaning": "to lend",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "바꾸다": {
   "headword": "바꾸다",
   "hanja": null,
   "meaning": "to change, to exchange",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "공과금": {
   "headword": "공과금",
   "hanja": "公課金",
   "meaning": "utility and public charges",
   "characters": [
    {
     "char": "課",
     "reading": "과",
     "gloss": "to impose, a lesson — as in 과제, 과목"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "관리비": {
   "headword": "관리비",
   "hanja": "管理費",
   "meaning": "maintenance fees",
   "characters": [],
   "notes": [
    "The monthly charge on a Korean flat, covering the building's shared costs."
   ],
   "surfaces": []
  },
  "등록금": {
   "headword": "등록금",
   "hanja": "登錄金",
   "meaning": "tuition fees",
   "characters": [
    {
     "char": "登",
     "reading": "등",
     "gloss": "to register — as in 등록, 등산"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "납부": {
   "headword": "납부",
   "hanja": "納付",
   "meaning": "payment (of a charge)",
   "characters": [
    {
     "char": "納",
     "reading": "납",
     "gloss": "to pay in — as in 납세"
    },
    {
     "char": "付",
     "reading": "부",
     "gloss": "to hand over — as in 배부, 첨부"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "업무": {
   "headword": "업무",
   "hanja": "業務",
   "meaning": "business, work",
   "characters": [
    {
     "char": "業",
     "reading": "업",
     "gloss": "trade — as in 직업, 산업"
    },
    {
     "char": "務",
     "reading": "무",
     "gloss": "duty — as in 의무, 국무총리"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "평일": {
   "headword": "평일",
   "hanja": "平日",
   "meaning": "a weekday",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "한국은행": {
   "headword": "한국은행",
   "hanja": "韓國銀行",
   "meaning": "the Bank of Korea",
   "characters": [],
   "notes": [
    "The central bank: it issues the currency and sets the policy rate. Not a bank one holds an account with."
   ],
   "surfaces": []
  },
  "시중은행": {
   "headword": "시중은행",
   "hanja": "市中銀行",
   "meaning": "a commercial bank",
   "characters": [],
   "notes": [
    "시중 is “in the market, about town” — a bank open to the public, as against the central bank."
   ],
   "surfaces": []
  },
  "지방은행": {
   "headword": "지방은행",
   "hanja": "地方銀行",
   "meaning": "a local bank",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "빌리다": {
   "headword": "빌리다",
   "hanja": null,
   "meaning": "to borrow",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "지점": {
   "headword": "지점",
   "hanja": "支店",
   "meaning": "a branch",
   "characters": [
    {
     "char": "支",
     "reading": "지",
     "gloss": "branch, to support — as in 지출, 지원"
    },
    {
     "char": "店",
     "reading": "점",
     "gloss": "shop — as in 상점, 백화점"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "공급": {
   "headword": "공급",
   "hanja": "供給",
   "meaning": "supply",
   "characters": [
    {
     "char": "供",
     "reading": "공",
     "gloss": "to offer — as in 제공"
    },
    {
     "char": "給",
     "reading": "급",
     "gloss": "to give — as in 월급, 발급"
    }
   ],
   "notes": [
    "Its counterpart is 수요, demand."
   ],
   "surfaces": []
  },
  "주되다": {
   "headword": "주되다",
   "hanja": "主되다",
   "meaning": "to be the main one",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "설립": {
   "headword": "설립",
   "hanja": "設立",
   "meaning": "establishment, founding",
   "characters": [
    {
     "char": "設",
     "reading": "설",
     "gloss": "to establish — as in 시설, 설치"
    },
    {
     "char": "立",
     "reading": "립",
     "gloss": "to stand — as in 입장, 독립"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "단위농협": {
   "headword": "단위농협",
   "hanja": "單位農協",
   "meaning": "a local Nonghyup branch",
   "characters": [],
   "notes": [
    "The village-level agricultural cooperative, which takes deposits like a bank."
   ],
   "surfaces": []
  },
  "우체국": {
   "headword": "우체국",
   "hanja": "郵遞局",
   "meaning": "a post office",
   "characters": [
    {
     "char": "郵",
     "reading": "우",
     "gloss": "post — as in 우편, 우표"
    },
    {
     "char": "遞",
     "reading": "체",
     "gloss": "to deliver in turn"
    },
    {
     "char": "局",
     "reading": "국",
     "gloss": "bureau — as in 방송국, 약국"
    }
   ],
   "notes": [
    "Korean post offices take deposits and sell insurance as well as carrying letters."
   ],
   "surfaces": []
  },
  "안전성": {
   "headword": "안전성",
   "hanja": "安全性",
   "meaning": "safety, security",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "안심": {
   "headword": "안심",
   "hanja": "安心",
   "meaning": "peace of mind",
   "characters": [
    {
     "char": "安",
     "reading": "안",
     "gloss": "peace — as in 안전, 치안"
    },
    {
     "char": "心",
     "reading": "심",
     "gloss": "heart — as in 관심, 중심"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "대체로": {
   "headword": "대체로",
   "hanja": "大體로",
   "meaning": "on the whole, generally",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "반면": {
   "headword": "반면",
   "hanja": "反面",
   "meaning": "whereas, on the other hand",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "금리": {
   "headword": "금리",
   "hanja": "金利",
   "meaning": "an interest rate",
   "characters": [
    {
     "char": "利",
     "reading": "리",
     "gloss": "profit, interest — as in 이익, 이자"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "상호저축은행": {
   "headword": "상호저축은행",
   "hanja": "相互貯蓄銀行",
   "meaning": "a mutual savings bank",
   "characters": [
    {
     "char": "互",
     "reading": "호",
     "gloss": "mutual — as in 상호"
    },
    {
     "char": "貯",
     "reading": "저",
     "gloss": "to store up — as in 저축"
    }
   ],
   "notes": [
    "Higher rates, smaller and less safe than a commercial bank — the trade-off the article is making."
   ],
   "surfaces": []
  },
  "장점": {
   "headword": "장점",
   "hanja": "長點",
   "meaning": "an advantage, a strong point",
   "characters": [],
   "notes": [
    "Its opposite is 단점, which chapter 26's warm-up pairs it with."
   ],
   "surfaces": []
  },
  "인터넷 전문 은행": {
   "headword": "인터넷 전문 은행",
   "hanja": "인터넷專門銀行",
   "meaning": "an internet-only bank",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "등장": {
   "headword": "등장",
   "hanja": "登場",
   "meaning": "appearance, coming on the scene",
   "characters": [
    {
     "char": "登",
     "reading": "등",
     "gloss": "to climb, to appear — as in 등록"
    },
    {
     "char": "場",
     "reading": "장",
     "gloss": "place, stage — as in 장면, 시장"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "케이뱅크": {
   "headword": "케이뱅크",
   "hanja": null,
   "meaning": "K bank",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "카카오뱅크": {
   "headword": "카카오뱅크",
   "hanja": null,
   "meaning": "KakaoBank",
   "characters": [],
   "notes": [
    "Opened 2017 and now one of Korea's largest banks by customers, with no branches at all."
   ],
   "surfaces": []
  },
  "절차": {
   "headword": "절차",
   "hanja": "節次",
   "meaning": "a procedure, formalities",
   "characters": [
    {
     "char": "節",
     "reading": "절",
     "gloss": "a joint, a season — as in 명절, 절기"
    },
    {
     "char": "次",
     "reading": "차",
     "gloss": "order, next — as in 차례, 제25차"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "수수료": {
   "headword": "수수료",
   "hanja": "手數料",
   "meaning": "a fee, a commission",
   "characters": [
    {
     "char": "手",
     "reading": "수",
     "gloss": "hand — as in 수표, 수단"
    },
    {
     "char": "數",
     "reading": "수",
     "gloss": "number — as in 횟수, 과반수"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "소득": {
   "headword": "소득",
   "hanja": "所得",
   "meaning": "income",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "상품": {
   "headword": "상품",
   "hanja": "商品",
   "meaning": "a product",
   "characters": [],
   "notes": [
    "A bank's 상품 is an account or a plan, not a thing on a shelf."
   ],
   "surfaces": []
  },
  "입금": {
   "headword": "입금",
   "hanja": "入金",
   "meaning": "a deposit, paying in",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "출금": {
   "headword": "출금",
   "hanja": "出金",
   "meaning": "a withdrawal",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "보통 예금": {
   "headword": "보통 예금",
   "hanja": "普通預金",
   "meaning": "an ordinary deposit account",
   "characters": [],
   "notes": [
    "Money in and out as you please, at almost no interest."
   ],
   "surfaces": []
  },
  "정기 예금": {
   "headword": "정기 예금",
   "hanja": "定期預金",
   "meaning": "a time deposit",
   "characters": [],
   "notes": [
    "A lump sum left for a fixed term."
   ],
   "surfaces": []
  },
  "정기 적금": {
   "headword": "정기 적금",
   "hanja": "定期積金",
   "meaning": "a regular savings plan",
   "characters": [
    {
     "char": "積",
     "reading": "적",
     "gloss": "to pile up — as in 면적, 적극"
    }
   ],
   "notes": [
    "A set amount paid in every month for a fixed term — the commonest way Koreans save."
   ],
   "surfaces": []
  },
  "계좌": {
   "headword": "계좌",
   "hanja": "計座",
   "meaning": "an account",
   "characters": [
    {
     "char": "計",
     "reading": "계",
     "gloss": "to reckon — as in 계획, 통계"
    },
    {
     "char": "座",
     "reading": "좌",
     "gloss": "seat — as in 좌석, 강좌"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "방문": {
   "headword": "방문",
   "hanja": "訪問",
   "meaning": "a visit",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "금융실명제": {
   "headword": "금융실명제",
   "hanja": "金融實名制",
   "meaning": "the real-name financial system",
   "characters": [
    {
     "char": "實",
     "reading": "실",
     "gloss": "real — as in 사실, 실제"
    },
    {
     "char": "名",
     "reading": "명",
     "gloss": "name — as in 성명, 유명"
    }
   ],
   "notes": [
    "Introduced by emergency decree in 1993 to stop money moving under borrowed names."
   ],
   "surfaces": []
  },
  "외국인등록증": {
   "headword": "외국인등록증",
   "hanja": "外國人登錄證",
   "meaning": "an alien registration card",
   "characters": [],
   "notes": [
    "The residence card the 출입국·외국인정책본부 issues — chapter 22's office."
   ],
   "surfaces": []
  },
  "외국국적동포": {
   "headword": "외국국적동포",
   "hanja": "外國國籍同胞",
   "meaning": "an ethnic Korean of foreign nationality",
   "characters": [
    {
     "char": "同",
     "reading": "동",
     "gloss": "same — as in 동일, 동의"
    },
    {
     "char": "胞",
     "reading": "포",
     "gloss": "womb, sibling — as in 세포 “a cell”"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "국내 거소 신고증": {
   "headword": "국내 거소 신고증",
   "hanja": "國內居所申告證",
   "meaning": "a domestic residence report certificate",
   "characters": [],
   "notes": [
    "What an 외국국적동포 carries in place of the alien registration card."
   ],
   "surfaces": []
  },
  "재직증명서": {
   "headword": "재직증명서",
   "hanja": "在職證明書",
   "meaning": "proof of employment",
   "characters": [
    {
     "char": "在",
     "reading": "재",
     "gloss": "to be at — as in 재적, 현재"
    },
    {
     "char": "職",
     "reading": "직",
     "gloss": "post — as in 직업, 고위 공직자"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "재학증명서": {
   "headword": "재학증명서",
   "hanja": "在學證明書",
   "meaning": "proof of enrolment at a school",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "서류": {
   "headword": "서류",
   "hanja": "書類",
   "meaning": "papers, documents",
   "characters": [
    {
     "char": "書",
     "reading": "서",
     "gloss": "writing — as in 도서, 서명"
    },
    {
     "char": "類",
     "reading": "류",
     "gloss": "kind, sort — as in 종류, 인류"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "인터넷 뱅킹": {
   "headword": "인터넷 뱅킹",
   "hanja": null,
   "meaning": "internet banking",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "현금 인출 카드": {
   "headword": "현금 인출 카드",
   "hanja": "現金引出카드",
   "meaning": "a cash card",
   "characters": [
    {
     "char": "引",
     "reading": "인",
     "gloss": "to pull — as in 할인, 인상"
    },
    {
     "char": "出",
     "reading": "출",
     "gloss": "to take out — as in 출금, 지출"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "신중": {
   "headword": "신중",
   "hanja": "愼重",
   "meaning": "care, prudence",
   "characters": [
    {
     "char": "愼",
     "reading": "신",
     "gloss": "to be cautious"
    },
    {
     "char": "重",
     "reading": "중",
     "gloss": "heavy, weighty — as in 중요, 비중"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "배송": {
   "headword": "배송",
   "hanja": "配送",
   "meaning": "delivery",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "거래": {
   "headword": "거래",
   "hanja": "去來",
   "meaning": "a transaction, dealing",
   "characters": [
    {
     "char": "去",
     "reading": "거",
     "gloss": "to go — as in 과거, 제거"
    },
    {
     "char": "來",
     "reading": "래",
     "gloss": "to come — as in 미래, 원래"
    }
   ],
   "notes": [
    "Literally going and coming — money or goods passing both ways."
   ],
   "surfaces": []
  },
  "ATM": {
   "headword": "ATM",
   "hanja": "現金自動入出金機",
   "meaning": "a cash machine",
   "characters": [],
   "notes": [
    "Korean names it 현금자동입출금기 in full — the machine that takes cash in and pays it out automatically."
   ],
   "surfaces": []
  },
  "이체": {
   "headword": "이체",
   "hanja": "移替",
   "meaning": "a transfer between accounts",
   "characters": [
    {
     "char": "移",
     "reading": "이",
     "gloss": "to move — as in 이민, 이사"
    },
    {
     "char": "替",
     "reading": "체",
     "gloss": "to replace, to substitute"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "계좌조회": {
   "headword": "계좌조회",
   "hanja": "計座照會",
   "meaning": "checking an account",
   "characters": [
    {
     "char": "照",
     "reading": "조",
     "gloss": "to shine, to consult — as in 조명"
    },
    {
     "char": "會",
     "reading": "회",
     "gloss": "to meet — as in 회의, 국회"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "기기": {
   "headword": "기기",
   "hanja": "機器",
   "meaning": "a device, a machine",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "신청서": {
   "headword": "신청서",
   "hanja": "申請書",
   "meaning": "an application form",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "작성": {
   "headword": "작성",
   "hanja": "作成",
   "meaning": "filling in, drawing up",
   "characters": [
    {
     "char": "作",
     "reading": "작",
     "gloss": "to make — as in 제작, 작품"
    },
    {
     "char": "成",
     "reading": "성",
     "gloss": "to complete — as in 성장, 구성"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "공동인증서": {
   "headword": "공동인증서",
   "hanja": "共同認證書",
   "meaning": "a joint certificate",
   "characters": [],
   "notes": [
    "Renamed from 공인인증서 in 2020. The digital certificate Korean banking has long run on."
   ],
   "surfaces": []
  },
  "OTP": {
   "headword": "OTP",
   "hanja": null,
   "meaning": "a one-time password device",
   "characters": [],
   "notes": [
    "A token or card that shows a number good for one use."
   ],
   "surfaces": []
  },
  "1회용": {
   "headword": "1회용",
   "hanja": "一回用",
   "meaning": "single-use, one-time",
   "characters": [
    {
     "char": "回",
     "reading": "회",
     "gloss": "a time, to turn — as in 횟수, 회기"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "문자": {
   "headword": "문자",
   "hanja": "文字",
   "meaning": "a text message; a letter of an alphabet",
   "characters": [],
   "notes": [
    "문자를 보내다 “to send a text”, and 문자 “characters” as in 한글이라는 문자."
   ],
   "surfaces": []
  },
  "통장": {
   "headword": "통장",
   "hanja": "通帳",
   "meaning": "a bankbook",
   "characters": [
    {
     "char": "帳",
     "reading": "장",
     "gloss": "a ledger, an account book"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "곧바로": {
   "headword": "곧바로",
   "hanja": null,
   "meaning": "straight away, directly",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "빠져나가다": {
   "headword": "빠져나가다",
   "hanja": null,
   "meaning": "to slip out, to go out (of money)",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "예금자 보호 제도": {
   "headword": "예금자 보호 제도",
   "hanja": "預金者保護制度",
   "meaning": "deposit insurance",
   "characters": [],
   "notes": [
    "Up to 50 million won per person per institution — raised to 100 million in 2025, after this printing."
   ],
   "surfaces": []
  },
  "시행": {
   "headword": "시행",
   "hanja": "施行",
   "meaning": "enforcement, being in operation",
   "characters": [
    {
     "char": "施",
     "reading": "시",
     "gloss": "to carry out — as in 실시, 시설"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "의해": {
   "headword": "의해",
   "hanja": "依해",
   "meaning": "by, under (a rule)",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "원금": {
   "headword": "원금",
   "hanja": "元金",
   "meaning": "the principal",
   "characters": [
    {
     "char": "元",
     "reading": "원",
     "gloss": "origin — as in 원래, 원인"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "이자": {
   "headword": "이자",
   "hanja": "利子",
   "meaning": "interest",
   "characters": [
    {
     "char": "利",
     "reading": "리",
     "gloss": "profit — as in 금리, 이익"
    },
    {
     "char": "子",
     "reading": "자",
     "gloss": "child, thing — as in 의자, 원자재"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "예금액": {
   "headword": "예금액",
   "hanja": "預金額",
   "meaning": "the amount deposited",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "메신저 피싱": {
   "headword": "메신저 피싱",
   "hanja": null,
   "meaning": "messenger phishing",
   "characters": [],
   "notes": [
    "Taking over a messaging account and asking the victim's friends for money — the commonest fraud of its kind in Korea."
   ],
   "surfaces": []
  },
  "소셜 미디어": {
   "headword": "소셜 미디어",
   "hanja": null,
   "meaning": "social media",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "계정": {
   "headword": "계정",
   "hanja": "計定",
   "meaning": "an account (online)",
   "characters": [],
   "notes": [
    "An online account is a 계정; a bank account a 계좌."
   ],
   "surfaces": []
  },
  "몰래": {
   "headword": "몰래",
   "hanja": null,
   "meaning": "secretly, without being noticed",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "빼가다": {
   "headword": "빼가다",
   "hanja": null,
   "meaning": "to take away, to siphon off",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "급히": {
   "headword": "급히",
   "hanja": "急히",
   "meaning": "urgently, in a hurry",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "방식": {
   "headword": "방식",
   "hanja": "方式",
   "meaning": "a method, a way",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "안부": {
   "headword": "안부",
   "hanja": "安否",
   "meaning": "asking after someone",
   "characters": [
    {
     "char": "否",
     "reading": "부",
     "gloss": "not, whether — as in 여부, 거부"
    }
   ],
   "notes": [
    "안부 전화 “a call to see how someone is”, 안부를 묻다 “to ask after”."
   ],
   "surfaces": []
  },
  "뒤늦게": {
   "headword": "뒤늦게",
   "hanja": null,
   "meaning": "belatedly, too late",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "예방": {
   "headword": "예방",
   "hanja": "豫防",
   "meaning": "prevention",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "요구": {
   "headword": "요구",
   "hanja": "要求",
   "meaning": "a demand, asking for",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "출처": {
   "headword": "출처",
   "hanja": "出處",
   "meaning": "a source, where something comes from",
   "characters": [],
   "notes": [
    "The word at the foot of every quoted passage in this book."
   ],
   "surfaces": []
  },
  "분명": {
   "headword": "분명",
   "hanja": "分明",
   "meaning": "being clear, evident",
   "characters": [
    {
     "char": "分",
     "reading": "분",
     "gloss": "to divide — as in 부분, 신분"
    },
    {
     "char": "明",
     "reading": "명",
     "gloss": "bright — as in 설명, 투명"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "첨부 파일": {
   "headword": "첨부 파일",
   "hanja": "添附파일",
   "meaning": "an attached file",
   "characters": [
    {
     "char": "添",
     "reading": "첨",
     "gloss": "to add — as in 첨가"
    },
    {
     "char": "附",
     "reading": "부",
     "gloss": "to attach — as in 부록"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "공공장소": {
   "headword": "공공장소",
   "hanja": "公共場所",
   "meaning": "a public place",
   "characters": [],
   "notes": [],
   "surfaces": []
  }
 },
 "notes": [
  {
   "why": "Chapter 28 has no Google Doc: the Korean is my reading of the photos of pp. 148-151, so it is worth checking against the pages."
  },
  {
   "why": "The margin gloss for ATM is my own wording: the book heads the entry ATM(현금자동입출금기) and leaves the definition to the article."
  },
  {
   "why": "The five rules against messenger phishing are printed numbered in their own box, and set here as a numbered list; the case study is set as a quoted passage."
  },
  {
   "why": "The review gaps on p. 151 are blank in the book and left blank here."
  }
 ],
 "slug": "28-banking"
});
