/* Generated by tools/build.py — do not edit.
   Content lives in tools/chapters/chNN_*.py; rebuild after changing it. */

KIIP.manifest([
 {
  "number": 1,
  "slug": "01-symbols-of-korea",
  "title": "한국의 상징",
  "titleEn": "Symbols of Korea"
 },
 {
  "number": 2,
  "slug": "02-family",
  "title": "가족",
  "titleEn": "Family"
 },
 {
  "number": 3,
  "slug": "03-workplace",
  "title": "일터",
  "titleEn": "The workplace"
 },
 {
  "number": 4,
  "slug": "04-transport-and-communication",
  "title": "교통과 통신",
  "titleEn": "Transport and communication"
 },
 {
  "number": 5,
  "slug": "05-housing",
  "title": "주거",
  "titleEn": "Housing"
 },
 {
  "number": 6,
  "slug": "06-city-and-country",
  "title": "도시와 농촌",
  "titleEn": "The city and the countryside"
 },
 {
  "number": 7,
  "slug": "07-welfare",
  "title": "복지",
  "titleEn": "Welfare"
 },
 {
  "number": 8,
  "slug": "08-health-and-safety",
  "title": "의료와 안전",
  "titleEn": "Health care and safety"
 },
 {
  "number": 9,
  "slug": "09-childcare",
  "title": "보육 제도",
  "titleEn": "Childcare"
 },
 {
  "number": 10,
  "slug": "10-school-education",
  "title": "초·중등 교육",
  "titleEn": "Primary and secondary education"
 },
 {
  "number": 11,
  "slug": "11-higher-education",
  "title": "고등 교육과 입시",
  "titleEn": "Higher education and entrance exams"
 },
 {
  "number": 12,
  "slug": "12-lifelong-learning",
  "title": "평생 교육",
  "titleEn": "Lifelong learning"
 },
 {
  "number": 13,
  "slug": "13-traditional-values",
  "title": "전통 가치",
  "titleEn": "Traditional values"
 },
 {
  "number": 14,
  "slug": "14-food-dress-and-housing",
  "title": "전통 의식주",
  "titleEn": "Traditional food, dress and housing"
 },
 {
  "number": 15,
  "slug": "15-rites-of-passage",
  "title": "의례",
  "titleEn": "Rites of passage"
 },
 {
  "number": 16,
  "slug": "16-seasonal-festivals",
  "title": "명절",
  "titleEn": "The seasonal festivals"
 },
 {
  "number": 17,
  "slug": "17-religion",
  "title": "종교",
  "titleEn": "Religion"
 },
 {
  "number": 18,
  "slug": "18-popular-culture",
  "title": "대중문화",
  "titleEn": "Popular culture"
 },
 {
  "number": 19,
  "slug": "19-leisure",
  "title": "여가문화",
  "titleEn": "Leisure"
 },
 {
  "number": 20,
  "slug": "20-democratic-politics",
  "title": "한국의 민주 정치",
  "titleEn": "Democratic politics in Korea"
 },
 {
  "number": 21,
  "slug": "21-legislature",
  "title": "입법부",
  "titleEn": "The legislature"
 },
 {
  "number": 22,
  "slug": "22-executive",
  "title": "행정부",
  "titleEn": "The executive"
 },
 {
  "number": 23,
  "slug": "23-judiciary",
  "title": "사법부",
  "titleEn": "The judiciary"
 },
 {
  "number": 24,
  "slug": "24-elections-and-local-government",
  "title": "선거와 지방자치",
  "titleEn": "Elections and local self-government"
 },
 {
  "number": 25,
  "slug": "25-daily-economic-life",
  "title": "일상생활과 경제 활동",
  "titleEn": "Everyday life and economic activity"
 },
 {
  "number": 26,
  "slug": "26-economic-growth",
  "title": "경제 성장",
  "titleEn": "Economic growth"
 },
 {
  "number": 27,
  "slug": "27-shopping-and-consumers",
  "title": "장보기와 소비자 보호",
  "titleEn": "Shopping and consumer protection"
 },
 {
  "number": 28,
  "slug": "28-banking",
  "title": "금융기관 이용하기",
  "titleEn": "Using a financial institution"
 },
 {
  "number": 29,
  "slug": "29-finding-work",
  "title": "취업하기",
  "titleEn": "Finding work"
 },
 {
  "number": 30,
  "slug": "30-foreigners-and-law",
  "title": "외국인과 법",
  "titleEn": "Foreigners and the law"
 },
 {
  "number": 31,
  "slug": "31-staying-in-korea",
  "title": "한국 체류와 법",
  "titleEn": "Staying in Korea and the law"
 },
 {
  "number": 32,
  "slug": "32-korean-nationality",
  "title": "한국 국적과 법",
  "titleEn": "Korean nationality and the law"
 },
 {
  "number": 33,
  "slug": "33-family-and-law",
  "title": "가족과 법",
  "titleEn": "The family and the law"
 },
 {
  "number": 34,
  "slug": "34-property-and-law",
  "title": "재산과 법",
  "titleEn": "Property and the law"
 }
]);
