/* Generated by tools/build.py — do not edit.
   Content lives in tools/chapters/chNN_*.py; rebuild after changing it. */

KIIP.manifest([
 {
  "number": 1,
  "slug": "01-symbols-of-korea",
  "title": "한국의 상징",
  "titleEn": "Symbols of Korea"
 },
 {
  "number": 2,
  "slug": "02-family",
  "title": "가족",
  "titleEn": "Family"
 },
 {
  "number": 3,
  "slug": "03-workplace",
  "title": "일터",
  "titleEn": "The workplace"
 },
 {
  "number": 4,
  "slug": "04-transport-and-communication",
  "title": "교통과 통신",
  "titleEn": "Transport and communication"
 },
 {
  "number": 5,
  "slug": "05-housing",
  "title": "주거",
  "titleEn": "Housing"
 },
 {
  "number": 6,
  "slug": "06-city-and-country",
  "title": "도시와 농촌",
  "titleEn": "The city and the countryside"
 },
 {
  "number": 7,
  "slug": "07-welfare",
  "title": "복지",
  "titleEn": "Welfare"
 },
 {
  "number": 8,
  "slug": "08-health-and-safety",
  "title": "의료와 안전",
  "titleEn": "Health care and safety"
 },
 {
  "number": 9,
  "slug": "09-childcare",
  "title": "보육 제도",
  "titleEn": "Childcare"
 },
 {
  "number": 10,
  "slug": "10-school-education",
  "title": "초·중등 교육",
  "titleEn": "Primary and secondary education"
 },
 {
  "number": 11,
  "slug": "11-higher-education",
  "title": "고등 교육과 입시",
  "titleEn": "Higher education and entrance exams"
 },
 {
  "number": 12,
  "slug": "12-lifelong-learning",
  "title": "평생 교육",
  "titleEn": "Lifelong learning"
 },
 {
  "number": 13,
  "slug": "13-traditional-values",
  "title": "전통 가치",
  "titleEn": "Traditional values"
 },
 {
  "number": 14,
  "slug": "14-food-dress-and-housing",
  "title": "전통 의식주",
  "titleEn": "Traditional food, dress and housing"
 },
 {
  "number": 15,
  "slug": "15-rites-of-passage",
  "title": "의례",
  "titleEn": "Rites of passage"
 },
 {
  "number": 16,
  "slug": "16-seasonal-festivals",
  "title": "명절",
  "titleEn": "The seasonal festivals"
 },
 {
  "number": 17,
  "slug": "17-religion",
  "title": "종교",
  "titleEn": "Religion"
 }
]);
