/* Generated by tools/build.py — do not edit.
   Content lives in tools/chapters/chNN_*.py; rebuild after changing it. */

KIIP.manifest([
 {
  "number": 1,
  "slug": "01-symbols-of-korea",
  "title": "한국의 상징",
  "titleEn": "Symbols of Korea"
 },
 {
  "number": 2,
  "slug": "02-family",
  "title": "가족",
  "titleEn": "Family"
 },
 {
  "number": 3,
  "slug": "03-workplace",
  "title": "일터",
  "titleEn": "The workplace"
 }
]);
