/* Generated by tools/build.py — do not edit.
   Content lives in tools/chapters/pt04_politics.py; rebuild after changing it. */

KIIP.chapter({
 "number": 4,
 "unit": "정치",
 "title": "대단원 마무리",
 "titleEnglish": "Closing the part",
 "chapterGlossary": [],
 "blocks": [
  {
   "type": "section",
   "kind": "summary",
   "text": "대단원 정리"
  },
  {
   "type": "table",
   "rows": [
    [
     "한국의 민주 정치",
     "정치와 민주주의 의미, 주권, 권력 분립"
    ],
    [
     "입법부",
     "국회의 구성, 국회의원의 특권과 의무, 국회가 하는 일(입법, 국가 재정, 국정)"
    ],
    [
     "행정부",
     "정부의 구성, 국무회의, 대통령의 권한, 정부가 하는 일"
    ],
    [
     "사법부",
     "법원의 구성, 재판을 통한 권리 보호와 질서 유지, 공정한 재판을 위한 제도, 재판의 종류"
    ],
    [
     "선거와 지방자치",
     "선거의 의미, 선거의 4대 원칙, 선거의 종류, 지방자치제의 의미, 지방자치의 모습"
    ]
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "찾아볼 곳"
  },
  {
   "type": "bullet",
   "spans": [
    "정부24 — www.gov.kr"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "청와대 — www.president.go.kr"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "대한민국 국회 — www.assembly.go.kr"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "중앙선거관리위원회 — www.nec.go.kr"
   ]
  },
  {
   "type": "section",
   "kind": "quiz",
   "text": "가로 세로 퀴즈"
  },
  {
   "type": "figure",
   "text": "일곱 칸씩 가로세로로 짜인 낱말 퍼즐 판. 가로 열쇠 ㉮~㉲와 세로 열쇠 ①~④가 시작하는 칸에 번호가 적혀 있다."
  },
  {
   "type": "heading",
   "level": 4,
   "text": "가로 열쇠"
  },
  {
   "type": "bullet",
   "spans": [
    "㉮ 주인으로서의 권리, 한국 국민은 국가의 주인으로서 이것을 가지고 있음 ",
    {
     "blank": "주권"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "㉯ 국민의 기본권을 규정하고 있는 국가 최고의 법 ",
    {
     "blank": "헌법"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "㉰ 국민에게 필요한 정책을 직접 집행하면서 나라의 살림을 하는 기관 ",
    {
     "blank": "행정부"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "㉱ 대한민국 대통령이 일하는 곳 ",
    {
     "blank": "청와대"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "㉲ 국민을 대표하는 기관인 국회의 구성원 ",
    {
     "blank": "국회의원"
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "세로 열쇠"
  },
  {
   "type": "bullet",
   "spans": [
    "① 국민이 권력을 가지고 스스로 다스린다는 것을 의미하는 정치 제도 ",
    {
     "blank": "민주주의"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "② 법을 적용하여 재판을 담당하는 기관 ",
    {
     "blank": "사법부"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "③ 국회에서 필요한 경우에 당사자, 증인, 참고인 등을 불러 질문하고 사실이나 의견을 듣는 제도 ",
    {
     "blank": "청문회"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "④ 공정한 재판을 위해 한 사건에 대하여 세 번 심판을 받을 수 있는 제도 ",
    {
     "blank": "삼심제"
    }
   ]
  },
  {
   "type": "section",
   "kind": "exam",
   "text": "단원 종합 평가"
  },
  {
   "type": "heading",
   "level": 4,
   "text": "01 한국의 민주주의 발전과 관계없는 것은?"
  },
  {
   "type": "bullet",
   "spans": [
    "① 4·19혁명"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "② 6월 항쟁"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "③ 6·25전쟁"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "④ 5·18 민주화 운동"
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "정답 ",
    {
     "blank": "③"
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "02 다음 중 선거의 기본 원칙에 속하지 않는 것은?"
  },
  {
   "type": "bullet",
   "spans": [
    "① 간접 선거"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "② 보통 선거"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "③ 평등 선거"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "④ 비밀 선거"
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "정답 ",
    {
     "blank": "①"
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "03 다음 중 민주주의 국가의 특징에 해당하지 않는 것은?"
  },
  {
   "type": "bullet",
   "spans": [
    "① 국민의 대표를 국민이 직접 선출한다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "② 권력을 가진 한 사람이 모든 것을 결정한다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "③ 모든 국민이 나라의 주인으로서 권리를 갖는다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "④ 국가 권력을 여러 기관에서 나누어 견제와 균형을 이룬다."
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "정답 ",
    {
     "blank": "②"
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "04 〈보기〉의 ㉠, ㉡에서 설명하는 용어로 옳은 것은?"
  },
  {
   "type": "verse",
   "lines": [
    [
     "ㄱ. 지역 주민이 스스로 자기 지역의 대표자를 뽑아서 지역의 정치를 담당하도록 하는 제도."
    ],
    [
     "ㄴ. 공정한 재판을 위해 같은 사건에 대해 세 번까지 재판을 받을 수 있도록 한 제도."
    ]
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "① 지방자치제 / 삼권분립"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "② 지방자치제 / 삼심제"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "③ 의원내각제 / 삼권분립"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "④ 의원내각제 / 삼심제"
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "정답 ",
    {
     "blank": "②"
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "05 다음 〈보기〉에서 설명하는 기관으로 알맞은 곳은?"
  },
  {
   "type": "verse",
   "lines": [
    [
     "국무회의를 통해 국가의 주요 정책을 의논하고 결정한다."
    ],
    [
     "대통령이 최고 책임자이며, 국무총리, 장관 등이 속해 있는 기관이다."
    ]
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "① 법무부"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "② 사법부"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "③ 입법부"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "④ 행정부"
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "정답 ",
    {
     "blank": "④"
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "06 다음 〈보기〉에서 선거에 대한 옳은 설명을 모두 고른 것은?"
  },
  {
   "type": "verse",
   "lines": [
    [
     "ㄱ. 친한 사람끼리는 비밀 선거의 원칙을 지킬 필요 없다."
    ],
    [
     "ㄴ. 선거는 국민이 자신을 대표할 사람을 직접 뽑는 것을 말한다."
    ],
    [
     "ㄷ. 보통 선거는 만 17세가 되면 국민 누구나 참여할 수 있는 것이다."
    ],
    [
     "ㄹ. 평등 선거는 조건에 관계없이 공평하게 1인 1표씩 투표하는 것이다."
    ]
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "① ㄱ, ㄴ"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "② ㄱ, ㄷ"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "③ ㄷ, ㄹ"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "④ ㄴ, ㄹ"
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "정답 ",
    {
     "blank": "④"
    }
   ]
  },
  {
   "type": "section",
   "kind": "feature",
   "text": "일상생활과 민주주의"
  },
  {
   "type": "heading",
   "level": 3,
   "text": "다수결",
   "titleTranslation": "Majority rule"
  },
  {
   "type": "paragraph",
   "spans": [
    "다양한 의견을 하나로 모으기 위해 많은 사람들의 의견에 따라 결정하는 것."
   ],
   "translation": "Deciding a matter by the view of the greater number, so as to gather many views into one.",
   "sentences": [
    {
     "spans": [
      "다양한 의견을 하나로 모으기 위해 많은 사람들의 의견에 따라 결정하는 것."
     ],
     "translation": "Deciding a matter by the view of the greater number, so as to gather many views into one."
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    {
     "word": "다수결",
     "annotation": "다수결"
    },
    " 결정 방식으로는 선거와 같은 대표자 선출, 학급 회장 선출, 학급에서 소풍 장소 결정 등이 있다."
   ],
   "translation": "Choosing representatives at an election, electing a class president, settling where a class will go on an outing are all decisions taken by majority.",
   "sentences": [
    {
     "spans": [
      {
       "word": "다수결",
       "annotation": "다수결"
      },
      " 결정 방식으로는 선거와 같은 대표자 선출, 학급 회장 선출, 학급에서 소풍 장소 결정 등이 있다."
     ],
     "translation": "Choosing representatives at an election, electing a class president, settling where a class will go on an outing are all decisions taken by majority."
    }
   ]
  },
  {
   "type": "figure",
   "text": "교실에서 손을 들어 소풍 장소를 정하는 아이들 — 칠판에 ‘제12회 봄소풍 장소 투표’"
  },
  {
   "type": "heading",
   "level": 3,
   "text": "관용",
   "titleTranslation": "Tolerance"
  },
  {
   "type": "paragraph",
   "spans": [
    "자신의 신념만을 절대시하지 않고 다른 사람의 이익과 신념, 가치도 인정하고 ",
    {
     "word": "포용",
     "annotation": "포용"
    },
    "하는 생각과 태도."
   ],
   "translation": "A cast of mind that does not hold one's own convictions to be absolute, but acknowledges and makes room for the interests, convictions and values of others.",
   "sentences": [
    {
     "spans": [
      "자신의 신념만을 절대시하지 않고 다른 사람의 이익과 신념, 가치도 인정하고 ",
      {
       "word": "포용",
       "annotation": "포용"
      },
      "하는 생각과 태도."
     ],
     "translation": "A cast of mind that does not hold one's own convictions to be absolute, but acknowledges and makes room for the interests, convictions and values of others."
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    {
     "word": "관용",
     "annotation": "관용"
    },
    "은 민주주의의 ",
    {
     "word": "다양성",
     "annotation": "다양성"
    },
    "의 ",
    {
     "word": "전제",
     "annotation": "전제"
    },
    "이며 ",
    {
     "word": "소수자",
     "annotation": "소수자"
    },
    "들이 어떠한 ",
    {
     "word": "탄압",
     "annotation": "탄압"
    },
    "이나 ",
    {
     "word": "소외",
     "annotation": "소외"
    },
    " 없이 ",
    {
     "word": "더불어",
     "annotation": "더불어"
    },
    " 살아가는 것을 ",
    {
     "word": "보장",
     "annotation": "보장"
    },
    "하는 데 있어 중요한 ",
    {
     "word": "요소",
     "annotation": "요소"
    },
    "이다."
   ],
   "translation": "Tolerance is the premise of democracy's plurality, and an important part of guaranteeing that minorities may live alongside everyone else without oppression or exclusion of any kind.",
   "sentences": [
    {
     "spans": [
      {
       "word": "관용",
       "annotation": "관용"
      },
      "은 민주주의의 ",
      {
       "word": "다양성",
       "annotation": "다양성"
      },
      "의 ",
      {
       "word": "전제",
       "annotation": "전제"
      },
      "이며 ",
      {
       "word": "소수자",
       "annotation": "소수자"
      },
      "들이 어떠한 ",
      {
       "word": "탄압",
       "annotation": "탄압"
      },
      "이나 ",
      {
       "word": "소외",
       "annotation": "소외"
      },
      " 없이 ",
      {
       "word": "더불어",
       "annotation": "더불어"
      },
      " 살아가는 것을 ",
      {
       "word": "보장",
       "annotation": "보장"
      },
      "하는 데 있어 중요한 ",
      {
       "word": "요소",
       "annotation": "요소"
      },
      "이다."
     ],
     "translation": "Tolerance is the premise of democracy's plurality, and an important part of guaranteeing that minorities may live alongside everyone else without oppression or exclusion of any kind."
    }
   ]
  },
  {
   "type": "figure",
   "text": "길에서 서로 다른 주장을 든 사람들이 마주 선 모습"
  },
  {
   "type": "heading",
   "level": 3,
   "text": "토론",
   "titleTranslation": "Debate"
  },
  {
   "type": "paragraph",
   "spans": [
    "어떤 문제에 대해 찬성과 반대의 의견을 말하며 ",
    {
     "word": "논의",
     "annotation": "논의"
    },
    "하는 것."
   ],
   "translation": "Talking a question over, with views stated for and against.",
   "sentences": [
    {
     "spans": [
      "어떤 문제에 대해 찬성과 반대의 의견을 말하며 ",
      {
       "word": "논의",
       "annotation": "논의"
      },
      "하는 것."
     ],
     "translation": "Talking a question over, with views stated for and against."
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    {
     "word": "토론",
     "annotation": "토론"
    },
    "은 찬성하는 쪽과 반대하는 쪽이 있어서 서로 자기의 주장이 ",
    {
     "word": "옳음",
     "annotation": "옳음"
    },
    "을 ",
    {
     "word": "내세우며",
     "annotation": "내세우다"
    },
    " 각각 자기 쪽의 주장을 ",
    {
     "word": "받아들이도록",
     "annotation": "받아들이다"
    },
    " ",
    {
     "word": "상대방",
     "annotation": "상대방"
    },
    " 또는 ",
    {
     "word": "제3자",
     "annotation": "제3자"
    },
    "를 ",
    {
     "word": "설득",
     "annotation": "설득"
    },
    "하는 것이다."
   ],
   "translation": "In a debate there is a side in favour and a side against, each asserting that its own claim is the right one and each trying to persuade the other side, or a third party, to accept it.",
   "sentences": [
    {
     "spans": [
      {
       "word": "토론",
       "annotation": "토론"
      },
      "은 찬성하는 쪽과 반대하는 쪽이 있어서 서로 자기의 주장이 ",
      {
       "word": "옳음",
       "annotation": "옳음"
      },
      "을 ",
      {
       "word": "내세우며",
       "annotation": "내세우다"
      },
      " 각각 자기 쪽의 주장을 ",
      {
       "word": "받아들이도록",
       "annotation": "받아들이다"
      },
      " ",
      {
       "word": "상대방",
       "annotation": "상대방"
      },
      " 또는 ",
      {
       "word": "제3자",
       "annotation": "제3자"
      },
      "를 ",
      {
       "word": "설득",
       "annotation": "설득"
      },
      "하는 것이다."
     ],
     "translation": "In a debate there is a side in favour and a side against, each asserting that its own claim is the right one and each trying to persuade the other side, or a third party, to accept it."
    }
   ]
  },
  {
   "type": "figure",
   "text": "‘제2회 □△ 토론 대회’ — 찬성과 반대 표지를 놓고 마주 앉은 학생들"
  },
  {
   "type": "heading",
   "level": 3,
   "text": "타협",
   "titleTranslation": "Compromise"
  },
  {
   "type": "paragraph",
   "spans": [
    "어떤 일을 서로 ",
    {
     "word": "양보",
     "annotation": "양보"
    },
    "해서 ",
    {
     "word": "협의",
     "annotation": "협의"
    },
    "하는 것."
   ],
   "translation": "Coming to terms on something, each side giving ground.",
   "sentences": [
    {
     "spans": [
      "어떤 일을 서로 ",
      {
       "word": "양보",
       "annotation": "양보"
      },
      "해서 ",
      {
       "word": "협의",
       "annotation": "협의"
      },
      "하는 것."
     ],
     "translation": "Coming to terms on something, each side giving ground."
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    {
     "word": "타협",
     "annotation": "타협"
    },
    "은 민주주의 ",
    {
     "word": "의사 결정",
     "annotation": "의사 결정"
    },
    " 과정에서 ",
    {
     "word": "합의",
     "annotation": "합의"
    },
    "를 이끌어 내는 하나의 방식이다. 서로 다른 주장이 있을 때 서로의 ",
    {
     "word": "입장",
     "annotation": "입장"
    },
    "에서 조금씩 ",
    {
     "word": "물러나",
     "annotation": "물러나다"
    },
    " 양보와 타협을 하게 되면 더 많은 사람이 ",
    {
     "word": "만족",
     "annotation": "만족"
    },
    "할 만한 결과를 얻을 수도 있다."
   ],
   "translation": "Compromise is one of the ways agreement is reached in democratic decision-making. Where two claims differ, drawing back a little from each position and giving and taking may reach a result that more people can be satisfied with.",
   "sentences": [
    {
     "spans": [
      {
       "word": "타협",
       "annotation": "타협"
      },
      "은 민주주의 ",
      {
       "word": "의사 결정",
       "annotation": "의사 결정"
      },
      " 과정에서 ",
      {
       "word": "합의",
       "annotation": "합의"
      },
      "를 이끌어 내는 하나의 방식이다. "
     ],
     "translation": "Compromise is one of the ways agreement is reached in democratic decision-making."
    },
    {
     "spans": [
      "서로 다른 주장이 있을 때 서로의 ",
      {
       "word": "입장",
       "annotation": "입장"
      },
      "에서 조금씩 ",
      {
       "word": "물러나",
       "annotation": "물러나다"
      },
      " 양보와 타협을 하게 되면 더 많은 사람이 ",
      {
       "word": "만족",
       "annotation": "만족"
      },
      "할 만한 결과를 얻을 수도 있다."
     ],
     "translation": "Where two claims differ, drawing back a little from each position and giving and taking may reach a result that more people can be satisfied with."
    }
   ]
  },
  {
   "type": "figure",
   "text": "돈주머니와 임금 인상을 놓고 악수하는 두 사람 — “올라간 게 조금이겠”, “네!”"
  },
  {
   "type": "section",
   "kind": "feature",
   "text": "한국 대통령과 만난 정상들"
  },
  {
   "type": "paragraph",
   "spans": [
    "2020년 3월 G20 특별 ",
    {
     "word": "정상회의",
     "annotation": "정상회의"
    },
    "는 주요 20개국 ",
    {
     "word": "협의체",
     "annotation": "협의체"
    },
    " 정상들이 ",
    {
     "word": "화상",
     "annotation": "화상"
    },
    "으로 한자리에 모였다. 코로나19 ",
    {
     "word": "대응",
     "annotation": "대응"
    },
    "을 위한 G20 특별 정상회의에서 한국은 ",
    {
     "word": "선제적",
     "annotation": "선제적"
    },
    "이고 ",
    {
     "word": "투명",
     "annotation": "투명"
    },
    "한 ",
    {
     "word": "방역조치",
     "annotation": "방역조치"
    },
    " 활동을 국제사회와 ",
    {
     "word": "공유",
     "annotation": "공유"
    },
    "했다."
   ]
  },
  {
   "type": "figure",
   "text": "화상으로 열린 G20 특별 정상회의 (사진 출처: 청와대)"
  },
  {
   "type": "paragraph",
   "spans": [
    "2019 한-",
    {
     "word": "아세안",
     "annotation": "아세안"
    },
    " 특별 정상회의에 ",
    {
     "word": "참석",
     "annotation": "참석"
    },
    "한 정상들과 ",
    {
     "word": "기념촬영",
     "annotation": "기념촬영"
    },
    " 모습이다. 2019 한-아세안 특별 정상회의 ",
    {
     "word": "공동 의장",
     "annotation": "공동 의장"
    },
    " ",
    {
     "word": "성명",
     "annotation": "성명"
    },
    "에서 정상들은 1988년 한-아세안 ",
    {
     "word": "대화 관계",
     "annotation": "대화 관계"
    },
    " ",
    {
     "word": "수립",
     "annotation": "수립"
    },
    " 이후의 다양한 분야에서의 협력 ",
    {
     "word": "성과",
     "annotation": "성과"
    },
    "를 높이 평가하면서 ",
    {
     "word": "안보",
     "annotation": "안보"
    },
    "·",
    {
     "word": "교역",
     "annotation": "교역"
    },
    "·",
    {
     "word": "첨단 산업",
     "annotation": "첨단 산업"
    },
    "·",
    {
     "word": "인적 교류",
     "annotation": "인적 교류"
    },
    " 등의 분야에서 협력을 ",
    {
     "word": "확대",
     "annotation": "확대"
    },
    "하기로 했다. 기념촬영은 왼쪽부터 말레이시아 총리, 미얀마 ",
    {
     "word": "국가고문",
     "annotation": "국가고문"
    },
    ", 필리핀 대통령, 싱가포르 총리, 태국 총리, 한국의 문재인 대통령, 베트남 총리, 브루나이 국왕, 캄보디아 ",
    {
     "word": "외교장관",
     "annotation": "외교장관"
    },
    ", 인도네시아 대통령, 라오스 총리이다."
   ]
  },
  {
   "type": "figure",
   "text": "2019 한-아세안 특별 정상회의 기념촬영 (사진 출처: 청와대)"
  },
  {
   "type": "paragraph",
   "spans": [
    "2017년 11월 제25차 APEC 정상회의는 베트남 다낭에서 ",
    {
     "word": "개최",
     "annotation": "개최"
    },
    "되었다. 이번 정상회의에는 한국의 문재인 대통령과 미국 트럼프 대통령, 중국 시진핑 ",
    {
     "word": "국가주석",
     "annotation": "국가주석"
    },
    ", 일본 아베 신조 총리, 러시아 블라디미르 푸틴 대통령 등 21개 ",
    {
     "word": "회원국",
     "annotation": "회원국"
    },
    " 정상이 모두 참석했다. 이들 정상은 ‘새로운 ",
    {
     "word": "역동성",
     "annotation": "역동성"
    },
    " ",
    {
     "word": "창조",
     "annotation": "창조"
    },
    ", 함께하는 미래만들기’를 ",
    {
     "word": "주제",
     "annotation": "주제"
    },
    "로 ",
    {
     "word": "지속가능",
     "annotation": "지속가능"
    },
    "하고 ",
    {
     "word": "혁신적",
     "annotation": "혁신적"
    },
    "이며 ",
    {
     "word": "포용적",
     "annotation": "포용적"
    },
    " ",
    {
     "word": "성장",
     "annotation": "성장"
    },
    " ",
    {
     "word": "증진",
     "annotation": "증진"
    },
    "과 ",
    {
     "word": "역내",
     "annotation": "역내"
    },
    " ",
    {
     "word": "경제통합",
     "annotation": "경제통합"
    },
    " 등을 ",
    {
     "word": "집중적",
     "annotation": "집중적"
    },
    "으로 논의했다."
   ]
  },
  {
   "type": "figure",
   "text": "제25차 APEC 정상회의 (사진 출처: 청와대)"
  }
 ],
 "annotations": {
  "다수결": {
   "headword": "다수결",
   "hanja": "多數決",
   "meaning": "a decision by majority",
   "characters": [
    {
     "char": "多",
     "reading": "다",
     "gloss": "many — as in 다양, 다문화"
    },
    {
     "char": "數",
     "reading": "수",
     "gloss": "number — as in 과반수, 횟수"
    },
    {
     "char": "決",
     "reading": "결",
     "gloss": "to decide — as in 결정, 판결"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "포용": {
   "headword": "포용",
   "hanja": "包容",
   "meaning": "embracing, accepting",
   "characters": [
    {
     "char": "包",
     "reading": "포",
     "gloss": "to wrap, to include — as in 포함"
    },
    {
     "char": "容",
     "reading": "용",
     "gloss": "to contain, to allow — as in 허용, 내용"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "관용": {
   "headword": "관용",
   "hanja": "寬容",
   "meaning": "tolerance",
   "characters": [
    {
     "char": "寬",
     "reading": "관",
     "gloss": "broad, lenient"
    },
    {
     "char": "容",
     "reading": "용",
     "gloss": "to allow — the same 容 as in 포용"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "다양성": {
   "headword": "다양성",
   "hanja": "多樣性",
   "meaning": "diversity, plurality",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "전제": {
   "headword": "전제",
   "hanja": "前提",
   "meaning": "a premise, a precondition",
   "characters": [
    {
     "char": "前",
     "reading": "전",
     "gloss": "before — as in 사전 투표, 전주"
    },
    {
     "char": "提",
     "reading": "제",
     "gloss": "to put forward — as in 제시, 제출"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "소수자": {
   "headword": "소수자",
   "hanja": "少數者",
   "meaning": "a member of a minority",
   "characters": [
    {
     "char": "少",
     "reading": "소",
     "gloss": "few — as in 소년, 감소"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "탄압": {
   "headword": "탄압",
   "hanja": "彈壓",
   "meaning": "oppression, suppression",
   "characters": [
    {
     "char": "彈",
     "reading": "탄",
     "gloss": "to flick, a bullet — as in 폭탄"
    },
    {
     "char": "壓",
     "reading": "압",
     "gloss": "to press — as in 압력, 압수"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "소외": {
   "headword": "소외",
   "hanja": "疏外",
   "meaning": "exclusion, alienation",
   "characters": [
    {
     "char": "疏",
     "reading": "소",
     "gloss": "sparse, distant — as in 의사소통"
    },
    {
     "char": "外",
     "reading": "외",
     "gloss": "outside — as in 외국, 제외"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "더불어": {
   "headword": "더불어",
   "hanja": null,
   "meaning": "together with, alongside",
   "characters": [],
   "notes": [
    "더불어 살다 “to live alongside others” — the phrase the textbook keeps returning to. Also the 더불어 of 더불어민주당."
   ],
   "surfaces": []
  },
  "보장": {
   "headword": "보장",
   "hanja": "保障",
   "meaning": "guarantee",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "요소": {
   "headword": "요소",
   "hanja": "要素",
   "meaning": "an element, a factor",
   "characters": [
    {
     "char": "要",
     "reading": "요",
     "gloss": "necessary — as in 중요, 필요"
    },
    {
     "char": "素",
     "reading": "소",
     "gloss": "element, plain — as in 소재"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "논의": {
   "headword": "논의",
   "hanja": "論議",
   "meaning": "discussion",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "토론": {
   "headword": "토론",
   "hanja": "討論",
   "meaning": "debate",
   "characters": [
    {
     "char": "討",
     "reading": "토",
     "gloss": "to discuss, to attack — as in 검토"
    },
    {
     "char": "論",
     "reading": "론",
     "gloss": "to argue — as in 논의, 이론"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "옳음": {
   "headword": "옳음",
   "hanja": null,
   "meaning": "being right, rightness",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "내세우다": {
   "headword": "내세우다",
   "hanja": null,
   "meaning": "to put forward, to assert",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "받아들이다": {
   "headword": "받아들이다",
   "hanja": null,
   "meaning": "to accept, to take in",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "상대방": {
   "headword": "상대방",
   "hanja": "相對方",
   "meaning": "the other party",
   "characters": [
    {
     "char": "相",
     "reading": "상",
     "gloss": "mutual — as in 상속, 수상"
    },
    {
     "char": "對",
     "reading": "대",
     "gloss": "against, facing — as in 대비, 반대"
    },
    {
     "char": "方",
     "reading": "방",
     "gloss": "side, direction — as in 방법, 지방"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "제3자": {
   "headword": "제3자",
   "hanja": "第三者",
   "meaning": "a third party",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "설득": {
   "headword": "설득",
   "hanja": "說得",
   "meaning": "persuasion",
   "characters": [
    {
     "char": "說",
     "reading": "설",
     "gloss": "to explain — as in 설명, 소설"
    },
    {
     "char": "得",
     "reading": "득",
     "gloss": "to obtain — as in 득표율, 소득"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "양보": {
   "headword": "양보",
   "hanja": "讓步",
   "meaning": "yielding, giving way",
   "characters": [
    {
     "char": "讓",
     "reading": "양",
     "gloss": "to yield, to concede"
    },
    {
     "char": "步",
     "reading": "보",
     "gloss": "a step — as in 산책's 보행, 진보"
    }
   ],
   "notes": [
    "The word on the priority-seat signs: 양보해 주세요."
   ],
   "surfaces": []
  },
  "협의": {
   "headword": "협의",
   "hanja": "協議",
   "meaning": "consultation, coming to terms",
   "characters": [
    {
     "char": "協",
     "reading": "협",
     "gloss": "to cooperate — as in 협력, 협의체"
    },
    {
     "char": "議",
     "reading": "의",
     "gloss": "to deliberate — as in 회의, 의논"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "타협": {
   "headword": "타협",
   "hanja": "妥協",
   "meaning": "compromise",
   "characters": [
    {
     "char": "妥",
     "reading": "타",
     "gloss": "peaceful, settled"
    },
    {
     "char": "協",
     "reading": "협",
     "gloss": "to cooperate — the same 協 as in 협의"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "의사 결정": {
   "headword": "의사 결정",
   "hanja": "意思決定",
   "meaning": "decision-making",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "합의": {
   "headword": "합의",
   "hanja": "合意",
   "meaning": "agreement, consensus",
   "characters": [
    {
     "char": "合",
     "reading": "합",
     "gloss": "to join — as in 결합, 통합"
    },
    {
     "char": "意",
     "reading": "의",
     "gloss": "intention — as in 동의, 의견"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "입장": {
   "headword": "입장",
   "hanja": "立場",
   "meaning": "a position, a standpoint",
   "characters": [
    {
     "char": "立",
     "reading": "립",
     "gloss": "to stand — as in 입법, 독립"
    },
    {
     "char": "場",
     "reading": "장",
     "gloss": "place — as in 장면, 시장"
    }
   ],
   "notes": [
    "Not the 입장 “entry” (入場) of 입장료."
   ],
   "surfaces": []
  },
  "물러나다": {
   "headword": "물러나다",
   "hanja": null,
   "meaning": "to step back, to withdraw",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "만족": {
   "headword": "만족",
   "hanja": "滿足",
   "meaning": "satisfaction",
   "characters": [
    {
     "char": "滿",
     "reading": "만",
     "gloss": "full — as in 만원, 만점"
    },
    {
     "char": "足",
     "reading": "족",
     "gloss": "foot, enough — as in 부족, 충족"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "정상회의": {
   "headword": "정상회의",
   "hanja": "頂上會議",
   "meaning": "a summit",
   "characters": [
    {
     "char": "頂",
     "reading": "정",
     "gloss": "summit, top"
    },
    {
     "char": "上",
     "reading": "상",
     "gloss": "above — as in 상원, 이상"
    }
   ],
   "notes": [
    "정상 here is the peak, hence the heads of state — not the 정상 “normal” (正常) of 정상적."
   ],
   "surfaces": []
  },
  "협의체": {
   "headword": "협의체",
   "hanja": "協議體",
   "meaning": "a consultative body",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "화상": {
   "headword": "화상",
   "hanja": "畫像",
   "meaning": "video, a screen image",
   "characters": [],
   "notes": [
    "화상 회의 is a video conference. A different 화상 (火傷) is a burn."
   ],
   "surfaces": []
  },
  "대응": {
   "headword": "대응",
   "hanja": "對應",
   "meaning": "a response, countermeasures",
   "characters": [
    {
     "char": "應",
     "reading": "응",
     "gloss": "to respond — as in 응답, 적응"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "선제적": {
   "headword": "선제적",
   "hanja": "先制的",
   "meaning": "pre-emptive",
   "characters": [
    {
     "char": "先",
     "reading": "선",
     "gloss": "first — as in 선생, 우선"
    },
    {
     "char": "制",
     "reading": "제",
     "gloss": "to control — as in 제도, 통제"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "투명": {
   "headword": "투명",
   "hanja": "透明",
   "meaning": "transparency",
   "characters": [
    {
     "char": "透",
     "reading": "투",
     "gloss": "to penetrate — as in 투과"
    },
    {
     "char": "明",
     "reading": "명",
     "gloss": "bright, clear — as in 설명, 분명"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "방역조치": {
   "headword": "방역조치",
   "hanja": "防疫措置",
   "meaning": "disease-control measures",
   "characters": [
    {
     "char": "防",
     "reading": "방",
     "gloss": "to defend — as in 예방, 방지"
    },
    {
     "char": "疫",
     "reading": "역",
     "gloss": "epidemic — as in 검역, 면역"
    },
    {
     "char": "措",
     "reading": "조",
     "gloss": "to arrange, to take (a step)"
    },
    {
     "char": "置",
     "reading": "치",
     "gloss": "to place — as in 설치, 위치"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "공유": {
   "headword": "공유",
   "hanja": "共有",
   "meaning": "sharing",
   "characters": [
    {
     "char": "共",
     "reading": "공",
     "gloss": "together — as in 공동, 공공"
    },
    {
     "char": "有",
     "reading": "유",
     "gloss": "to have — as in 유권자, 소유"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "아세안": {
   "headword": "아세안",
   "hanja": null,
   "meaning": "ASEAN",
   "characters": [],
   "notes": [
    "동남아시아국가연합 — the ten states of Southeast Asia. Korea opened dialogue relations with them in 1988."
   ],
   "surfaces": []
  },
  "참석": {
   "headword": "참석",
   "hanja": "參席",
   "meaning": "attendance, taking part",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "기념촬영": {
   "headword": "기념촬영",
   "hanja": "紀念撮影",
   "meaning": "a commemorative photograph",
   "characters": [
    {
     "char": "紀",
     "reading": "기",
     "gloss": "record, era — as in 세기"
    },
    {
     "char": "念",
     "reading": "념",
     "gloss": "thought — as in 개념, 이념"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "공동 의장": {
   "headword": "공동 의장",
   "hanja": "共同議長",
   "meaning": "a co-chair",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "성명": {
   "headword": "성명",
   "hanja": "聲明",
   "meaning": "a statement, a declaration",
   "characters": [
    {
     "char": "聲",
     "reading": "성",
     "gloss": "voice, sound — as in 음성"
    },
    {
     "char": "明",
     "reading": "명",
     "gloss": "to make clear — as in 투명, 설명"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "대화 관계": {
   "headword": "대화 관계",
   "hanja": "對話關係",
   "meaning": "dialogue relations",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "수립": {
   "headword": "수립",
   "hanja": "樹立",
   "meaning": "establishment (of relations, a plan)",
   "characters": [
    {
     "char": "樹",
     "reading": "수",
     "gloss": "tree, to plant"
    },
    {
     "char": "立",
     "reading": "립",
     "gloss": "to set up — as in 입장, 설립"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "성과": {
   "headword": "성과",
   "hanja": "成果",
   "meaning": "an achievement, results",
   "characters": [
    {
     "char": "成",
     "reading": "성",
     "gloss": "to accomplish — as in 성장, 구성"
    },
    {
     "char": "果",
     "reading": "과",
     "gloss": "fruit, result — as in 결과, 효과"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "안보": {
   "headword": "안보",
   "hanja": "安保",
   "meaning": "security",
   "characters": [],
   "notes": [
    "Short for 안전 보장. 국가 안보 is national security."
   ],
   "surfaces": []
  },
  "교역": {
   "headword": "교역",
   "hanja": "交易",
   "meaning": "trade",
   "characters": [
    {
     "char": "交",
     "reading": "교",
     "gloss": "to exchange — as in 외교, 교통"
    },
    {
     "char": "易",
     "reading": "역",
     "gloss": "to trade, easy — as in 무역"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "첨단 산업": {
   "headword": "첨단 산업",
   "hanja": "尖端産業",
   "meaning": "high-technology industry",
   "characters": [
    {
     "char": "尖",
     "reading": "첨",
     "gloss": "pointed, sharp"
    },
    {
     "char": "端",
     "reading": "단",
     "gloss": "end, tip — as in 단서"
    }
   ],
   "notes": [
    "첨단 is literally the sharp tip — the leading edge."
   ],
   "surfaces": []
  },
  "인적 교류": {
   "headword": "인적 교류",
   "hanja": "人的交流",
   "meaning": "people-to-people exchange",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "확대": {
   "headword": "확대",
   "hanja": "擴大",
   "meaning": "expansion",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "국가고문": {
   "headword": "국가고문",
   "hanja": "國家顧問",
   "meaning": "State Counsellor",
   "characters": [],
   "notes": [
    "Myanmar's office held by Aung San Suu Kyi at the time; abolished after the 2021 coup."
   ],
   "surfaces": []
  },
  "외교장관": {
   "headword": "외교장관",
   "hanja": "外交長官",
   "meaning": "a foreign minister",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "개최": {
   "headword": "개최",
   "hanja": "開催",
   "meaning": "holding (an event)",
   "characters": [
    {
     "char": "開",
     "reading": "개",
     "gloss": "to open — as in 공개, 개방"
    },
    {
     "char": "催",
     "reading": "최",
     "gloss": "to urge, to hold"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "국가주석": {
   "headword": "국가주석",
   "hanja": "國家主席",
   "meaning": "the President of China",
   "characters": [
    {
     "char": "主",
     "reading": "주",
     "gloss": "main — as in 주권, 주인"
    },
    {
     "char": "席",
     "reading": "석",
     "gloss": "seat — as in 출석, 좌석"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "회원국": {
   "headword": "회원국",
   "hanja": "會員國",
   "meaning": "a member state",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "역동성": {
   "headword": "역동성",
   "hanja": "力動性",
   "meaning": "dynamism",
   "characters": [
    {
     "char": "力",
     "reading": "력",
     "gloss": "force — as in 능력, 권력"
    },
    {
     "char": "動",
     "reading": "동",
     "gloss": "to move — as in 운동, 활동"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "창조": {
   "headword": "창조",
   "hanja": "創造",
   "meaning": "creation",
   "characters": [
    {
     "char": "創",
     "reading": "창",
     "gloss": "to originate — as in 창의, 창업"
    },
    {
     "char": "造",
     "reading": "조",
     "gloss": "to make — as in 제조, 구조"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "주제": {
   "headword": "주제",
   "hanja": "主題",
   "meaning": "a theme, a subject",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "지속가능": {
   "headword": "지속가능",
   "hanja": "持續可能",
   "meaning": "sustainable",
   "characters": [
    {
     "char": "持",
     "reading": "지",
     "gloss": "to hold — as in 유지, 지지"
    },
    {
     "char": "續",
     "reading": "속",
     "gloss": "to continue — as in 계속, 상속"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "혁신적": {
   "headword": "혁신적",
   "hanja": "革新的",
   "meaning": "innovative",
   "characters": [
    {
     "char": "革",
     "reading": "혁",
     "gloss": "leather, to reform — as in 개혁"
    },
    {
     "char": "新",
     "reading": "신",
     "gloss": "new — as in 신문, 최신"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "포용적": {
   "headword": "포용적",
   "hanja": "包容的",
   "meaning": "inclusive",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "성장": {
   "headword": "성장",
   "hanja": "成長",
   "meaning": "growth",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "증진": {
   "headword": "증진",
   "hanja": "增進",
   "meaning": "promotion, furthering",
   "characters": [
    {
     "char": "增",
     "reading": "증",
     "gloss": "to increase — as in 증가"
    },
    {
     "char": "進",
     "reading": "진",
     "gloss": "to advance — as in 진행, 진출"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "역내": {
   "headword": "역내",
   "hanja": "域內",
   "meaning": "within the region",
   "characters": [
    {
     "char": "域",
     "reading": "역",
     "gloss": "region — as in 지역, 광역"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "경제통합": {
   "headword": "경제통합",
   "hanja": "經濟統合",
   "meaning": "economic integration",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "집중적": {
   "headword": "집중적",
   "hanja": "集中的",
   "meaning": "intensive, concentrated",
   "characters": [
    {
     "char": "集",
     "reading": "집",
     "gloss": "to gather — as in 집회 “a rally”"
    },
    {
     "char": "中",
     "reading": "중",
     "gloss": "middle — as in 중심, 집중"
    }
   ],
   "notes": [],
   "surfaces": []
  }
 },
 "notes": [
  {
   "why": "The crossword grid is not reproduced; its clues are, with the answers covered. Those answers, and the answers to the 종합 평가, are mine — worked out from the chapters. The book keeps its own in 정답보기 on p. 262, which is not photographed."
  },
  {
   "why": "The 〈보기〉 boxes of questions 04 to 06 are set as quoted lines, which is how the book boxes them. Question 04's stem names ㉠ and ㉡ while its box is labelled ㄱ and ㄴ; that is the book's own slip and stands as printed."
  },
  {
   "why": "The three summit notes on p. 133 are left untranslated, as the 알아두면 좋아요 boxes are."
  }
 ],
 "slug": "part-4",
 "part": true
});
