/* Generated by tools/build.py — do not edit.
   Content lives in tools/chapters/pt06_law.py; rebuild after changing it. */

KIIP.chapter({
 "number": 6,
 "unit": "법",
 "title": "대단원 마무리",
 "titleEnglish": "Closing the part",
 "chapterGlossary": [],
 "blocks": [
  {
   "type": "section",
   "kind": "summary",
   "text": "대단원 정리"
  },
  {
   "type": "table",
   "rows": [
    [
     "법치국가 대한민국",
     "치안과 준법이 잘 갖춰진 나라, 법을 잘 지키는 나라, 외국인의 권리와 의무"
    ],
    [
     "한국에 정착하기",
     "비자, 단기체류, 장기체류, 재한외국인처우기본법, 외국인을 위한 제도"
    ],
    [
     "한국인 되기",
     "대한민국의 국적, 속인주의, 일반귀화, 간이귀화, 특별귀화"
    ],
    [
     "가족와 법",
     "부부의 권리와 의무, 가정폭력과 이혼"
    ],
    [
     "재산과 법",
     "계약, 차용증과 영수증, 부동산과 등기부등본"
    ],
    [
     "생활 법률",
     "경범죄, 안전수칙, 쓰레기 무단투기, 무단횡단, 음주운전, 학교폭력"
    ],
    [
     "범죄와 법",
     "형법, 죄형법정주의, 경찰과 검찰의 역할"
    ],
    [
     "권리 보호와 법",
     "재판과 분쟁해결, 공정한 재판, 대안적 분쟁해결제도, 권리 보호 기관"
    ]
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "찾아볼 곳"
  },
  {
   "type": "bullet",
   "spans": [
    "법무부 — http://www.moj.go.kr/"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "한국법교육센터 — http://www.lawedu.or.kr/"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "법사랑 사이버랜드 — http://www.lawnorder.go.kr/"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "대한법률구조공단 — www.klac.or.kr"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "법무부(2019). 『한국인의 법과 생활: 일반인들이 알아야 할 생활법률 가이드북』. 법무부."
   ]
  },
  {
   "type": "section",
   "kind": "quiz",
   "text": "가로 세로 퀴즈"
  },
  {
   "type": "crossword",
   "cols": 10,
   "rows": 10,
   "entries": [
    {
     "label": "㉮",
     "dir": "across",
     "x": 2,
     "y": 1,
     "answer": "재한외국인처우",
     "cells": [
      [
       2,
       1
      ],
      [
       3,
       1
      ],
      [
       4,
       1
      ],
      [
       5,
       1
      ],
      [
       6,
       1
      ],
      [
       7,
       1
      ],
      [
       8,
       1
      ]
     ]
    },
    {
     "label": "㉯",
     "dir": "across",
     "x": 1,
     "y": 4,
     "answer": "간이",
     "cells": [
      [
       1,
       4
      ],
      [
       2,
       4
      ]
     ]
    },
    {
     "label": "㉰",
     "dir": "across",
     "x": 7,
     "y": 4,
     "answer": "법치주의",
     "cells": [
      [
       7,
       4
      ],
      [
       8,
       4
      ],
      [
       9,
       4
      ],
      [
       10,
       4
      ]
     ]
    },
    {
     "label": "㉱",
     "dir": "across",
     "x": 2,
     "y": 5,
     "answer": "혼인신고",
     "cells": [
      [
       2,
       5
      ],
      [
       3,
       5
      ],
      [
       4,
       5
      ],
      [
       5,
       5
      ]
     ]
    },
    {
     "label": "㉲",
     "dir": "across",
     "x": 9,
     "y": 7,
     "answer": "임차",
     "cells": [
      [
       9,
       7
      ],
      [
       10,
       7
      ]
     ]
    },
    {
     "label": "㉳",
     "dir": "across",
     "x": 1,
     "y": 8,
     "answer": "국가인권위원회",
     "cells": [
      [
       1,
       8
      ],
      [
       2,
       8
      ],
      [
       3,
       8
      ],
      [
       4,
       8
      ],
      [
       5,
       8
      ],
      [
       6,
       8
      ],
      [
       7,
       8
      ]
     ]
    },
    {
     "label": "㉴",
     "dir": "across",
     "x": 8,
     "y": 9,
     "answer": "영수증",
     "cells": [
      [
       8,
       9
      ],
      [
       9,
       9
      ],
      [
       10,
       9
      ]
     ]
    },
    {
     "label": "①",
     "dir": "down",
     "x": 2,
     "y": 1,
     "answer": "재판상이혼",
     "cells": [
      [
       2,
       1
      ],
      [
       2,
       2
      ],
      [
       2,
       3
      ],
      [
       2,
       4
      ],
      [
       2,
       5
      ]
     ]
    },
    {
     "label": "②",
     "dir": "down",
     "x": 5,
     "y": 1,
     "answer": "국적",
     "cells": [
      [
       5,
       1
      ],
      [
       5,
       2
      ]
     ]
    },
    {
     "label": "③",
     "dir": "down",
     "x": 7,
     "y": 3,
     "answer": "준법정신",
     "cells": [
      [
       7,
       3
      ],
      [
       7,
       4
      ],
      [
       7,
       5
      ],
      [
       7,
       6
      ]
     ]
    },
    {
     "label": "④",
     "dir": "down",
     "x": 10,
     "y": 1,
     "answer": "세계인의날",
     "cells": [
      [
       10,
       1
      ],
      [
       10,
       2
      ],
      [
       10,
       3
      ],
      [
       10,
       4
      ],
      [
       10,
       5
      ]
     ]
    },
    {
     "label": "⑤",
     "dir": "down",
     "x": 3,
     "y": 7,
     "answer": "속인주의",
     "cells": [
      [
       3,
       7
      ],
      [
       3,
       8
      ],
      [
       3,
       9
      ],
      [
       3,
       10
      ]
     ]
    },
    {
     "label": "⑥",
     "dir": "down",
     "x": 5,
     "y": 8,
     "answer": "위자료",
     "cells": [
      [
       5,
       8
      ],
      [
       5,
       9
      ],
      [
       5,
       10
      ]
     ]
    },
    {
     "label": "⑦",
     "dir": "down",
     "x": 10,
     "y": 7,
     "answer": "차용증",
     "cells": [
      [
       10,
       7
      ],
      [
       10,
       8
      ],
      [
       10,
       9
      ]
     ]
    }
   ],
   "grid": [
    [
     null,
     {
      "answer": "재",
      "labels": [
       "㉮",
       "①"
      ]
     },
     {
      "answer": "한",
      "labels": []
     },
     {
      "answer": "외",
      "labels": []
     },
     {
      "answer": "국",
      "labels": [
       "②"
      ]
     },
     {
      "answer": "인",
      "labels": []
     },
     {
      "answer": "처",
      "labels": []
     },
     {
      "answer": "우",
      "labels": []
     },
     null,
     {
      "answer": "세",
      "labels": [
       "④"
      ]
     }
    ],
    [
     null,
     {
      "answer": "판",
      "labels": []
     },
     null,
     null,
     {
      "answer": "적",
      "labels": []
     },
     null,
     null,
     null,
     null,
     {
      "answer": "계",
      "labels": []
     }
    ],
    [
     null,
     {
      "answer": "상",
      "labels": []
     },
     null,
     null,
     null,
     null,
     {
      "answer": "준",
      "labels": [
       "③"
      ]
     },
     null,
     null,
     {
      "answer": "인",
      "labels": []
     }
    ],
    [
     {
      "answer": "간",
      "labels": [
       "㉯"
      ]
     },
     {
      "answer": "이",
      "labels": []
     },
     null,
     null,
     null,
     null,
     {
      "answer": "법",
      "labels": [
       "㉰"
      ]
     },
     {
      "answer": "치",
      "labels": []
     },
     {
      "answer": "주",
      "labels": []
     },
     {
      "answer": "의",
      "labels": []
     }
    ],
    [
     null,
     {
      "answer": "혼",
      "labels": [
       "㉱"
      ]
     },
     {
      "answer": "인",
      "labels": []
     },
     {
      "answer": "신",
      "labels": []
     },
     {
      "answer": "고",
      "labels": []
     },
     null,
     {
      "answer": "정",
      "labels": []
     },
     null,
     null,
     {
      "answer": "날",
      "labels": []
     }
    ],
    [
     null,
     null,
     null,
     null,
     null,
     null,
     {
      "answer": "신",
      "labels": []
     },
     null,
     null,
     null
    ],
    [
     null,
     null,
     {
      "answer": "속",
      "labels": [
       "⑤"
      ]
     },
     null,
     null,
     null,
     null,
     null,
     {
      "answer": "임",
      "labels": [
       "㉲"
      ]
     },
     {
      "answer": "차",
      "labels": [
       "⑦"
      ]
     }
    ],
    [
     {
      "answer": "국",
      "labels": [
       "㉳"
      ]
     },
     {
      "answer": "가",
      "labels": []
     },
     {
      "answer": "인",
      "labels": []
     },
     {
      "answer": "권",
      "labels": []
     },
     {
      "answer": "위",
      "labels": [
       "⑥"
      ]
     },
     {
      "answer": "원",
      "labels": []
     },
     {
      "answer": "회",
      "labels": []
     },
     null,
     null,
     {
      "answer": "용",
      "labels": []
     }
    ],
    [
     null,
     null,
     {
      "answer": "주",
      "labels": []
     },
     null,
     {
      "answer": "자",
      "labels": []
     },
     null,
     null,
     {
      "answer": "영",
      "labels": [
       "㉴"
      ]
     },
     {
      "answer": "수",
      "labels": []
     },
     {
      "answer": "증",
      "labels": []
     }
    ],
    [
     null,
     null,
     {
      "answer": "의",
      "labels": []
     },
     null,
     {
      "answer": "료",
      "labels": []
     },
     null,
     null,
     null,
     null,
     null
    ]
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "가로 열쇠"
  },
  {
   "type": "bullet",
   "spans": [
    "㉮ 2007년 한국에서는 외국인들의 적응을 돕고 처우를 개선하고자 ○○○○○○○기본법을 만듦 ",
    {
     "blank": "재한외국인처우"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "㉯ 귀화에는 일반귀화, ○○귀화, 특별귀화가 있다 ",
    {
     "blank": "간이"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "㉰ 법에 따라 나라를 다스리고 운영하는 것 ",
    {
     "blank": "법치주의"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "㉱ 법적 부부로 인정받으려면 ○○○○를 해야 한다 ",
    {
     "blank": "혼인 신고"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "㉲ 부동산을 빌려쓰는 것, 임대의 반대말 ",
    {
     "blank": "임차"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "㉳ 한국에서 모든 사람들의 인권을 보호하기 위해 만든 국가기관 ",
    {
     "blank": "국가인권위원회"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "㉴ 돈이나 물품 등을 받았음을 증명하는 문서 ",
    {
     "blank": "영수증"
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "세로 열쇠"
  },
  {
   "type": "bullet",
   "spans": [
    "① 법원에 소송을 제기하여 판결을 통해 이혼하는 것 ",
    {
     "blank": "재판상 이혼"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "② 한 사람이 특정한 국가의 구성원으로 공식적으로 인정받는 자격 ",
    {
     "blank": "국적"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "③ 법을 잘 지키려는 정신 ",
    {
     "blank": "준법 정신"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "④ 국민과 재한외국인이 서로 존중하며 살 것을 기념하는 날, 매년 5월 20일 ",
    {
     "blank": "세계인의 날"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "⑤ 국적을 부여할 때 태어난 아이의 부모를 중시하는 것, 태어난 장소를 중시하는 것을 속지주의라고 함 ",
    {
     "blank": "속인주의"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "⑥ 이혼에 책임이 있는 배우자는 상대방에게 ○○○를 지급해야 한다 ",
    {
     "blank": "위자료"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "⑦ 남의 돈이나 물건을 빌린 것을 증명하는 문서 ",
    {
     "blank": "차용증"
    }
   ]
  },
  {
   "type": "section",
   "kind": "exam",
   "text": "단원 종합 평가"
  },
  {
   "type": "heading",
   "level": 4,
   "text": "01 두 사례의 밑줄 친 (가)에 공통적으로 들어갈 내용으로 가장 적절한 것은?"
  },
  {
   "type": "paragraph",
   "spans": [
    "좋은 법이 있다고 해도 국민들이 지키지 않는다면 법이 기능할 수 없다. 따라서 법이 제 역할을 할 수 있도록 하기 위해서는 국민들이 (가)"
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "한국에서는 법을 통해 외국인의 권리와 의무를 규정하고 있다. 따라서 외국인들 역시 (가)"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "① 직접 법을 제정해야 한다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "② 법을 지키는 것이 중요하다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "③ 처벌의 강도를 높여야 한다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "④ 국민권익위원회를 잘 이용해야 한다."
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "정답 ",
    {
     "blank": "②"
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "02 〈보기〉에서 설명하는 귀화 방식으로 알맞은 것은?"
  },
  {
   "type": "bullet",
   "spans": [
    "대한민국과 아무런 혈연적, 지연적 관계가 없는 외국인이 한국 국적을 취득하는 절차"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "한국에서 5년 이상 생활한 주소가 있고, 민법상 만 19세 이상 성인이어야 가능함"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "품행이 단정하고, 생계 유지 능력이 있으며, 국민으로서의 기본 소양을 갖추어야 함"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "① 영주권"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "② 간이귀화"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "③ 특별귀화"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "④ 일반귀화"
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "정답 ",
    {
     "blank": "④"
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "03 한국에서의 가족 관계 관련 법적 내용에 대한 옳은 설명을 〈보기〉에서 모두 고른 것은?"
  },
  {
   "type": "bullet",
   "spans": [
    "ㄱ. 결혼식을 하면 법적 부부로 인정받을 수 있다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "ㄴ. 부부는 각자 자신의 재산을 소유하고 관리할 수 있다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "ㄷ. 가정 폭력은 가족들 간의 문제로 국가가 개입하지 않는다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "ㄹ. 이혼을 할 경우 자녀를 키우는 쪽은 상대방에게 자녀 양육 비용을 요구할 수 있다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "① ㄱ, ㄷ"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "② ㄱ, ㄹ"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "③ ㄴ, ㄷ"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "④ ㄴ, ㄹ"
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "정답 ",
    {
     "blank": "④"
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "04 ㉠에 들어갈 법으로 옳은 것은?"
  },
  {
   "type": "bullet",
   "spans": [
    "한국에서는 2007년 ㉠을 제정하여 외국인에 대한 차별 금지 및 외국인의 사회 적응을 돕고 있다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "㉠에 따라 매년 5월 20일을 세계인의 날로 정하여 운영하고 있다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "① 민법"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "② 형법"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "③ 헌법"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "④ 재한외국인처우기본법"
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "정답 ",
    {
     "blank": "④"
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "05 (가), (나) 사례에 대한 설명으로 옳은 것은?"
  },
  {
   "type": "paragraph",
   "spans": [
    "(가) 최근 일어난 살인 사건에 대해 경찰은 범죄용의자를 체포하여 수사하고 있습니다. 조만간 재판을 받고 법에 따라 처벌될 것으로 예상됩니다."
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "(나) ○○ 지역에서는 아파트 층간 소음 문제로 피해를 받은 측에서 소송을 걸었습니다. 법에 따라 어떤 판결이 내려질지 기대됩니다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "① (가)에 제시된 재판은 민사재판이다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "② (가)에서는 검찰이 직접 재판에 참여한다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "③ (나)는 가정법원에서 재판을 진행한다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "④ (나)의 재판에서는 범죄 여부와 형벌의 종류를 결정한다."
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "정답 ",
    {
     "blank": "②"
    }
   ]
  },
  {
   "type": "section",
   "kind": "feature",
   "text": "법 관련 기관 이야기"
  },
  {
   "type": "heading",
   "level": 4,
   "text": "출입국·외국인청"
  },
  {
   "type": "paragraph",
   "spans": [
    "법무부 소속으로 내외국인의 출입국 심사, 국적 취득, 비자 발급 등과 관련된 업무를 담당한다."
   ],
   "translation": "Part of the Ministry of Justice, it handles the work to do with immigration control for Koreans and foreigners alike, the acquisition of nationality and the issue of visas.",
   "sentences": [
    {
     "spans": [
      "법무부 소속으로 내외국인의 출입국 심사, 국적 취득, 비자 발급 등과 관련된 업무를 담당한다."
     ],
     "translation": "Part of the Ministry of Justice, it handles the work to do with immigration control for Koreans and foreigners alike, the acquisition of nationality and the issue of visas."
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "대법원"
  },
  {
   "type": "paragraph",
   "spans": [
    "대법원은 한국 최고의 법원으로 심급제도에서 마지막 재판을 담당한다."
   ],
   "translation": "The Supreme Court is Korea’s highest court and hears the final trial in the system of instances.",
   "sentences": [
    {
     "spans": [
      "대법원은 한국 최고의 법원으로 심급제도에서 마지막 재판을 담당한다."
     ],
     "translation": "The Supreme Court is Korea’s highest court and hears the final trial in the system of instances."
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "행정복지센터"
  },
  {
   "type": "paragraph",
   "spans": [
    "행정복지센터는 과거 동사무소, 동주민센터로 불리던 것이 2016년부터 이름이 바뀌었다. 주민 자치와 주민 복리를 위한 행정을 담당하고 있다."
   ],
   "translation": "The community service centre is what used to be called the 동사무소 or 동주민센터; the name changed in 2016. It handles the administration of local self-government and residents’ welfare.",
   "sentences": [
    {
     "spans": [
      "행정복지센터는 과거 동사무소, 동주민센터로 불리던 것이 2016년부터 이름이 바뀌었다. "
     ],
     "translation": "The community service centre is what used to be called the 동사무소 or 동주민센터; the name changed in 2016."
    },
    {
     "spans": [
      "주민 자치와 주민 복리를 위한 행정을 담당하고 있다."
     ],
     "translation": "It handles the administration of local self-government and residents’ welfare."
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "대한법률구조공단"
  },
  {
   "type": "paragraph",
   "spans": [
    "대한법률구조공단은 경제적으로 어렵거나 법을 모르기 때문에 법의 보호를 충분히 받지 못하는 사람들을 위해 법률에 관한 각종 지원을 담당한다."
   ],
   "translation": "The Korea Legal Aid Corporation handles every kind of legal support for those who do not have the full protection of the law because they are in financial difficulty or do not know the law.",
   "sentences": [
    {
     "spans": [
      "대한법률구조공단은 경제적으로 어렵거나 법을 모르기 때문에 법의 보호를 충분히 받지 못하는 사람들을 위해 법률에 관한 각종 지원을 담당한다."
     ],
     "translation": "The Korea Legal Aid Corporation handles every kind of legal support for those who do not have the full protection of the law because they are in financial difficulty or do not know the law."
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "경찰서"
  },
  {
   "type": "paragraph",
   "spans": [
    "경찰서는 각 지역에서 경찰 행정을 맡아 하는 관청이다. 경찰서 밑에는 지구대 및 파출소가 있어서 공공질서를 지키는 역할을 수행한다."
   ],
   "translation": "A police station is the office that carries out police administration in each area. Under it are the district units and the local posts, which do the work of keeping public order.",
   "sentences": [
    {
     "spans": [
      "경찰서는 각 지역에서 경찰 행정을 맡아 하는 관청이다. "
     ],
     "translation": "A police station is the office that carries out police administration in each area."
    },
    {
     "spans": [
      "경찰서 밑에는 지구대 및 파출소가 있어서 공공질서를 지키는 역할을 수행한다."
     ],
     "translation": "Under it are the district units and the local posts, which do the work of keeping public order."
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "검찰청"
  },
  {
   "type": "paragraph",
   "spans": [
    "검찰청은 범죄수사, 공소 제기 등 검사의 사무를 총괄하는 행정기관이다. 대검찰청과 고등검찰청, 지방검찰청이 있다."
   ],
   "translation": "The prosecution service is the administrative body that oversees prosecutors’ work — investigating crime, bringing charges and so on. There is the Supreme Prosecutors’ Office, the high prosecutors’ offices and the district prosecutors’ offices.",
   "sentences": [
    {
     "spans": [
      "검찰청은 범죄수사, 공소 제기 등 검사의 사무를 총괄하는 행정기관이다. "
     ],
     "translation": "The prosecution service is the administrative body that oversees prosecutors’ work — investigating crime, bringing charges and so on."
    },
    {
     "spans": [
      "대검찰청과 고등검찰청, 지방검찰청이 있다."
     ],
     "translation": "There is the Supreme Prosecutors’ Office, the high prosecutors’ offices and the district prosecutors’ offices."
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "국가인권위원회"
  },
  {
   "type": "paragraph",
   "spans": [
    "국가인권위원회는 모든 사람의 인권 보호와 향상을 위한 업무를 수행한다. 입법, 행정, 사법 3부 어디에도 속하지 않는 독립적 지위를 가지고 있다."
   ],
   "translation": "The National Human Rights Commission carries out the work of protecting and advancing everyone’s human rights. It holds an independent standing, belonging to none of the three branches — legislature, executive, judiciary.",
   "sentences": [
    {
     "spans": [
      "국가인권위원회는 모든 사람의 인권 보호와 향상을 위한 업무를 수행한다. "
     ],
     "translation": "The National Human Rights Commission carries out the work of protecting and advancing everyone’s human rights."
    },
    {
     "spans": [
      "입법, 행정, 사법 3부 어디에도 속하지 않는 독립적 지위를 가지고 있다."
     ],
     "translation": "It holds an independent standing, belonging to none of the three branches — legislature, executive, judiciary."
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "국민권익위원회"
  },
  {
   "type": "paragraph",
   "spans": [
    "국민권익위원회는 국민들의 고충 처리와 관련된 업무를 담당하면서 불합리한 행정제도를 개선하고 부정부패를 규제하는 업무를 담당한다."
   ],
   "translation": "The Anti-Corruption and Civil Rights Commission handles the work to do with dealing with people’s grievances, putting unreasonable administrative arrangements right and curbing corruption.",
   "sentences": [
    {
     "spans": [
      "국민권익위원회는 국민들의 고충 처리와 관련된 업무를 담당하면서 불합리한 행정제도를 개선하고 부정부패를 규제하는 업무를 담당한다."
     ],
     "translation": "The Anti-Corruption and Civil Rights Commission handles the work to do with dealing with people’s grievances, putting unreasonable administrative arrangements right and curbing corruption."
    }
   ]
  },
  {
   "type": "figure",
   "text": "여덟 기관의 건물 사진 — 인천출입국·외국인청, 대법원, 행정복지센터, 대한법률구조공단, 경찰서, 검찰청, 국가인권위원회, 국민권익위원회"
  }
 ],
 "annotations": {},
 "notes": [
  {
   "why": "제6편's closing spread runs pp. 194-197."
  },
  {
   "why": "The crossword grid is not reproduced; its clues are, with the answers covered. Those answers, and the answers to the 종합 평가, are mine — worked out from chapters 30-37, since 정답보기 on p. 262 is not photographed."
  },
  {
   "why": "대단원 정리 prints 가족와 법 for chapter 33, where the chapter itself is 가족과 법. It is set as printed."
  },
  {
   "why": "The eight buildings on pp. 196-197 are photographs; they are not reproduced, and the descriptions beside them are set as the feature’s text."
  }
 ],
 "slug": "part-6",
 "part": true
});
