/* Generated by tools/build.py — do not edit.
   Content lives in tools/chapters/pt03_culture.py; rebuild after changing it. */

KIIP.chapter({
 "number": 3,
 "unit": "문화",
 "title": "대단원 마무리",
 "titleEnglish": "Closing the part",
 "chapterGlossary": [],
 "blocks": [
  {
   "type": "section",
   "kind": "summary",
   "text": "대단원 정리"
  },
  {
   "type": "table",
   "rows": [
    [
     "전통 가치",
     "효와 예절: 높임말, 웃어른 공경 / 공동체와 연고 중시: ‘우리, 함께’를 중요시함"
    ],
    [
     "전통 의식주",
     "한국 음식: 밥, 국, 반찬이 기본 식단 / 한복: 바지와 저고리(남자), 치마와 저고리(여자) / 한옥: 기와집과 초가집"
    ],
    [
     "의례",
     "결혼식: 부부가 되는 의례 / 장례식: 사람이 죽었을 때 치르는 의례"
    ],
    [
     "명절",
     "설날: 음력 1월 1일, 떡국을 먹으며 건강과 장수를 기원 / 추석: 음력 8월 15일, 한 해 농사에 감사하는 전통에서 유래"
    ],
    [
     "종교",
     "한국은 불교와 유교, 천주교와 개신교 등과 같은 종교를 누구나 자유롭게 가질 수 있음"
    ],
    [
     "대중문화",
     "한국의 인기 있는 대중문화: 드라마, 음악과 노래(K-POP), 영화, 스포츠, 예능 프로그램 등"
    ],
    [
     "여가문화",
     "일과 생활이 균형 잡힌 삶을 살아가기 위해서는 여가활동이 필요함"
    ]
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "찾아볼 곳"
  },
  {
   "type": "bullet",
   "spans": [
    "문화체육관광부 — www.mcst.go.kr"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "남산골한옥마을 — www.hanokmaeul.or.kr"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "전통문화포털 — www.kculture.or.kr"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "한식포털 — www.hansik.or.kr"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "한국예절문화원 — www.etiquette.or.kr"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "대한민국 구석구석 — korean.visitkorea.or.kr"
   ]
  },
  {
   "type": "section",
   "kind": "quiz",
   "text": "가로 세로 퀴즈"
  },
  {
   "type": "figure",
   "text": "일곱 칸씩 가로세로로 짜인 낱말 퍼즐 판. 가로 열쇠 ㉮~㉱와 세로 열쇠 ①~④가 시작하는 칸에 번호가 적혀 있다."
  },
  {
   "type": "heading",
   "level": 4,
   "text": "가로 열쇠"
  },
  {
   "type": "bullet",
   "spans": [
    "㉮ 한옥의 중요한 특징으로 아궁이에 불을 때어 방을 따뜻하게 하는 난방 장치 ",
    {
     "blank": "온돌"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "㉯ 추석은 ○○○ 또는 가배라고도 불림 ",
    {
     "blank": "한가위"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "㉰ 석가모니가 만든 종교로 중국을 거쳐 4세기 무렵 삼국 시대에 들어옴 ",
    {
     "blank": "불교"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "㉱ 사람이 죽었을 때, 예를 갖추어 돌아가신 분을 보내는 의례 ",
    {
     "blank": "장례식"
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "세로 열쇠"
  },
  {
   "type": "bullet",
   "spans": [
    "① 아이가 태어난 지 1년이 되는 첫 번째 생일 ",
    {
     "blank": "돌"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "② 한국의 대중문화가 여러 나라로 확산되면서 대중적 인기를 끌게 된 현상 ",
    {
     "blank": "한류"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "③ 개신교 예배는 ○○에서 드림 ",
    {
     "blank": "교회"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "④ 남자와 여자가 부부가 되기로 서약하는 의례 ",
    {
     "blank": "결혼식"
    }
   ]
  },
  {
   "type": "section",
   "kind": "exam",
   "text": "단원 종합 평가"
  },
  {
   "type": "heading",
   "level": 4,
   "text": "01 〈보기〉의 설날에 먹는 음식에 대한 설명 중 ㉠과 ㉡에 들어갈 용어로 적합한 것은?"
  },
  {
   "type": "paragraph",
   "spans": [
    "차례와 세배를 마친 후에는 떡국을 먹는다. 떡국은 흰 가래떡을 얇게 썰어 끓인 것으로 설날의 대표적인 음식이다. 흰 가래떡은 ㉠와과 ㉡을/를 상징하며, 떡국 한 그릇을 먹으면 나이도 한 살 더 먹는다는 의미가 담겨 있다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "① 건강 — 장수"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "② 장수 — 희망"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "③ 장수 — 기쁨"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "④ 건강 — 기쁨"
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "정답 ",
    {
     "blank": "①"
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "02 〈보기〉의 빈 칸에 공통으로 들어갈 알맞은 말은?"
  },
  {
   "type": "paragraph",
   "spans": [
    "설날 아침에는 ",
    {
     "word": "조상",
     "annotation": "조상"
    },
    "에게 감사하는 의식인 ",
    {
     "word": "차례",
     "annotation": "차례"
    },
    "를 지낸다. 그리고 부모님 또는 ",
    {
     "word": "조부모님",
     "annotation": "조부모님"
    },
    " 등 집안의 ",
    {
     "word": "윗사람",
     "annotation": "윗사람"
    },
    "에게 ",
    {
     "blank": ""
    },
    "를 한다. ",
    {
     "blank": ""
    },
    "를 받은 윗사람은 자녀 등 아랫사람에게 한 해 동안 건강하고 잘 지내라고 ",
    {
     "word": "덕담",
     "annotation": "덕담"
    },
    "을 한다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "① ",
    {
     "word": "성묘",
     "annotation": "성묘"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "② ",
    {
     "word": "세배",
     "annotation": "세배"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "③ ",
    {
     "word": "벌초",
     "annotation": "벌초"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "④ ",
    {
     "word": "연날리기",
     "annotation": "연날리기"
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "정답 ",
    {
     "blank": "②"
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "03 다음 중 한국의 식사 예절로 옳은 것을 〈보기〉에서 모두 고른 것은?"
  },
  {
   "type": "bullet",
   "spans": [
    "ㄱ. 숟가락과 젓가락을 동시에 들고 사용한다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "ㄴ. 밥그릇이나 국그릇을 손으로 들고 먹는다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "ㄷ. ",
    {
     "word": "웃어른",
     "annotation": "웃어른"
    },
    "이 먼저 ",
    {
     "word": "수저",
     "annotation": "수저"
    },
    "를 들 때까지 기다린다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "ㄹ. 입안에 음식이 있을 때에는 ",
    {
     "word": "가급적",
     "annotation": "가급적"
    },
    " 말하지 않는다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "① ㄱ, ㄴ"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "② ㄱ, ㄹ"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "③ ㄴ, ㄷ"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "④ ㄷ, ㄹ"
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "정답 ",
    {
     "blank": "④"
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "04 다음 중 한국에서 창시된 종교가 아닌 것은?"
  },
  {
   "type": "bullet",
   "spans": [
    "① ",
    {
     "word": "유교",
     "annotation": "유교"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "② ",
    {
     "word": "원불교",
     "annotation": "원불교"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "③ ",
    {
     "word": "대종교",
     "annotation": "대종교"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "④ ",
    {
     "word": "천도교",
     "annotation": "천도교"
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "정답 ",
    {
     "blank": "①"
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "05 한국의 여가문화에 대한 설명으로 옳은 것은?"
  },
  {
   "type": "bullet",
   "spans": [
    "① 영화 관람의 경우 반드시 영화관에 직접 가서 표를 구매해야 한다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "② 주 52시간 근무제가 ",
    {
     "word": "도입되면서",
     "annotation": "도입되다"
    },
    " 여가의 중요성이 더욱 높아졌다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "③ 행정복지센터나 평생학습관에서 운영하는 여가 프로그램은 모두 무료이다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "④ 자신이 좋아하거나 배우고 싶은 것을 다른 사람들과 함께 공유하기는 불가능하다."
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "정답 ",
    {
     "blank": "②"
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "06 〈보기〉의 빈 칸에 공통으로 들어갈 알맞은 말은?"
  },
  {
   "type": "paragraph",
   "spans": [
    "제사를 지낼 때 가족이 함께 모여 ",
    {
     "word": "추모하는",
     "annotation": "추모하다"
    },
    " 마음으로 제사 음식 앞에서 조상에게 절을 두 번 한다. 제사를 마친 후에는 가족들이 함께 모여 제사 음식을 나누어 먹는다. 이를 ",
    {
     "blank": ""
    },
    "이라고 한다. ",
    {
     "blank": ""
    },
    "은 조상이 주는 복을 나누어 받는다는 의미가 담겨 있다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "① 절"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "② 화장"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "③ ",
    {
     "word": "음복",
     "annotation": "음복"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "④ ",
    {
     "word": "문상",
     "annotation": "문상"
    }
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "정답 ",
    {
     "blank": "③"
    }
   ]
  },
  {
   "type": "section",
   "kind": "feature",
   "text": "한국의 세시풍속 이야기: 절기"
  },
  {
   "type": "paragraph",
   "spans": [
    "기후 변화가 뚜렷한 한국은 예로부터 1년을 봄, 여름, 가을, 겨울 네 계절로 나누고 다시 4계절을 24절기로 나누어 놓았다. 보통 한 절기와 다음 절기 사이에서는 평균 15일 가량의 차이가 있고, 보통 한 달에 두 번 가량 절기가 들어있게 된다. 또한 계절에 따라 의미 있는 날을 정해 놓고 기념하였는데 이러한 날들을 명절이라 한다. 이러한 절기나 명절에 따라 연례 행사를 진행하였는데 이를 세시풍속이라 한다. 절기와 명절의 대표적인 예는 다음과 같다."
   ],
   "translation": "Korea, where the change of climate is marked, has long divided the year into four seasons — spring, summer, autumn, winter — and divided those four again into 24 solar terms. There are about 15 days on average between one term and the next, so about two terms fall in a month. Days of significance were also set by the season and marked, and those days are called 명절. Annual events were held according to these terms and festivals, and that is what 세시풍속 means. Here are the best-known of the terms and the festivals.",
   "sentences": [
    {
     "spans": [
      "기후 변화가 뚜렷한 한국은 예로부터 1년을 봄, 여름, 가을, 겨울 네 계절로 나누고 다시 4계절을 24절기로 나누어 놓았다. "
     ],
     "translation": "Korea, where the change of climate is marked, has long divided the year into four seasons — spring, summer, autumn, winter — and divided those four again into 24 solar terms."
    },
    {
     "spans": [
      "보통 한 절기와 다음 절기 사이에서는 평균 15일 가량의 차이가 있고, 보통 한 달에 두 번 가량 절기가 들어있게 된다. "
     ],
     "translation": "There are about 15 days on average between one term and the next, so about two terms fall in a month."
    },
    {
     "spans": [
      "또한 계절에 따라 의미 있는 날을 정해 놓고 기념하였는데 이러한 날들을 명절이라 한다. "
     ],
     "translation": "Days of significance were also set by the season and marked, and those days are called 명절."
    },
    {
     "spans": [
      "이러한 절기나 명절에 따라 연례 행사를 진행하였는데 이를 세시풍속이라 한다. "
     ],
     "translation": "Annual events were held according to these terms and festivals, and that is what 세시풍속 means."
    },
    {
     "spans": [
      "절기와 명절의 대표적인 예는 다음과 같다."
     ],
     "translation": "Here are the best-known of the terms and the festivals."
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "[입춘] 양력 2월 4일"
  },
  {
   "type": "paragraph",
   "spans": [
    "1년의 시작을 알리는 봄을 대표하는 절기인 입춘. 이날은 콩을 문이나 마루에 뿌려 악귀를 쫓고 좋은 글귀를 써서 천장에 붙이곤 하였다. 봄이면 흔히 보이는 ‘입춘대길 立春大吉’이 대표적인 예이다."
   ],
   "translation": "입춘, the term that stands for the spring announcing the year’s beginning. On this day people would scatter beans at the door or on the floor to drive off evil spirits, and write a good phrase and paste it to the ceiling. The ‘입춘대길 立春大吉’ commonly seen in spring is the best-known example.",
   "sentences": [
    {
     "spans": [
      "1년의 시작을 알리는 봄을 대표하는 절기인 입춘. "
     ],
     "translation": "입춘, the term that stands for the spring announcing the year’s beginning."
    },
    {
     "spans": [
      "이날은 콩을 문이나 마루에 뿌려 악귀를 쫓고 좋은 글귀를 써서 천장에 붙이곤 하였다. "
     ],
     "translation": "On this day people would scatter beans at the door or on the floor to drive off evil spirits, and write a good phrase and paste it to the ceiling."
    },
    {
     "spans": [
      "봄이면 흔히 보이는 ‘입춘대길 立春大吉’이 대표적인 예이다."
     ],
     "translation": "The ‘입춘대길 立春大吉’ commonly seen in spring is the best-known example."
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "[소서] 양력 7월 7일"
  },
  {
   "type": "paragraph",
   "spans": [
    "소서. 즉 작은 여름이라 하는데, 이때부터 본격적인 무더위가 시작되며 각종 채소나 과일이 풍성해진다. 특히 단오때부터 즐기기 시작하는 ‘국수’와 ‘수제비’ 등이 이 시기에 가장 맛이 좋다고 한다."
   ],
   "translation": "소서 — the ‘lesser heat’. From this point the real heat begins and vegetables and fruit of every kind grow plentiful. ‘국수’ and ‘수제비’, which people begin to enjoy from 단오, are said to taste best at this time.",
   "sentences": [
    {
     "spans": [
      "소서. "
     ],
     "translation": "소서 — the ‘lesser heat’."
    },
    {
     "spans": [
      "즉 작은 여름이라 하는데, 이때부터 본격적인 무더위가 시작되며 각종 채소나 과일이 풍성해진다. "
     ],
     "translation": "From this point the real heat begins and vegetables and fruit of every kind grow plentiful."
    },
    {
     "spans": [
      "특히 단오때부터 즐기기 시작하는 ‘국수’와 ‘수제비’ 등이 이 시기에 가장 맛이 좋다고 한다."
     ],
     "translation": "‘국수’ and ‘수제비’, which people begin to enjoy from 단오, are said to taste best at this time."
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "[처서] 양력 8월 23일"
  },
  {
   "type": "paragraph",
   "spans": [
    "여름이 지나 더위도 가시고 선선한 가을을 맞이하게 된다고 하여 처서라 불렀다. 처서가 지나면 따가운 햇볕이 누그러져 풀이 더 자라지 않기 때문에 산소의 풀을 깎아 벌초를 한다."
   ],
   "translation": "It was called 처서 because summer passes, the heat goes and a cool autumn is met. Once 처서 is past, the fierce sun softens and the grass grows no further, so the grass on the graves is cut in 벌초.",
   "sentences": [
    {
     "spans": [
      "여름이 지나 더위도 가시고 선선한 가을을 맞이하게 된다고 하여 처서라 불렀다. "
     ],
     "translation": "It was called 처서 because summer passes, the heat goes and a cool autumn is met."
    },
    {
     "spans": [
      "처서가 지나면 따가운 햇볕이 누그러져 풀이 더 자라지 않기 때문에 산소의 풀을 깎아 벌초를 한다."
     ],
     "translation": "Once 처서 is past, the fierce sun softens and the grass grows no further, so the grass on the graves is cut in 벌초."
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "[동지] 양력 12월 22일"
  },
  {
   "type": "paragraph",
   "spans": [
    "1년 중 밤이 가장 길고, 낮이 가장 짧은 날이다. 붉은 색의 팥죽을 먹어 귀신을 쫓는 풍습이 지금까지 이어져 오고 있다. 팥죽에는 나이만큼 새알이라 불리는 떡을 넣었다."
   ],
   "translation": "The day with the longest night and the shortest day of the year. The custom of eating red 팥죽 to drive off spirits has carried on to this day. Into the 팥죽 went rice cakes called 새알, as many as one’s years.",
   "sentences": [
    {
     "spans": [
      "1년 중 밤이 가장 길고, 낮이 가장 짧은 날이다. "
     ],
     "translation": "The day with the longest night and the shortest day of the year."
    },
    {
     "spans": [
      "붉은 색의 팥죽을 먹어 귀신을 쫓는 풍습이 지금까지 이어져 오고 있다. "
     ],
     "translation": "The custom of eating red 팥죽 to drive off spirits has carried on to this day."
    },
    {
     "spans": [
      "팥죽에는 나이만큼 새알이라 불리는 떡을 넣었다."
     ],
     "translation": "Into the 팥죽 went rice cakes called 새알, as many as one’s years."
    }
   ]
  },
  {
   "type": "figure",
   "text": "네 절기 사진 — 입춘의 문에 붙인 입춘대길, 소서의 수제비, 처서의 들녘, 동지의 팥죽"
  },
  {
   "type": "section",
   "kind": "feature",
   "text": "한국의 세시풍속 이야기: 명절"
  },
  {
   "type": "heading",
   "level": 4,
   "text": "[설날] 음력 1월 1일"
  },
  {
   "type": "paragraph",
   "spans": [
    "음력으로 한 해가 시작되는 새해 첫 달의 첫날, 서로에게 ‘새해 복 많이 받으세요.’라고 인사하며 덕담을 나누는 풍습이 있는 명절"
   ],
   "translation": "The first day of the first month of the new year on the lunar calendar, the festival with the custom of greeting one another with ‘새해 복 많이 받으세요’ and exchanging good wishes.",
   "sentences": [
    {
     "spans": [
      "음력으로 한 해가 시작되는 새해 첫 달의 첫날, 서로에게 ‘새해 복 많이 받으세요.’라고 인사하며 덕담을 나누는 풍습이 있는 명절"
     ],
     "translation": "The first day of the first month of the new year on the lunar calendar, the festival with the custom of greeting one another with ‘새해 복 많이 받으세요’ and exchanging good wishes."
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "[정월대보름] 음력 1월 15일"
  },
  {
   "type": "paragraph",
   "spans": [
    "음력 정월보름날을 말하며 나쁜 일을 물리치고 좋은 일이 오기를 바라는 마음에서 부럼 깨물기, 더위팔기, 귀밝이술 마시기, 줄다리기, 다리밟기, 고싸움, 돌싸움, 쥐불놀이 등을 하는 명절"
   ],
   "translation": "The fifteenth of the first lunar month: the festival at which, in the hope of driving off ill fortune and drawing in good, people crack nuts, ‘sell the heat’, drink 귀밝이술, hold tug-of-war, walk the bridges, and hold 고싸움, 돌싸움 and 쥐불놀이.",
   "sentences": [
    {
     "spans": [
      "음력 정월보름날을 말하며 나쁜 일을 물리치고 좋은 일이 오기를 바라는 마음에서 부럼 깨물기, 더위팔기, 귀밝이술 마시기, 줄다리기, 다리밟기, 고싸움, 돌싸움, 쥐불놀이 등을 하는 명절"
     ],
     "translation": "The fifteenth of the first lunar month: the festival at which, in the hope of driving off ill fortune and drawing in good, people crack nuts, ‘sell the heat’, drink 귀밝이술, hold tug-of-war, walk the bridges, and hold 고싸움, 돌싸움 and 쥐불놀이."
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "[삼짇날] 음력 3월 3일"
  },
  {
   "type": "paragraph",
   "spans": [
    "다시 새로운 농사일을 시작할 시점에 겨울 동안 움츠렸던 몸과 마음을 펴고 한 해의 건강과 평화를 비는 명절"
   ],
   "translation": "The festival at which, as the new farming year is about to begin, people stretch out the body and mind that had drawn in over the winter and pray for health and peace for the year.",
   "sentences": [
    {
     "spans": [
      "다시 새로운 농사일을 시작할 시점에 겨울 동안 움츠렸던 몸과 마음을 펴고 한 해의 건강과 평화를 비는 명절"
     ],
     "translation": "The festival at which, as the new farming year is about to begin, people stretch out the body and mind that had drawn in over the winter and pray for health and peace for the year."
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "[단오] 음력 5월 5일"
  },
  {
   "type": "paragraph",
   "spans": [
    "모내기를 끝내고 풍년을 기원하는 제사이기도 한 단오는 단오떡을 해먹고 여자는 창포물에 머리를 감고 그네를 뛰며 남자는 씨름을 하면서 하루를 보내는 명절"
   ],
   "translation": "단오, which is also the rite praying for a good harvest once the rice planting is done: the festival where people make and eat 단오떡, the women wash their hair in iris water and ride the swings, and the men wrestle 씨름, spending the day so.",
   "sentences": [
    {
     "spans": [
      "모내기를 끝내고 풍년을 기원하는 제사이기도 한 단오는 단오떡을 해먹고 여자는 창포물에 머리를 감고 그네를 뛰며 남자는 씨름을 하면서 하루를 보내는 명절"
     ],
     "translation": "단오, which is also the rite praying for a good harvest once the rice planting is done: the festival where people make and eat 단오떡, the women wash their hair in iris water and ride the swings, and the men wrestle 씨름, spending the day so."
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "[유두] 음력 6월 15일"
  },
  {
   "type": "paragraph",
   "spans": [
    "신라 때부터 유래한 것으로, 나쁜 일을 떨어 버리기 위하여 동쪽으로 흐르는 물에 머리를 감는 풍습이 있는 명절"
   ],
   "translation": "Dating from the Silla period, the festival with the custom of washing one’s hair in east-flowing water to shake off ill fortune.",
   "sentences": [
    {
     "spans": [
      "신라 때부터 유래한 것으로, 나쁜 일을 떨어 버리기 위하여 동쪽으로 흐르는 물에 머리를 감는 풍습이 있는 명절"
     ],
     "translation": "Dating from the Silla period, the festival with the custom of washing one’s hair in east-flowing water to shake off ill fortune."
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "[추석] 음력 8월 15일"
  },
  {
   "type": "paragraph",
   "spans": [
    "음력 팔월 보름을 일컫는 말로 가을의 한가운데 달이며 또한 팔월의 한가운데 날이라는 뜻을 지니고 있는 연중 으뜸인 명절"
   ],
   "translation": "The name for the fifteenth of the eighth lunar month: the middle month of autumn and the middle day of the eighth month, and the foremost festival of the year.",
   "sentences": [
    {
     "spans": [
      "음력 팔월 보름을 일컫는 말로 가을의 한가운데 달이며 또한 팔월의 한가운데 날이라는 뜻을 지니고 있는 연중 으뜸인 명절"
     ],
     "translation": "The name for the fifteenth of the eighth lunar month: the middle month of autumn and the middle day of the eighth month, and the foremost festival of the year."
    }
   ]
  },
  {
   "type": "figure",
   "text": "여섯 명절 사진 — 설날의 세배, 정월대보름의 부럼, 삼짇날의 화전, 단오의 그네, 유두, 추석의 달과 토끼"
  }
 ],
 "annotations": {
  "조상": {
   "headword": "조상",
   "hanja": "祖上",
   "meaning": "an ancestor",
   "characters": [
    {
     "char": "祖",
     "reading": "조",
     "gloss": "ancestor — as in 조부모, 조상"
    },
    {
     "char": "上",
     "reading": "상",
     "gloss": "above — as in 이상, 상급"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "차례": {
   "headword": "차례",
   "hanja": "茶禮",
   "meaning": "the ancestral rite held on a festival day",
   "characters": [
    {
     "char": "茶",
     "reading": "차",
     "gloss": "tea — as in 차, 다도"
    },
    {
     "char": "禮",
     "reading": "례",
     "gloss": "rite, courtesy — as in 예절, 의례"
    }
   ],
   "notes": [
    "Held on the morning of 설날 and 추석; 제사 is the rite on the anniversary of a death."
   ],
   "surfaces": []
  },
  "조부모님": {
   "headword": "조부모님",
   "hanja": "祖父母님",
   "meaning": "grandparents",
   "characters": [
    {
     "char": "祖",
     "reading": "조",
     "gloss": "ancestor — the same 祖 as in 조상"
    },
    {
     "char": "父母",
     "gloss": "parents"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "윗사람": {
   "headword": "윗사람",
   "hanja": null,
   "meaning": "a senior, someone above one in age or standing",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "덕담": {
   "headword": "덕담",
   "hanja": "德談",
   "meaning": "words of blessing, a kind wish",
   "characters": [
    {
     "char": "德",
     "reading": "덕",
     "gloss": "virtue — as in 덕분, 미덕"
    },
    {
     "char": "談",
     "reading": "담",
     "gloss": "to talk — as in 상담, 회담"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "성묘": {
   "headword": "성묘",
   "hanja": "省墓",
   "meaning": "visiting an ancestor’s grave",
   "characters": [
    {
     "char": "省",
     "reading": "성",
     "gloss": "to reflect, to visit"
    },
    {
     "char": "墓",
     "reading": "묘",
     "gloss": "a grave — as in 묘지, 성묘"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "세배": {
   "headword": "세배",
   "hanja": "歲拜",
   "meaning": "the new year bow",
   "characters": [
    {
     "char": "歲",
     "reading": "세",
     "gloss": "year, age — as in 만 65세, 세월"
    },
    {
     "char": "拜",
     "reading": "배",
     "gloss": "to bow — as in 예배, 참배"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "벌초": {
   "headword": "벌초",
   "hanja": "伐草",
   "meaning": "cutting the grass on a grave",
   "characters": [
    {
     "char": "伐",
     "reading": "벌",
     "gloss": "to cut down, to fell"
    },
    {
     "char": "草",
     "reading": "초",
     "gloss": "grass — as in 초가집, 잡초"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "연날리기": {
   "headword": "연날리기",
   "hanja": null,
   "meaning": "kite flying",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "웃어른": {
   "headword": "웃어른",
   "hanja": null,
   "meaning": "an elder, one’s senior",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "수저": {
   "headword": "수저",
   "hanja": null,
   "meaning": "spoon and chopsticks",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "가급적": {
   "headword": "가급적",
   "hanja": "可及的",
   "meaning": "as far as possible, if possible",
   "characters": [
    {
     "char": "可",
     "reading": "가",
     "gloss": "possible — as in 가능, 허가"
    },
    {
     "char": "及",
     "reading": "급",
     "gloss": "to reach — as in 보급, 급하다"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "유교": {
   "headword": "유교",
   "hanja": "儒敎",
   "meaning": "Confucianism",
   "characters": [
    {
     "char": "儒",
     "reading": "유",
     "gloss": "a Confucian scholar"
    },
    {
     "char": "敎",
     "reading": "교",
     "gloss": "teaching, religion — as in 종교, 불교"
    }
   ],
   "notes": [
    "Not founded in Korea, which is what question 4 turns on."
   ],
   "surfaces": []
  },
  "원불교": {
   "headword": "원불교",
   "hanja": "圓佛敎",
   "meaning": "Won Buddhism",
   "characters": [],
   "notes": [
    "Founded by 박중빈 in 1916 — chapter 17’s table."
   ],
   "surfaces": []
  },
  "대종교": {
   "headword": "대종교",
   "hanja": "大倧敎",
   "meaning": "Daejonggyo",
   "characters": [],
   "notes": [
    "Founded by 나철 in 1909, tracing itself to 단군."
   ],
   "surfaces": []
  },
  "천도교": {
   "headword": "천도교",
   "hanja": "天道敎",
   "meaning": "Cheondogyo",
   "characters": [],
   "notes": [
    "Founded by 최제우 in 1860, first called 동학."
   ],
   "surfaces": []
  },
  "도입되다": {
   "headword": "도입되다",
   "hanja": "導入되다",
   "meaning": "to be introduced, brought in",
   "characters": [
    {
     "char": "導",
     "reading": "도",
     "gloss": "to guide — as in 지도, 인도적"
    },
    {
     "char": "入",
     "reading": "입",
     "gloss": "to enter — as in 입국, 수입"
    }
   ],
   "notes": [],
   "surfaces": [
    "도입되면서"
   ]
  },
  "추모하다": {
   "headword": "추모하다",
   "hanja": "追慕하다",
   "meaning": "to remember, to cherish the memory of",
   "characters": [
    {
     "char": "追",
     "reading": "추",
     "gloss": "to chase, to follow — as in 추구, 추적"
    },
    {
     "char": "慕",
     "reading": "모",
     "gloss": "to long for, to admire"
    }
   ],
   "notes": [
    "The page prints 추모; 추모 and 추도 both appear for this, 추모 being the older form."
   ],
   "surfaces": [
    "추모하는"
   ]
  },
  "음복": {
   "headword": "음복",
   "hanja": "飮福",
   "meaning": "sharing the food from an ancestral rite",
   "characters": [
    {
     "char": "飮",
     "reading": "음",
     "gloss": "to drink — as in 음식, 음주"
    },
    {
     "char": "福",
     "reading": "복",
     "gloss": "blessing, fortune — as in 복, 축복"
    }
   ],
   "notes": [
    "Literally drinking the blessing: the family shares what was offered, and so shares the ancestors’ blessing."
   ],
   "surfaces": []
  },
  "문상": {
   "headword": "문상",
   "hanja": "問喪",
   "meaning": "paying a condolence call",
   "characters": [
    {
     "char": "問",
     "reading": "문",
     "gloss": "to ask — as in 질문, 문의"
    },
    {
     "char": "喪",
     "reading": "상",
     "gloss": "mourning — as in 장례, 상주"
    }
   ],
   "notes": [],
   "surfaces": []
  }
 },
 "notes": [
  {
   "why": "제3편's closing spread runs pp. 104-107."
  },
  {
   "why": "The crossword grid is not reproduced; its clues are, with the answers covered. Those answers are mine, worked out from chapters 13-19."
  },
  {
   "why": "The 종합 평가 answers to questions 3 and 5 are the ones you marked on p. 105; the rest are mine, since 정답보기 on p. 262 is not photographed. Your English glosses on that page are the entries for 조상, 차례, 조부모님, 윗사람, 덕담, 성묘, 세배, 벌초, 연날리기, 웃어른, 수저, 가급적, 유교, 원불교, 대종교, 천도교 and 도입되다."
  },
  {
   "why": "The photographs on pp. 106-107 are not reproduced; their captions and the text beside them are."
  }
 ],
 "slug": "part-3",
 "part": true
});
