/* Generated by tools/build.py — do not edit.
   Content lives in tools/chapters/pt05_economy.py; rebuild after changing it. */

KIIP.chapter({
 "number": 5,
 "unit": "경제",
 "title": "대단원 마무리",
 "titleEnglish": "Closing the part",
 "chapterGlossary": [],
 "blocks": [
  {
   "type": "section",
   "kind": "summary",
   "text": "대단원 정리"
  },
  {
   "type": "heading",
   "level": 4,
   "text": "25. 일상생활과 경제 활동"
  },
  {
   "type": "bullet",
   "spans": [
    "경제 활동이란 재화와 서비스를 만들고 사고 파는 모든 활동을 말함"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "합리적 선택의 필요성: ",
    {
     "word": "희소성",
     "annotation": "희소성"
    },
    "으로 인해 가치 있는 것을 결정하는 것이 필요함"
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "26. 경제 성장"
  },
  {
   "type": "bullet",
   "spans": [
    "한국의 빠른 경제 성장 과정을 ‘한강의 기적’이라 부름"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "자유무역협정(FTA)을 통해 무역 규모를 확대함"
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "27. 장보기와 소비자 보호"
  },
  {
   "type": "bullet",
   "spans": [
    "최근에는 모바일 ",
    {
     "word": "기기",
     "annotation": "기기"
    },
    "를 활용한 온라인 쇼핑이 증가함"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "소비자에게는 권리와 책임이 있음"
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "28. 금융기관 이용하기"
  },
  {
   "type": "bullet",
   "spans": [
    "은행은 입금, 출금, 대출, 송금, 공과금 납부 등의 업무를 맡고 있음"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "최근에는 지점을 따로 만들지 않고, 온라인 네트워크를 통한 인터넷 전문 은행이 등장함"
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "29. 취업하기"
  },
  {
   "type": "bullet",
   "spans": [
    "일자리 지원을 위해 정부는 맞춤형 정책을 시행하고 있음"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "취업할 때는 근로 계약서를 반드시 작성하고, 근로자의 기본 권리를 알아두어야 함"
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "찾아볼 곳"
  },
  {
   "type": "bullet",
   "spans": [
    "국가지표체계 — www.index.go.kr"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "통계청 — www.kostat.go.kr"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "한국무역협회 — www.kita.net"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "한국소비자원 — www.kca.go.kr"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "한국은행 — www.bok.or.kr"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "한국산업인력공단 — www.hrdkorea.or.kr"
   ]
  },
  {
   "type": "section",
   "kind": "quiz",
   "text": "가로 세로 퀴즈"
  },
  {
   "type": "figure",
   "text": "여덟 칸씩 가로세로로 짜인 낱말 퍼즐 판. 가로 열쇠 ㉮~㉲와 세로 열쇠 ①~④가 시작하는 칸에 번호가 적혀 있다."
  },
  {
   "type": "heading",
   "level": 4,
   "text": "가로 열쇠"
  },
  {
   "type": "bullet",
   "spans": [
    "㉮ 한국에서 화폐를 발행하는 은행 ",
    {
     "blank": "한국은행"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "㉯ 제품을 구입하고 사용할 때 누릴 수 있는 권리를 ○○○기본법으로 정해 놓음 ",
    {
     "blank": "소비자"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "㉰ 본인의 이름으로만 금융 거래를 할 수 있도록 한 제도 ",
    {
     "blank": "금융실명제"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "㉱ 대형 마트에 비해 좀 더 비싸고 고급스러운 물건을 많이 파는 시장 ",
    {
     "blank": "백화점"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "㉲ 은행 계좌를 만들기 위해서는 반듯이 본인이 ○○○을 가지고 은행을 방문해야 함 ",
    {
     "blank": "신분증"
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "세로 열쇠"
  },
  {
   "type": "bullet",
   "spans": [
    "① 한국의 빠른 경제 성장을 ‘○○의 기적’이라고 부름 ",
    {
     "blank": "한강"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "② 국가 간 상품이나 서비스의 자유로운 수출과 수입을 위한 약속 ",
    {
     "blank": "자유무역협정"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "③ 사람이 살아가는 데 필요한 재화와 서비스를 만들어 사고 팔며 사용하는 모든 활동 ",
    {
     "blank": "경제 활동"
    }
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "④ 사람들이 많이 이동하는 곳에 주로 있고, 24시간 이용할 수 있는 시장 ",
    {
     "blank": "편의점"
    }
   ]
  },
  {
   "type": "section",
   "kind": "exam",
   "text": "단원 종합 평가"
  },
  {
   "type": "heading",
   "level": 4,
   "text": "01 한국의 경제 성장 과정을 ‘한강의 기적’이라고 부르는 이유는?"
  },
  {
   "type": "bullet",
   "spans": [
    "① 한강이 없었다면 경제 성장을 할 수 없었기 때문이다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "② 한강 주변의 공장에서 생산된 제품이 많았기 때문이다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "③ 세계가 놀랄 정도로 빠른 경제 성장을 이루었기 때문이다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "④ 로봇 산업, 생명 공학, 신소재 산업이 발달하고 있기 때문이다."
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "정답 ",
    {
     "blank": "③"
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "02 시장에 대한 설명으로 옳지 않은 것은?"
  },
  {
   "type": "bullet",
   "spans": [
    "① 전통 시장에서는 가격 흥정을 하는 모습을 흔히 볼 수 있다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "② 5일장은 교통이 편리해지고 도시의 인구가 늘어나면서 활성화되고 있다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "③ 대형 마트는 주차장이 넓고 물건의 종류가 많아 사람들에게 인기가 있다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "④ 슈퍼마켓은 주로 집 근처 동네에 위치하고 있으며 식료품을 구매할 수 있다."
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "정답 ",
    {
     "blank": "②"
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "03 소비자가 보호 받을 권리에 대한 설명으로 옳은 것을 〈보기〉에서 모두 고른 것은?"
  },
  {
   "type": "bullet",
   "spans": [
    "ㄱ. 한국에는 법으로 소비자의 권리를 규정하고 있다."
   ],
   "level": 2
  },
  {
   "type": "bullet",
   "spans": [
    "ㄴ. 제품을 구입한 후에는 교환이나 환불이 되지 않는다."
   ],
   "level": 2
  },
  {
   "type": "bullet",
   "spans": [
    "ㄷ. 외국인의 경우 소비 생활에서 문제가 발생한 경우 해결할 수 없다."
   ],
   "level": 2
  },
  {
   "type": "bullet",
   "spans": [
    "ㄹ. 제품에서 문제가 발생한 경우에는 우선 구입한 상점이나 기업과 상담을 한다."
   ],
   "level": 2
  },
  {
   "type": "bullet",
   "spans": [
    "① ㄱ, ㄴ"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "② ㄱ, ㄹ"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "③ ㄴ, ㄷ"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "④ ㄷ, ㄹ"
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "정답 ",
    {
     "blank": "②"
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "04 금융기관에 대한 설명으로 옳은 것은?"
  },
  {
   "type": "bullet",
   "spans": [
    "① 농협에서는 예금 업무가 가능하지만 우체국에서는 할 수 없다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "② 은행은 사람들의 돈을 맡아주는 예금, 빌려주는 대출 업무만 담당하고 있다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "③ 상호저축은행은 시중은행보다 금리가 낮은 편이지만 그에 비해 안전성은 높다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "④ ",
    {
     "word": "점포",
     "annotation": "점포"
    },
    "를 마련하지 않고 온라인 네트워크를 통해 금융 서비스를 제공하는 은행도 있다."
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "정답 ",
    {
     "blank": "④"
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "05 〈보기〉에서 설명하는 것으로 옳은 것은?"
  },
  {
   "type": "bullet",
   "spans": [
    "가짜 이름이나 다른 사람이 아닌 오직 본인의 이름으로만 금융 거래를 할 수 있도록 한 제도"
   ],
   "level": 2
  },
  {
   "type": "bullet",
   "spans": [
    "① 리콜제"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "② 금융실명제"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "③ 자유무역협정"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "④ 인터넷 뱅킹"
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "정답 ",
    {
     "blank": "②"
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "06 일자리 지원을 위한 정부의 대책에 대한 설명으로 옳지 않은 것은?"
  },
  {
   "type": "bullet",
   "spans": [
    "① 60세 이상 국민의 재취업 지원을 하고 있다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "② ",
    {
     "word": "임신",
     "annotation": "임신"
    },
    " 또는 육아 여성의 근로 시간을 ",
    {
     "word": "연장",
     "annotation": "연장"
    },
    "하고 있다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "③ 실업자에게 다양한 교육 프로그램을 제공하고 있다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "④ 청년에게는 구직 활동 지원금 정책을 시행하고 있다."
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "정답 ",
    {
     "blank": "②"
    }
   ]
  },
  {
   "type": "section",
   "kind": "feature",
   "text": "화폐 이야기",
   "titleTranslation": "The story on the money"
  },
  {
   "type": "paragraph",
   "spans": [
    "화폐는 물건을 사고 팔 때 사용하는 수단인 ",
    {
     "word": "동시",
     "annotation": "동시"
    },
    "에 각 나라의 ",
    {
     "word": "특색",
     "annotation": "특색"
    },
    "이 ",
    {
     "word": "반영",
     "annotation": "반영"
    },
    "되어 있다. 즉, 화폐에는 그 나라나 지역을 대표하는 ",
    {
     "word": "훌륭",
     "annotation": "훌륭"
    },
    "한 ",
    {
     "word": "인물",
     "annotation": "인물"
    },
    "이나 ",
    {
     "word": "상징",
     "annotation": "상징"
    },
    "이 ",
    {
     "word": "담겨",
     "annotation": "담기다"
    },
    " 있다. 한국의 화폐에도 인물, 자연, 동물 등이 ",
    {
     "word": "소재",
     "annotation": "소재"
    },
    "로 ",
    {
     "word": "활용",
     "annotation": "활용"
    },
    "되었다. ",
    {
     "word": "최초",
     "annotation": "최초"
    },
    " ",
    {
     "word": "발행",
     "annotation": "발행"
    },
    " 시기와 담겨 있는 그림에 대한 설명은 다음과 같다."
   ],
   "translation": "Money is the means of buying and selling, and at the same time it carries the character of the country that issues it. A banknote holds a distinguished figure, or a symbol, that stands for the country or the region. Korean money too draws on people, nature and animals for its subjects. When each was first issued, and what is pictured on it, is as follows.",
   "sentences": [
    {
     "spans": [
      "화폐는 물건을 사고 팔 때 사용하는 수단인 ",
      {
       "word": "동시",
       "annotation": "동시"
      },
      "에 각 나라의 ",
      {
       "word": "특색",
       "annotation": "특색"
      },
      "이 ",
      {
       "word": "반영",
       "annotation": "반영"
      },
      "되어 있다. "
     ],
     "translation": "Money is the means of buying and selling, and at the same time it carries the character of the country that issues it."
    },
    {
     "spans": [
      "즉, 화폐에는 그 나라나 지역을 대표하는 ",
      {
       "word": "훌륭",
       "annotation": "훌륭"
      },
      "한 ",
      {
       "word": "인물",
       "annotation": "인물"
      },
      "이나 ",
      {
       "word": "상징",
       "annotation": "상징"
      },
      "이 ",
      {
       "word": "담겨",
       "annotation": "담기다"
      },
      " 있다. "
     ],
     "translation": "A banknote holds a distinguished figure, or a symbol, that stands for the country or the region."
    },
    {
     "spans": [
      "한국의 화폐에도 인물, 자연, 동물 등이 ",
      {
       "word": "소재",
       "annotation": "소재"
      },
      "로 ",
      {
       "word": "활용",
       "annotation": "활용"
      },
      "되었다. "
     ],
     "translation": "Korean money too draws on people, nature and animals for its subjects."
    },
    {
     "spans": [
      {
       "word": "최초",
       "annotation": "최초"
      },
      " ",
      {
       "word": "발행",
       "annotation": "발행"
      },
      " 시기와 담겨 있는 그림에 대한 설명은 다음과 같다."
     ],
     "translation": "When each was first issued, and what is pictured on it, is as follows."
    }
   ]
  },
  {
   "type": "heading",
   "level": 3,
   "text": "동전"
  },
  {
   "type": "table",
   "header": [
    "동전",
    "최초 발행",
    "그림"
   ],
   "rows": [
    [
     "1원 (일 원)",
     "1966년 8월 16일 (현재 사용되는 모습과 같은 동전은 1983년 1월 15일)",
     "무궁화"
    ],
    [
     "5원 (오 원)",
     "1966년 8월 16일 (현재 사용되는 모습과 같은 동전은 1983년 1월 15일)",
     "거북선"
    ],
    [
     "10원 (십 원)",
     "1966년 8월 16일 (현재 사용되는 모습과 같은 동전은 2006년 12월 18일)",
     "다보탑"
    ],
    [
     "50원 (오십 원)",
     "1972년 12월 1일 (현재 사용되는 모습과 같은 동전은 1983년 1월 15일)",
     "벼이삭"
    ],
    [
     "100원 (백 원)",
     "1970년 11월 30일 (현재 사용되는 모습과 같은 동전은 1983년 1월 15일)",
     "충무공 이순신"
    ],
    [
     "500원 (오백 원)",
     "1982년 6월 12일",
     "두루미"
    ]
   ]
  },
  {
   "type": "heading",
   "level": 3,
   "text": "지폐"
  },
  {
   "type": "table",
   "header": [
    "지폐",
    "최초 발행",
    "그림"
   ],
   "rows": [
    [
     "1,000원 (천 원)",
     "1975년 8월 14일 (현재 사용되는 모습과 같은 지폐는 2007년 1월 22일)",
     "앞: 이황, 성균관 명륜당, 매화 / 뒤: 정선의 계상정거도"
    ],
    [
     "5,000원 (오천 원)",
     "1972년 7월 1일 (현재 사용되는 모습과 같은 지폐는 2006년 1월 2일)",
     "앞: 이이, 오죽헌과 오죽 / 뒤: 신사임당의 초충도"
    ],
    [
     "10,000원 (만 원)",
     "1973년 6월 12일 (현재 사용되는 모습과 같은 지폐는 2007년 1월 22일)",
     "앞: 세종대왕, 일월오봉도, 용비어천가 / 뒤: 혼천의, 천상열차분야지도, 보현산 천문대 망원경"
    ],
    [
     "50,000원 (오만 원)",
     "2009년 6월 23일",
     "앞: 신사임당, 묵포도도, 초충도수병의 가지 / 뒤: 어몽룡의 월매도, 이정의 풍죽도"
    ]
   ]
  }
 ],
 "annotations": {
  "희소성": {
   "headword": "희소성",
   "hanja": "稀少性",
   "meaning": "scarcity",
   "characters": [
    {
     "char": "稀",
     "reading": "희",
     "gloss": "rare — as in 희귀하다"
    },
    {
     "char": "少",
     "reading": "소",
     "gloss": "few — as in 소수, 감소"
    }
   ],
   "notes": [
    "The premise of economics: wants exceed what there is, so choosing is unavoidable. It is why the book keeps returning to 합리적 선택."
   ],
   "surfaces": []
  },
  "기기": {
   "headword": "기기",
   "hanja": "機器",
   "meaning": "a device",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "점포": {
   "headword": "점포",
   "hanja": "店鋪",
   "meaning": "a shop premises",
   "characters": [
    {
     "char": "店",
     "reading": "점",
     "gloss": "shop — as in 상점, 편의점"
    },
    {
     "char": "鋪",
     "reading": "포",
     "gloss": "shop, to spread out"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "임신": {
   "headword": "임신",
   "hanja": "妊娠",
   "meaning": "pregnancy",
   "characters": [
    {
     "char": "妊",
     "reading": "임",
     "gloss": "to conceive"
    },
    {
     "char": "娠",
     "reading": "신",
     "gloss": "to be pregnant"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "연장": {
   "headword": "연장",
   "hanja": "延長",
   "meaning": "extension, lengthening",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "동시": {
   "headword": "동시",
   "hanja": "同時",
   "meaning": "the same time",
   "characters": [
    {
     "char": "同",
     "reading": "동",
     "gloss": "same — as in 동일, 공동"
    },
    {
     "char": "時",
     "reading": "시",
     "gloss": "time — as in 시간, 임시"
    }
   ],
   "notes": [
    "A와 동시에 “at once A and…”."
   ],
   "surfaces": []
  },
  "특색": {
   "headword": "특색",
   "hanja": "特色",
   "meaning": "a distinctive character",
   "characters": [
    {
     "char": "特",
     "reading": "특",
     "gloss": "special — as in 특징, 특산품"
    },
    {
     "char": "色",
     "reading": "색",
     "gloss": "colour — as in 색깔, 염색"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "반영": {
   "headword": "반영",
   "hanja": "反映",
   "meaning": "reflection, being reflected in",
   "characters": [
    {
     "char": "反",
     "reading": "반",
     "gloss": "opposite, to reflect — as in 반면, 반대"
    },
    {
     "char": "映",
     "reading": "영",
     "gloss": "to project — as in 영화, 상영"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "훌륭": {
   "headword": "훌륭",
   "hanja": null,
   "meaning": "being fine, admirable",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "인물": {
   "headword": "인물",
   "hanja": "人物",
   "meaning": "a figure, a personage",
   "characters": [
    {
     "char": "物",
     "reading": "물",
     "gloss": "thing — as in 물건, 인물화"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "상징": {
   "headword": "상징",
   "hanja": "象徵",
   "meaning": "a symbol",
   "characters": [
    {
     "char": "象",
     "reading": "상",
     "gloss": "form, image — as in 상상, 현상"
    },
    {
     "char": "徵",
     "reading": "징",
     "gloss": "sign — as in 징조"
    }
   ],
   "notes": [
    "Chapter 1 is 한국의 상징."
   ],
   "surfaces": []
  },
  "담기다": {
   "headword": "담기다",
   "hanja": null,
   "meaning": "to be contained in, to be held",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "소재": {
   "headword": "소재",
   "hanja": "素材",
   "meaning": "subject matter, material",
   "characters": [
    {
     "char": "素",
     "reading": "소",
     "gloss": "element, plain — as in 요소, 신소재"
    },
    {
     "char": "材",
     "reading": "재",
     "gloss": "material — as in 재료, 인재"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "활용": {
   "headword": "활용",
   "hanja": "活用",
   "meaning": "use, putting to use",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "최초": {
   "headword": "최초",
   "hanja": "最初",
   "meaning": "the first",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "발행": {
   "headword": "발행",
   "hanja": "發行",
   "meaning": "issuance",
   "characters": [],
   "notes": [
    "Of money, a document or a newspaper alike."
   ],
   "surfaces": []
  }
 },
 "notes": [
  {
   "why": "The crossword grid is not reproduced; its clues are, with the answers covered. Those answers, and the answers to the 종합 평가, are mine — worked out from the chapters, since 정답보기 on p. 262 is not photographed."
  },
  {
   "why": "Clue ㉲ prints 반듯이 where 반드시 is the word. That is the book's own slip and stands as printed."
  },
  {
   "why": "대단원 정리 prints each chapter's points as two bullets in a table cell; they are set here as a heading with its bullets beneath, since a cell holds one run of text."
  },
  {
   "why": "화폐 이야기 keeps its two tables. The pictures on each coin and note are the book's own words; the front and back of a note are joined in one cell with a slash, as a cell holds one run of text."
  },
  {
   "why": "The coins and notes themselves are not reproduced."
  }
 ],
 "slug": "part-5",
 "part": true
});
