/* Generated by tools/build.py — do not edit.
   Content lives in tools/chapters/pt01_society.py; rebuild after changing it. */

KIIP.chapter({
 "number": 1,
 "unit": "사회",
 "title": "대단원 마무리",
 "titleEnglish": "Closing the part",
 "chapterGlossary": [],
 "blocks": [
  {
   "type": "section",
   "kind": "summary",
   "text": "대단원 정리"
  },
  {
   "type": "heading",
   "level": 3,
   "text": "키워드로 보는 한국사회"
  },
  {
   "type": "table",
   "rows": [
    [
     "1. 한국의 상징",
     "공식 국가명, 국기, 국화, 국가, 국가 문장, 한글"
    ],
    [
     "2. 가족",
     "확대가족, 핵가족, 1인 가족, 가족문화, 호칭, 촌수"
    ],
    [
     "3. 일터",
     "한국인들이 선호하는 일터, 여성의 경제활동, 정규 근무, 탄력적 근무 시간제, 교대 근무, 직장 문화"
    ],
    [
     "4. 교통와 통신",
     "교통수단, 교통카드, 환승 할인, 버스 전용 차로제, 우편, 택배, 휴대 전화, 인터넷"
    ],
    [
     "5. 주거",
     "단독 주택, 공동 주택, 전세, 월세, 반전세, 부동산"
    ],
    [
     "6. 도시와 농촌",
     "도시화, 위성도시, 도시재생, 농촌의 고령화, 농산물 직거래, 기계화, 자동화"
    ],
    [
     "7. 복지",
     "사회보험, 공공부조, 긴급복지지원, 외국인 종합 안내센터"
    ],
    [
     "8. 의료와 안전",
     "의료 기관, 동네 의원, 보건소, 종합병원, 행정안전부, 긴급 신고 전화"
    ]
   ]
  },
  {
   "type": "section",
   "kind": "quiz",
   "text": "퀴즈"
  },
  {
   "type": "paragraph",
   "spans": [
    "한국의 상징과 관련 있는 정답 단어 3개를 ",
    {
     "word": "조합",
     "annotation": "조합"
    },
    "하여 아래 퀴즈의 정답을 찾아보세요."
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "퀴즈: 세계에서 가장 큰 ",
    {
     "word": "야외",
     "annotation": "야외"
    },
    " ",
    {
     "word": "벽화",
     "annotation": "벽화"
    },
    "는?"
   ]
  },
  {
   "type": "table",
   "header": [
    "한국상징",
    "정답단어"
   ],
   "rows": [
    [
     "주택",
     "부산"
    ],
    [
     "복지",
     "목포"
    ],
    [
     "무궁화",
     "인천"
    ],
    [
     "농촌",
     "서울"
    ],
    [
     "사회보험",
     "수원"
    ],
    [
     "인터넷",
     "대구"
    ],
    [
     "애국가",
     "사일로"
    ],
    [
     "공공부조",
     "이화"
    ],
    [
     "교통수단",
     "재생"
    ],
    [
     "건강보험",
     "디자인"
    ],
    [
     "태극기",
     "벽화"
    ],
    [
     "통신수단",
     "조각"
    ]
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "정답 ",
    {
     "blank": "인천 사일로 벽화"
    }
   ]
  },
  {
   "type": "section",
   "kind": "exam",
   "text": "단원 종합 평가"
  },
  {
   "type": "heading",
   "level": 4,
   "text": "01 〈보기〉에서 설명하는 것은 무엇인가?"
  },
  {
   "type": "verse",
   "lines": [
    [
     "조선의 세종대왕이 만들었다."
    ],
    [
     "매년 10월 9일에 기념 행사를 개최하고 있다."
    ],
    [
     "사람의 발음 기관과 하늘, 땅, 사람 모양을 본떠 만들었다."
    ]
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "① 한글"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "② 태극기"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "③ 애국가"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "④ 국가 문장"
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "정답 ",
    {
     "blank": "①"
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "02 한국 사회에 관한 설명으로 옳은 것을 〈보기〉에서 모두 고른 것은?"
  },
  {
   "type": "verse",
   "lines": [
    [
     "ㄱ. 직업별 남녀 간 불균형이 뚜렷해지고 있다."
    ],
    [
     "ㄴ. 여성의 사회 진출이 과거에 비해 활발해졌다."
    ],
    [
     "ㄷ. 과거에는 확대가족이 많았으나 요즘은 핵가족 형태가 많다."
    ],
    [
     "ㄹ. 아내의 가족과 남편의 가족에 대한 호칭 구분이 명확해지고 있다."
    ]
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "① ㄱ, ㄷ"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "② ㄱ, ㄹ"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "③ ㄴ, ㄷ"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "④ ㄴ, ㄹ"
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "정답 ",
    {
     "blank": "③"
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "03 다음 중 대중교통 이용 장려 제도와 관련이 깊은 것은?"
  },
  {
   "type": "bullet",
   "spans": [
    "① 인터넷"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "② 사회보험"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "③ 환승 제도"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "④ 도시 재생"
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "정답 ",
    {
     "blank": "③"
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "04 다음 중 공동 주택에 속하지 않는 것은?"
  },
  {
   "type": "bullet",
   "spans": [
    "① 아파트"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "② 연립주택"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "③ 다세대 주택"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "④ 다가구 주택"
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "정답 ",
    {
     "blank": "④"
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "05 안전한 생활을 위한 방법으로 옳지 않은 것은?"
  },
  {
   "type": "bullet",
   "spans": [
    "① 작업할 때는 보호 장비를 반드시 착용한다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "② 긴급한 사고가 발생했을 때는 빨리 118에 전화한다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "③ 정부 차원에서 매년 실시하는 재난 대비 훈련에 참여한다."
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "④ 평상시 비상구와 구급 상자, 소화기 설치 위치를 확인해 둔다."
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "정답 ",
    {
     "blank": "②"
    }
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "06 〈보기〉의 ㉠, ㉡에서 설명하는 복지 제도로 옳은 것은?"
  },
  {
   "type": "verse",
   "lines": [
    [
     "㉠ 아파서 병원에 갈 때 의료비의 일부를 지원 받을 수 있다."
    ],
    [
     "㉡ 나이가 들어 더 이상 돈을 벌기 어려울 때 매달 일정 금액을 생활비로 지급받을 수 있다."
    ]
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "① 병원보험 / 긴급복지"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "② 의료급여 / 노후자금"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "③ 고용보험 / 공공부조"
   ]
  },
  {
   "type": "bullet",
   "spans": [
    "④ 건강보험 / 국민연금"
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "정답 ",
    {
     "blank": "④"
    }
   ]
  },
  {
   "type": "section",
   "kind": "feature",
   "text": "5대 국경일의 유래와 의미"
  },
  {
   "type": "heading",
   "level": 3,
   "text": "국경일: 나라의 경사스러운 날을 기념하기 위하여 법률로써 지정한 날"
  },
  {
   "type": "paragraph",
   "spans": [
    {
     "word": "국경일",
     "annotation": "국경일"
    },
    "은 1949년 10월 1일 법률 제53호 〈국경일에 관한 법률〉에 의하여 지정되었다. 이 법률에 의해 ",
    {
     "word": "삼일절",
     "annotation": "삼일절"
    },
    ", ",
    {
     "word": "제헌절",
     "annotation": "제헌절"
    },
    ", ",
    {
     "word": "광복절",
     "annotation": "광복절"
    },
    ", ",
    {
     "word": "개천절",
     "annotation": "개천절"
    },
    "이 국경일로 지정되어 네 개의 국경일을 4대 국경일이라고 ",
    {
     "word": "불렀으며",
     "annotation": "부르다"
    },
    ", 2006년부터는 ",
    {
     "word": "한글날",
     "annotation": "한글날"
    },
    "도 국경일에 포함되어 5대 국경일이 되었다. 국경일에는 태극기를 ",
    {
     "word": "게양",
     "annotation": "게양"
    },
    "한다."
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "3월 1일(삼일절): 일본의 지배에 저항하여 일어난 독립 만세 운동을 기념하는 날"
  },
  {
   "type": "paragraph",
   "spans": [
    "1919년 3월 1일 민족 대표 33인의 ",
    {
     "word": "독립 선언서",
     "annotation": "독립 선언서"
    },
    " ",
    {
     "word": "낭독",
     "annotation": "낭독"
    },
    "으로 시작된 독립 만세 운동은 당시 한국을 지배하고 있는 ",
    {
     "word": "일제",
     "annotation": "일제"
    },
    "의 ",
    {
     "word": "압박",
     "annotation": "압박"
    },
    "에 ",
    {
     "word": "항거",
     "annotation": "항거"
    },
    "하기 위해 전 세계에 민족의 ",
    {
     "word": "자주 독립",
     "annotation": "자주 독립"
    },
    "을 ",
    {
     "word": "선언",
     "annotation": "선언"
    },
    "하고 독립 만세를 외친 민족 운동이었다. 이러한 한국의 자주 독립 ",
    {
     "word": "정신",
     "annotation": "정신"
    },
    "을 기념하기 위하여 정부는 1949년에 3월 1일을 국경일로 정하였다."
   ]
  },
  {
   "type": "figure",
   "text": "태극기를 든 사람들이 만세를 부르는 그림"
  },
  {
   "type": "heading",
   "level": 4,
   "text": "7월 17일(제헌절): 대한민국 최초의 헌법이 제정된 날을 기념하는 날"
  },
  {
   "type": "paragraph",
   "spans": [
    "자유 민주주의를 기본으로 한 대한민국 헌법의 ",
    {
     "word": "제정",
     "annotation": "제정"
    },
    "(1948년 7월 12일)과 ",
    {
     "word": "공포",
     "annotation": "공포"
    },
    "(국민에게 알림, 1948년 7월 17일)를 ",
    {
     "word": "축하",
     "annotation": "축하"
    },
    "하고, ",
    {
     "word": "준법정신",
     "annotation": "준법정신"
    },
    "을 높일 목적으로 제정된 국경일이다. 국경일들은 모두 ",
    {
     "word": "공휴일",
     "annotation": "공휴일"
    },
    "(공적으로 쉬기로 정해진 날)로 되어 왔으나, 2008년부터는 국경일의 ",
    {
     "word": "지위",
     "annotation": "지위"
    },
    "는 유지하지만 공휴일에서는 ",
    {
     "word": "제외",
     "annotation": "제외"
    },
    "되었다."
   ]
  },
  {
   "type": "figure",
   "text": "대한민국헌법 제1장 제1조 — ① 대한민국은 민주공화국이다. ② 대한민국의 주권은 국민에게 있고, 모든 권력은 국민으로부터 나온다."
  },
  {
   "type": "heading",
   "level": 4,
   "text": "8월 15일(광복절): 일본의 지배에서 벗어나 독립한 것을 기념하는 날"
  },
  {
   "type": "paragraph",
   "spans": [
    "1945년 8월 15일 일본의 ",
    {
     "word": "항복",
     "annotation": "항복"
    },
    "으로 제2차 세계 대전이 ",
    {
     "word": "종식",
     "annotation": "종식"
    },
    "되어 한국이 독립하였고, 1948년 8월 15일 대한민국 정부가 ",
    {
     "word": "수립",
     "annotation": "수립"
    },
    "되었다. 대한민국 정부는 일본의 지배로부터 벗어난 날과 ",
    {
     "word": "독립국",
     "annotation": "독립국"
    },
    "으로서 정부가 수립된 날을 기념하기 위해 매년 8월 15일을 광복절이라 하고 국경일로 지정하였다. ‘",
    {
     "word": "광복",
     "annotation": "광복"
    },
    "’이란 ‘빛을 되찾다’는 뜻으로서 잃었던 ",
    {
     "word": "국권",
     "annotation": "국권"
    },
    "의 ",
    {
     "word": "회복",
     "annotation": "회복"
    },
    "을 의미한다."
   ]
  },
  {
   "type": "figure",
   "text": "광복으로 서울 서대문형무소를 나서는 독립지사들의 환호하는 모습. 한국학중앙연구원"
  },
  {
   "type": "heading",
   "level": 4,
   "text": "10월 3일(개천절): 한국 최초의 국가인 고조선이 만들어진 것을 기념하는 날"
  },
  {
   "type": "paragraph",
   "spans": [
    "기원전 2333년(戊辰年), ",
    {
     "word": "음력",
     "annotation": "음력"
    },
    " 10월 3일에 ",
    {
     "word": "국조",
     "annotation": "국조"
    },
    " ",
    {
     "word": "단군",
     "annotation": "단군"
    },
    "이 최초의 민족 국가인 ",
    {
     "word": "단군조선",
     "annotation": "단군조선"
    },
    "을 ",
    {
     "word": "건국",
     "annotation": "건국"
    },
    "했음을 ",
    {
     "word": "기리는",
     "annotation": "기리다"
    },
    " 뜻으로 제정되었다. 여기서 ",
    {
     "word": "개천",
     "annotation": "개천"
    },
    "(開天; 하늘이 열림)이라 함은 최초의 국가 ",
    {
     "word": "고조선",
     "annotation": "고조선"
    },
    "을 ",
    {
     "word": "건설",
     "annotation": "건설"
    },
    "한 사건을 ",
    {
     "word": "상징적",
     "annotation": "상징적"
    },
    "으로 표현한 것으로 민족의 ",
    {
     "word": "탄생",
     "annotation": "탄생"
    },
    "이나 ",
    {
     "word": "민족사",
     "annotation": "민족사"
    },
    "의 시작을 의미한다. 음력 10월 3일로 ",
    {
     "word": "지켜오다가",
     "annotation": "지키다"
    },
    " 그 뒤 음력보다 ",
    {
     "word": "양력",
     "annotation": "양력"
    },
    "을 주로 쓰게 되면서, 개천절도 1949년에 양력 10월 3일로 바뀌었다."
   ]
  },
  {
   "type": "figure",
   "text": "단군릉, 개천절 기념행사. 한국학중앙연구원"
  },
  {
   "type": "heading",
   "level": 4,
   "text": "10월 9일(한글날): 세종대왕이 한글 만든 것을 기념하는 날"
  },
  {
   "type": "paragraph",
   "spans": [
    "〈훈민정음〉 해례본(해설한 책)에 적힌 ‘정통(正統) 11년 9월 ",
    {
     "word": "상한",
     "annotation": "상한"
    },
    "(上澣)-세종 28년 9월’을 양력으로 ",
    {
     "word": "환산",
     "annotation": "환산"
    },
    "하면 10월 9일이 되어, 이날을 훈민정음을 ",
    {
     "word": "반포",
     "annotation": "반포"
    },
    "(세상에 널리 퍼뜨려 모두 알게 함)한 날로 ",
    {
     "word": "확정",
     "annotation": "확정"
    },
    "하였다. 그리하여 한글 ",
    {
     "word": "창제",
     "annotation": "창제"
    },
    " 500주년인 1946년부터 10월 9일을 한글날로 지켜 오고 있다."
   ]
  },
  {
   "type": "figure",
   "text": "훈민정음을 반포하는 세종대왕 그림"
  },
  {
   "type": "section",
   "kind": "feature",
   "text": "국가 기념일"
  },
  {
   "type": "heading",
   "level": 3,
   "text": "국가 기념일: 국가가 제정·주관하는 기념일"
  },
  {
   "type": "paragraph",
   "spans": [
    {
     "word": "국가 기념일",
     "annotation": "국가 기념일"
    },
    "이란 ‘각종 기념일 등에 관한 ",
    {
     "word": "규정",
     "annotation": "규정"
    },
    "’(대통령령)에 따라 국가가 제정·",
    {
     "word": "주관",
     "annotation": "주관"
    },
    "하는 기념일로, ‘",
    {
     "word": "법정 기념일",
     "annotation": "법정 기념일"
    },
    "’이라고도 한다. 국가 기념일은 원래 공휴일이 아니지만, 일부 기념일이 공휴일이 되었다. 국가 기념일로 지정되면 ",
    {
     "word": "주관 부처",
     "annotation": "주관 부처"
    },
    "(정부 조직의 부와 처)가 정해지고, 이후 부처 ",
    {
     "word": "자체적",
     "annotation": "자체적"
    },
    "으로 예산을 확보해 ",
    {
     "word": "기념식",
     "annotation": "기념식"
    },
    "과 관련 행사를 전국적인 ",
    {
     "word": "범위",
     "annotation": "범위"
    },
    "로 행할 수 있다."
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "[4월 5일] 식목일, [4월 19일] 4·19혁명 기념일, [4월 20일] 장애인의 날, [5월 1일] 근로자의 날, [5월 5일] 어린이날, [5월 8일] 어버이날, [5월 15일] 스승의 날, [5월 18일] 5·18 민주화 운동 기념일, [5월 셋째 월요일] 성년의 날, [6월 6일] 현충일, [10월 1일] 국군의 날 등 총 51개의 기념일이 지정돼 있다."
   ]
  },
  {
   "type": "heading",
   "level": 4,
   "text": "6월 6일(현충일): 국가를 위해 자신의 목숨을 바친 분들을 기리는 날"
  },
  {
   "type": "paragraph",
   "spans": [
    "한국은 1948년 8월에 정부를 수립한 뒤, 2년도 못 되어 1950년에 6·25 전쟁을 겪었는데 이 때 25만 명 이상의 국군이 사망하였다. 그래서 정부는 1956년에 대통령령으로 6월 6일을 ",
    {
     "word": "현충일",
     "annotation": "현충일"
    },
    "로 정하고, ",
    {
     "word": "추모",
     "annotation": "추모"
    },
    " 행사를 갖도록 하였다. 그 후 매년 6월 6일 현충일이 되면 대통령과 정부 사람들은 각종 추모 기념식을 갖고 ",
    {
     "word": "현충원",
     "annotation": "현충원"
    },
    "(국가를 위해 목숨을 바친 분들이 ",
    {
     "word": "안장",
     "annotation": "안장"
    },
    "되어 있는 ",
    {
     "word": "국립묘지",
     "annotation": "국립묘지"
    },
    ")을 ",
    {
     "word": "참배",
     "annotation": "참배"
    },
    "한다. 오전 10시 정각에 사이렌 소리와 함께 전 국민은 1분간 ",
    {
     "word": "경건히",
     "annotation": "경건히"
    },
    " ",
    {
     "word": "묵념",
     "annotation": "묵념"
    },
    "을 하고 나라를 위해 싸우다 숨진 국군 ",
    {
     "word": "장병",
     "annotation": "장병"
    },
    " 및 ",
    {
     "word": "순국선열",
     "annotation": "순국선열"
    },
    "(나라를 위해 목숨을 바친 분)들을 추모하는 시간을 갖는다. 현충일에는 각 ",
    {
     "word": "관공서",
     "annotation": "관공서"
    },
    "를 비롯하여 각 기업, 단체, 가정 등에서 태극기를 게양한다."
   ]
  },
  {
   "type": "figure",
   "text": "현충원 모습"
  },
  {
   "type": "heading",
   "level": 4,
   "text": "10월 1일(국군의 날): 한국 군대의 창설과 발전을 기념하여 정한 날"
  },
  {
   "type": "paragraph",
   "spans": [
    "1950년 10월 1일은 한국군이 ",
    {
     "word": "남침",
     "annotation": "남침"
    },
    "한 북한 ",
    {
     "word": "공산군",
     "annotation": "공산군"
    },
    "을 ",
    {
     "word": "반격",
     "annotation": "반격"
    },
    "한 끝에 ",
    {
     "word": "38선",
     "annotation": "38선"
    },
    "(북위 38°선)을 ",
    {
     "word": "돌파",
     "annotation": "돌파"
    },
    "한 날로서, 이 날의 ",
    {
     "word": "의의",
     "annotation": "의의"
    },
    "를 살리기 위하여 국군의 날로 지정하였다."
   ]
  },
  {
   "type": "paragraph",
   "spans": [
    "이 날에는 육군·해군·공군·해병대 및 육군사관학교, 해군사관학교, 공군사관학교, 육군3사관학교, 국군간호사관학교 ",
    {
     "word": "생도",
     "annotation": "생도"
    },
    "들의 ",
    {
     "word": "행진",
     "annotation": "행진"
    },
    " 등 각종 기념 행사가 열리기도 한다."
   ]
  },
  {
   "type": "figure",
   "text": "국군의 날 행진 모습"
  }
 ],
 "annotations": {
  "부르다": {
   "headword": "부르다",
   "hanja": null,
   "meaning": "to call (something) by a name",
   "characters": [],
   "notes": [
    "4대 국경일이라고 불렀으며 — “were called the four great national holidays”. 부르다 also means to sing and to summon."
   ],
   "surfaces": []
  },
  "상징적": {
   "headword": "상징적",
   "hanja": "象徵的",
   "meaning": "symbolic",
   "characters": [
    {
     "char": "象",
     "reading": "상",
     "gloss": "image, likeness — as in 상징, 현상"
    },
    {
     "char": "徵",
     "reading": "징",
     "gloss": "a sign — as in 징조, 특징"
    },
    {
     "char": "的",
     "reading": "적",
     "gloss": "the adjective suffix"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "조합": {
   "headword": "조합",
   "hanja": "組合",
   "meaning": "combining, a combination",
   "characters": [
    {
     "char": "組",
     "reading": "조",
     "gloss": "to organise — as in 조직, 조합원"
    },
    {
     "char": "合",
     "reading": "합",
     "gloss": "to join — as in 합의, 결합"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "야외": {
   "headword": "야외",
   "hanja": "野外",
   "meaning": "outdoors",
   "characters": [
    {
     "char": "野",
     "reading": "야",
     "gloss": "field, wild — as in 분야, 야구"
    },
    {
     "char": "外",
     "reading": "외",
     "gloss": "outside — as in 외국, 국내외"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "벽화": {
   "headword": "벽화",
   "hanja": "壁畫",
   "meaning": "a mural",
   "characters": [
    {
     "char": "壁",
     "reading": "벽",
     "gloss": "wall — as in 벽지, 담벼락"
    },
    {
     "char": "畫",
     "reading": "화",
     "gloss": "picture — as in 그림's 畫, 영화"
    }
   ],
   "notes": [
    "The quiz's answer is 인천 사일로 벽화 — the grain silos at Incheon port, painted in 2018 and held to be the largest outdoor mural in the world."
   ],
   "surfaces": []
  },
  "국경일": {
   "headword": "국경일",
   "hanja": "國慶日",
   "meaning": "a national holiday",
   "characters": [
    {
     "char": "慶",
     "reading": "경",
     "gloss": "auspicious, to celebrate — as in 경사, 경축"
    },
    {
     "char": "日",
     "reading": "일",
     "gloss": "day — as in 평일, 기념일"
    }
   ],
   "notes": [
    "Five of them: 삼일절, 제헌절, 광복절, 개천절, 한글날. Not the same as 공휴일, a day off — 제헌절 is a 국경일 but not a holiday from work."
   ],
   "surfaces": []
  },
  "삼일절": {
   "headword": "삼일절",
   "hanja": "三一節",
   "meaning": "Independence Movement Day, 1 March",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "제헌절": {
   "headword": "제헌절",
   "hanja": "制憲節",
   "meaning": "Constitution Day, 17 July",
   "characters": [
    {
     "char": "制",
     "reading": "제",
     "gloss": "to establish — as in 제정, 제도"
    },
    {
     "char": "憲",
     "reading": "헌",
     "gloss": "constitution — as in 헌법"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "광복절": {
   "headword": "광복절",
   "hanja": "光復節",
   "meaning": "Liberation Day, 15 August",
   "characters": [
    {
     "char": "光",
     "reading": "광",
     "gloss": "light — as in 광고, 관광"
    },
    {
     "char": "復",
     "reading": "복",
     "gloss": "to restore — as in 회복, 복구"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "개천절": {
   "headword": "개천절",
   "hanja": "開天節",
   "meaning": "National Foundation Day, 3 October",
   "characters": [
    {
     "char": "開",
     "reading": "개",
     "gloss": "to open — as in 개최, 공개"
    },
    {
     "char": "天",
     "reading": "천",
     "gloss": "heaven — as in 천지, 천문대"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "한글날": {
   "headword": "한글날",
   "hanja": null,
   "meaning": "Hangul Day, 9 October",
   "characters": [],
   "notes": [
    "The only 국경일 named for a piece of writing. Chapter 1 tells the story."
   ],
   "surfaces": []
  },
  "게양": {
   "headword": "게양",
   "hanja": "揭揚",
   "meaning": "hoisting (a flag)",
   "characters": [
    {
     "char": "揭",
     "reading": "게",
     "gloss": "to raise, to put up — as in 게시"
    },
    {
     "char": "揚",
     "reading": "양",
     "gloss": "to raise up — as in 선양"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "독립 선언서": {
   "headword": "독립 선언서",
   "hanja": "獨立宣言書",
   "meaning": "the declaration of independence",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "낭독": {
   "headword": "낭독",
   "hanja": "朗讀",
   "meaning": "reading aloud",
   "characters": [
    {
     "char": "朗",
     "reading": "랑",
     "gloss": "bright, clear"
    },
    {
     "char": "讀",
     "reading": "독",
     "gloss": "to read — as in 독서, 구독"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "일제": {
   "headword": "일제",
   "hanja": "日帝",
   "meaning": "imperial Japan",
   "characters": [],
   "notes": [
    "Short for 일본 제국주의. 일제 강점기 is the colonial period, 1910-1945."
   ],
   "surfaces": []
  },
  "압박": {
   "headword": "압박",
   "hanja": "壓迫",
   "meaning": "oppression, pressure",
   "characters": [
    {
     "char": "壓",
     "reading": "압",
     "gloss": "to press — as in 압력, 탄압"
    },
    {
     "char": "迫",
     "reading": "박",
     "gloss": "to press upon, urgent — as in 박해"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "항거": {
   "headword": "항거",
   "hanja": "抗拒",
   "meaning": "resistance",
   "characters": [
    {
     "char": "抗",
     "reading": "항",
     "gloss": "to resist — as in 저항, 반항"
    },
    {
     "char": "拒",
     "reading": "거",
     "gloss": "to refuse — as in 거부, 거절"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "자주 독립": {
   "headword": "자주 독립",
   "hanja": "自主獨立",
   "meaning": "self-determination and independence",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "선언": {
   "headword": "선언",
   "hanja": "宣言",
   "meaning": "a declaration",
   "characters": [
    {
     "char": "宣",
     "reading": "선",
     "gloss": "to proclaim — as in 선전, 선포"
    },
    {
     "char": "言",
     "reading": "언",
     "gloss": "word, to say — as in 언어, 발언"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "정신": {
   "headword": "정신",
   "hanja": "精神",
   "meaning": "spirit, mind",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "제정": {
   "headword": "제정",
   "hanja": "制定",
   "meaning": "enactment (of a law)",
   "characters": [
    {
     "char": "制",
     "reading": "제",
     "gloss": "to institute — as in 제도, 제헌절"
    },
    {
     "char": "定",
     "reading": "정",
     "gloss": "to fix — as in 확정, 지정"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "공포": {
   "headword": "공포",
   "hanja": "公布",
   "meaning": "promulgation, making public",
   "characters": [
    {
     "char": "布",
     "reading": "포",
     "gloss": "cloth; to spread — as in 반포, 배포"
    }
   ],
   "notes": [
    "Not the 공포 “fear” (恐怖) of 공포 영화."
   ],
   "surfaces": []
  },
  "축하": {
   "headword": "축하",
   "hanja": "祝賀",
   "meaning": "congratulation, celebration",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "준법정신": {
   "headword": "준법정신",
   "hanja": "遵法精神",
   "meaning": "respect for the law",
   "characters": [
    {
     "char": "遵",
     "reading": "준",
     "gloss": "to comply with — as in 준수"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "공휴일": {
   "headword": "공휴일",
   "hanja": "公休日",
   "meaning": "a public holiday",
   "characters": [],
   "notes": [
    "A day off in law. 제헌절 kept its standing as a 국경일 in 2008 but stopped being one of these."
   ],
   "surfaces": []
  },
  "지위": {
   "headword": "지위",
   "hanja": "地位",
   "meaning": "standing, status",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "제외": {
   "headword": "제외",
   "hanja": "除外",
   "meaning": "exclusion",
   "characters": [
    {
     "char": "除",
     "reading": "제",
     "gloss": "to remove — as in 면제, 삭제"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "항복": {
   "headword": "항복",
   "hanja": "降伏",
   "meaning": "surrender",
   "characters": [
    {
     "char": "降",
     "reading": "항",
     "gloss": "to surrender; 강 to descend — as in 하강"
    },
    {
     "char": "伏",
     "reading": "복",
     "gloss": "to lie prostrate"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "종식": {
   "headword": "종식",
   "hanja": "終熄",
   "meaning": "an end, cessation",
   "characters": [
    {
     "char": "終",
     "reading": "종",
     "gloss": "end — as in 최종, 종료"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "수립": {
   "headword": "수립",
   "hanja": "樹立",
   "meaning": "establishment (of a government)",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "독립국": {
   "headword": "독립국",
   "hanja": "獨立國",
   "meaning": "an independent state",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "광복": {
   "headword": "광복",
   "hanja": "光復",
   "meaning": "liberation, the recovery of light",
   "characters": [],
   "notes": [
    "Literally the light restored — which is how the article glosses it: 빛을 되찾다."
   ],
   "surfaces": []
  },
  "국권": {
   "headword": "국권",
   "hanja": "國權",
   "meaning": "national sovereignty",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "회복": {
   "headword": "회복",
   "hanja": "回復",
   "meaning": "recovery, restoration",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "음력": {
   "headword": "음력",
   "hanja": "陰曆",
   "meaning": "the lunar calendar",
   "characters": [
    {
     "char": "陰",
     "reading": "음",
     "gloss": "shade, negative — the 음 of 음양"
    },
    {
     "char": "曆",
     "reading": "력",
     "gloss": "calendar — as in 달력, 양력"
    }
   ],
   "notes": [
    "설날 and 추석 are reckoned by it. 양력 is the solar calendar."
   ],
   "surfaces": []
  },
  "양력": {
   "headword": "양력",
   "hanja": "陽曆",
   "meaning": "the solar calendar",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "국조": {
   "headword": "국조",
   "hanja": "國祖",
   "meaning": "the founding father of the nation",
   "characters": [
    {
     "char": "祖",
     "reading": "조",
     "gloss": "ancestor — as in 조상, 조부모"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "단군": {
   "headword": "단군",
   "hanja": null,
   "meaning": "Dangun, the legendary founder of Gojoseon",
   "characters": [],
   "notes": [
    "Said to have founded the first Korean state in 2333 BC, which is the year 개천절 marks."
   ],
   "surfaces": []
  },
  "단군조선": {
   "headword": "단군조선",
   "hanja": "檀君朝鮮",
   "meaning": "Dangun's Joseon, the first Korean state",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "건국": {
   "headword": "건국",
   "hanja": "建國",
   "meaning": "the founding of a country",
   "characters": [
    {
     "char": "建",
     "reading": "건",
     "gloss": "to build — as in 건설, 건의"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "기리다": {
   "headword": "기리다",
   "hanja": null,
   "meaning": "to commemorate, to honour",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "개천": {
   "headword": "개천",
   "hanja": "開天",
   "meaning": "the opening of heaven",
   "characters": [],
   "notes": [
    "The book explains the characters itself: 하늘이 열림."
   ],
   "surfaces": []
  },
  "고조선": {
   "headword": "고조선",
   "hanja": "古朝鮮",
   "meaning": "Gojoseon, the ancient Korean state",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "건설": {
   "headword": "건설",
   "hanja": "建設",
   "meaning": "construction, founding",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "탄생": {
   "headword": "탄생",
   "hanja": "誕生",
   "meaning": "birth",
   "characters": [
    {
     "char": "誕",
     "reading": "탄",
     "gloss": "to be born — as in 탄신"
    },
    {
     "char": "生",
     "reading": "생",
     "gloss": "to live, to be born — as in 생일, 학생"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "민족사": {
   "headword": "민족사",
   "hanja": "民族史",
   "meaning": "the history of a people",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "지키다": {
   "headword": "지키다",
   "hanja": null,
   "meaning": "to keep, to observe (a day, a rule)",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "상한": {
   "headword": "상한",
   "hanja": "上澣",
   "meaning": "the first ten days of a lunar month",
   "characters": [],
   "notes": [
    "An old way of dividing the month into 상한, 중한, 하한. The date in the 해례본 is what Hangul Day is reckoned from."
   ],
   "surfaces": []
  },
  "환산": {
   "headword": "환산",
   "hanja": "換算",
   "meaning": "conversion (of one reckoning into another)",
   "characters": [
    {
     "char": "換",
     "reading": "환",
     "gloss": "to exchange — as in 교환, 환전"
    },
    {
     "char": "算",
     "reading": "산",
     "gloss": "to reckon — as in 계산, 예산"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "반포": {
   "headword": "반포",
   "hanja": "頒布",
   "meaning": "promulgation, publishing abroad",
   "characters": [
    {
     "char": "頒",
     "reading": "반",
     "gloss": "to distribute"
    },
    {
     "char": "布",
     "reading": "포",
     "gloss": "to spread — the same 布 as in 공포"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "확정": {
   "headword": "확정",
   "hanja": "確定",
   "meaning": "settling, fixing",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "창제": {
   "headword": "창제",
   "hanja": "創製",
   "meaning": "the creation (of a writing system)",
   "characters": [
    {
     "char": "創",
     "reading": "창",
     "gloss": "to originate — as in 창조, 창업"
    },
    {
     "char": "製",
     "reading": "제",
     "gloss": "to make — as in 제작, 제품"
    }
   ],
   "notes": [
    "Used almost only of 한글: 한글 창제."
   ],
   "surfaces": []
  },
  "국가 기념일": {
   "headword": "국가 기념일",
   "hanja": "國家記念日",
   "meaning": "a national day of remembrance",
   "characters": [],
   "notes": [
    "Fifty-one of them, set by presidential decree rather than by statute, which is what separates them from a 국경일."
   ],
   "surfaces": []
  },
  "규정": {
   "headword": "규정",
   "hanja": "規定",
   "meaning": "a regulation",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "주관": {
   "headword": "주관",
   "hanja": "主管",
   "meaning": "to preside over, to have charge of",
   "characters": [
    {
     "char": "主",
     "reading": "주",
     "gloss": "main — as in 주인, 주권"
    },
    {
     "char": "管",
     "reading": "관",
     "gloss": "to manage — as in 관리, 보관"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "법정 기념일": {
   "headword": "법정 기념일",
   "hanja": "法定記念日",
   "meaning": "a statutory day of remembrance",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "주관 부처": {
   "headword": "주관 부처",
   "hanja": "主管部處",
   "meaning": "the ministry in charge",
   "characters": [],
   "notes": [
    "부 and 처 are the two ranks chapter 22 sets out."
   ],
   "surfaces": []
  },
  "자체적": {
   "headword": "자체적",
   "hanja": "自體的",
   "meaning": "on its own, internally",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "기념식": {
   "headword": "기념식",
   "hanja": "記念式",
   "meaning": "a commemorative ceremony",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "범위": {
   "headword": "범위",
   "hanja": "範圍",
   "meaning": "scope, extent",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "현충일": {
   "headword": "현충일",
   "hanja": "顯忠日",
   "meaning": "Memorial Day, 6 June",
   "characters": [
    {
     "char": "顯",
     "reading": "현",
     "gloss": "to make manifest — as in 현저하다"
    },
    {
     "char": "忠",
     "reading": "충",
     "gloss": "loyalty — as in 충성, 충신"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "추모": {
   "headword": "추모",
   "hanja": "追慕",
   "meaning": "remembrance of the dead",
   "characters": [
    {
     "char": "追",
     "reading": "추",
     "gloss": "to pursue, to follow — as in 추가, 추천"
    },
    {
     "char": "慕",
     "reading": "모",
     "gloss": "to long for, to admire"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "현충원": {
   "headword": "현충원",
   "hanja": "顯忠院",
   "meaning": "the national cemetery",
   "characters": [],
   "notes": [
    "서울현충원 at 동작동 and 대전현충원 are the two."
   ],
   "surfaces": []
  },
  "안장": {
   "headword": "안장",
   "hanja": "安葬",
   "meaning": "burial, interment",
   "characters": [
    {
     "char": "葬",
     "reading": "장",
     "gloss": "to bury — as in 장례식"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "국립묘지": {
   "headword": "국립묘지",
   "hanja": "國立墓地",
   "meaning": "a national cemetery",
   "characters": [
    {
     "char": "墓",
     "reading": "묘",
     "gloss": "grave — as in 성묘, 묘비"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "참배": {
   "headword": "참배",
   "hanja": "參拜",
   "meaning": "paying respects at a grave or shrine",
   "characters": [
    {
     "char": "參",
     "reading": "참",
     "gloss": "to take part — as in 참여, 참석"
    },
    {
     "char": "拜",
     "reading": "배",
     "gloss": "to bow — as in 세배, 예배"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "경건히": {
   "headword": "경건히",
   "hanja": "敬虔히",
   "meaning": "reverently",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "묵념": {
   "headword": "묵념",
   "hanja": "默念",
   "meaning": "a silent tribute",
   "characters": [
    {
     "char": "默",
     "reading": "묵",
     "gloss": "silent — as in 침묵, 묵비권"
    },
    {
     "char": "念",
     "reading": "념",
     "gloss": "thought — as in 기념, 개념"
    }
   ],
   "notes": [
    "The minute of silence at ten in the morning on 현충일, marked by sirens across the country."
   ],
   "surfaces": []
  },
  "장병": {
   "headword": "장병",
   "hanja": "將兵",
   "meaning": "officers and men, servicemen",
   "characters": [
    {
     "char": "將",
     "reading": "장",
     "gloss": "general, commander — as in 장군"
    },
    {
     "char": "兵",
     "reading": "병",
     "gloss": "soldier — as in 병사, 군병"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "순국선열": {
   "headword": "순국선열",
   "hanja": "殉國先烈",
   "meaning": "patriotic martyrs",
   "characters": [
    {
     "char": "殉",
     "reading": "순",
     "gloss": "to die for a cause"
    },
    {
     "char": "國",
     "reading": "국",
     "gloss": "country — as in 국가, 국권"
    },
    {
     "char": "先",
     "reading": "선",
     "gloss": "earlier, ancestor — as in 선조, 선배"
    },
    {
     "char": "烈",
     "reading": "렬",
     "gloss": "ardent, heroic — as in 치열, 열사"
    }
   ],
   "notes": [
    "Those who died for the country before liberation; the book glosses it 나라를 위해 목숨을 바친 분."
   ],
   "surfaces": []
  },
  "관공서": {
   "headword": "관공서",
   "hanja": "官公署",
   "meaning": "a government office",
   "characters": [],
   "notes": [],
   "surfaces": []
  },
  "남침": {
   "headword": "남침",
   "hanja": "南侵",
   "meaning": "an invasion of the south",
   "characters": [
    {
     "char": "南",
     "reading": "남",
     "gloss": "south — as in 남한, 남북"
    },
    {
     "char": "侵",
     "reading": "침",
     "gloss": "to invade — as in 침략, 침해"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "공산군": {
   "headword": "공산군",
   "hanja": "共産軍",
   "meaning": "the communist army",
   "characters": [
    {
     "char": "共",
     "reading": "공",
     "gloss": "together — as in 공동, 공공"
    },
    {
     "char": "産",
     "reading": "산",
     "gloss": "to produce — as in 생산, 재산"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "반격": {
   "headword": "반격",
   "hanja": "反擊",
   "meaning": "a counter-attack",
   "characters": [
    {
     "char": "反",
     "reading": "반",
     "gloss": "opposite — as in 반대, 반면"
    },
    {
     "char": "擊",
     "reading": "격",
     "gloss": "to strike — as in 공격, 충격"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "38선": {
   "headword": "38선",
   "hanja": "三八線",
   "meaning": "the 38th parallel",
   "characters": [],
   "notes": [
    "The line the peninsula was divided along in 1945; the armistice line of 1953 runs near but not on it."
   ],
   "surfaces": []
  },
  "돌파": {
   "headword": "돌파",
   "hanja": "突破",
   "meaning": "a breakthrough",
   "characters": [
    {
     "char": "突",
     "reading": "돌",
     "gloss": "to dash, sudden — as in 돌발, 충돌"
    },
    {
     "char": "破",
     "reading": "파",
     "gloss": "to break — as in 파괴, 돌파구"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "의의": {
   "headword": "의의",
   "hanja": "意義",
   "meaning": "significance",
   "characters": [
    {
     "char": "意",
     "reading": "의",
     "gloss": "meaning, intent — as in 의미, 의견"
    },
    {
     "char": "義",
     "reading": "의",
     "gloss": "righteousness, meaning — as in 정의, 의무"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "생도": {
   "headword": "생도",
   "hanja": "生徒",
   "meaning": "a cadet",
   "characters": [
    {
     "char": "徒",
     "reading": "도",
     "gloss": "follower, disciple — as in 신도"
    }
   ],
   "notes": [],
   "surfaces": []
  },
  "행진": {
   "headword": "행진",
   "hanja": "行進",
   "meaning": "a march, a parade",
   "characters": [
    {
     "char": "行",
     "reading": "행",
     "gloss": "to go — as in 행사, 여행"
    },
    {
     "char": "進",
     "reading": "진",
     "gloss": "to advance — as in 진행, 추진"
    }
   ],
   "notes": [],
   "surfaces": []
  }
 },
 "notes": [
  {
   "why": "The 대단원 정리 on pp. 48-49 is a mind map of eight boxes rather than a table; the boxes are set here in chapter order, which the map itself does not have."
  },
  {
   "why": "The 대단원 정리 box for chapter 4 reads 교통와 통신, where the chapter is 교통과 통신. That is the book's own slip and stands as printed."
  },
  {
   "why": "The quiz's answers and the 종합 평가's are mine, worked out from the chapters, since 정답보기 on p. 262 is not photographed. The quiz wants the three words that are symbols of Korea — 무궁화, 애국가, 태극기 — and their partners spell 인천 사일로 벽화."
  },
  {
   "why": "Pages 52-53, the opener for 제2편 교육, carry the part's name and nothing else, so there is nothing to transcribe."
  }
 ],
 "slug": "part-1",
 "part": true
});
